# Catalan translation for update-manager
# Copyright (C) 2006
# This file is distributed under the same license as the update-manager package.
# Jordi Irazuzta Cardús <irazuzta@gmail.com>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2009-10-03 11:14+0000\n"
"PO-Revision-Date: 2009-10-06 01:12+0000\n"
"Last-Translator: Joan Duran <jodufi@gmail.com>\n"
"Language-Team: Catalan <tradgnome@softcatala.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2009-10-08 06:52+0000\n"
"X-Generator: Launchpad (build Unknown)\n"

#. TRANSLATORS: download size is 0
#: ../DistUpgrade/utils.py:278 ../UpdateManager/Core/utils.py:278
msgid "0 KB"
msgstr "0 KB"

#. TRANSLATORS: download size of very small updates
#: ../DistUpgrade/utils.py:281 ../UpdateManager/Core/utils.py:281
msgid "1 KB"
msgstr "1 KB"

#. TRANSLATORS: download size of small updates, e.g. "250 KB"
#: ../DistUpgrade/utils.py:284 ../UpdateManager/Core/utils.py:284
#, python-format
msgid "%.0f KB"
msgstr "%.0f KB"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:287 ../UpdateManager/Core/utils.py:287
#, python-format
msgid "%.1f MB"
msgstr "%.1f MB"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:208 ../DistUpgrade/distro.py:423
#, python-format
msgid "Server for %s"
msgstr "Servidor per %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:226 ../DistUpgrade/distro.py:232
#: ../DistUpgrade/distro.py:248
msgid "Main server"
msgstr "Servidor principal"

#: ../DistUpgrade/distro.py:252
msgid "Custom servers"
msgstr "Servidors personalitzats"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:131
msgid "Could not calculate sources.list entry"
msgstr "No s'ha pogut calcular l'entrada del fitxer sources.list"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:234
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"No s'ha pogut trobar cap paquet, esteu utilitzat un disc de l'Ubuntu per a "
"l'arquitectura adequada?"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:277
msgid "Failed to add the CD"
msgstr "No s'ha pogut afegir el CD"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:278
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"S'ha produït un error en afegir el CD i l'actualització s'ha cancel·lat. "
"Informeu d'aquest error si això ha passat amb un CD d'Ubuntu vàlid.\n"
"\n"
"El missatge d'error ha estat:\n"
"«%s»"

#: ../DistUpgrade/DistUpgradeCache.py:130
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Elimina el paquet en mal estat"
msgstr[1] "Elimina els paquets en mal estat"

#: ../DistUpgrade/DistUpgradeCache.py:133
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"El paquet «%s» es troba en un estat inconsistent i s'ha de tornar a "
"instal·lar, però no s'ha trobat l'arxiu per a fer-ho. Voleu eliminar aquest "
"paquet i continuar?"
msgstr[1] ""
"Els paquets «%s» es troben en un estat inconsistent i s'han de tornar a "
"instal·lar, però no s'ha trobat els arxius per a fer-ho. Voleu eliminar "
"aquests paquets i continuar?"

#: ../DistUpgrade/DistUpgradeCache.py:330
msgid "Broken packages"
msgstr "Paquets trencats"

#: ../DistUpgrade/DistUpgradeCache.py:331
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"El vostre sistema conté paquets trencats que no es poden arreglar amb "
"aquesta aplicació. Utilitzeu el Synaptic o l'apt-get abans de continuar."

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:598
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"S'ha produït un problema irresoluble mentre es calculava l'actualització:\n"
"%s\n"
"\n"
"Això pot ser degut a:\n"
" * l'actualització a una versió en desenvolupament de l'Ubuntu\n"
" * l'execució de l'actual versió en desenvolupament de l'Ubuntu\n"
" * la instal·lació de paquets no oficials de programari i no proporcionats "
"per l'Ubuntu\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:608
msgid "This is most likely a transient problem, please try again later."
msgstr ""
"Això és probablement un problema transitori, torneu a provar-ho més tard."

#: ../DistUpgrade/DistUpgradeCache.py:611
msgid ""
"If none of this applies, then please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"Si res d'això funciona, informeu de l'error del gestor d'actualitzacions (al "
"paquet update-manager) i adjunteu els fitxers de /var/log/dist-upgrade/ en "
"l'informe."

#: ../DistUpgrade/DistUpgradeCache.py:617
#: ../UpdateManager/UpdateManager.py:732
msgid "Could not calculate the upgrade"
msgstr "No s'ha pogut calcular l'actualització"

#: ../DistUpgrade/DistUpgradeCache.py:667
msgid "Error authenticating some packages"
msgstr "S'ha produït un error en autenticar alguns paquets"

#: ../DistUpgrade/DistUpgradeCache.py:668
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"No s'han pogut autenticar alguns paquets. Potser hi ha un problema temporal "
"amb la xarxa. Podeu provar-ho més tard. A continuació es mostra la llista "
"amb els paquets no autenticats."

#: ../DistUpgrade/DistUpgradeCache.py:688
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"El paquet «%s» està marcat per a eliminar-lo, però apareix a la llista negra "
"de fitxers a eliminar."

#: ../DistUpgrade/DistUpgradeCache.py:692
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "El paquet essencial «%s» està marcat per a ésser eliminat."

#: ../DistUpgrade/DistUpgradeCache.py:701
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:801
#, python-format
msgid "Can not mark '%s' for upgrade"
msgstr "No s'ha pogut marcar «%s» per a actualitzar-lo"

#: ../DistUpgrade/DistUpgradeCache.py:815
#, python-format
msgid "Can't install '%s'"
msgstr "No s'ha pogut instal·lar «%s»"

#: ../DistUpgrade/DistUpgradeCache.py:816
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""
"No s'ha pogut instal·lar un dels paquets requerits. Hauríeu d'enviar un "
"informe d'error. "

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:825
msgid "Can't guess meta-package"
msgstr "No s'ha pogut conjecturar el metapaquet"

#: ../DistUpgrade/DistUpgradeCache.py:826
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"No teniu instal·lats el paquet ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop o edubuntu-desktop i no s'ha pogut detectar la versió de l'Ubuntu "
"que esteu utilitzant.\n"
"Instal·leu un d'aquests paquets abans de continuar; per fer-ho podeu "
"utilitzar el Synaptic o l'apt-get"

#: ../DistUpgrade/DistUpgradeController.py:85
msgid "Reading cache"
msgstr "S'està llegint la memòria cau"

#: ../DistUpgrade/DistUpgradeController.py:181
msgid "Unable to get exclusive lock"
msgstr "No s'ha pogut obtenir un bloqueig exclusiu"

#: ../DistUpgrade/DistUpgradeController.py:182
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Normalment això es deu al fet que teniu un altre gestor de paquets en "
"execució (com  ara l'apt-get o l'aptitude) i cal que abans el tanqueu."

#: ../DistUpgrade/DistUpgradeController.py:235
msgid "Upgrading over remote connection not supported"
msgstr "No és possible actualitzar a través d'una connexió remota"

#: ../DistUpgrade/DistUpgradeController.py:236
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. The upgrade will abort now. Please try without "
"ssh."
msgstr ""
"Esteu intentant fer una actualització des d'una connexió ssh amb un frontal "
"que no ho permet. L'actualització es cancel·larà. Proveu-ho sense l'ssh."

#: ../DistUpgrade/DistUpgradeController.py:247
msgid "Continue running under SSH?"
msgstr "Voleu continuar treballant via SSH?"

#: ../DistUpgrade/DistUpgradeController.py:248
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, a additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Sembla ser que aquesta sessió s'està executant sota ssh. Actualment o es "
"recomana realitzar una actualització sota ssh, atès que en cas de fallada la "
"recuperació es fa més difícil.\n"
"Si continueu, s'iniciarà un dimoni ssh addicional al port «%s».\n"
"Voleu continuar?"

#: ../DistUpgrade/DistUpgradeController.py:263
msgid "Starting additional sshd"
msgstr "S'està iniciant un sshd addicional"

#: ../DistUpgrade/DistUpgradeController.py:264
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Per facilitar la recuperació en cas de fallada, s'iniciarà un sshd "
"addicional al port «%s». Si alguna cosa anés malament amb l'ssh en ús, podeu "
"fer servir l'addicional.\n"

#: ../DistUpgrade/DistUpgradeController.py:334
#: ../DistUpgrade/DistUpgradeController.py:379
msgid "Can not upgrade"
msgstr "No es pot actualitzar"

#: ../DistUpgrade/DistUpgradeController.py:335
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "Aquesta eina no permet l'actualització de «%s» a «%s»."

#: ../DistUpgrade/DistUpgradeController.py:344
msgid "Sandbox setup failed"
msgstr "Ha fallat la configuració d'un entorn de proves"

#: ../DistUpgrade/DistUpgradeController.py:345
msgid "It was not possible to create the sandbox environment."
msgstr "No ha estat possible crear un entorn de proves."

#: ../DistUpgrade/DistUpgradeController.py:351
msgid "Sandbox mode"
msgstr "Mode de prova"

#: ../DistUpgrade/DistUpgradeController.py:352
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a systemdir from now until the next reboot are "
"permanent."
msgstr ""
"L'actualització s'està executant en mode de prova. Tots els canvis "
"s'efectuen a «%s» i es perdran en reiniciar el sistema.\n"
"\n"
"Cap canvi efectuat des d'ara fins que es reinicie el sistema serà permanent."

#: ../DistUpgrade/DistUpgradeController.py:380
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"La vostra instal·lació del Python està malmesa. Reviseu l'enllaç simbòlic "
"«/usr/bin/python»."

#: ../DistUpgrade/DistUpgradeController.py:406
msgid "Package 'debsig-verify' is installed"
msgstr "El paquet «debsig-verify» està instal·lat"

#: ../DistUpgrade/DistUpgradeController.py:407
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""
"L'actualització no pot continuar amb aquest paquet instal·lat.\n"
"Elimineu-lo amb el synaptic o amb l'ordre «apt-get remove debsig-verify» i "
"torneu a executar l'actualització."

#: ../DistUpgrade/DistUpgradeController.py:417
msgid "Include latest updates from the Internet?"
msgstr "Voleu incloure les darreres actualitzacions d'Internet?"

#: ../DistUpgrade/DistUpgradeController.py:418
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"El sistema d'actualitzacions pot utilitzar Internet per a baixar i "
"instal·lar automàticament les darreres actualitzacions. Si disposeu d'una "
"connexió de xarxa, aquesta opció és molt recomanable.\n"
"\n"
"L'actualització trigarà més, però en acabar tindreu un sistema completament "
"actualitzat. Podeu optar per no fer-ho, però en breu tindreu que actualitzar "
"el sistema.\n"
"Si responeu «no» la xarxa no s'utilitzarà per a res."

#: ../DistUpgrade/DistUpgradeController.py:641
#, python-format
msgid "disabled on upgrade to %s"
msgstr "desactivat en actualitzar a %s"

#: ../DistUpgrade/DistUpgradeController.py:667
msgid "No valid mirror found"
msgstr "No s'ha trobat cap rèplica vàlida"

#: ../DistUpgrade/DistUpgradeController.py:668
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:688
msgid "Generate default sources?"
msgstr "Voleu generar les fonts per defecte?"

#: ../DistUpgrade/DistUpgradeController.py:689
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:724
msgid "Repository information invalid"
msgstr "La informació dels dipòsits no és vàlida"

#: ../DistUpgrade/DistUpgradeController.py:725
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""
"S'ha produït un error en actualitzar la informació dels dipòsits. Hauríeu "
"d'informar-ne."

#: ../DistUpgrade/DistUpgradeController.py:731
msgid "Third party sources disabled"
msgstr "S'han desactivat les fonts de tercers"

#: ../DistUpgrade/DistUpgradeController.py:732
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"S'han desactivat algunes entrades de tercers. Les podeu reactivar després de "
"l'actualització des de l'eina «software-properties» en el vostre gestor de "
"paquets."

#: ../DistUpgrade/DistUpgradeController.py:772
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Paquet en estat inconsistent"
msgstr[1] "Paquets en estat inconsistent"

#: ../DistUpgrade/DistUpgradeController.py:775
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"El paquet «%s» es troba en un estat inconsistent i s'ha de tornar a "
"instal·lar, però no s'ha trobat l'arxiu per a fer-ho. Torneu-lo a instal·lar "
"manualment o suprimiu-lo del sistema."
msgstr[1] ""
"Els paquets «%s» es troben en un estat inconsistent i s'han de tornar a "
"instal·lar, però no s'ha trobat els arxius per a fer-ho. Torneu-los a "
"instal·lar manualment o suprimiu-los del sistema."

#: ../DistUpgrade/DistUpgradeController.py:823
msgid "Error during update"
msgstr "S'ha produït un error en l'actualització"

#: ../DistUpgrade/DistUpgradeController.py:824
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"S'ha produït un error mentre s'actualitzava el vostre sistema. Normalment "
"això es degut a problemes de xarxa. Comproveu la vostra connexió de xarxa i "
"torneu a intentar-ho."

#. print "on_button_install_clicked"
#: ../DistUpgrade/DistUpgradeController.py:833
#: ../UpdateManager/UpdateManager.py:555
msgid "Not enough free disk space"
msgstr "No disposeu de suficient espai al disc"

#: ../DistUpgrade/DistUpgradeController.py:834
#, python-format
msgid ""
"The upgrade is now aborted. The upgrade needs a total of %s free space on "
"disk '%s'. Please free at least an additional %s of disk space on '%s'. "
"Empty your trash and remove temporary packages of former installations using "
"'sudo apt-get clean'."
msgstr ""
"L'actualització s'interromprà. Aquesta requereix %s d'espai lliure al disc "
"«%s». Hauríeu d'alliberar almenys %s d'espai de disc a «%s». Buideu la "
"vostra paperera i esborreu els paquets temporals utilitzant «sudo apt-get "
"clean»."

#: ../DistUpgrade/DistUpgradeController.py:874
msgid "Support for some applications ended"
msgstr "S'ha deixat de donar suport a algunes aplicacions"

#: ../DistUpgrade/DistUpgradeController.py:875
msgid ""
"Canonical Ltd. no longer provides support for the following software "
"packages. You can still get support from the community.\n"
"\n"
"If you have not enabled community maintained software (universe), these "
"packages will be suggested for removal at the end of the upgrade."
msgstr ""
"Canonical Ltd. ja no mantindrà aquests paquets de manera oficial. Tot i "
"això, com sempre, obtindreu l'ajuda de la comunitat.\n"
"\n"
"Si no teniu activat el dipòsit «universe» se us suggerirà que els "
"desinstal·leu en finalitzar l'actualització."

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:884
#: ../DistUpgrade/DistUpgradeController.py:1554
msgid "Calculating the changes"
msgstr "S'estan calculant els canvis"

#. ask the user if he wants to do the changes
#: ../DistUpgrade/DistUpgradeController.py:899
msgid "Do you want to start the upgrade?"
msgstr "Voleu iniciar l'actualització?"

#: ../DistUpgrade/DistUpgradeController.py:955
msgid "Upgrade canceled"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:956
msgid ""
"The upgrade cancels now and the original system state is restored. You can "
"resume the upgrade at a later time."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:961
#: ../DistUpgrade/DistUpgradeController.py:1048
msgid "Could not download the upgrades"
msgstr "No s'han pogut baixar les actualitzacions"

#: ../DistUpgrade/DistUpgradeController.py:962
msgid ""
"The upgrade is now aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far are kept."
msgstr ""
"L'actualització s'ha interromput. Comproveu la vostra connexió a Internet o "
"el suport d'instal·lació. Tots el fitxers baixats es mantindran."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1015
#: ../DistUpgrade/DistUpgradeController.py:1138
msgid "Error during commit"
msgstr "S'ha produït un error durant l'enviament"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1017
#: ../DistUpgrade/DistUpgradeController.py:1177
msgid "Restoring original system state"
msgstr "S'està restaurant l'estat original del sistema"

#: ../DistUpgrade/DistUpgradeController.py:1018
#: ../DistUpgrade/DistUpgradeController.py:1032
msgid "Could not install the upgrades"
msgstr "No s'han pogut instal·lar les actualitzacions"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1023
msgid ""
"The upgrade is now aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"S'ha interromput l'actualització. Pot ser que el sistema hagi quedat en un "
"estat inutilitzable. S'executarà una recuperació (dpkg --configure -a) "
"immediatament."

#: ../DistUpgrade/DistUpgradeController.py:1028
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"Informeu d'aquest error del gestor d'actualitzacions (paquet «update-"
"manager») i adjunteu els fitxers de /var/log/dist-upgrade/ en l'informe.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1049
msgid ""
"The upgrade is now aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"L'actualització s'ha interromput. Comproveu la vostra connexió a Internet o "
"el suport d'instal·lació i torneu a provar-ho "

#: ../DistUpgrade/DistUpgradeController.py:1126
msgid "Remove obsolete packages?"
msgstr "Voleu suprimir els paquets obsolets?"

#: ../DistUpgrade/DistUpgradeController.py:1127
#: ../DistUpgrade/DistUpgrade.ui.h:20
msgid "_Keep"
msgstr "_Manté"

#: ../DistUpgrade/DistUpgradeController.py:1127
msgid "_Remove"
msgstr "Sup_rimeix"

#: ../DistUpgrade/DistUpgradeController.py:1139
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""
"S'ha produït un error durant el procés de neteja. Vegeu el següent missatge "
"per a més informació. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1215
msgid "Required depends is not installed"
msgstr "Les dependències requerides no estan instal·lades"

#: ../DistUpgrade/DistUpgradeController.py:1216
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "La dependència requerida «%s» no està instal·lada. "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1461
#: ../DistUpgrade/DistUpgradeController.py:1528
msgid "Checking package manager"
msgstr "S'està comprovant el gestor de paquets"

#: ../DistUpgrade/DistUpgradeController.py:1466
msgid "Preparing the upgrade failed"
msgstr "S'ha produït un error en la preparació de l'actualització"

#: ../DistUpgrade/DistUpgradeController.py:1467
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bug report."
msgstr ""
"S'ha produït un error mentre es preparava el sistema per a l'actualització. "
"Informeu de l'error del gestor d'actualitzacions (update-manager) i adjunteu "
"els fitxers de /var/log/dist-upgrade/ en l'informe."

#: ../DistUpgrade/DistUpgradeController.py:1483
msgid "Getting upgrade prerequisites failed"
msgstr "S'ha produït un error en obtenir els prerequisits de l'actualització"

#: ../DistUpgrade/DistUpgradeController.py:1484
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bug report."
msgstr ""
"El sistema no ha pogut obtenir els prerequisits per a l'actualizació. "
"L'actualització és cancel·larà i es restaurarà el sistema previ a "
"l'actualització.\n"
"\n"
"Informeu d'aquest error del paquet update-manager i afegiu els fitxers de "
"/var/log/dist-upgrade/ en l'informe."

#: ../DistUpgrade/DistUpgradeController.py:1514
msgid "Updating repository information"
msgstr "S'està actualitzant la informació dels dipòsits"

#: ../DistUpgrade/DistUpgradeController.py:1542
msgid "Invalid package information"
msgstr "La informació dels paquets no és valida"

#: ../DistUpgrade/DistUpgradeController.py:1543
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"No s'ha trobat «%s» després d'actualitzar la informació dels paquets.\n"
"Això suposa un error greu; informeu d'aquest error del gestor "
"d'actualitzacions (update-manager) i adjunteu els fitxers de  /var/log/dist-"
"upgrade/ en l'informe."

#: ../DistUpgrade/DistUpgradeController.py:1560
#: ../DistUpgrade/DistUpgradeController.py:1608
msgid "Fetching"
msgstr "S'està recollint"

#: ../DistUpgrade/DistUpgradeController.py:1566
#: ../DistUpgrade/DistUpgradeController.py:1612
msgid "Upgrading"
msgstr "S'està actualitzant"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1571
#: ../DistUpgrade/DistUpgradeController.py:1614
#: ../DistUpgrade/DistUpgradeController.py:1621
#: ../DistUpgrade/DistUpgradeController.py:1626
msgid "Upgrade complete"
msgstr "S'ha completat l'actualització"

#: ../DistUpgrade/DistUpgradeController.py:1572
#: ../DistUpgrade/DistUpgradeController.py:1615
#: ../DistUpgrade/DistUpgradeController.py:1622
msgid ""
"The upgrade is completed but there were errors during the upgrade process."
msgstr ""
"L'actualització s'ha completat, però s'han produït errors durant el procés."

#: ../DistUpgrade/DistUpgradeController.py:1579
msgid "Searching for obsolete software"
msgstr "S'està cercant programari obsolet"

#: ../DistUpgrade/DistUpgradeController.py:1584
msgid "System upgrade is complete."
msgstr "S'ha completat l'actualització del sistema."

#: ../DistUpgrade/DistUpgradeController.py:1627
msgid "The partial upgrade was completed."
msgstr "L'actualització parcial s'ha completat."

#: ../DistUpgrade/DistUpgradeQuirks.py:143
msgid "No ARMv6 CPU"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:144
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""

#. TRANSLATORS: this string is not displayed in the 9.10 upgrade
#. (but it will be used for 8.04 -> 10.04 LTS upgrades)
#: ../DistUpgrade/DistUpgradeQuirks.py:164
#: ../DistUpgrade/DistUpgradeQuirks.py:243
#: ../DistUpgrade/DistUpgradeQuirks.py:270
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"L'actualització pot reduir els efectes d'escriptori i el rendiment en jocs i "
"altres programes que facin un ús exhaustiu de processament gràfic."

#: ../DistUpgrade/DistUpgradeQuirks.py:168
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04.\n"
"\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:247
#: ../DistUpgrade/DistUpgradeQuirks.py:274
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04.\n"
"\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:444
msgid "evms in use"
msgstr "S'està utilitzant l'evms"

#: ../DistUpgrade/DistUpgradeQuirks.py:445
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""
"El vostre sistema utilitza el gestor de volum «evms» a /proc/mounts. Aquest "
"programari no es mantindrà més, desconnecteu-lo i torneu a executar "
"l'actualització."

#: ../DistUpgrade/DistUpgradeMain.py:43
msgid "Sandbox upgrade using aufs"
msgstr "Actualització en entorn de proves utilitzant aufs"

#: ../DistUpgrade/DistUpgradeMain.py:45
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr ""
"Utilitza el camí especificat per cercar un CDROM amb paquets actualitzables"

#: ../DistUpgrade/DistUpgradeMain.py:51
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Utilitzeu un frontal. Actualment es disposa de: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:54
msgid "*DEPRECATED* this option will be ignore"
msgstr "*EN DESÚS* aquesta opció serà ignorada"

#: ../DistUpgrade/DistUpgradeMain.py:57
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""
"Realitza només una actualització parcial (sense reescriure el sources.list)"

#: ../DistUpgrade/DistUpgradeMain.py:59
msgid "Set datadir"
msgstr "Estableix el datadir"

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:106
#: ../DistUpgrade/DistUpgradeViewKDE.py:190
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Inseriu «%s» a la unitat «%s»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:125
#: ../DistUpgrade/DistUpgradeViewKDE.py:203
msgid "Fetching is complete"
msgstr "S'ha completat el recull"

#: ../DistUpgrade/DistUpgradeViewGtk.py:137
#: ../DistUpgrade/DistUpgradeViewKDE.py:216
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "S'està obtenint el fitxer %li de %li a %sB/s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:138
#: ../DistUpgrade/DistUpgradeViewGtk.py:273
#: ../DistUpgrade/DistUpgradeViewKDE.py:217
#: ../DistUpgrade/DistUpgradeViewKDE.py:357
#, python-format
msgid "About %s remaining"
msgstr "Queden %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:140
#: ../DistUpgrade/DistUpgradeViewKDE.py:219
#, python-format
msgid "Fetching file %li of %li"
msgstr "S'està obtenint el fitxer %li de %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:172
#: ../DistUpgrade/DistUpgradeViewKDE.py:253
msgid "Applying changes"
msgstr "S'estan aplicant els canvis"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:197
#: ../DistUpgrade/DistUpgradeViewKDE.py:266
msgid "dependency problems - leaving unconfigured"
msgstr "problemes de dependències - queda sense configurar"

#: ../DistUpgrade/DistUpgradeViewGtk.py:202
#: ../DistUpgrade/DistUpgradeViewKDE.py:268
#, python-format
msgid "Could not install '%s'"
msgstr "No s'ha pogut instal·lar «%s»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:203
#: ../DistUpgrade/DistUpgradeViewKDE.py:269
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:219
#: ../DistUpgrade/DistUpgradeViewKDE.py:290
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Voleu reemplaçar el fitxer de\n"
"configuració personalitzat «%s»?"

#: ../DistUpgrade/DistUpgradeViewGtk.py:220
#: ../DistUpgrade/DistUpgradeViewKDE.py:291
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"Perdreu tots els canvis realitzats en el fitxer de configuració si trieu "
"reemplaçar-lo per una versió més nova."

#: ../DistUpgrade/DistUpgradeViewGtk.py:233
#: ../DistUpgrade/DistUpgradeViewKDE.py:309
msgid "The 'diff' command was not found"
msgstr "No s'ha trobat l'ordre «diffx»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:419
#: ../DistUpgrade/DistUpgradeViewText.py:107
msgid "A fatal error occurred"
msgstr "S'ha produït un error greu"

#: ../DistUpgrade/DistUpgradeViewGtk.py:420
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade is now aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Informeu d'aquest problema (si ja no ho heu fet) i afegiu-hi els fitxers "
"/var/log/dist-upgrade/main.log i /var/log/dist-upgrade/apt.log en l'informe. "
"L'actualització s'ha cancel·lat.\n"
"El vostre fitxer sources.list original s'ha desat a "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewGtk.py:435
msgid "Ctrl-c pressed"
msgstr "S'ha premut Ctrl-C"

#: ../DistUpgrade/DistUpgradeViewGtk.py:436
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Això interromprà l'operació i pot deixar trencat el sistema. Esteu segur que "
"voleu fer-ho?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:578
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Per a evitar una possible pèrdua de dades, tanqueu tos els documents i "
"aplicacions."

#: ../DistUpgrade/DistUpgradeViewGtk.py:592
#, python-format
msgid "<b>Downgrade %s</b>"
msgstr "<b>Torna a una versió anterior de %s</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:594
#: ../DistUpgrade/DistUpgradeViewKDE.py:757
#, python-format
msgid "Remove %s"
msgstr "Suprimeix %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:599
#: ../DistUpgrade/DistUpgradeViewKDE.py:759
#, python-format
msgid "Install %s"
msgstr "Instal·la %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:601
#: ../DistUpgrade/DistUpgradeViewKDE.py:761
#, python-format
msgid "Upgrade %s"
msgstr "Actualitza %s"

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:191
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Media Change"
msgstr "Canvi de suport"

#: ../DistUpgrade/DistUpgradeViewKDE.py:321
msgid "Show Difference >>>"
msgstr "Mostra les diferències >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:324
msgid "<<< Hide Difference"
msgstr "<<< Oculta les diferències"

#: ../DistUpgrade/DistUpgradeViewKDE.py:538
msgid "Error"
msgstr "Error"

#: ../DistUpgrade/DistUpgradeViewKDE.py:550
msgid "&Cancel"
msgstr "&Cancel·la"

#: ../DistUpgrade/DistUpgradeViewKDE.py:552
#: ../DistUpgrade/DistUpgradeViewKDE.py:789
msgid "&Close"
msgstr "&Tanca"

#: ../DistUpgrade/DistUpgradeViewKDE.py:598
msgid "Show Terminal >>>"
msgstr "Mostra el terminal >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:601
msgid "<<< Hide Terminal"
msgstr "<<< Oculta el terminal"

#: ../DistUpgrade/DistUpgradeViewKDE.py:681
msgid "Information"
msgstr "Informació"

#: ../DistUpgrade/DistUpgradeViewKDE.py:731
#: ../DistUpgrade/DistUpgradeViewKDE.py:772
#: ../DistUpgrade/DistUpgradeViewKDE.py:775 ../DistUpgrade/DistUpgrade.ui.h:9
msgid "Details"
msgstr "Detalls"

#: ../DistUpgrade/DistUpgradeViewKDE.py:785
#: ../DistUpgrade/DistUpgradeViewText.py:225
msgid "Restart required"
msgstr "Cal que reinicieu el sistema"

#: ../DistUpgrade/DistUpgradeViewKDE.py:785 ../DistUpgrade/DistUpgrade.ui.h:5
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr ""
"<b><big>Reinicieu el sistema per a completar l'actualització</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:788 ../DistUpgrade/DistUpgrade.ui.h:23
msgid "_Restart Now"
msgstr "_Reinicia"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:800
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>Voleu cancel·lar l'actualització en curs?</big></b>\n"
"\n"
"El sistema pot quedar inusable si cancel·leu l'actualització. Es molt "
"recomanable continuar amb l'actualització."

#: ../DistUpgrade/DistUpgradeViewKDE.py:804
msgid "Cancel Upgrade?"
msgstr "Voleu cancel·lar l'actualització?"

#: ../DistUpgrade/DistUpgradeView.py:59
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li dia"
msgstr[1] "%li dies"

#: ../DistUpgrade/DistUpgradeView.py:61
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li hora"
msgstr[1] "%li hores"

#: ../DistUpgrade/DistUpgradeView.py:63
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li minut"
msgstr[1] "%li minuts"

#: ../DistUpgrade/DistUpgradeView.py:64
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li segon"
msgstr[1] "%li segons"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:77
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:92
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:113
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"La baixada trigarà aproximadament %s amb una connexió ADSL d'1Mb, i "
"aproximadament %s amb un mòdem de 56k"

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:117
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "La baixada trigarà aproximadament %s amb la vostra connexió. "

#: ../DistUpgrade/DistUpgradeView.py:186 ../DistUpgrade/DistUpgrade.ui.h:14
msgid "Preparing to upgrade"
msgstr "S'està preparant l'actualització"

#: ../DistUpgrade/DistUpgradeView.py:187
msgid "Getting new software channels"
msgstr "S'estan obtenint canals de programari nous"

#: ../DistUpgrade/DistUpgradeView.py:188 ../DistUpgrade/DistUpgrade.ui.h:12
msgid "Getting new packages"
msgstr "S'estan obtenint els paquets nous"

#: ../DistUpgrade/DistUpgradeView.py:189 ../DistUpgrade/DistUpgrade.ui.h:13
msgid "Installing the upgrades"
msgstr "S'estan instal·lant les actualitzacions"

#: ../DistUpgrade/DistUpgradeView.py:190 ../DistUpgrade/DistUpgrade.ui.h:8
msgid "Cleaning up"
msgstr "S'està netejant"

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:263
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "Se suprimirà %d paquet"
msgstr[1] "Se suprimiran %d paquets"

#: ../DistUpgrade/DistUpgradeView.py:268
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "S'instal·larà %d paquet nou"
msgstr[1] "S'instal·laran %d paquets nous"

#: ../DistUpgrade/DistUpgradeView.py:274
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "S'actualitzarà %d paquet"
msgstr[1] "S'actualitzaran %d paquets"

#: ../DistUpgrade/DistUpgradeView.py:279
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Heu de baixar un total de %s. "

#: ../DistUpgrade/DistUpgradeView.py:283
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be cancelled."
msgstr ""
"La baixada i l'actualització poden durar algunes hores, i no podreu "
"cancel·lar aquesta última un cop hagi començat."

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:289 ../UpdateManager/UpdateManager.py:489
msgid "Your system is up-to-date"
msgstr "El vostre sistema està actualitzat"

#: ../DistUpgrade/DistUpgradeView.py:290
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"No hi ha actualitzacions disponibles per al vostre sistema. L'actualització "
"es cancel·larà"

#: ../DistUpgrade/DistUpgradeView.py:303
msgid "Reboot required"
msgstr "Cal que reinicieu el sistema"

#: ../DistUpgrade/DistUpgradeView.py:304
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"L'actualització ha finalitzat i cal reiniciar el sistema. Voleu fer-ho ara?"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:134
#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:134
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
msgid "Could not run the upgrade tool"
msgstr "No es pot executar l'eina d'actualització"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""
"El més probable és que es tracti d'un error de l'eina d'actualització del "
"qual n'hauríeu d'informar"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:204
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:204
msgid "Upgrade tool signature"
msgstr "Signatura de l'eina d'actualització"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:207
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:207
msgid "Upgrade tool"
msgstr "Eina d'actualització"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:237
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:237
msgid "Failed to fetch"
msgstr "Ha fallat la baixada"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:238
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""
"Ha fallat l'obtenció de l'actualització. Pot ser que hi hagi algun problema "
"a la xarxa. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:242
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:242
msgid "Failed to extract"
msgstr "Ha fallat l'extracció"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:243
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Ha fallat l'extracció de l'actualització. Pot ser que hi hagi algun problema "
"a la xarxa o al servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:248
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:248
msgid "Verification failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:249
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Ha fallat la verificació de l'actualització. Pot ser que hi hagi algun "
"problema a la xarxa o al servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:254
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:254
msgid "Authentication failed"
msgstr "Ha fallat l'autenticació"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:255
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Ha fallat l'autenticació de l'actualització. Pot ser que hi hagi algun "
"problema a la xarxa o al servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:263
#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:263
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:269
msgid "Can not run the upgrade"
msgstr "No es pot executar l'actualització"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:264
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:264
msgid ""
"This usually is caused by a system were /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"Normalment això és degut al fet que /tmp estigui muntat amb l'opció noexec. "
"Torneu a muntar-lo sense aquesta opció i proveu d'executar l'actualització."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:270
#, python-format
msgid "The error message is '%s'."
msgstr "El missatge d'error és «%s»"

#: ../DistUpgrade/DistUpgradeViewText.py:108
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade is now aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Informeu d'aquest error i adjunteu-hi els fitxers /var/log/dist-"
"upgrade/main.log i /var/log/dist-upgrade/apt.log en l'informe. "
"L'actualització s'ha cancel·lat.\n"
"El fitxer sources.list original s'ha desat a "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewText.py:132
msgid "Aborting"
msgstr "S'està interrompent"

#: ../DistUpgrade/DistUpgradeViewText.py:137
msgid "Demoted:\n"
msgstr "Degradat:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:169
#: ../DistUpgrade/DistUpgradeViewText.py:191
#: ../DistUpgrade/DistUpgradeViewText.py:198
msgid "Continue [yN] "
msgstr "Continua [sN] "

#: ../DistUpgrade/DistUpgradeViewText.py:169
#: ../DistUpgrade/DistUpgradeViewText.py:191
msgid "Details [d]"
msgstr "Detalls [d]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:173
#: ../DistUpgrade/DistUpgradeViewText.py:201
msgid "y"
msgstr "s"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:176
#: ../DistUpgrade/DistUpgradeViewText.py:208
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:179
msgid "d"
msgstr "d"

#: ../DistUpgrade/DistUpgradeViewText.py:183
#, python-format
msgid "Remove: %s\n"
msgstr "Suprimeix: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:186
#, python-format
msgid "Install: %s\n"
msgstr "Instal·la: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:189
#, python-format
msgid "Upgrade: %s\n"
msgstr "Actualitza: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:205
msgid "Continue [Yn] "
msgstr "Continua [Sn] "

#: ../DistUpgrade/DistUpgradeViewText.py:226
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Cal reiniciar el sistema per a finalitzar l'actualització.\n"
"Si seleccioneu «s», es reiniciarà el sistema."

#: ../DistUpgrade/DistUpgrade.ui.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.ui.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>Voleu cancel·lar l'actualització?</big></b>\n"
"\n"
"Si ho feu, pot ser que el sistema sigui inutilitzable. És extremament "
"recomanable continuar amb l'actualització."

#: ../DistUpgrade/DistUpgrade.ui.h:6
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Voleu iniciar l'actualització?</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:7
msgid "<b><big>Upgrading Ubuntu to version 9.10</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "Diferències entre els fitxers"

#: ../DistUpgrade/DistUpgrade.ui.h:11
msgid "Distribution Upgrade"
msgstr "Actualització de la distribució"

#: ../DistUpgrade/DistUpgrade.ui.h:15
msgid "Restarting the computer"
msgstr "S'està reiniciant l'ordinador"

#: ../DistUpgrade/DistUpgrade.ui.h:16
msgid "Setting new software channels"
msgstr "S'estan configurant els canals de programari nous"

#: ../DistUpgrade/DistUpgrade.ui.h:17
msgid "Terminal"
msgstr "Terminal"

#: ../DistUpgrade/DistUpgrade.ui.h:18
msgid "_Cancel Upgrade"
msgstr "_Cancel·la l'actualització"

#: ../DistUpgrade/DistUpgrade.ui.h:19
msgid "_Continue"
msgstr "_Continua"

#: ../DistUpgrade/DistUpgrade.ui.h:21
msgid "_Replace"
msgstr "_Reemplaça"

#: ../DistUpgrade/DistUpgrade.ui.h:22
msgid "_Report Bug"
msgstr "_Informa de l'error"

#: ../DistUpgrade/DistUpgrade.ui.h:24
msgid "_Resume Upgrade"
msgstr "_Reprèn l'actualització"

#: ../DistUpgrade/DistUpgrade.ui.h:25
msgid "_Start Upgrade"
msgstr "_Comença l'actualització"

#: ../UpdateManager/backend/InstallBackendSynaptic.py:42
msgid "Please wait, this can take some time."
msgstr "Espereu un moment, això pot tardar una estona."

#: ../UpdateManager/backend/InstallBackendSynaptic.py:44
msgid "Update is complete"
msgstr "S'ha completat l'actualització"

#: ../UpdateManager/DistUpgradeFetcher.py:85
#: ../UpdateManager/DistUpgradeFetcherKDE.py:103
msgid "Could not find the release notes"
msgstr "No s'han trobat les notes de la versió"

#: ../UpdateManager/DistUpgradeFetcher.py:86
#: ../UpdateManager/DistUpgradeFetcherKDE.py:104
msgid "The server may be overloaded. "
msgstr "El servidor potser està sobrecarregat. "

#: ../UpdateManager/DistUpgradeFetcher.py:96
#: ../UpdateManager/DistUpgradeFetcherKDE.py:108
msgid "Could not download the release notes"
msgstr "No s'han pogut baixar les notes de la versió"

#: ../UpdateManager/DistUpgradeFetcher.py:97
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Please check your internet connection."
msgstr "Comproveu la vostra connexió a Internet"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:62
#: ../UpdateManager/DistUpgradeFetcherKDE.py:85
msgid "Upgrade"
msgstr "Actualització"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:89
#: ../data/glade/UpdateManager.ui.h:12
msgid "Release Notes"
msgstr "Notes de la versió"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:128
#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
msgid "Downloading additional package files..."
msgstr "S'estan baixant els fitxers de paquet addicionals..."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Fitxer %s de %s a %s B/s"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
#, python-format
msgid "File %s of %s"
msgstr "Fitxer %s de %s"

#: ../UpdateManager/ChangelogViewer.py:70
msgid "Open Link in Browser"
msgstr "Obre l'enllaç al navegador"

#: ../UpdateManager/ChangelogViewer.py:72
msgid "Copy Link to Clipboard"
msgstr "Copia l'enllaç al porta-retalls"

#: ../UpdateManager/GtkProgress.py:115
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "S'està baixant el fitxer %(current)li de %(total)li a %(speed)s/s"

#: ../UpdateManager/GtkProgress.py:120
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "S'està baixant el fitxer %(current)li de %(total)li"

#: ../UpdateManager/UpdateManager.py:302
#, python-format
msgid "Version %s: \n"
msgstr "Versió %s: \n"

#: ../UpdateManager/UpdateManager.py:359
msgid "Downloading list of changes..."
msgstr "S'està descarregant la llista de canvis..."

#: ../UpdateManager/UpdateManager.py:399
msgid "_Uncheck All"
msgstr "_Desmarca-ho tot"

#: ../UpdateManager/UpdateManager.py:405
msgid "_Check All"
msgstr "_Marca-ho tot"

#: ../UpdateManager/UpdateManager.py:449
#, python-format
msgid "%s selected. Download size: %s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:454
msgid "Unknown download size"
msgstr "Mida de la baixada desconeguda"

#: ../UpdateManager/UpdateManager.py:462
msgid ""
"It is unknown when the package information was updated last. Please try "
"clicking on the 'Check' button to update the information."
msgstr ""
"No s'ha pogut determinar quan es va actualitzar la informació dels paquets "
"per darrera vegada. Feu clic al botó «Comprova» per a actualitzar-la."

#: ../UpdateManager/UpdateManager.py:471
#, python-format
msgid "The package information was last updated %s day ago."
msgid_plural "The package information was last updated %s days ago."
msgstr[0] ""
"La informació dels paquets s'ha actualitzat per darrer cop fa %s dia."
msgstr[1] ""
"La informació dels paquets s'ha actualitzat per darrer cop fa %s dies."

#: ../UpdateManager/UpdateManager.py:475
#, python-format
msgid "The package information was last updated %s hour ago."
msgid_plural "The package information was last updated %s hours ago."
msgstr[0] ""
"La informació dels paquets s'ha actualitzat per darrer cop fa %s hora."
msgstr[1] ""
"La informació dels paquets s'ha actualitzat per darrer cop fa %s hores."

#: ../UpdateManager/UpdateManager.py:479
msgid "The package information was last updated less than one hour ago."
msgstr ""
"La informació dels paquets s'ha actualitzat per darrer cop fa menys d'un "
"hora."

#: ../UpdateManager/UpdateManager.py:487 ../data/glade/UpdateManager.ui.h:22
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""
"Les actualitzacions de programari corregeixen errors, eliminen problemes de "
"seguretat i proporcionen prestacions noves."

#: ../UpdateManager/UpdateManager.py:503
msgid "Welcome to Ubuntu"
msgstr "Benvingut a l'Ubuntu"

#: ../UpdateManager/UpdateManager.py:504
msgid ""
"These software updates have been issued since Ubuntu was released. If you "
"don't want to install them now, choose \"Update Manager\" from the "
"Administration Menu later."
msgstr ""
"Aquestes actualitzacions de programari son posteriors al llançament "
"d'Ubuntu. Si no voleu instal·lar-les ara, trieu més tard \"Gestor "
"d'actualitzacions\" del menú d'administració."

#: ../UpdateManager/UpdateManager.py:507
msgid "Software updates are available for this computer"
msgstr "Hi ha actualitzacions de programari per a aquest ordinador"

#: ../UpdateManager/UpdateManager.py:508
msgid ""
"If you don't want to install them now, choose \"Update Manager\" from the "
"Administration menu later."
msgstr ""
"Si no les voleu instal·lar ara, trieu \"Gestor d'actualitzacions\" des del "
"menú d'administració més tard."

#: ../UpdateManager/UpdateManager.py:556
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""
"L'actualització requereix %s d'espai lliure al disc «%s». Hauríeu "
"d'alliberar almenys %s d'espai de disc a «%s». Buideu la vostra paperera i "
"esborreu els paquets temporals utilitzant «sudo apt-get clean»."

#: ../UpdateManager/UpdateManager.py:593
#: ../UpdateManagerHildon/UpdateManagerHildon.py:114
msgid "Reading package information"
msgstr "S'està llegint la informació dels paquets"

#: ../UpdateManager/UpdateManager.py:710
msgid "Could not initialize the package information"
msgstr "No es pot inicialitzar la informació dels paquets"

#: ../UpdateManager/UpdateManager.py:711
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""
"S'ha produït un error irresoluble mentre s'inicialitzava la informació de "
"paquets.\n"
"\n"
"Informeu d'aquest error de l'update-manager i incloeu el missatge següent:\n"

#: ../UpdateManager/UpdateManager.py:733
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""
"S'ha produït un error irresoluble mentre es calculava l'actualització.\n"
"\n"
"Informeu d'aquest error de l'update-manager i incloeu el missatge següent:"

#: ../UpdateManager/UpdateManager.py:756
msgid " (New install)"
msgstr ""

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:760
#, python-format
msgid "(Size: %s)"
msgstr "(Mida: %s)"

#: ../UpdateManager/UpdateManager.py:762
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr "De la versió %(old_version)s a la %(new_version)s"

#: ../UpdateManager/UpdateManager.py:766
#, python-format
msgid "Version %s"
msgstr "Versió %s"

#: ../UpdateManager/UpdateManager.py:779
msgid "Your Ubuntu release is not supported anymore"
msgstr ""

#: ../UpdateManager/UpdateManager.py:780
msgid ""
"You will not get any further security fixes or critical updates. Please "
"Upgrade to a later version of Ubuntu Linux."
msgstr ""

#: ../UpdateManager/UpdateManager.py:787
msgid "Upgrade information"
msgstr "Informació de l'actualització"

#: ../UpdateManager/UpdateManager.py:814
#, python-format
msgid "<b>New Ubuntu release '%s' is available</b>"
msgstr ""

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:853
msgid "Software index is broken"
msgstr "L'índex de programari està trencat"

#: ../UpdateManager/UpdateManager.py:854
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""
"No és possible instal·lar o desinstal·lar programari. Per a arreglar-ho, "
"utilitzeu el gestor de paquets «Synaptic» o executeu «sudo apt-get install -"
"f» en un terminal."

#: ../UpdateManagerHildon/UpdateManagerHildon.py:136
msgid "Downloading Package Information"
msgstr "S'està baixant la informació dels paquets"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:137
msgid ""
"The repositories are being checked for new, removed, or updated software "
"packages"
msgstr ""
"S'està comprovant als repositoris si es disposa de paquets nous, eliminats o "
"actualitzats"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:145
msgid "Downloading Package Updates"
msgstr "S'estan baixant les actualitzacions dels paquets"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:146
msgid ""
"The selected package updates are being downloaded and installed on the system"
msgstr ""
"Les actualitzacions seleccionades s'estan baixant i instal·lant al sistema"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:152
msgid "run_synaptic called with unknown action"
msgstr "S'ha cridat run_synaptic amb una acció desconeguda"

#: ../UpdateManagerText/UpdateManagerText.py:26
msgid "Cancel"
msgstr "Cancel·la"

#: ../UpdateManagerText/UpdateManagerText.py:27
msgid "Install"
msgstr "Instal·la"

#: ../UpdateManagerText/UpdateManagerText.py:45
msgid "Building Updates List"
msgstr "S'està construint la llista d'actualitzacions"

#: ../UpdateManagerText/UpdateManagerText.py:48
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" ◦ A previous upgrade which didn't complete\n"
" ◦ Problems with some of the installed software\n"
" ◦ Unofficial software packages not provided by Ubuntu\n"
" ◦ Normal changes of a pre-release version of Ubuntu"
msgstr ""
"\n"
"No es pot calcular una actualització normal, executeu: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"Les causes d'això poden ser:\n"
" ◦ Una actualització prèvia no s'ha completat\n"
" ◦ Problemes amb programari instal·lat\n"
" ◦ Paquets de programari no oficial que no estan proveïts per l'Ubuntu\n"
" ◦ Canvis normals en una versió de desenvolupament de l'Ubuntu"

#: ../UpdateManagerText/UpdateManagerText.py:117
msgid "Downloading changelog"
msgstr "S'està baixant el registre de canvis"

#: ../UpdateManager/Core/MyCache.py:108
#, python-format
msgid "Other updates (%s)"
msgstr "Altres actualitzacions (%s)"

#: ../UpdateManager/Core/MyCache.py:227
#, python-format
msgid ""
"Changes for the versions:\n"
"%s\n"
"%s\n"
"\n"
msgstr ""

#: ../UpdateManager/Core/MyCache.py:229
msgid "This change is not coming from a source that supports changelogs."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:237
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"El fitxer de canvis no conté canvis rellevants.\n"
"\n"
"Vegeu http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"mentre els canvis no estan disponobles o torneu a provar-ho més tard."

#: ../UpdateManager/Core/MyCache.py:242
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"La llista de canvis encara no està disponible.\n"
"\n"
"Utilitzeu http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"mentre els canvis no estiguin disponibles o torneu a provar-ho més tard."

#: ../UpdateManager/Core/MyCache.py:248
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""
"S'ha produït un error en baixar la llista de canvis. \n"
"Comproveu la vostra connexió a Internet."

#: ../UpdateManager/Core/UpdateList.py:50
msgid "Failed to detect distribution"
msgstr "No s'ha pogut detectar la distribució"

#: ../UpdateManager/Core/UpdateList.py:51
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr ""
"S'ha produït un error «%s» mentre es comprovava el sistema que esteu "
"utilitzant."

#: ../UpdateManager/Core/UpdateList.py:62
msgid "Important security updates"
msgstr "Actualitzacions de seguretat importants"

#: ../UpdateManager/Core/UpdateList.py:63
msgid "Recommended updates"
msgstr "Actualitzacions recomanades"

#: ../UpdateManager/Core/UpdateList.py:64
msgid "Proposed updates"
msgstr "Actualitzacions proposades"

#: ../UpdateManager/Core/UpdateList.py:65
msgid "Backports"
msgstr "Backports"

#: ../UpdateManager/Core/UpdateList.py:66
msgid "Distribution updates"
msgstr "Actualitzacions de la distribució"

#: ../UpdateManager/Core/UpdateList.py:71
msgid "Other updates"
msgstr "Altres actualitzacions"

#: ../UpdateManager/Core/UpdateList.py:80
msgid "Previous selected"
msgstr "Seleccionat prèviament"

#: ../data/glade/UpdateManager.ui.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""
"<b><big>Heu de comprovar les actualitzacions manualment</big></b>\n"
"\n"
"El vostre sistema no comprova les actualitzacions automàticament. Si voleu "
"que ho faci, configureu-ho a <i>Fonts de programari</i> a la pestanya "
"<i>Actualitzacions</i>."

#: ../data/glade/UpdateManager.ui.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr ""
"<big><b>No s'han pogut instal·lar totes les actualitzacions</b></big>"

#: ../data/glade/UpdateManager.ui.h:5
msgid "<big><b>Running on battery</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:6
msgid "<big><b>Starting Update Manager</b></big>"
msgstr "<big><b>S'està iniciant el gestor d'actualitzacions</b></big>"

#: ../data/glade/UpdateManager.ui.h:7
msgid "Changes"
msgstr "Canvis"

#: ../data/glade/UpdateManager.ui.h:8
msgid "Chec_k"
msgstr "Compro_va"

#: ../data/glade/UpdateManager.ui.h:9
msgid "Co_ntinue"
msgstr "Co_ntinua"

#: ../data/glade/UpdateManager.ui.h:10
msgid "Description"
msgstr "Descripció"

#: ../data/glade/UpdateManager.ui.h:11
msgid "Description of update"
msgstr "Descripció de l'actualització"

#: ../data/glade/UpdateManager.ui.h:13
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" &#x25E6; A previous upgrade which didn't complete\n"
" &#x25E6; Problems with some of the installed software\n"
" &#x25E6; Unofficial software packages not provided by Ubuntu\n"
" &#x25E6; Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:20
msgid "Settings..."
msgstr ""

#: ../data/glade/UpdateManager.ui.h:21
msgid "Show progress of individual files"
msgstr "Mostra el progrés dels fitxers individuals"

#: ../data/glade/UpdateManager.ui.h:23
msgid "U_pgrade"
msgstr "_Actualitza"

#: ../data/glade/UpdateManager.ui.h:24 ../data/update-manager.desktop.in.h:3
#: ../data/update-manager-hildon.desktop.in.h:3
msgid "Update Manager"
msgstr "Gestor d'actualitzacions"

#: ../data/glade/UpdateManager.ui.h:25
msgid "Your system is running on battery. Are you sure you want to continue?"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:26
msgid "_Hide this information in the future"
msgstr "_En el futur oculta aquesta informació"

#: ../data/glade/UpdateManager.ui.h:27
msgid "_Install Updates"
msgstr "_Instal·la les actualitzacions"

#: ../data/glade/UpdateManager.ui.h:28
msgid "_Partial Upgrade"
msgstr "Actualització _parcial"

#: ../data/glade/UpdateManager.ui.h:29
msgid "_Upgrade"
msgstr "_Actualitza"

#: ../data/glade/UpdateManager.ui.h:30
msgid "updates"
msgstr "actualitzacions"

#: ../data/update-manager.desktop.in.h:1
#: ../data/update-manager-hildon.desktop.in.h:1
msgid "Show and install available updates"
msgstr "Mostra i instal·la les actualitzacions disponibles"

#: ../data/update-manager.desktop.in.h:2
#: ../data/update-manager-hildon.desktop.in.h:2
msgid "Software Updates"
msgstr "Actualitzacions de programari"

#: ../data/update-manager.schemas.in.h:1
msgid "*deprecated* Check for new distribution releases"
msgstr "*obsolet* Comprova si hi ha distribucions noves"

#: ../data/update-manager.schemas.in.h:2
msgid "Auto close the install window after successful install"
msgstr ""
"Tanca automàticament la finestra de l'instal·lador després d'una "
"instal·lació satisfactòria"

#: ../data/update-manager.schemas.in.h:3
msgid "First run welcome message"
msgstr "Missatge de benvinguda en executar per primer cop"

#: ../data/update-manager.schemas.in.h:4
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""
"Si no activeu la comprovació automàtica d'actualitzacions, haureu de "
"recarregar manualment la llista de canals. Aquesta opció us permet ocultar "
"la notificació que es mostra en aquest cas."

#: ../data/update-manager.schemas.in.h:5
msgid "If this key is set a first run welcome message will be presented."
msgstr ""
"Si seleccioneu aquesta opció, es presentarà un missatge de benvinguda en "
"iniciar per primer cop."

#: ../data/update-manager.schemas.in.h:6
msgid ""
"If this key is set the install window will be automatically closed on "
"successful installation."
msgstr ""
"Si es defineix aquesta clau, la finestra de l'instal·lador es tancarà de "
"manera automàtica després d'una instal·lació satisfactòria."

#: ../data/update-manager.schemas.in.h:7
msgid ""
"If this key is set the main update list window will show version information "
"(from version to version)."
msgstr ""
"Si establiu aquesta clau, la finestra principal amb la llista "
"d'actualització mostrarà la informació de versió (de la versió a la versió)."

#: ../data/update-manager.schemas.in.h:8
msgid "Remind to reload the channel list"
msgstr "Recorda'm de recarregar la llista de canals"

#: ../data/update-manager.schemas.in.h:9
msgid "Show details of an update"
msgstr "Mostra els detalls d'una actualització"

#: ../data/update-manager.schemas.in.h:10
msgid "Show version in update list"
msgstr "Mostra la versió a la llista d'actualització"

#: ../data/update-manager.schemas.in.h:11
msgid "Stores the size of the update-manager dialog"
msgstr "Emmagatzema la mida del diàleg del gestor d'actualitzacions"

#: ../data/update-manager.schemas.in.h:12
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr ""
"Emmagatzema l'estat de l'expansor que conté la llista de canvis i la "
"descripció"

#: ../data/update-manager.schemas.in.h:13
msgid "The window size"
msgstr "La mida de la finestra"

#: ../data/update-manager.schemas.in.h:14
msgid ""
"This key is deprecated in favor of the file /etc/update-manager/release-"
"upgrades Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""
"Aquesta clau és obsoleta en favor del fitxer /etc/update-manager/release-"
"upgrades. Comprova automàticament si es disposa d'una nova versió de la "
"distribució actual i, si és possible, n'ofereix l'actualització"

#: ../update-manager:56
msgid "Show version and exit"
msgstr "Mostra la versió i surt"

#: ../update-manager:59
msgid "Directory that contains the data files"
msgstr ""

#: ../update-manager:62
msgid "Check if a new Ubuntu release is available"
msgstr ""

#: ../update-manager:65 ../do-release-upgrade:23 ../check-new-release:24
msgid "Check if upgrading to the latest devel release is possible"
msgstr ""
"Comprova si és possible actualitzar a la darrera versió de desenvolupament"

#: ../update-manager:69
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""
"Duu a terme l'actualització utilitzant la darrera versió proposada de "
"l'actualitzador"

#: ../update-manager:76
msgid "Do not focus on map when starting"
msgstr "No passes a primer pla en iniciar"

#: ../update-manager:79
msgid "Try to run a dist-upgrade"
msgstr "Prova d'executar un dist-upgrade"

#: ../update-manager:83 ../do-release-upgrade:39
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "Prova d'actualitzar en un entorn de proves amb aufs"

#: ../update-manager:103
msgid "Running partial upgrade"
msgstr "S'està executant una actualització parcial"

#: ../do-release-upgrade:27 ../check-new-release:28
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Proveu d'actualitzar a l'última versió fent servir l'actualitzador de "
"$distro-proposed"

#: ../do-release-upgrade:31
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Executeu un mode d'actualització especial.\n"
"Actualment disposeu del mode «desktop» per a actualitzacions de sistemes "
"d'escriptori i del mode «server» per a sistemes servidors."

#: ../do-release-upgrade:37
msgid "Run the specified frontend"
msgstr "Executa el frontal especificat"

#: ../do-release-upgrade:43
msgid "Checking for a new ubuntu release"
msgstr "S'està comprovant si hi ha una versió nova de l'Ubuntu"

#: ../do-release-upgrade:50
msgid "No new release found"
msgstr "No s'ha trobat cap versió nova"

#: ../check-new-release:32
#, c-format
msgid ""
"Do not output anything, just return %s if there is a new release and %s if "
"there is none."
msgstr ""
"No es mostra cap sortida, només es retorna %s si hi ha una nova versió i %s "
"si no en hi ha cap."

#: ../check-new-release:46
#, c-format
msgid "New release '%s' available."
msgstr "La versió nova «%s» ja està disponible"

#: ../check-new-release:47
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "Executeu «do-release-upgrade» per actualitzar a la nova versió."

#: ../Janitor/computerjanitor/exc.py:30
#, python-format
msgid "Unimplemented method: %s"
msgstr "El mètode %s no està implementat"

#: ../Janitor/computerjanitor/file_cruft.py:46
msgid "A file on disk"
msgstr "Un fitxer en disc"

#: ../Janitor/computerjanitor/package_cruft.py:45
msgid ".deb package"
msgstr "Paquet .deb"

#: ../Janitor/computerjanitor/missing_package_cruft.py:33
msgid "Install missing package."
msgstr "Instal·la el paquet que falta."

#: ../Janitor/computerjanitor/missing_package_cruft.py:42
#, python-format
msgid "Package %s should be installed."
msgstr "El paquet %s s'hauria d'instal·lar."

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:36
#, python-format
msgid "%i obsolete entries in the status file"
msgstr "%i entrades obsoletes en el fitxer status"

#: ../Janitor/plugins/dpkg_status_plugin.py:39
msgid "Obsolete entries in dpkg status"
msgstr "Entrades obsoletes a dpkg status"

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:42
msgid "Obsolete dpkg status entries"
msgstr "Entrades obsoletes a dpkg status"

#: ../Janitor/plugins/kdelibs4to5_plugin.py:39
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""

#: ../Janitor/plugins/langpack_manual_plugin.py:34
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr "%s s'ha de marcar com a instal·lat manualment."

#: ../Janitor/plugins/remove_lilo_plugin.py:28
msgid ""
"Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr ""
"Esborra el lilo ja que el grub també està instal·lat (Si voleu més detalls "
"vegeu l'error #314004)"

#~ msgid ""
#~ "This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
#~ "version of this driver is available that works with your video card in "
#~ "Ubuntu 8.10.\n"
#~ "\n"
#~ "Do you want to continue?"
#~ msgstr ""
#~ "Aquest ordinador està utilitzant el controlador gràfic de NVDIA «nvidia». "
#~ "L'Ubuntu 8.10 no disposa d'una versió funcional d'aquest controlador per a "
#~ "la vostra targeta gràfica.\n"
#~ "\n"
#~ "Voleu continuar?"

#~ msgid "Check if a new distribution release is available"
#~ msgstr "Comprova si hi ha una versió nova de la distribució disponible"

#~ msgid "Upgrade to the latest version of Ubuntu"
#~ msgstr "Actualitza a la versió més actual de l'Ubuntu"

#~ msgid "Check the software channels for new updates"
#~ msgstr "Comprova si hi ha actualitzacions noves als canals de programari"

#, python-format
#~ msgid "<b>New distribution release '%s' is available</b>"
#~ msgstr "<b>Ja està disponible la nova distribució «%s»</b>"

#~ msgid "Your distribution is not supported anymore"
#~ msgstr "La vostra distribució ja no es mantindrà més"

#~ msgid "Verfication failed"
#~ msgstr "Ha fallat la verificació"

#~ msgid ""
#~ "A unresolvable problem occurred while calculating the upgrade.\n"
#~ "\n"
#~ "Please report this bug against the 'update-manager' package and include the "
#~ "files in /var/log/dist-upgrade/ in the bugreport."
#~ msgstr ""
#~ "S'ha produït un problema irresoluble en calcular l'actualització.\n"
#~ "\n"
#~ "Informeu de l'error, referent al paquet update-manager, i adjunteu tots els "
#~ "fitxers de /var/log/dist-upgrade/ en l'informe."

#~ msgid ""
#~ "The upgrade aborts now. Your system could be in an unusable state. A "
#~ "recovery was run (dpkg --configure -a)."
#~ msgstr ""
#~ "L'actualització s'ha cancel·lat. Pot ser que el sistema hagi quedat "
#~ "inusable. S'ha executat una recuperació (dpkg --configure -a)."
