# Kashubian translation for update-manager
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the update-manager package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2007-03-15 18:56+0100\n"
"PO-Revision-Date: 2006-10-08 04:10+0000\n"
"Last-Translator: Michôł Òstrowsczi <ostrowski.michal@gmail.com>\n"
"Language-Team: Kashubian <csb@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
"|| n%100>=20) ? 1 : 2\n"

#: ../DistUpgrade/DistUpgradeCache.py:91
msgid "Broken packages"
msgstr "Paczétë są zmiłkòwé"

#: ../DistUpgrade/DistUpgradeCache.py:92
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:262
msgid "Can't upgrade required meta-packages"
msgstr "Nie je mòżno zaktualizowac wëmôgónëch meta-paczétów"

#: ../DistUpgrade/DistUpgradeCache.py:266
msgid "A essential package would have to be removed"
msgstr ""

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:269
#: ../UpdateManager/UpdateManager.py:846
msgid "Could not calculate the upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:270
msgid ""
"A unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bugreport."
msgstr ""

#. FIXME: maybe ask a question here? instead of failing?
#: ../DistUpgrade/DistUpgradeCache.py:304
msgid "Error authenticating some packages"
msgstr "Fela òbczas ùdowierzaniô niechtërnëch paczétów"

#: ../DistUpgrade/DistUpgradeCache.py:305
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:406
#, python-format
msgid "Can't install '%s'"
msgstr "Nie je mòżno zainstalowac '%s'"

#: ../DistUpgrade/DistUpgradeCache.py:407
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""
"Nie bëło mòżna zainstalowac wëmôgónegò paczétu. Proszã zgłoszëc to jakno "
"felã. "

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:414
msgid "Can't guess meta-package"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:415
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop or edubuntu-"
"desktop package and it was not possible to detect which version of Ubuntu "
"you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:79
msgid "Failed to add the CD"
msgstr "Nie je mòżno dodac platë CD"

#: ../DistUpgrade/DistUpgradeControler.py:80
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:112
msgid "Reading cache"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:164
msgid "Continue running under SSH?"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:165
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, a additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:178
msgid "Starting additional sshd"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:179
#, python-format
msgid ""
"To make recovery in case of failure easier a additional sshd will be started "
"on port '%s'. If anything goes wrong with the running ssh you can still "
"connect to the additional one.\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:222
msgid "Include latest updates from the Internet?"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:223
msgid ""
"The upgrade process can automatically download the latest updates and "
"install them during the upgrade.  The upgrade will take longer, but when it "
"is complete, your system will be fully up to date.  You can choose not to do "
"this, but you should install the latest updates soon after upgrading."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:326
msgid "No valid mirror found"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:327
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found.This cam happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'no' the update will cancel."
msgstr ""

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeControler.py:344
msgid "Generate default sources?"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:345
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No' the update will "
"cancel."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:379
msgid "Repository information invalid"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:380
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:386
msgid "Third party sources disabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:387
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:444
msgid "Error during update"
msgstr "Fela òbczas aktualizacëji"

#: ../DistUpgrade/DistUpgradeControler.py:445
msgid ""
"A problem occured during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:454
msgid "Not enough free disk space"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:455
#, python-format
msgid ""
"The upgrade aborts now. Please free at least %s of disk space on %s. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""

#. ask the user if he wants to do the changes
#: ../DistUpgrade/DistUpgradeControler.py:521
msgid "Do you want to start the upgrade?"
msgstr "CZë chcesz zrëszëc aktualizacëjã?"

#. invoke the frontend now
#: ../DistUpgrade/DistUpgradeControler.py:547
msgid ""
"The upgrade aborts now. Your system could be in an unusable state. A "
"recovery was run (dpkg --configure -a)."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:551
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bugreport.\n"
"%s"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:555
msgid "Could not install the upgrades"
msgstr "Instalacëja aktualizacëji nie darzëła sã."

#: ../DistUpgrade/DistUpgradeControler.py:567
msgid "Could not download the upgrades"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:568
msgid ""
"The upgrade aborts now. Please check your internet connection or "
"installation media and try again. "
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:608
msgid "Support for some applications ended"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:609
msgid ""
"Canonical Ltd. no longer provides support for the following software "
"packages. You can still get support from the community.\n"
"\n"
"If you have not enabled community maintained software (universe), these "
"packages will be suggested for removal in the next step."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:644
msgid "Remove obsolete packages?"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:645
msgid "_Skip This Step"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:645
msgid "_Remove"
msgstr "_Rëmôj"

#: ../DistUpgrade/DistUpgradeControler.py:656
msgid "Error during commit"
msgstr "Fela òbczas zacwierdzaniô"

#: ../DistUpgrade/DistUpgradeControler.py:657
msgid ""
"A problem occured during the clean-up. Please see the below message for more "
"information. "
msgstr ""

#. generate a new cache
#: ../DistUpgrade/DistUpgradeControler.py:669
msgid "Restoring original system state"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:723
#, python-format
msgid "Fetching backport of '%s'"
msgstr ""

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeControler.py:758
#: ../DistUpgrade/DistUpgradeControler.py:801
msgid "Checking package manager"
msgstr "Sprôwdzanié menadżera paczétów"

#: ../DistUpgrade/DistUpgradeControler.py:763
msgid "Preparing the upgrade failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:764
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bugreport."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:787
msgid "Updating repository information"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:812
msgid "Invalid package information"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:813
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the "
"bugreport."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:825
msgid "Asking for confirmation"
msgstr ""

#. no do the upgrade
#: ../DistUpgrade/DistUpgradeControler.py:832
msgid "Upgrading"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:839
msgid "Searching for obsolete software"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:844
msgid "System upgrade is complete."
msgstr ""

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:101
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:119
msgid "Fetching is complete"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:130
#, python-format
msgid "Fetching file %li of %li at %sb/s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:131
#: ../DistUpgrade/DistUpgradeViewGtk.py:256
#, python-format
msgid "About %s remaining"
msgstr "Òsta kòl %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:133
#, python-format
msgid "Fetching file %li of %li"
msgstr ""

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:165
msgid "Applying changes"
msgstr "Zacwierdzanié zmianów"

#: ../DistUpgrade/DistUpgradeViewGtk.py:190
#, python-format
msgid "Could not install '%s'"
msgstr "Nie bëło mòżno zainstalowac '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:191
msgid ""
"The upgrade aborts now. Please report this bug against the 'update-manager' "
"package and include the files in /var/log/dist-upgrade/ in the bugreport."
msgstr ""

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:206
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Zastãpic swójny lopk kònfigùracëji\n"
"'%s'?"

#: ../DistUpgrade/DistUpgradeViewGtk.py:207
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:220
msgid "The 'diff' command was not found"
msgstr "Pòlét 'diff' nie òsta nalazłé"

#: ../DistUpgrade/DistUpgradeViewGtk.py:390
msgid "A fatal error occured"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:391
msgid ""
"Please report this as a bug (if you haven't already) and include thefiles /"
"var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade aborts now.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#. FIXME: make those two seperate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeViewGtk.py:526
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d paczét òstanié rëmniãty."
msgstr[1] "%d paczétë òstaną rëmniãte."
msgstr[2] "%d paczétów òstaną rëmniãtëch."

#: ../DistUpgrade/DistUpgradeViewGtk.py:531
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d nowi paczétë òstaną zainstalowóne."
msgstr[1] "%d nowi paczét òstanie zainstalowóny."
msgstr[2] "%d nowëch paczétów òstanie zainstalowónëch."

#: ../DistUpgrade/DistUpgradeViewGtk.py:537
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d paczét òstanié zaktualizowóny."
msgstr[1] "%d paczétë òstaną zaktualizowóne."
msgstr[2] "%d paczétów òstanie zaktualizowónëch."

#: ../DistUpgrade/DistUpgradeViewGtk.py:542
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:548
msgid ""
"Fetching and installing the upgrade can take several hours and cannot be "
"canceled at any time later."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:551
msgid "To prevent data loss close all open applications and documents."
msgstr ""

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeViewGtk.py:557
#: ../UpdateManager/UpdateManager.py:635
msgid "Your system is up-to-date"
msgstr "Twojô systema je fùl zaktualizowónô"

#: ../DistUpgrade/DistUpgradeViewGtk.py:558
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr "Felëjë przistãpnëch aktualizacëjów. Aktualizacëjô òstanié òprzestónô."

#: ../DistUpgrade/DistUpgradeViewGtk.py:574
#, python-format
msgid "<b>Remove %s</b>"
msgstr "<b>Rëmôj %s</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:576
#, python-format
msgid "Install %s"
msgstr "Instalëjë %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:578
#, python-format
msgid "Upgrade %s"
msgstr "Aktualizëjë %s"

#: ../DistUpgrade/DistUpgradeView.py:33
#, python-format
msgid "%li days %li hours %li minutes"
msgstr "%li dni %li gòdzin %li minut"

#: ../DistUpgrade/DistUpgradeView.py:35
#, python-format
msgid "%li hours %li minutes"
msgstr "%li gòdzin %li minut"

#: ../DistUpgrade/DistUpgradeView.py:37
#, python-format
msgid "%li minutes"
msgstr "%li minut"

#: ../DistUpgrade/DistUpgradeView.py:38
#, python-format
msgid "%li seconds"
msgstr "%li sekùnd"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:44
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:135
msgid "Reboot required"
msgstr "Wëmògóne je zrëszenié kòmpùtra znowa"

#: ../DistUpgrade/DistUpgradeView.py:136
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"Aktualizacëjô òsta zakùńczonô ë nót je zrëszëc kòmpùtr znowa. Zrobic to terô?"

#: ../DistUpgrade/dist-upgrade.py:15
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr ""

#: ../DistUpgrade/dist-upgrade.py:21
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""

#: ../DistUpgrade/dist-upgrade.py:24
msgid ""
"Use special upgrade mode. Available:\n"
"desktop, server"
msgstr ""

#. testcode to see if the bullets look nice in the dialog
#. for i in range(4):
#. view.setStep(i+1)
#. app.openCache()
#: ../DistUpgrade/DistUpgrade.glade.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.glade.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:5
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Zrëszë kòpmùtr znowa, żebë zakùńczëc aktualizacëjã</big></b>"

#: ../DistUpgrade/DistUpgrade.glade.h:6
msgid "<b><big>Start the upgrade?</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:7
#, fuzzy
msgid "<b><big>Upgrading Ubuntu to version 7.04</big></b>"
msgstr "<b></big>Aktualizacëjô Ubuntu do wersëji 6.10</big></b>"

#: ../DistUpgrade/DistUpgrade.glade.h:8
msgid "Cleaning up"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:9
msgid "Details"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:10
msgid "Difference between the files"
msgstr "Zjinaczi midze lopkama"

#: ../DistUpgrade/DistUpgrade.glade.h:11
msgid "Fetching and installing the upgrades"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:12
msgid "Modifying the software channels"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:13
msgid "Preparing the upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:14
msgid "Restarting the system"
msgstr "Zrëszanié znowa systemë"

#: ../DistUpgrade/DistUpgrade.glade.h:15
msgid "Terminal"
msgstr "Terminal"

#: ../DistUpgrade/DistUpgrade.glade.h:16
msgid "_Cancel Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:17
msgid "_Continue"
msgstr "Ò_przestanié aktualizacëji"

#: ../DistUpgrade/DistUpgrade.glade.h:18
msgid "_Keep"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:19
msgid "_Replace"
msgstr "_Zastãpi"

#: ../DistUpgrade/DistUpgrade.glade.h:20
msgid "_Report Bug"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:21
msgid "_Restart Now"
msgstr "_Zrëszë znowa"

#: ../DistUpgrade/DistUpgrade.glade.h:22
msgid "_Resume Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:23
msgid "_Start Upgrade"
msgstr "_Startëjë aktualizacëjã"

#: ../UpdateManager/DistUpgradeFetcher.py:65
msgid "Could not find the release notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:66
msgid "The server may be overloaded. "
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:76
msgid "Could not download the release notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:77
msgid "Please check your internet connection."
msgstr ""

#: ../UpdateManager/GtkProgress.py:108
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr ""

#: ../UpdateManager/GtkProgress.py:113
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr ""

#: ../UpdateManager/UpdateManager.py:209
msgid "The list of changes is not available"
msgstr ""

#: ../UpdateManager/UpdateManager.py:215
msgid ""
"The list of changes is not available yet.\n"
"Please try again later."
msgstr ""

#: ../UpdateManager/UpdateManager.py:220
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""

#: ../UpdateManager/UpdateManager.py:241
msgid "Important security updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:243
msgid "Recommended updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:244
msgid "Proposed updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:245
msgid "Backports"
msgstr ""

#: ../UpdateManager/UpdateManager.py:246
msgid "Distribution updates"
msgstr ""

#. TRANSLATORS: updates from an 'unknown' origin
#: ../UpdateManager/UpdateManager.py:253 ../UpdateManager/UpdateManager.py:270
msgid "Other updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:485
#, python-format
msgid "Version %s: \n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:546
msgid "Downloading list of changes..."
msgstr ""

#: ../UpdateManager/UpdateManager.py:573
msgid "_Uncheck All"
msgstr ""

#: ../UpdateManager/UpdateManager.py:579
msgid "_Check All"
msgstr ""

#. TRANSLATORS: b stands for Bytes
#: ../UpdateManager/UpdateManager.py:623 ../UpdateManager/UpdateManager.py:650
#, python-format
msgid "Download size: %s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:627
msgid "Unknown download size"
msgstr ""

#: ../UpdateManager/UpdateManager.py:646
#, python-format
msgid "You can install %s update"
msgid_plural "You can install %s updates"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""

#: ../UpdateManager/UpdateManager.py:679
msgid "Please wait, this can take some time."
msgstr ""

#: ../UpdateManager/UpdateManager.py:681
msgid "Update is complete"
msgstr ""

#: ../UpdateManager/UpdateManager.py:732
msgid "Checking for updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:824
#, fuzzy
msgid "Could not initialize the package information"
msgstr "Instalacëja aktualizacëji nie darzëła sã."

#: ../UpdateManager/UpdateManager.py:825
msgid ""
"A unresolvable problem occurred while initializing the package information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:847
msgid ""
"A unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""

#: ../UpdateManager/UpdateManager.py:872
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:876
#, python-format
msgid "Version %s"
msgstr ""

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:878
#, python-format
msgid "(Size: %s)"
msgstr ""

#: ../UpdateManager/UpdateManager.py:889
msgid "Your distribution is not supported anymore"
msgstr ""

#: ../UpdateManager/UpdateManager.py:890
msgid ""
"You will not get any further security fixes or critical updates. Upgrade to "
"a later version of Ubuntu Linux. See http://www.ubuntu.com for more "
"information on upgrading."
msgstr ""

#: ../UpdateManager/UpdateManager.py:905
msgid "Downloading the upgrade tool"
msgstr ""

#: ../UpdateManager/UpdateManager.py:907
msgid "The upgrade tool will guide you through the upgrade process."
msgstr ""

#: ../UpdateManager/UpdateManager.py:915
#, python-format
msgid "<b>New distribution release '%s' is available</b>"
msgstr ""

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:954
msgid "Software index is broken"
msgstr ""

#: ../UpdateManager/UpdateManager.py:955
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:112
msgid "Could not run the upgrade tool"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:113
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:129
msgid "Upgrade tool signature"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:132
msgid "Upgrade tool"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:156
msgid "Failed to fetch"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:157
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:161
msgid "Failed to extract"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:162
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:167
msgid "Verfication failed"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:168
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:173
msgid "Authentication failed"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:174
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""

#: ../data/glade/UpdateManager.glade.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Internet Updates</i> tab."
msgstr ""

#: ../data/glade/UpdateManager.glade.h:4
msgid "<big><b>Keep your system up-to-date</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:5
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:6
#, fuzzy
msgid "<big><b>Starting Update Manager</b></big>"
msgstr ""
"<big><b>Wëstśpiła fela òbczas skanowania platë CD</b></big>\n"
"\n"
"%s"

#: ../data/glade/UpdateManager.glade.h:7
msgid "Changes"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:8
msgid "Chec_k"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:9
msgid "Check the software channels for new updates"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:10
msgid "Description"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:11
msgid "Description of update"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:12
msgid "Release Notes"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:13
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" ◦ A previous upgrade which didn't complete\n"
" ◦ Unofficial software packages not provided by Ubuntu\n"
" ◦ Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:19
msgid "Show progress of single files"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:20
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""

#: ../data/glade/UpdateManager.glade.h:21
msgid "U_pgrade"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:22
#: ../data/update-manager.desktop.in.h:3
msgid "Update Manager"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:23
msgid "Upgrade to the latest version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:24
msgid "_Check"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:25
msgid "_Hide this information in the future"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:26
msgid "_Install Updates"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:27
#, fuzzy
msgid "_Partial Upgrade"
msgstr "_Startëjë aktualizacëjã"

#: ../data/glade/UpdateManager.glade.h:28
msgid "_Upgrade"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:29
msgid "updates"
msgstr ""

#: ../data/update-manager.desktop.in.h:1
msgid "Show and install available updates"
msgstr ""

#: ../data/update-manager.desktop.in.h:2
msgid "System Update Tool"
msgstr ""

#: ../data/update-manager.schemas.in.h:1
msgid ""
"Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""

#: ../data/update-manager.schemas.in.h:2
msgid "Check for new distribution releases"
msgstr ""

#: ../data/update-manager.schemas.in.h:3
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""

#: ../data/update-manager.schemas.in.h:4
msgid "Remind to reload the channel list"
msgstr ""

#: ../data/update-manager.schemas.in.h:5
msgid "Show details of an update"
msgstr ""

#: ../data/update-manager.schemas.in.h:6
msgid "Stores the size of the update-manager dialog"
msgstr ""

#: ../data/update-manager.schemas.in.h:7
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr ""

#: ../data/update-manager.schemas.in.h:8
msgid "The window size"
msgstr ""

#~ msgid "Daily"
#~ msgstr "Codniowò"

#~ msgid "Every two days"
#~ msgstr "Co dwa dni"

#~ msgid "Weekly"
#~ msgstr "Co tidzeń"

#~ msgid "Every two weeks"
#~ msgstr "Co dwa tidzenie"

#~ msgid "Every %s days"
#~ msgstr "Co %s dni"

#~ msgid "After one week"
#~ msgstr "Pò tidzeniu"

#~ msgid "After two weeks"
#~ msgstr "Pò dwóch tidzeniach"

#~ msgid "After one month"
#~ msgstr "Pò miesącu"

#~ msgid "After %s days"
#~ msgstr "P %s dniach"

#~ msgid "%s updates"
#~ msgstr "%s aktualizacëji"

#~ msgid "%s (%s)"
#~ msgstr "%s (%s)"

#~ msgid "Main server"
#~ msgstr "Przédny serwera"

#~ msgid "Server for %s"
#~ msgstr "Serwera dlô kraju %s"

#~ msgid "Nearest server"
#~ msgstr "Nôblëższi serwera"

#~ msgid "Custom servers"
#~ msgstr "Jine serwerë"

#~ msgid "Software Channel"
#~ msgstr "Kanal òprogramòwania"

#~ msgid "Active"
#~ msgstr "Aktiwny"

#~ msgid "(Source Code)"
#~ msgstr "(zdrojowi kòd)"

#~ msgid "Source Code"
#~ msgstr "Zdrojowi kòd"

#~ msgid "Import key"
#~ msgstr "Impòrtëjë klucz"

#~ msgid "Error importing selected file"
#~ msgstr "Fela òbczas impòrtowania wëbrónegò lopkù"

#~ msgid "The selected file may not be a GPG key file or it might be corrupt."
#~ msgstr "Wëbróny lopk może nie bëc kluczã abò mòże bëc pòpsëti."

#~ msgid "Error removing the key"
#~ msgstr "Fela òbczas rëmaniô klucza"

#~ msgid ""
#~ "The key you selected could not be removed. Please report this as a bug."
#~ msgstr "Nie mòżna bëło rëmnąc klucza. Proszã zgłoszëc to jakno felã."

#~ msgid "Please enter a name for the disc"
#~ msgstr "Proszã dac miono dlô platë"
