# Kashubian translation for update-manager
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the update-manager package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2015-10-07 09:44-0700\n"
"PO-Revision-Date: 2013-05-22 11:00+0000\n"
"Last-Translator: Yurek Hinz <yurekh@yahoo.com>\n"
"Language-Team: Kashubian <csb@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
"|| n%100>=20) ? 1 : 2;\n"
"X-Launchpad-Export-Date: 2016-11-09 05:40+0000\n"
"X-Generator: Launchpad (build 18246)\n"
"Language: csb\n"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:211 ../DistUpgrade/distro.py:442
#, python-format
msgid "Server for %s"
msgstr "Serwera dlô kraju %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:229 ../DistUpgrade/distro.py:235
#: ../DistUpgrade/distro.py:251
msgid "Main server"
msgstr "Przédnô serwera"

#: ../DistUpgrade/distro.py:255
msgid "Custom servers"
msgstr "Jine serwerë"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:151
msgid "Could not calculate sources.list entry"
msgstr "Ni mòże òbrachòwac wpisënka w lopkù sources.list"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:260
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"Ni mòże nalezc niżódnëch lopków z paczetama, mòże to nie je disk z Ubuntu "
"abò lëchô architektura?"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:310
msgid "Failed to add the CD"
msgstr "Ni mòże dodac platë CD"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:311
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"Fela przë dodôwaniu platë CD, aktualizacëjô òprzestónô. Proszã zgłoszëc "
"rapòrt ò felë jeżlë je to òficjalnô platka Ubuntu.\n"
"\n"
"Zamkłosc felë to:\n"
"\"%s\""

#: ../DistUpgrade/DistUpgradeCache.py:154
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Rëmanié lëchegò paczétu"
msgstr[1] "Rëmanié lëchich paczétów"
msgstr[2] "Rëmanié lëchich paczétów"

#: ../DistUpgrade/DistUpgradeCache.py:157
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"Paczét \"%s\" je w niezgòdnym stónie ë je nót gò winstalowac znowa,  ni "
"òstało równak nalazłé archiwùm negò paczétu. Rëmnąc paczét terô abë jisc "
"dali?"
msgstr[1] ""
"Paczétë \"%s\" są w niezgòdnym stónie ë je nót je winstalowac znowa,  ni "
"òstało równak nalazłé archiwùm nych paczétu. Rëmnąc paczétë terô abë jisc "
"dali?"
msgstr[2] ""
"Paczétë \"%s\" są w niezgòdnym stónie ë je nót je winstalowac znowa,  ni "
"òstało równak nalazłé archiwùm nych paczétu. Rëmnąc paczétë terô abë jisc "
"dali?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:259
msgid "The server may be overloaded"
msgstr "Serwer mòże bëc przecãżony"

#: ../DistUpgrade/DistUpgradeCache.py:372
msgid "Broken packages"
msgstr "Paczétë są zepsëté"

#: ../DistUpgrade/DistUpgradeCache.py:373
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"Systema zamëkô w se zepsëté paczetë, jaczich nie szło ùprawic. Proszã wprzód "
"pòprawic je brëkùjąc menadżera paczetów Synaptic abò apt-get."

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:644
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:654
msgid "This is most likely a transient problem, please try again later."
msgstr "To są le chwilowé problemë. Proszã spróbòwac pòzdze."

#: ../DistUpgrade/DistUpgradeCache.py:657
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:662
msgid "Could not calculate the upgrade"
msgstr "Nié mòże przerobic aktualizacëjów"

#: ../DistUpgrade/DistUpgradeCache.py:721
msgid "Error authenticating some packages"
msgstr "Fela ùdowierzaniô niechtërnych paczétów"

#: ../DistUpgrade/DistUpgradeCache.py:722
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"Nie dało sã ùdowierzëc niejednych paczétów. Mòże to bëc czasowô fela sécë. "
"Mòże spróbòwac pòzdze znowa. Niżi nachôdô sã lësta nieùdowierzónych paczétów"

#: ../DistUpgrade/DistUpgradeCache.py:743
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"Paczét \"%s\" je wëbróny do rëmniãcô, je òn rówank na lësce paczétów, "
"chtërnych nie je nót rëmac."

#: ../DistUpgrade/DistUpgradeCache.py:749
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "Nóterny paczét \"%s\" je nacéchòwóny do rëmniãcô."

#: ../DistUpgrade/DistUpgradeCache.py:758
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "Próba instalacëji wersëji \"%s\", jakô je na czôrny lësce"

#: ../DistUpgrade/DistUpgradeCache.py:877
#, python-format
msgid "Can't install '%s'"
msgstr "Ni mòże winstalowac '%s'"

#: ../DistUpgrade/DistUpgradeCache.py:878
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:889
msgid "Can't guess meta-package"
msgstr "Ni mòże òpisac meta-paczétu"

#: ../DistUpgrade/DistUpgradeCache.py:890
#, python-format
msgid ""
"Your system does not contain a %s or %s package and it was not possible to "
"detect which version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:119
msgid "Reading cache"
msgstr "Czëtanié pòdrãcznegò bùfora"

#: ../DistUpgrade/DistUpgradeController.py:226
msgid "Unable to get exclusive lock"
msgstr "Ni mòże dobëc blokadë na wëłãcznotã"

#: ../DistUpgrade/DistUpgradeController.py:227
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Zwëczajno òznôczô to, że jinszô aplikacëjô do sprôwianiô paczétama (jakno "
"apt-get abò aptitude) je zrëszonô. Nót je wprzód zamknąc nã aplikacëjã."

#: ../DistUpgrade/DistUpgradeController.py:285
msgid "Upgrading over remote connection not supported"
msgstr "Aktualizacëjô przez daleczé sparłãcznie nie je wspierónô"

#: ../DistUpgrade/DistUpgradeController.py:286
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"Môsz zrëszoné aktualizacjã przez sparłãczenié ssh ë jinterfejs chtërny tegò "
"nie wspiérô. Proszã, spróbùje ùżëc tekstowégò tribu wpisëjąc 'do-release-"
"upgrade'.\n"
"Zaktualnienié òstanie przerwóné. Spróbùjë bez pòwłoczi ssh."

#: ../DistUpgrade/DistUpgradeController.py:300
msgid "Continue running under SSH?"
msgstr "Jic dali ze sparłãczeniã SSH?"

#: ../DistUpgrade/DistUpgradeController.py:301
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:315
msgid "Starting additional sshd"
msgstr "Zrëszanié dodôwnëch ùsłëżnotów ssh"

#: ../DistUpgrade/DistUpgradeController.py:316
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Dodôwny demon sshd bãdze zrëszony na pòrce '%s', abë zletczic dobëwanié "
"nazôd w przëtrôfkù problemów z aktualaną ùsłëżnotą ssh. W przëtrôfkù "
"niedarzënkù z aktualną sesëją ssh, wcyg mòże przëłączëc sã do dodôwny "
"sesëji.\n"

#: ../DistUpgrade/DistUpgradeController.py:324
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:397
#: ../DistUpgrade/DistUpgradeController.py:442
msgid "Can not upgrade"
msgstr "Nié mòże zaktualnic"

#: ../DistUpgrade/DistUpgradeController.py:398
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr ""
"Aktualizacëjô z wersëji \\\"%s\\\" do \\\"%s\\\" nie je wspierónô przez to "
"nôrzãdze."

#: ../DistUpgrade/DistUpgradeController.py:407
msgid "Sandbox setup failed"
msgstr "Nastôw tekstowégò tribù nie darzëł sã"

#: ../DistUpgrade/DistUpgradeController.py:408
msgid "It was not possible to create the sandbox environment."
msgstr "Ùsôdzanié tekstowégò òkrãżô nie bëło mòżlëwé."

#: ../DistUpgrade/DistUpgradeController.py:414
msgid "Sandbox mode"
msgstr "Tekstowi trib"

#: ../DistUpgrade/DistUpgradeController.py:415
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a system directory from now until the next reboot "
"are permanent."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:443
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"Instalacëjô python je zepsëtô. Proszã naprawic dowiązanié do "
"\"/usr/bin/python\"."

#: ../DistUpgrade/DistUpgradeController.py:472
#, python-format
msgid "Can not write to '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:473
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:484
msgid "Include latest updates from the Internet?"
msgstr "Dodac nônowszé zaktualnienia z internetu?"

#: ../DistUpgrade/DistUpgradeController.py:485
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:659
#, python-format
msgid "Not for humans during development stage of release %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:744
#, python-format
msgid "disabled on upgrade to %s"
msgstr "wëłączony przë aktualizacëji do %s"

#: ../DistUpgrade/DistUpgradeController.py:801
msgid "No valid mirror found"
msgstr "Pòprôwny szpéglowi serwer ni nalazłi"

#: ../DistUpgrade/DistUpgradeController.py:802
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run an internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:822
msgid "Generate default sources?"
msgstr "Wëgenerowac domëszlné zdroje?"

#: ../DistUpgrade/DistUpgradeController.py:823
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:858
#: ../DistUpgrade/DistUpgradeController.py:864
msgid "Repository information invalid"
msgstr "Lëchô wëdowiédzô ò repòzëtorëjach"

#: ../DistUpgrade/DistUpgradeController.py:859
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:865
msgid ""
"Upgrading the repository information resulted in a invalid file. To report a "
"bug install apport and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:874
msgid "Third party sources disabled"
msgstr "Zdoje samòstójnëch dostôwców òstałë włączoné"

#: ../DistUpgrade/DistUpgradeController.py:875
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:916
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Paczét w niezgòdnym stónie"
msgstr[1] "Paczétë w niezgòdnym stónie"
msgstr[2] "Paczétë w niezgòdnym stónie"

#: ../DistUpgrade/DistUpgradeController.py:919
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"Paczét \"%s\" je w niezgòdnym stónie ë mùszi bëc winstalowóny znowa, ni mòże "
"równak nalezc niżódnegò archiwùm negò paczétu. Proszã winstalowac paczét "
"rãczno abò rëmnąc gò z systemë."
msgstr[1] ""
"Paczétë \"%s\"są w niezgòdnym stónie ë mùszą bëc winstalowóné znowa, ni mòże "
"równak nalezc niżódnegò archiwùm nych paczétów. Proszã winstalowac paczétë "
"rãczno abò rëmnąc je z systemë."
msgstr[2] ""
"Paczétë \"%s\"są w niezgòdnym stónie ë mùszą bëc winstalowóné znowa, ni mòże "
"równak nalezc niżódnegò archiwùm nych paczétów. Proszã winstalowac paczétë "
"rãczno abò rëmnąc je z systemë."

#: ../DistUpgrade/DistUpgradeController.py:976
msgid "Error during update"
msgstr "Fela òbczas aktualizacëji"

#: ../DistUpgrade/DistUpgradeController.py:977
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:986
msgid "Not enough free disk space"
msgstr "Za mało placu na diskù"

#: ../DistUpgrade/DistUpgradeController.py:987
#, python-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of %s free space on disk "
"'%s'. Please free at least an additional %s of disk space on '%s'. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:1016
#: ../DistUpgrade/DistUpgradeController.py:1832
msgid "Calculating the changes"
msgstr "Przerôbianié zmianów"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:1048
msgid "Do you want to start the upgrade?"
msgstr "Chcesz zrëszëc aktualizacëjã?"

#: ../DistUpgrade/DistUpgradeController.py:1121
msgid "Upgrade canceled"
msgstr "Aktualizacëjô òprzestónô"

#: ../DistUpgrade/DistUpgradeController.py:1122
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1128
#: ../DistUpgrade/DistUpgradeController.py:1257
msgid "Could not download the upgrades"
msgstr "Nié mòże zladowac zaktualnieniów"

#: ../DistUpgrade/DistUpgradeController.py:1129
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1206
#: ../DistUpgrade/DistUpgradeController.py:1245
#: ../DistUpgrade/DistUpgradeController.py:1350
msgid "Error during commit"
msgstr "Fela òbczas zacwierdzaniô"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1208
#: ../DistUpgrade/DistUpgradeController.py:1247
#: ../DistUpgrade/DistUpgradeController.py:1389
msgid "Restoring original system state"
msgstr "Doprowôdzanié nazôd òriginalnegò stónu systemë"

#: ../DistUpgrade/DistUpgradeController.py:1209
#: ../DistUpgrade/DistUpgradeController.py:1224
#: ../DistUpgrade/DistUpgradeController.py:1248
msgid "Could not install the upgrades"
msgstr "Instalacëjô aktualizacëji nie darzëła sã."

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1214
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1219
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at "
"http://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+filebug "
"and attach the files in /var/log/dist-upgrade/ to the bug report.\n"
"%s"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1258
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1338
msgid "Remove obsolete packages?"
msgstr "Rëmnąc stôre paczétë?"

#: ../DistUpgrade/DistUpgradeController.py:1339
#: ../data/gtkbuilder/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "Ù_trzëmôj"

#: ../DistUpgrade/DistUpgradeController.py:1339
msgid "_Remove"
msgstr "_Rëmôj"

#: ../DistUpgrade/DistUpgradeController.py:1351
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr "Pòkôza sã fela przë czëszczeniô. Wicy wëdowiédzë niżi. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1427
msgid "Required depends is not installed"
msgstr "Wëmôgónô zanóleżnota nie je winstalowónô."

#: ../DistUpgrade/DistUpgradeController.py:1428
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "Wëmôgónô zanóleżnota '%s' nie je winstalowónô "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1695
#: ../DistUpgrade/DistUpgradeController.py:1782
msgid "Checking package manager"
msgstr "Sprôwdzanié menadżera paczétów"

#: ../DistUpgrade/DistUpgradeController.py:1701
#: ../DistUpgrade/DistUpgradeController.py:1707
msgid "Preparing the upgrade failed"
msgstr "Przëszëkòwanié aktualizacëjów nie darzëło sã"

#: ../DistUpgrade/DistUpgradeController.py:1702
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1708
msgid ""
"Preparing the system for the upgrade failed. To report a bug install apport "
"and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1725
#: ../DistUpgrade/DistUpgradeController.py:1735
msgid "Getting upgrade prerequisites failed"
msgstr "Dobëcé elementów nótrnych do aktualizacëji nie darzëło sã"

#: ../DistUpgrade/DistUpgradeController.py:1726
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1736
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"To report a bug install apport and then execute 'apport-bug ubuntu-release-"
"upgrader'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1766
msgid "Updating repository information"
msgstr "Aktualizacëjô wëdowiédzë ò respòzëtorëjach"

#: ../DistUpgrade/DistUpgradeController.py:1773
msgid "Failed to add the cdrom"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1774
msgid "Sorry, adding the cdrom was not successful."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1809
msgid "Invalid package information"
msgstr "Lëchô wëdowiédzô ò paczétach"

#: ../DistUpgrade/DistUpgradeController.py:1810
#, python-format
msgid ""
"After updating your package information, the essential package '%s' could "
"not be located. This may be because you have no official mirrors listed in "
"your software sources, or because of excessive load on the mirror you are "
"using. See /etc/apt/sources.list for the current list of configured software "
"sources.\n"
"In the case of an overloaded mirror, you may want to try the upgrade again "
"later."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1838
#: ../DistUpgrade/DistUpgradeController.py:1894
msgid "Fetching"
msgstr "Zladënk"

#: ../DistUpgrade/DistUpgradeController.py:1844
#: ../DistUpgrade/DistUpgradeController.py:1898
msgid "Upgrading"
msgstr "Zaktualnienié"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1849
#: ../DistUpgrade/DistUpgradeController.py:1900
#: ../DistUpgrade/DistUpgradeController.py:1907
#: ../DistUpgrade/DistUpgradeController.py:1918
msgid "Upgrade complete"
msgstr "Zaktualnienié zakùńczoné"

#: ../DistUpgrade/DistUpgradeController.py:1850
#: ../DistUpgrade/DistUpgradeController.py:1901
#: ../DistUpgrade/DistUpgradeController.py:1908
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1857
msgid "Searching for obsolete software"
msgstr "Szëkba za stôrą softwôrą"

#: ../DistUpgrade/DistUpgradeController.py:1870
msgid "System upgrade is complete."
msgstr "Zaktualnienié systemë dzrzëło sã"

#: ../DistUpgrade/DistUpgradeController.py:1919
msgid "The partial upgrade was completed."
msgstr "Dzélowô aktualizacëjô skùńcoznô"

#: ../DistUpgrade/DistUpgradeFetcher.py:114
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:158
msgid "Could not find the release notes"
msgstr "NIé mòże nalezc wëdowiédzë ò wëdôwkù"

#: ../DistUpgrade/DistUpgradeFetcher.py:115
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:159
msgid "The server may be overloaded. "
msgstr "Serwera mòże bëc przeladowóny "

#: ../DistUpgrade/DistUpgradeFetcher.py:127
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:163
msgid "Could not download the release notes"
msgstr "Zladënk wëdowiédzë ò wëdôwkò nie darzëł sã"

#: ../DistUpgrade/DistUpgradeFetcher.py:128
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:164
msgid "Please check your internet connection."
msgstr "Proszã sprôwdzëc sécowé nastôwë"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:73
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:97
#, python-format
msgid "extracting '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:118
#: ../DistUpgrade/DistUpgradeFetcherCore.py:119
msgid "Could not run the upgrade tool"
msgstr "Zrëszenié nôrzãdza aktualizacëji nie darzëło sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:120
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug ubuntu-release-upgrader-core'."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:197
msgid "Upgrade tool signature"
msgstr "Pòdpisënk nôrzãdza aktualizacëji"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:204
msgid "Upgrade tool"
msgstr "Nôrzãdze aktualizacëji"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
msgid "Failed to fetch"
msgstr "Zladënk nie darzëł sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:239
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""
"Zladënk aktualizacëji nie darzëł sã. Mòże to òznôczac problemë z sécą. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
msgid "Authentication failed"
msgstr "Ùdowierzanié nie darzëło sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:244
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Ùdowierzanié aktualizacëji nie darzëło sã. Mòże je to problem z sécą abò "
"serwerã. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
msgid "Failed to extract"
msgstr "Rozpakòwëwanié nie darzëło sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:250
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Rozpakòwëwanié aktualizacëji nie darzëło sã. Mòże je to problem z sécą abò "
"serwerã. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
msgid "Verification failed"
msgstr "Werifikacëjô nie darzëła sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:256
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Werifikacëjô aktualizacëji nie darzëła sã. Mòże je to problem z sécą abò "
"serwerã. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../DistUpgrade/DistUpgradeFetcherCore.py:276
msgid "Can not run the upgrade"
msgstr "Ni mòże nacząc aktualizacëji"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:271
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:277
#, python-format
msgid "The error message is '%s'."
msgstr "Zamkłosc wiadła felë: \\\"%s\\\""

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:139
msgid "&Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:142
msgid "&Cancel"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:144
#: ../data/gtkbuilder/ReleaseNotes.ui.h:1
msgid "Release Notes"
msgstr "Wëdowiédzô ò wëdôwkù"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:201
msgid "Upgrade"
msgstr "Aktualizëjë"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:217
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:232
msgid "Downloading additional package files..."
msgstr "Zladënk dôdôwnych paczétów..."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:234
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Lopk %s z %s z chùtkòscą %sB/s"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:238
#, python-format
msgid "File %s of %s"
msgstr "Lopk %s z %s"

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:245
#: ../DistUpgrade/DistUpgradeViewGtk3.py:124
#: ../DistUpgrade/DistUpgradeViewKDE.py:219
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Proszã włożëc '%s' do nëkù '%s'"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:247
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:252
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:253
#: ../DistUpgrade/DistUpgradeViewKDE.py:220
msgid "Media Change"
msgstr "Zmiana media"

#: ../DistUpgrade/DistUpgradeQuirks.py:183
msgid "Your graphics hardware may not be fully supported in Ubuntu 14.04."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:185
msgid ""
"Running the 'unity' desktop environment is not fully supported by your "
"graphics hardware. You will maybe end up in a very slow environment after "
"the upgrade. Our advice is to keep the LTS version for now. For more "
"information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForUnity3D Do you still "
"want to continue with the upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:209
msgid ""
"Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:211
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:231
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:235
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Kòmpùtr brëkùje czérownika graficzi AMD \"fglrx\". Felënk wersëji czérownika "
"z chtërną wespółrobi twòjô hardwôra w Ubuntu 10.04 LTS.\n"
"\n"
"Jisc dali?"

#: ../DistUpgrade/DistUpgradeQuirks.py:270
msgid "No i686 CPU"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:271
msgid ""
"Your system uses an i586 CPU or a CPU that does not have the 'cmov' "
"extension. All packages were built with optimizations requiring i686 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:308
msgid "No ARMv6 CPU"
msgstr "Felënk procesora ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:309
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:329
msgid "No init available"
msgstr "Felënk przëstãpù do procesu init"

#: ../DistUpgrade/DistUpgradeQuirks.py:330
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:483
msgid "PAE not enabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:484
msgid ""
"Your system uses a CPU that does not have PAE enabled. Ubuntu only supports "
"non-PAE systems up to Ubuntu 12.04. To upgrade to a later version of Ubuntu, "
"you must enable PAE (if this is possible) see:\n"
"http://help.ubuntu.com/community/EnablingPAE"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:59
msgid "Sandbox upgrade using aufs"
msgstr "Testowô aktualizacëjô brëkùjąc aufs"

#: ../DistUpgrade/DistUpgradeMain.py:61
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr "Ùżëjë pòdóną stegnã do szëkbë za CD z paczétama aktualizacëji"

#: ../DistUpgrade/DistUpgradeMain.py:67
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Brëkùnk graficzny nôdkładczi. Terô przëstãpné: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:70
msgid "*DEPRECATED* this option will be ignored"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:73
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr "Ùżëjë blós dzélowi aktualizacëji (bez nadpisaniô source.list)"

#: ../DistUpgrade/DistUpgradeMain.py:76
msgid "Disable GNU screen support"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:78
msgid "Set datadir"
msgstr "Nastôwi stegnã do pòdôwków"

#: ../DistUpgrade/DistUpgradeMain.py:81
msgid "Upgrade to the development release"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:145
#: ../DistUpgrade/DistUpgradeViewKDE.py:233
msgid "Fetching is complete"
msgstr "Zladënk zakùńczony"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:160
#: ../DistUpgrade/DistUpgradeViewKDE.py:249
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Zladënk %li lopka z %li z chùtkòscą %sB/s"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:162
#: ../DistUpgrade/DistUpgradeViewGtk3.py:320
#: ../DistUpgrade/DistUpgradeViewKDE.py:250
#: ../DistUpgrade/DistUpgradeViewKDE.py:400
#, python-format
msgid "About %s remaining"
msgstr "Òstało kòl %s"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:165
#: ../DistUpgrade/DistUpgradeViewKDE.py:252
#, python-format
msgid "Fetching file %li of %li"
msgstr "Zladënk lopka %li z %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk3.py:197
#: ../DistUpgrade/DistUpgradeViewKDE.py:290
msgid "Applying changes"
msgstr "Zacwierdzanié zmianów"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk3.py:223
#: ../DistUpgrade/DistUpgradeViewKDE.py:303
msgid "dependency problems - leaving unconfigured"
msgstr "problemë z zanôleżnotama - òstôwioné nieskònfigùrowóné"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:228
#: ../DistUpgrade/DistUpgradeViewKDE.py:305
#, python-format
msgid "Could not install '%s'"
msgstr "Nie bëło mòżno zainstalowac '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:229
#: ../DistUpgrade/DistUpgradeViewKDE.py:306
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk3.py:246
#: ../DistUpgrade/DistUpgradeViewKDE.py:328
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Zastãpic swój lopk kònfigùracëji\n"
"'%s'?"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:247
#: ../DistUpgrade/DistUpgradeViewKDE.py:329
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:267
#: ../DistUpgrade/DistUpgradeViewKDE.py:352
msgid "The 'diff' command was not found"
msgstr "Pòlét 'diff' nie òstôł nalazłi"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:524
#: ../DistUpgrade/DistUpgradeViewText.py:138
msgid "A fatal error occurred"
msgstr "Pòkôza sã kriticznô fela"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:525
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:555
msgid "Ctrl-c pressed"
msgstr "Wcësniãto Ctrl-C"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:556
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk3.py:694
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Abë nie ùtracëc pòdôwków proszã zamknąc wszëtczé òtemkłé aplikacëje ë "
"dokùmentë."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:708
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:709
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:710
#, python-format
msgid "Remove (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:711
#, python-format
msgid "No longer needed (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:712
#, python-format
msgid "Install (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:713
#, python-format
msgid "Upgrade (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:364
msgid "Show Difference >>>"
msgstr "Wëskrzëni  nierównoscë >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:367
msgid "<<< Hide Difference"
msgstr "<<< Zatacë nierównoscë"

#: ../DistUpgrade/DistUpgradeViewKDE.py:567
msgid "Error"
msgstr "Fela"

#: ../DistUpgrade/DistUpgradeViewKDE.py:819
msgid "&Close"
msgstr "Z&amkni"

#: ../DistUpgrade/DistUpgradeViewKDE.py:619
msgid "Show Terminal >>>"
msgstr "Wëskrzëni terminal >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:622
msgid "<<< Hide Terminal"
msgstr "<<< Zatacë terminal"

#: ../DistUpgrade/DistUpgradeViewKDE.py:701
msgid "Information"
msgstr "Wëdowiédzô"

#: ../DistUpgrade/DistUpgradeViewKDE.py:753
msgid "&Start Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:755
#: ../DistUpgrade/DistUpgradeViewKDE.py:800
#: ../DistUpgrade/DistUpgradeViewKDE.py:805
#: ../data/gtkbuilder/DistUpgrade.ui.h:7
msgid "Details"
msgstr "Drobnotë"

#: ../DistUpgrade/DistUpgradeViewKDE.py:781
#, python-format
msgid "No longer supported %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:783
#, python-format
msgid "Remove %s"
msgstr "Rëmôj %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:785
#: ../DistUpgrade/DistUpgradeViewText.py:236
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "Rëmôj (bëło aùtomatno winstalowóné) %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:787
#, python-format
msgid "Install %s"
msgstr "Instalëjë %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:789
#, python-format
msgid "Upgrade %s"
msgstr "Aktualizëjë %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:815
#: ../DistUpgrade/DistUpgradeViewText.py:284
msgid "Restart required"
msgstr "Wëmôgóne je zrëszenié kòmpùtra znowa"

#: ../DistUpgrade/DistUpgradeViewKDE.py:815
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Zrëszë kòpmùtr znowa, żebë zakùńczëc aktualizacëjã</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:818
#: ../data/gtkbuilder/DistUpgrade.ui.h:14
msgid "_Restart Now"
msgstr "_Zrëszë znowa"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:836
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"b><big>Òprzestac aktualizacëjã ?</big></b>\n"
"\n"
"Systema mòże stracëc sztabilnotã jeżlë òprzestóniesz aktualizacëjã. "
"Zamòdlëwô sã znowienié aktualizacëji."

#: ../DistUpgrade/DistUpgradeViewKDE.py:840
msgid "Cancel Upgrade?"
msgstr "Òprzestac zaktualnienié?"

#: ../DistUpgrade/DistUpgradeView.py:81
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li dzéń"
msgstr[1] "%li dni"
msgstr[2] "%li dniów"

#: ../DistUpgrade/DistUpgradeView.py:83
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li gòdzëna"
msgstr[1] "%li gòdzënë"
msgstr[2] "%li gòdzën"

#: ../DistUpgrade/DistUpgradeView.py:85
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li minuta"
msgstr[1] "%li minutë"
msgstr[2] "%li minutów"

#: ../DistUpgrade/DistUpgradeView.py:86
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li sekùnda"
msgstr[1] "%li sekòndë"
msgstr[2] "%li sekùndów"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:102
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:120
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:171
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"Zladënk dérëje kòl %s brëkùjąc sparłãczenia 1 Mbit DSL abò kòl %s brëkùjąc "
"mòdewòwégò sparłãczenia 56k."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:175
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "Zladënk mòże, w przëtrôfkù negò sparłãczenia, dérowac kòl %s . "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:280 ../data/gtkbuilder/DistUpgrade.ui.h:21
msgid "Preparing to upgrade"
msgstr "Przërechtowanié zaktualnienia"

#: ../DistUpgrade/DistUpgradeView.py:281
msgid "Getting new software channels"
msgstr "Zladënk nowich kanalów softwôrë"

#: ../DistUpgrade/DistUpgradeView.py:282 ../data/gtkbuilder/DistUpgrade.ui.h:23
msgid "Getting new packages"
msgstr "Zladënk nowich paczétów"

#: ../DistUpgrade/DistUpgradeView.py:283 ../data/gtkbuilder/DistUpgrade.ui.h:26
msgid "Installing the upgrades"
msgstr "Instalacëjô zaktualnieniô"

#: ../DistUpgrade/DistUpgradeView.py:284 ../data/gtkbuilder/DistUpgrade.ui.h:25
msgid "Cleaning up"
msgstr "Czëszczenié"

#: ../DistUpgrade/DistUpgradeView.py:372
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
msgstr[1] ""

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:381
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d paczét òstanié rëmniãty."
msgstr[1] "%d paczétë òstaną rëmniãte."
msgstr[2] "%d paczétów òstaną rëmniãtëch."

#: ../DistUpgrade/DistUpgradeView.py:386
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d nowi paczét òstanie winstalowóny."
msgstr[1] "%d nowé paczétë òstaną winstalowóné."
msgstr[2] "%d nowëch paczétów òstanie winstalowónëch."

#: ../DistUpgrade/DistUpgradeView.py:392
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d paczét òstanié zaktualiniony."
msgstr[1] "%d paczétë òstaną zaktualnione."
msgstr[2] "%d paczétów òstanie zaktualnionëch."

#: ../DistUpgrade/DistUpgradeView.py:400
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Mùszebny zladënk w grëpie %s. "

#: ../DistUpgrade/DistUpgradeView.py:405
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:409
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:414
msgid "Removing the packages can take several hours. "
msgstr ""

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:419
msgid "The software on this computer is up to date."
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:420
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"Felëjë przistãpnëch aktualizacëjów. Aktualizacëjô òstanié òprzestónô."

#: ../DistUpgrade/DistUpgradeView.py:433
msgid "Reboot required"
msgstr "Wëmôgóne je zrëszenié kòmpùtra znowa"

#: ../DistUpgrade/DistUpgradeView.py:434
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"Aktualizacëjô òsta zakùńczonô ë nót je zrëszëc kòmpùtr znowa. Zrobic to terô?"

#: ../DistUpgrade/DistUpgradeViewText.py:81
#, python-format
msgid "Progress: [%3i%%]"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:139
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:163
msgid "Aborting"
msgstr "Òprzestóń"

#: ../DistUpgrade/DistUpgradeViewText.py:168
msgid "Demoted:\n"
msgstr "Zdegradowóné:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:175
msgid "To continue please press [ENTER]"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:212
#: ../DistUpgrade/DistUpgradeViewText.py:250
#: ../DistUpgrade/DistUpgradeViewText.py:257
msgid "Continue [yN] "
msgstr "Biéj dali [jN] "

#: ../DistUpgrade/DistUpgradeViewText.py:212
#: ../DistUpgrade/DistUpgradeViewText.py:250
msgid "Details [d]"
msgstr "Detale [d]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:216
#: ../DistUpgrade/DistUpgradeViewText.py:260
msgid "y"
msgstr "j"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:219
#: ../DistUpgrade/DistUpgradeViewText.py:267
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:222
msgid "d"
msgstr "d"

#: ../DistUpgrade/DistUpgradeViewText.py:227
#, python-format
msgid "No longer supported: %s\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:232
#, python-format
msgid "Remove: %s\n"
msgstr "Rëmôj: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:242
#, python-format
msgid "Install: %s\n"
msgstr "Instalëjë %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:247
#, python-format
msgid "Upgrade: %s\n"
msgstr "Aktualizëjë %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:264
msgid "Continue [Yn] "
msgstr "Jisc dali [Jn] "

#: ../DistUpgrade/DistUpgradeViewText.py:285
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Abë skùńczëc aktualizacëjã je nót zrëszëc kòmpùtr znowa.\n"
"Pò wëbierkù \"J\" kòmpùtr bãdze zrëszony znowa."

#: ../DistUpgrade/GtkProgress.py:71
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Ladowanié lopka %(current)li z %(total)li z chùtkòscą %(speed)s/s"

#: ../DistUpgrade/GtkProgress.py:77
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Ladowanié lopka %(current)li z %(total)li"

#: ../data/gtkbuilder/AcquireProgress.ui.h:1
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
msgid "Show progress of individual files"
msgstr "Pòkrok zladënkù indiwidualnych lopków"

#: ../data/gtkbuilder/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "Ò_przestóń zaktualnienié"

#: ../data/gtkbuilder/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "_Znowi zaktualnienié"

#: ../data/gtkbuilder/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>Òprzestac aktualizacëjã?</big></b>\n"
"\n"
"Systema mòże stac sã nieprzëdatnô do brëkùnkù jeżlë òprzestóniesz "
"aktualizacëjã. Zamòdlëwô sã jisc dali z aktualizacëją."

#: ../data/gtkbuilder/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "_Startëjë zaktualnienié"

#: ../data/gtkbuilder/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "_Zastãpi"

#: ../data/gtkbuilder/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "Zjinaczi midze lopkama"

#: ../data/gtkbuilder/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "Zgłoszë _felã"

#: ../data/gtkbuilder/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "_Biéj dali"

#: ../data/gtkbuilder/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Zacząc zaktualnienié?</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>Dlô zakùńczeniô aktualizacëji zrëszë kòmpùtr znbowa</big></b>\n"
"\n"
"Proszã zapisaćc swòją robòtã, niglë póńdzesz dali"

#: ../data/gtkbuilder/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "Aktualizacëjô distribùcëji"

#: ../data/gtkbuilder/DistUpgrade.ui.h:19
msgid "<b><big>Upgrading Ubuntu to version 15.10</big></b>"
msgstr ""

#: ../data/gtkbuilder/DistUpgrade.ui.h:20
msgid "    "
msgstr "    "

#: ../data/gtkbuilder/DistUpgrade.ui.h:22
msgid "Setting new software channels"
msgstr "Nastôwë nowich kanalów softwôrë"

#: ../data/gtkbuilder/DistUpgrade.ui.h:24
msgid "Restarting the computer"
msgstr "Zrëszanié kòmpùtra znowa"

#: ../data/gtkbuilder/DistUpgrade.ui.h:27
msgid "Terminal"
msgstr "Terminal"

#: ../data/gtkbuilder/ReleaseNotes.ui.h:2
msgid "_Upgrade"
msgstr "_Aktualizëjë"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid ""
"<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>Je przëstãpnô nowô wersëjô Ubuntu. Chcesz zaktualnic?</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Don't Upgrade"
msgstr "Nie aktualizëjë"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Ask Me Later"
msgstr "Pëtôj mie pózdni"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Yes, Upgrade Now"
msgstr "Jo, aktualizëjë terô"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "Môsz pòcësniãtą aktualizacëjã do nowi wersëji Ubuntu"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr ""

#: ../data/com.ubuntu.release-upgrader.policy.in.h:1
msgid "Perform a release upgrade"
msgstr ""

#: ../data/com.ubuntu.release-upgrader.policy.in.h:2
msgid "To upgrade Ubuntu, you need to authenticate."
msgstr ""

#: ../data/com.ubuntu.release-upgrader.policy.in.h:3
msgid "Perform a partial upgrade"
msgstr ""

#: ../data/com.ubuntu.release-upgrader.policy.in.h:4
msgid "To perform a partial upgrade, you need to authenticate."
msgstr ""

#: ../do-partial-upgrade:74 ../do-release-upgrade:78
msgid "Show version and exit"
msgstr "Wëskrzënianié wersëji ë wińdzënk"

#: ../do-partial-upgrade:77 ../do-release-upgrade:85
msgid "Directory that contains the data files"
msgstr "Katalog zamëkający lopczi pòdôwków"

#: ../do-partial-upgrade:80 ../do-release-upgrade:98
msgid "Run the specified frontend"
msgstr "Zrëszë òpisóną nadkłôdkã"

#: ../do-partial-upgrade:103
msgid "Running partial upgrade"
msgstr "Przerôbianié dzélowégò zaktualnienia"

#: ../do-release-upgrade:32 ../do-release-upgrade:44
msgid "Downloading the release upgrade tool"
msgstr "Zladënk nôrzãdza aktualizacëji wëdôwkù"

#: ../do-release-upgrade:81 ../check_new_release_gtk.py:177
msgid "Check if upgrading to the latest devel release is possible"
msgstr "Sprôwdzë mòżnotã zaktualnieniô do nônowszi testowi wersëji"

#: ../do-release-upgrade:88 ../check_new_release_gtk.py:181
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Proszã spróbòwac zaktualnic do nônowszi wersëji brëkùjąc zaktualniający "
"programë z $distro-proposed"

#: ../do-release-upgrade:92
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Zrëszë w specjalnym tribie aktualizacëji.\n"
"Terô wspieróné są tribë \"desktop\" dlô kòmpùtrów ë \"server\" dlô "
"serwerowich systemów."

#: ../do-release-upgrade:100
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "Testowô aktualizacëjô z nadkłôdką sandbox aufs"

#: ../do-release-upgrade:103
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""

#: ../do-release-upgrade:117
msgid "The options --devel-release and --proposed are"
msgstr ""

#: ../do-release-upgrade:118
msgid "mutually exclusive. Please use only one of them."
msgstr ""

#: ../do-release-upgrade:122
msgid "Checking for a new Ubuntu release"
msgstr ""

#: ../do-release-upgrade:134
msgid "Your Ubuntu release is not supported anymore."
msgstr ""

#: ../do-release-upgrade:135
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""

#: ../do-release-upgrade:141
msgid "No new release found"
msgstr "Felënk nowegò wëdôwka"

#: ../do-release-upgrade:146
msgid "Release upgrade not possible right now"
msgstr ""

#: ../do-release-upgrade:147
#, c-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""

#: ../do-release-upgrade:153
#, c-format
msgid "New release '%s' available."
msgstr "Nowi wëdôwk '%s' je przëstãpny"

#: ../do-release-upgrade:154
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "Zrëszë 'do-release-upgrade', abë zaktualnic."

#: ../check_new_release_gtk.py:85
msgid "Software Updater"
msgstr ""

#: ../check_new_release_gtk.py:113
#, python-format
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Przëstãpnô je aktualizacëjô do Ubuntu %(version)s"

#. print("don't upgrade")
#: ../check_new_release_gtk.py:144
#, python-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Pòcësniãto aktualizacëjã do Ubuntu %s"

#: ../check_new_release_gtk.py:186
msgid "Add debug output"
msgstr ""

#, python-format
#~ msgid ""
#~ "An unresolvable problem occurred while calculating the upgrade:\n"
#~ "%s\n"
#~ "\n"
#~ " This can be caused by:\n"
#~ " * Upgrading to a pre-release version of Ubuntu\n"
#~ " * Running the current pre-release version of Ubuntu\n"
#~ " * Unofficial software packages not provided by Ubuntu\n"
#~ "\n"
#~ msgstr ""
#~ "Pòkôzôł sã problem, chtënegò nie dô sã rozwiązac, przë òbrechòwaniu "
#~ "aktualizacëji:\n"
#~ "%s\n"
#~ "\n"
#~ " Mòże to bëc sparłãczoné z:\n"
#~ " * Aktualizacëją do testowi wersëji Ubuntu\n"
#~ " * Brëkòwaniém biéżny wersëji Ubuntu\n"
#~ " * Brëkòwanié nieòficjalnych paczétów z bùtna repòzytorëjów Ubuntu\n"
#~ "\n"

#~ msgid ""
#~ "Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
#~ "desktop or edubuntu-desktop package and it was not possible to detect which "
#~ "version of Ubuntu you are running.\n"
#~ " Please install one of the packages above first using synaptic or apt-get "
#~ "before proceeding."
#~ msgstr ""
#~ "Systema nie zamëkô w se paczétów ubuntu-desktop, kubuntu-desktop, xubuntu-"
#~ "desktop abò edubuntu-desktop ë ni mòże wëkrëc ùżëwóny wersëji Ubuntu.\n"
#~ " Proszã winstalowac jeden z tich paczétów brëkùjąc programë Synaptic abò apt-"
#~ "get nigle póńdzesz dali."

#~ msgid "Package 'debsig-verify' is installed"
#~ msgstr "Paczét \"debsig-verify\" je winstalowóny"

#~ msgid "evms in use"
#~ msgstr "EVMS w brëkùńkù"

#~ msgid ""
#~ "This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
#~ "version of this driver is available that works with your video card in "
#~ "Ubuntu 10.04 LTS.\n"
#~ "\n"
#~ "Do you want to continue?"
#~ msgstr ""
#~ "Kòmpùtr brëkùje czérownika graficzi NVIDIA \"nvidia\". Felënk wersëji "
#~ "czérownika z chtërną wespółrobi twòjô hardwôra w Ubuntu 10.04 LTS.\n"
#~ "\n"
#~ "Jisc dali?"
