# Kashubian translation for update-manager
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the update-manager package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2008-10-20 18:10+0000\n"
"PO-Revision-Date: 2008-10-20 20:30+0000\n"
"Last-Translator: Launchpad Translations Administrators "
"<rosetta@launchpad.net>\n"
"Language-Team: Kashubian <csb@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
"|| n%100>=20) ? 1 : 2;\n"
"X-Launchpad-Export-Date: 2008-10-24 13:41+0000\n"
"X-Generator: Launchpad (build Unknown)\n"

#. TRANSLATORS: download size is 0
#: ../DistUpgrade/utils.py:138 ../UpdateManager/Common/utils.py:138
msgid "0 KB"
msgstr "0 KB"

#. TRANSLATORS: download size of very small updates
#: ../DistUpgrade/utils.py:141 ../UpdateManager/Common/utils.py:141
msgid "1 KB"
msgstr "1 KB"

#. TRANSLATORS: download size of small updates, e.g. "250 KB"
#: ../DistUpgrade/utils.py:144 ../UpdateManager/Common/utils.py:144
#, python-format
msgid "%.0f KB"
msgstr "%.0f KB"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:147 ../UpdateManager/Common/utils.py:147
#, python-format
msgid "%.1f MB"
msgstr "%.1f MB"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:194 ../DistUpgrade/distro.py:401
#, python-format
msgid "Server for %s"
msgstr "Serwera dlô kraju %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:213 ../DistUpgrade/distro.py:218
#: ../DistUpgrade/distro.py:232
msgid "Main server"
msgstr "Przédnô serwera"

#: ../DistUpgrade/distro.py:235
msgid "Custom servers"
msgstr "Jine serwerë"

#: ../DistUpgrade/dist-upgrade.py:15
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr "Ùżëjë pòdóną stegnã do szëkbë za CD z paczétama aktualizacëji"

#: ../DistUpgrade/dist-upgrade.py:21
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""

#: ../DistUpgrade/dist-upgrade.py:24
msgid "*DEPRECATED* this option will be ignore"
msgstr ""

#: ../DistUpgrade/dist-upgrade.py:27
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""

#: ../DistUpgrade/dist-upgrade.py:29
msgid "Set datadir"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:101
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Rëmanié lëchegò paczétu"
msgstr[1] "Rëmanié lëchich paczétów"
msgstr[2] "Rëmanié lëchich paczétów"

#: ../DistUpgrade/DistUpgradeCache.py:104
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and needs to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeCache.py:299
msgid "Broken packages"
msgstr "Paczétë są zmiłkòwé"

#: ../DistUpgrade/DistUpgradeCache.py:300
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:521
msgid "Can't upgrade required meta-packages"
msgstr "Ni mòże zaktualnic wëmôgónëch meta-paczétów"

#: ../DistUpgrade/DistUpgradeCache.py:525
msgid "A essential package would have to be removed"
msgstr ""

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:532
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:542
msgid "This is most likely a transient problem, please try again later."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:545
msgid ""
"If none of this applies, then please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the "
"bugreport."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:550
#: ../UpdateManager/UpdateManager.py:906
msgid "Could not calculate the upgrade"
msgstr "Nié mòże przerobic aktualizacëjów"

#. FIXME: maybe ask a question here? instead of failing?
#: ../DistUpgrade/DistUpgradeCache.py:597
msgid "Error authenticating some packages"
msgstr "Fela òbczas ùdowierzaniô niechtërnëch paczétów"

#: ../DistUpgrade/DistUpgradeCache.py:598
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:710
#, python-format
msgid "Can't install '%s'"
msgstr "Ni mòże winstalowac '%s'"

#: ../DistUpgrade/DistUpgradeCache.py:711
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""
"Nie bëło mòżno winstalowac wëmôgónegò paczétu. Proszã zgłoszëc to jakno "
"felã. "

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:719
msgid "Can't guess meta-package"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:720
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:85
msgid "Reading cache"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:172
msgid "Unable to get exclusive lock"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:173
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:193
msgid "Continue running under SSH?"
msgstr "Jic dali ze sparłãczeniã SSH?"

#: ../DistUpgrade/DistUpgradeController.py:194
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, a additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:209
msgid "Starting additional sshd"
msgstr "Zrëszanié dodôwnëch ùsłëżnotów ssh"

#: ../DistUpgrade/DistUpgradeController.py:210
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:278
#: ../DistUpgrade/DistUpgradeController.py:301
msgid "Can not upgrade"
msgstr "Nié mòże zaktualnic"

#: ../DistUpgrade/DistUpgradeController.py:279
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:302
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:328
msgid "Package 'debsig-verify' is installed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:329
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:339
msgid "Include latest updates from the Internet?"
msgstr "Dodac nônowszé zaktualnienia z internetu?"

#: ../DistUpgrade/DistUpgradeController.py:340
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:511
msgid "No valid mirror found"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:512
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found.This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'no' the update will cancel."
msgstr ""

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:532
msgid "Generate default sources?"
msgstr "Wëgenerowac domëszlné zdroje?"

#: ../DistUpgrade/DistUpgradeController.py:533
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the update "
"will cancel."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:567
msgid "Repository information invalid"
msgstr "Lëchô wëdowiédzô ò repòzëtorëjach"

#: ../DistUpgrade/DistUpgradeController.py:568
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:574
msgid "Third party sources disabled"
msgstr "Zdoje samòstójnëch dostôwców òstałë włączoné"

#: ../DistUpgrade/DistUpgradeController.py:575
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:615
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeController.py:618
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for it.Please reinstall the packages manually or "
"remove them from the system."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeController.py:666
msgid "Error during update"
msgstr "Fela òbczas aktualizacëji"

#: ../DistUpgrade/DistUpgradeController.py:667
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:676
msgid "Not enough free disk space"
msgstr "Za mało placu na diskù"

#: ../DistUpgrade/DistUpgradeController.py:677
#, python-format
msgid ""
"The upgrade aborts now. The upgrade needs a total of %s free space on disk "
"'%s'. Please free at least an additional %s of disk space on '%s'. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:788
msgid "Support for some applications ended"
msgstr "Wspiarce dlô niejednrch aplikacrjów skùńczëło sã"

#: ../DistUpgrade/DistUpgradeController.py:789
msgid ""
"Canonical Ltd. no longer provides support for the following software "
"packages. You can still get support from the community.\n"
"\n"
"If you have not enabled community maintained software (universe), these "
"packages will be suggested for removal at the end of the upgrade."
msgstr ""

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:798
#: ../DistUpgrade/DistUpgradeController.py:1419
msgid "Calculating the changes"
msgstr "Przerôbianié zmianów"

#. ask the user if he wants to do the changes
#: ../DistUpgrade/DistUpgradeController.py:813
msgid "Do you want to start the upgrade?"
msgstr "Chcesz zrëszëc aktualizacëjã?"

#: ../DistUpgrade/DistUpgradeController.py:865
#: ../DistUpgrade/DistUpgradeController.py:921
msgid "Could not download the upgrades"
msgstr "Nié mòże zladowac zaktualnieniów"

#: ../DistUpgrade/DistUpgradeController.py:866
msgid ""
"The upgrade aborts now. Please check your Internet connection or "
"installation media and try again. All files downloaded so far are kept."
msgstr ""

#. invoke the frontend now
#: ../DistUpgrade/DistUpgradeController.py:896
msgid ""
"The upgrade aborts now. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:901
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bugreport.\n"
"%s"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:905
msgid "Could not install the upgrades"
msgstr "Instalacëjô aktualizacëji nie darzëła sã."

#: ../DistUpgrade/DistUpgradeController.py:922
msgid ""
"The upgrade aborts now. Please check your Internet connection or "
"installation media and try again. "
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:992
msgid "Remove obsolete packages?"
msgstr "Rëmnąc stôre paczétë?"

#: ../DistUpgrade/DistUpgradeController.py:993
#: ../DistUpgrade/DistUpgrade.glade.h:20
msgid "_Keep"
msgstr "Ù_trzëmôj"

#: ../DistUpgrade/DistUpgradeController.py:993
msgid "_Remove"
msgstr "_Rëmôj"

#: ../DistUpgrade/DistUpgradeController.py:1004
msgid "Error during commit"
msgstr "Fela òbczas zacwierdzaniô"

#: ../DistUpgrade/DistUpgradeController.py:1005
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr "Pòkôza sã fela przë czëszczeniô. Wicy wëdowiédzë niżi. "

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1040
msgid "Restoring original system state"
msgstr "Doprowôdzanié nazôd òriginalnegò stónu systemë"

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1078
msgid "Required depends is not installed"
msgstr "Wëmôgónô zanóleżnota nie je winstalowónô."

#: ../DistUpgrade/DistUpgradeController.py:1079
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "Wëmôgónô zanóleżnota '%s' nie je winstalowónô "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1329
#: ../DistUpgrade/DistUpgradeController.py:1396
msgid "Checking package manager"
msgstr "Sprôwdzanié menadżera paczétów"

#: ../DistUpgrade/DistUpgradeController.py:1334
msgid "Preparing the upgrade failed"
msgstr "Przëszëkòwanié aktualizacëjów nie darzëło sã"

#: ../DistUpgrade/DistUpgradeController.py:1335
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bugreport."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1351
msgid "Getting upgrade prerequisites failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1352
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bugreport."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1382
msgid "Updating repository information"
msgstr "Aktualizacëjô wëdowiédzë ò respòzëtorëjach"

#: ../DistUpgrade/DistUpgradeController.py:1407
msgid "Invalid package information"
msgstr "Lëchô wëdowiédzô ò paczétach"

#: ../DistUpgrade/DistUpgradeController.py:1408
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the "
"bugreport."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1425
#: ../DistUpgrade/DistUpgradeController.py:1473
msgid "Fetching"
msgstr "Zladënk"

#: ../DistUpgrade/DistUpgradeController.py:1432
#: ../DistUpgrade/DistUpgradeController.py:1477
msgid "Upgrading"
msgstr "Zaktualnienié"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1437
#: ../DistUpgrade/DistUpgradeController.py:1479
#: ../DistUpgrade/DistUpgradeController.py:1486
#: ../DistUpgrade/DistUpgradeController.py:1491
msgid "Upgrade complete"
msgstr "Zaktualnienié zakùńczoné"

#: ../DistUpgrade/DistUpgradeController.py:1438
#: ../DistUpgrade/DistUpgradeController.py:1480
#: ../DistUpgrade/DistUpgradeController.py:1487
msgid ""
"The upgrade is completed but there were errors during the ugprade process."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1445
msgid "Searching for obsolete software"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1450
msgid "System upgrade is complete."
msgstr "Zaktualnienié systemë dzrzëło sã"

#: ../DistUpgrade/DistUpgradeController.py:1492
msgid "The partial upgrade was completed."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:154
#: ../DistUpgrade/DistUpgradeQuirks.py:179
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:158
#: ../DistUpgrade/DistUpgradeQuirks.py:183
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 8.10.\n"
"\n"
"Do you want to continue?"
msgstr ""

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:108
#: ../DistUpgrade/DistUpgradeViewKDE.py:190
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Proszã włożëc '%s' do nëkù '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:127
#: ../DistUpgrade/DistUpgradeViewKDE.py:203
msgid "Fetching is complete"
msgstr "Zladënk zakùńczony"

#: ../DistUpgrade/DistUpgradeViewGtk.py:139
#: ../DistUpgrade/DistUpgradeViewKDE.py:216
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:140
#: ../DistUpgrade/DistUpgradeViewGtk.py:275
#: ../DistUpgrade/DistUpgradeViewKDE.py:217
#: ../DistUpgrade/DistUpgradeViewKDE.py:357
#, python-format
msgid "About %s remaining"
msgstr "Òstało kòl %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:142
#: ../DistUpgrade/DistUpgradeViewKDE.py:219
#, python-format
msgid "Fetching file %li of %li"
msgstr "Zladënk lopka %li z %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:174
#: ../DistUpgrade/DistUpgradeViewKDE.py:253
msgid "Applying changes"
msgstr "Zacwierdzanié zmianów"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:199
#: ../DistUpgrade/DistUpgradeViewKDE.py:266
msgid "dependency problems - leaving unconfigured"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:204
#: ../DistUpgrade/DistUpgradeViewKDE.py:268
#, python-format
msgid "Could not install '%s'"
msgstr "Nie bëło mòżno zainstalowac '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:205
#: ../DistUpgrade/DistUpgradeViewKDE.py:269
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may be in a not working "
"state. Please consider submitting a bugreport about it."
msgstr ""

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:221
#: ../DistUpgrade/DistUpgradeViewKDE.py:290
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Zastãpic swój lopk kònfigùracëji\n"
"'%s'?"

#: ../DistUpgrade/DistUpgradeViewGtk.py:222
#: ../DistUpgrade/DistUpgradeViewKDE.py:291
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:235
#: ../DistUpgrade/DistUpgradeViewKDE.py:309
msgid "The 'diff' command was not found"
msgstr "Pòlét 'diff' nie òstôł nalazłi"

#: ../DistUpgrade/DistUpgradeViewGtk.py:417
#: ../DistUpgrade/DistUpgradeViewText.py:110
msgid "A fatal error occurred"
msgstr "Pòkôza sã kriticznô fela"

#: ../DistUpgrade/DistUpgradeViewGtk.py:418
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade aborts now.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:433
msgid "Ctrl-c pressed"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:434
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:570
msgid "To prevent data loss close all open applications and documents."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:584
#, python-format
msgid "<b>Downgrade %s</b>"
msgstr "<b>Winstalëjë %s</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:586
#: ../DistUpgrade/DistUpgradeViewKDE.py:750
#, python-format
msgid "Remove %s"
msgstr "Rëmôj %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:591
#: ../DistUpgrade/DistUpgradeViewKDE.py:752
#, python-format
msgid "Install %s"
msgstr "Instalëjë %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:593
#: ../DistUpgrade/DistUpgradeViewKDE.py:754
#, python-format
msgid "Upgrade %s"
msgstr "Aktualizëjë %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:191
msgid "Media Change"
msgstr "Zmiana media"

#: ../DistUpgrade/DistUpgradeViewKDE.py:321
msgid "Show Difference >>>"
msgstr "Wëskrzëni  nierównoscë >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:324
msgid "<<< Hide Difference"
msgstr "<<< Zatacë nierównoscë"

#: ../DistUpgrade/DistUpgradeViewKDE.py:531
msgid "Error"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:543
msgid "&Cancel"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:545
#: ../DistUpgrade/DistUpgradeViewKDE.py:782
msgid "&Close"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:591
msgid "Show Terminal >>>"
msgstr "Wëskrzëni terminal >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:594
msgid "<<< Hide Terminal"
msgstr "<<< Zatacë terminal"

#: ../DistUpgrade/DistUpgradeViewKDE.py:674
msgid "Information"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:724
#: ../DistUpgrade/DistUpgradeViewKDE.py:765
#: ../DistUpgrade/DistUpgradeViewKDE.py:768
#: ../DistUpgrade/DistUpgrade.glade.h:9
msgid "Details"
msgstr "Drobnotë"

#: ../DistUpgrade/DistUpgradeViewKDE.py:778
#: ../DistUpgrade/DistUpgradeViewText.py:222
msgid "Restart required"
msgstr "Wëmôgóne je zrëszenié kòmpùtra znowa"

#: ../DistUpgrade/DistUpgradeViewKDE.py:778
#: ../DistUpgrade/DistUpgrade.glade.h:5
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Zrëszë kòpmùtr znowa, żebë zakùńczëc aktualizacëjã</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:781
#: ../DistUpgrade/DistUpgrade.glade.h:23
msgid "_Restart Now"
msgstr "_Zrëszë znowa"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:793
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:797
msgid "Cancel Upgrade?"
msgstr "Òprzestac zaktualnienié?"

#: ../DistUpgrade/DistUpgradeView.py:57
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:59
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:61
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:62
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] ""
msgstr[1] ""

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:75
#, python-format
msgid "%(str_days)s %(str_hours)s %(str_minutes)s"
msgstr ""

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:86
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr ""

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:107
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem"
msgstr ""

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:111
#, python-format
msgid "This download will take about %s with your connection. "
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:189 ../DistUpgrade/DistUpgrade.glade.h:14
msgid "Preparing to upgrade"
msgstr "Przërechtowanié zaktualnienia"

#: ../DistUpgrade/DistUpgradeView.py:190
msgid "Getting new software channels"
msgstr "Zladënk nowich kanalów softwôrë"

#: ../DistUpgrade/DistUpgradeView.py:191 ../DistUpgrade/DistUpgrade.glade.h:12
msgid "Getting new packages"
msgstr "Zladënk nowich paczétów"

#: ../DistUpgrade/DistUpgradeView.py:192 ../DistUpgrade/DistUpgrade.glade.h:13
msgid "Installing the upgrades"
msgstr "Instalacëjô zaktualnieniô"

#: ../DistUpgrade/DistUpgradeView.py:193 ../DistUpgrade/DistUpgrade.glade.h:8
msgid "Cleaning up"
msgstr "Czëszczenié"

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:266
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d paczét òstanié rëmniãty."
msgstr[1] "%d paczétë òstaną rëmniãte."
msgstr[2] "%d paczétów òstaną rëmniãtëch."

#: ../DistUpgrade/DistUpgradeView.py:271
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d nowi paczét òstanie winstalowóny."
msgstr[1] "%d nowé paczétë òstaną winstalowóné."
msgstr[2] "%d nowëch paczétów òstanie winstalowónëch."

#: ../DistUpgrade/DistUpgradeView.py:277
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d paczét òstanié zaktualiniony."
msgstr[1] "%d paczétë òstaną zaktualnione."
msgstr[2] "%d paczétów òstanie zaktualnionëch."

#: ../DistUpgrade/DistUpgradeView.py:282
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Mùszebny zladënk w grëpie %s. "

#: ../DistUpgrade/DistUpgradeView.py:286
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be cancelled."
msgstr ""

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:292 ../UpdateManager/UpdateManager.py:672
msgid "Your system is up-to-date"
msgstr "Twojô systema je fùl zaktualnionô"

#: ../DistUpgrade/DistUpgradeView.py:293
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"Felëjë przistãpnëch aktualizacëjów. Aktualizacëjô òstanié òprzestónô."

#: ../DistUpgrade/DistUpgradeView.py:306
msgid "Reboot required"
msgstr "Wëmôgóne je zrëszenié kòmpùtra znowa"

#: ../DistUpgrade/DistUpgradeView.py:307
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"Aktualizacëjô òsta zakùńczonô ë nót je zrëszëc kòmpùtr znowa. Zrobic to terô?"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:147
#: ../DistUpgrade/DistUpgradeFetcherCore.py:148
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:147
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:148
msgid "Could not run the upgrade tool"
msgstr "Zrëszenié nôrzãdza aktualizacëji nie darzëło sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:148
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:148
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:174
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:174
msgid "Upgrade tool signature"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:177
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:177
msgid "Upgrade tool"
msgstr "Nôrzãdze aktualizacëji"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:202
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:202
msgid "Failed to fetch"
msgstr "Zladënk nie darzëł sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:203
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:203
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""
"Zladënk aktualizacëji nie darzëł sã. Mòże to òznôczac problemë z sécą. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:207
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:207
msgid "Failed to extract"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:208
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:208
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:213
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:213
msgid "Verfication failed"
msgstr "Werifikacëjô nie darzëła sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:214
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:214
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:219
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:219
msgid "Authentication failed"
msgstr "Ùdowierzanié nie darzëło sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:220
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:220
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:228
#: ../DistUpgrade/DistUpgradeFetcherCore.py:234
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:228
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:234
msgid "Can not run the upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:229
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:229
msgid ""
"This usually is caused by a system were /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:235
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:235
#, python-format
msgid "The error message is '%s'."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:111
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade aborts now.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:135
msgid "Aborting"
msgstr "Òprzestóń"

#: ../DistUpgrade/DistUpgradeViewText.py:140
msgid "Demoted:\n"
msgstr "Zdegradowóné:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:172
#: ../DistUpgrade/DistUpgradeViewText.py:194
#: ../DistUpgrade/DistUpgradeViewText.py:201
msgid "Continue [yN] "
msgstr "Biéj dali [jN] "

#: ../DistUpgrade/DistUpgradeViewText.py:172
#: ../DistUpgrade/DistUpgradeViewText.py:194
msgid "Details [d]"
msgstr "Detale [d]"

#. TRANSLATORS: the "y" is "yes"
#: ../DistUpgrade/DistUpgradeViewText.py:176
#: ../DistUpgrade/DistUpgradeViewText.py:205
msgid "y"
msgstr "j"

#. TRANSLATORS: the "n" is "no"
#: ../DistUpgrade/DistUpgradeViewText.py:179
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:182
msgid "d"
msgstr "d"

#: ../DistUpgrade/DistUpgradeViewText.py:186
#, python-format
msgid "Remove: %s\n"
msgstr "Rëmôj: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:189
#, python-format
msgid "Install: %s\n"
msgstr "Instalëjë %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:192
#, python-format
msgid "Upgrade: %s\n"
msgstr "Aktualizëjë %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:223
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:227
msgid "Restart the system now [yN] "
msgstr "Zrëszëc kòmpùtr znowa? [jN] "

#: ../DistUpgrade/DistUpgrade.glade.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.glade.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:6
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Zacząc zaktualnienié?</big></b>"

#: ../DistUpgrade/DistUpgrade.glade.h:7
msgid "<b><big>Upgrading Ubuntu to version 8.10</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:10
msgid "Difference between the files"
msgstr "Zjinaczi midze lopkama"

#: ../DistUpgrade/DistUpgrade.glade.h:11
msgid "Distribution Upgrade"
msgstr "Aktualizacëjô distribùcëji"

#: ../DistUpgrade/DistUpgrade.glade.h:15
msgid "Restarting the computer"
msgstr "Zrëszanié kòmpùtra znowa"

#: ../DistUpgrade/DistUpgrade.glade.h:16
msgid "Setting new software channels"
msgstr "Nastôwë nowich kanalów softwôrë"

#: ../DistUpgrade/DistUpgrade.glade.h:17
msgid "Terminal"
msgstr "Terminal"

#: ../DistUpgrade/DistUpgrade.glade.h:18
msgid "_Cancel Upgrade"
msgstr "Ò_przestóń zaktualnienié"

#: ../DistUpgrade/DistUpgrade.glade.h:19
msgid "_Continue"
msgstr "_Biéj dali"

#: ../DistUpgrade/DistUpgrade.glade.h:21
msgid "_Replace"
msgstr "_Zastãpi"

#: ../DistUpgrade/DistUpgrade.glade.h:22
msgid "_Report Bug"
msgstr "Zgłoszë _felã"

#: ../DistUpgrade/DistUpgrade.glade.h:24
msgid "_Resume Upgrade"
msgstr "_Znowi zaktualnienié"

#: ../DistUpgrade/DistUpgrade.glade.h:25
msgid "_Start Upgrade"
msgstr "_Startëjë zaktualnienié"

#: ../UpdateManager/DistUpgradeFetcher.py:81
msgid "Could not find the release notes"
msgstr "NIé mòże nalezc wëdowiédzë ò wëdôwkù"

#: ../UpdateManager/DistUpgradeFetcher.py:82
msgid "The server may be overloaded. "
msgstr "Serwera mòże bëc przeladowóny "

#: ../UpdateManager/DistUpgradeFetcher.py:92
msgid "Could not download the release notes"
msgstr "Zladënk wëdowiédzë ò wëdôwkò nie darzëł sã"

#: ../UpdateManager/DistUpgradeFetcher.py:93
msgid "Please check your internet connection."
msgstr "Proszã sprôwdzëc sécowé nastôwë"

#: ../UpdateManager/GtkProgress.py:108
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr ""

#: ../UpdateManager/GtkProgress.py:113
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr ""

#: ../UpdateManager/UpdateManager.py:252
msgid "The list of changes is not available"
msgstr "Lësta zmianów nie je przëstãpnô"

#: ../UpdateManager/UpdateManager.py:260
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""

#: ../UpdateManager/UpdateManager.py:268
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""

#: ../UpdateManager/UpdateManager.py:290
msgid "Failed to detect distribution"
msgstr ""

#: ../UpdateManager/UpdateManager.py:291
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr ""

#: ../UpdateManager/UpdateManager.py:302
msgid "Important security updates"
msgstr "Wôżné zaktualnienia bezpiekù"

#: ../UpdateManager/UpdateManager.py:303
msgid "Recommended updates"
msgstr "Zamòdlëwóné zaktualnienia"

#: ../UpdateManager/UpdateManager.py:304
msgid "Proposed updates"
msgstr "Bédowóné zaktualnienia"

#: ../UpdateManager/UpdateManager.py:305
msgid "Backports"
msgstr "Backpòrtë"

#: ../UpdateManager/UpdateManager.py:306
msgid "Distribution updates"
msgstr "Zaktualnienia distribùcëji"

#: ../UpdateManager/UpdateManager.py:311
msgid "Other updates"
msgstr "Jinszé zaktualnienia"

#: ../UpdateManager/UpdateManager.py:320
msgid "Previous selected"
msgstr ""

#: ../UpdateManager/UpdateManager.py:495
#, python-format
msgid "Version %s: \n"
msgstr "Wersëjô %s: \n"

#: ../UpdateManager/UpdateManager.py:556
msgid "Downloading list of changes..."
msgstr "Zladënk lëstë zjinaków..."

#: ../UpdateManager/UpdateManager.py:583
msgid "_Uncheck All"
msgstr "_Òdznaczë wszëtczé"

#: ../UpdateManager/UpdateManager.py:589
msgid "_Check All"
msgstr "_Naznaczë wszëtczé"

#. TRANSLATORS: b stands for Bytes
#: ../UpdateManager/UpdateManager.py:633 ../UpdateManager/UpdateManager.py:689
#, python-format
msgid "Download size: %s"
msgstr "Do zladënkù: %s"

#: ../UpdateManager/UpdateManager.py:637
msgid "Unknown download size"
msgstr "Nieznónô miara lopków do zladënkù"

#: ../UpdateManager/UpdateManager.py:645
msgid ""
"It is unknown when the package information was updated last. Please try "
"clicking on the 'Check' button to update the information."
msgstr ""

#: ../UpdateManager/UpdateManager.py:654
#, python-format
msgid "The package information was last updated %s day ago."
msgid_plural "The package information was last updated %s days ago."
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:658
#, python-format
msgid "The package information was last updated %s hour ago."
msgid_plural "The package information was last updated %s hours ago."
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:662
msgid "The package information was last updated less than one hour ago."
msgstr ""

#: ../UpdateManager/UpdateManager.py:670
#: ../data/glade/UpdateManager.glade.h:21
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""

#: ../UpdateManager/UpdateManager.py:685
#, python-format
msgid "You can install %s update."
msgid_plural "You can install %s updates."
msgstr[0] "Mòże winstalowac %s zaktualnienié."
msgstr[1] "Mòże winstalowac %s zaktualnienia."
msgstr[2] "Mòże winstalowac %s zaktualnieniów."

#: ../UpdateManager/UpdateManager.py:727
msgid "Please wait, this can take some time."
msgstr "Proszã żdac, to mòże kąsk dérowac."

#: ../UpdateManager/UpdateManager.py:729
msgid "Update is complete"
msgstr "Zaktualnienié zakùńczoné."

#: ../UpdateManager/UpdateManager.py:781
msgid "Reading package information"
msgstr "Czëtanié wëdowiédzë ò paczétach"

#: ../UpdateManager/UpdateManager.py:884
msgid "Could not initialize the package information"
msgstr "Nié mòże zainicjowac wëdowiédzë ò paczétach"

#: ../UpdateManager/UpdateManager.py:885
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:907
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:932
#, python-format
msgid "(Size: %s)"
msgstr "(Miara: %s)"

#: ../UpdateManager/UpdateManager.py:934
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:938
#, python-format
msgid "Version %s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:951
msgid "Your distribution is not supported anymore"
msgstr ""

#: ../UpdateManager/UpdateManager.py:952
msgid ""
"You will not get any further security fixes or critical updates. Upgrade to "
"a later version of Ubuntu Linux. See http://www.ubuntu.com for more "
"information on upgrading."
msgstr ""

#: ../UpdateManager/UpdateManager.py:978
msgid "Downloading the upgrade tool"
msgstr "Zladënk nôrzãdzów zaktualnienia"

#: ../UpdateManager/UpdateManager.py:980
msgid "The upgrade tool will guide you through the upgrade process."
msgstr ""

#: ../UpdateManager/UpdateManager.py:988
#, python-format
msgid "<b>New distribution release '%s' is available</b>"
msgstr "<b>Nowi wëdôwk distribùcëji \"%s\" je przëstãpny</b>"

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:1031
msgid "Software index is broken"
msgstr "Spisënk softwôrë mô felã"

#: ../UpdateManager/UpdateManager.py:1032
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""

#: ../data/glade/UpdateManager.glade.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""

#: ../data/glade/UpdateManager.glade.h:4
msgid "<big><b>Keep your system up-to-date</b></big>"
msgstr "<big><b>Trzëmôj wiedno systemã fùl zaktualniona</b></big>"

#: ../data/glade/UpdateManager.glade.h:5
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:6
msgid "<big><b>Starting Update Manager</b></big>"
msgstr "<big><b>Zrëszanié menadżera aktualizacëji</b></big>"

#: ../data/glade/UpdateManager.glade.h:7
msgid "Changes"
msgstr "Zjinaczi"

#: ../data/glade/UpdateManager.glade.h:8
msgid "Chec_k"
msgstr "Sp_rôwdzë"

#: ../data/glade/UpdateManager.glade.h:9
msgid "Check the software channels for new updates"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:10
msgid "Description"
msgstr "Òpisënk"

#: ../data/glade/UpdateManager.glade.h:11
msgid "Description of update"
msgstr "Òpisënk zaktualnieniów"

#: ../data/glade/UpdateManager.glade.h:12
msgid "Release Notes"
msgstr "Wëdowiédzô ò wëdôwkù"

#: ../data/glade/UpdateManager.glade.h:13
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" ◦ A previous upgrade which didn't complete\n"
" ◦ Problems with some of the installed software\n"
" ◦ Unofficial software packages not provided by Ubuntu\n"
" ◦ Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:20
msgid "Show progress of individual files"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:22
msgid "U_pgrade"
msgstr "_Aktualizëjë"

#: ../data/glade/UpdateManager.glade.h:23
#: ../data/update-manager.desktop.in.h:3
msgid "Update Manager"
msgstr "Menedżera aktualizacëji"

#: ../data/glade/UpdateManager.glade.h:24
msgid "Upgrade to the latest version of Ubuntu"
msgstr "Zaktualni do nônowszegò wëdôwkù Ubuntu"

#: ../data/glade/UpdateManager.glade.h:25
msgid "_Hide this information in the future"
msgstr "_Zatacë tã wëdowiédzã w przińdnosce"

#: ../data/glade/UpdateManager.glade.h:26
msgid "_Install Updates"
msgstr "_Winstalëjë zaktualnienia"

#: ../data/glade/UpdateManager.glade.h:27
msgid "_Partial Upgrade"
msgstr "_Dzélowé zaktualnienié"

#: ../data/glade/UpdateManager.glade.h:28
msgid "_Upgrade"
msgstr "_Aktualizëjë"

#: ../data/glade/UpdateManager.glade.h:29
msgid "updates"
msgstr "zaktualnienia"

#: ../data/update-manager.desktop.in.h:1
msgid "Show and install available updates"
msgstr ""

#: ../data/update-manager.desktop.in.h:2
msgid "Software Updates"
msgstr "Zaktualnienia softwôrë"

#: ../data/update-manager.schemas.in.h:1
msgid "*deprecated* Check for new distribution releases"
msgstr ""

#: ../data/update-manager.schemas.in.h:2
msgid "Auto close the install window after successful install"
msgstr ""

#: ../data/update-manager.schemas.in.h:3
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""

#: ../data/update-manager.schemas.in.h:4
msgid ""
"If this key is set the install window will be automatically closed on "
"successful installation."
msgstr ""

#: ../data/update-manager.schemas.in.h:5
msgid ""
"If this key is set the main update list window will show version information "
"(from version to version)."
msgstr ""

#: ../data/update-manager.schemas.in.h:6
msgid "Remind to reload the channel list"
msgstr ""

#: ../data/update-manager.schemas.in.h:7
msgid "Show details of an update"
msgstr ""

#: ../data/update-manager.schemas.in.h:8
msgid "Show version in update list"
msgstr ""

#: ../data/update-manager.schemas.in.h:9
msgid "Stores the size of the update-manager dialog"
msgstr ""

#: ../data/update-manager.schemas.in.h:10
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr ""

#: ../data/update-manager.schemas.in.h:11
msgid "The window size"
msgstr "Miara òkna"

#: ../data/update-manager.schemas.in.h:12
msgid ""
"This key is deprecated in favor of the file /etc/update-manager/release-"
"upgrades Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""

#: ../update-manager:55
msgid "Show version and exit"
msgstr "Wëskrzënianié wersëji ë wińdzënk"

#: ../update-manager:58
msgid "Check if a new distribution release is available"
msgstr "Sprôwdzë przëstãpnosc nowegò wëdôwka distribùcëji"

#: ../update-manager:61 ../do-release-upgrade:23
msgid "Check if upgrading to the latest devel release is possible"
msgstr "Sprôwdzë mòżnotã zaktualnieniô do nônowszi testowi wersëji"

#: ../update-manager:65
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""

#: ../update-manager:68
msgid "Try to run a dist-upgrade"
msgstr "Spróbùjë zrëszëc zaktualnienié distribùcëji"

#: ../update-manager:87
msgid "Running partial upgrade"
msgstr "Przerôbianié dzélowégò zaktualnienia"

#: ../do-release-upgrade:27
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""

#: ../do-release-upgrade:31
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""

#: ../do-release-upgrade:37
msgid "Run the specified frontend"
msgstr ""

#: ../do-release-upgrade:41
msgid "Checking for a new ubuntu release"
msgstr "Sprôwdzë przëstãpnosc nowegò wëdôwka Ubuntu"

#: ../do-release-upgrade:48
msgid "No new release found"
msgstr "Felënk nowegò wëdôwka"

#~ msgid "Failed to add the CD"
#~ msgstr "Ni mòże dodac platë CD"

#, python-format
#~ msgid "Fetching file %li of %li at %sb/s"
#~ msgstr "Zladënk lopka %li z %li z chùtkòscą %sb/s"

#, python-format
#~ msgid "%li days %li hours %li minutes"
#~ msgstr "%li dni %li gòdzën %li minut"

#~ msgid "Daily"
#~ msgstr "Codniowò"

#~ msgid "Every two days"
#~ msgstr "Co dwa dni"

#~ msgid "Weekly"
#~ msgstr "Co tidzeń"

#~ msgid "Every two weeks"
#~ msgstr "Co dwa tidzenie"

#~ msgid "After one week"
#~ msgstr "Pò tidzeniu"

#~ msgid "After two weeks"
#~ msgstr "Pò dwóch tidzeniach"

#~ msgid "After one month"
#~ msgstr "Pò miesącu"

#~ msgid "Import key"
#~ msgstr "Impòrtëjë klucz"

#~ msgid "Error importing selected file"
#~ msgstr "Fela òbczas impòrtowania wëbrónegò lopkù"

#~ msgid "Error removing the key"
#~ msgstr "Fela òbczas rëmaniô klucza"

#~ msgid ""
#~ "The key you selected could not be removed. Please report this as a bug."
#~ msgstr "Nie mòżna bëło rëmnąc klucza. Proszã zgłoszëc to jakno felã."

#~ msgid "Every %s days"
#~ msgstr "Co %s dni"

#~ msgid "After %s days"
#~ msgstr "P %s dniach"

#~ msgid "Please enter a name for the disc"
#~ msgstr "Proszã dac miono dlô platë"

#~ msgid "<b>Remove %s</b>"
#~ msgstr "<b>Rëmôj %s</b>"

#~ msgid "The selected file may not be a GPG key file or it might be corrupt."
#~ msgstr "Wëbróny lopk może nie bëc kluczã abò mòże bëc pòpsëti."

#~ msgid "(Source Code)"
#~ msgstr "(zdrojowi kòd)"

#~ msgid "Source Code"
#~ msgstr "Zdrojowi kòd"

#~ msgid "%s updates"
#~ msgstr "%s aktualizacëji"

#~ msgid "%s (%s)"
#~ msgstr "%s (%s)"

#~ msgid "Nearest server"
#~ msgstr "Nôblëższi serwera"

#~ msgid "Active"
#~ msgstr "Aktiwny"
