# Kashubian translation for update-manager
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the update-manager package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2010-09-22 05:12+0000\n"
"PO-Revision-Date: 2010-09-06 03:52+0000\n"
"Last-Translator: Launchpad Translations Administrators "
"<rosetta@launchpad.net>\n"
"Language-Team: Kashubian <csb@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
"|| n%100>=20) ? 1 : 2;\n"
"X-Launchpad-Export-Date: 2010-09-27 08:04+0000\n"
"X-Generator: Launchpad (build Unknown)\n"

#. TRANSLATORS: download size is 0
#: ../DistUpgrade/utils.py:346 ../UpdateManager/Core/utils.py:346
msgid "0 KB"
msgstr "0 KB"

#. TRANSLATORS: download size of very small updates
#: ../DistUpgrade/utils.py:349 ../UpdateManager/Core/utils.py:349
msgid "1 KB"
msgstr "1 KB"

#. TRANSLATORS: download size of small updates, e.g. "250 KB"
#: ../DistUpgrade/utils.py:352 ../UpdateManager/Core/utils.py:352
#, python-format
msgid "%.0f KB"
msgstr "%.0f KB"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:355 ../UpdateManager/Core/utils.py:355
#, python-format
msgid "%.1f MB"
msgstr "%.1f MB"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:209 ../DistUpgrade/distro.py:424
#, python-format
msgid "Server for %s"
msgstr "Serwera dlô kraju %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:227 ../DistUpgrade/distro.py:233
#: ../DistUpgrade/distro.py:249
msgid "Main server"
msgstr "Przédnô serwera"

#: ../DistUpgrade/distro.py:253
msgid "Custom servers"
msgstr "Jine serwerë"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:131
msgid "Could not calculate sources.list entry"
msgstr "Ni mòże òbrachòwac wpisënka w lopkù sources.list"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:234
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"Ni mòże nalezc niżódnëch lopków z paczetama, mòże to nie je disk z Ubuntu "
"abò lëchô architektura?"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:277
msgid "Failed to add the CD"
msgstr "Ni mòże dodac platë CD"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:278
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"Fela przë dodôwaniu platë CD, aktualizacëjô òprzestónô. Proszã zgłoszëc "
"rapòrt ò felë jeżlë je to òficjalnô platka Ubuntu.\n"
"\n"
"Zamkłosc felë to:\n"
"\"%s\""

#: ../DistUpgrade/DistUpgradeCache.py:130
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Rëmanié lëchegò paczétu"
msgstr[1] "Rëmanié lëchich paczétów"
msgstr[2] "Rëmanié lëchich paczétów"

#: ../DistUpgrade/DistUpgradeCache.py:133
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"Paczét \"%s\" je w niezgòdnym stónie ë je nót gò winstalowac znowa,  ni "
"òstało równak nalazłé archiwùm negò paczétu. Rëmnąc paczét terô abë jisc "
"dali?"
msgstr[1] ""
"Paczétë \"%s\" są w niezgòdnym stónie ë je nót je winstalowac znowa,  ni "
"òstało równak nalazłé archiwùm nych paczétu. Rëmnąc paczétë terô abë jisc "
"dali?"
msgstr[2] ""
"Paczétë \"%s\" są w niezgòdnym stónie ë je nót je winstalowac znowa,  ni "
"òstało równak nalazłé archiwùm nych paczétu. Rëmnąc paczétë terô abë jisc "
"dali?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:231
msgid "The server may be overloaded"
msgstr "Serwer mòże bëc przecãżony"

#: ../DistUpgrade/DistUpgradeCache.py:341
msgid "Broken packages"
msgstr "Paczétë są zepsëté"

#: ../DistUpgrade/DistUpgradeCache.py:342
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"Systema zamëkô w se zepsëté paczetë, jaczich nie szło ùprawic. Proszã wprzód "
"pòprawic je brëkùjąc menadżera paczetów Synaptic abò apt-get."

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:631
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"Pòkôzôł sã problem, chtënegò nie dô sã rozwiązac, przë òbrechòwaniu "
"aktualizacëji:\n"
"%s\n"
"\n"
" Mòże to bëc sparłãczoné z:\n"
" * Aktualizacëją do testowi wersëji Ubuntu\n"
" * Brëkòwaniém biéżny wersëji Ubuntu\n"
" * Brëkòwanié nieòficjalnych paczétów z bùtna repòzytorëjów Ubuntu\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:641
msgid "This is most likely a transient problem, please try again later."
msgstr "To są le chwilowé problemë. Proszã spróbòwac pòzdze."

#: ../DistUpgrade/DistUpgradeCache.py:644
msgid ""
"If none of this applies, then please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"Jeżlë niżóden nie je sparłãczony, to proszã zgłoszëc felã paczétu \"update-"
"manager\"  ë dodac lopk rapòrtu z  /var/log/dist-upgrade/."

#: ../DistUpgrade/DistUpgradeCache.py:650
#: ../UpdateManager/UpdateManager.py:870
msgid "Could not calculate the upgrade"
msgstr "Nié mòże przerobic aktualizacëjów"

#: ../DistUpgrade/DistUpgradeCache.py:700
msgid "Error authenticating some packages"
msgstr "Fela ùdowierzaniô niechtërnych paczétów"

#: ../DistUpgrade/DistUpgradeCache.py:701
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"Nie dało sã ùdowierzëc niejednych paczétów. Mòże to bëc czasowô fela sécë. "
"Mòże spróbòwac pòzdze znowa. Niżi nachôdô sã lësta nieùdowierzónych paczétów"

#: ../DistUpgrade/DistUpgradeCache.py:721
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"Paczét \"%s\" je wëbróny do rëmniãcô, je òn rówank na lësce paczétów, "
"chtërnych nie je nót rëmac."

#: ../DistUpgrade/DistUpgradeCache.py:725
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "Nóterny paczét \"%s\" je nacéchòwóny do rëmniãcô."

#: ../DistUpgrade/DistUpgradeCache.py:734
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "Próba instalacëji wersëji \"%s\", jakô je na czôrny lësce"

#: ../DistUpgrade/DistUpgradeCache.py:836
#, python-format
msgid "Can not mark '%s' for upgrade"
msgstr "Ni mòże nacéchòwac \"%s\" do aktualizacëji"

#: ../DistUpgrade/DistUpgradeCache.py:850
#, python-format
msgid "Can't install '%s'"
msgstr "Ni mòże winstalowac '%s'"

#: ../DistUpgrade/DistUpgradeCache.py:851
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""
"Nie bëło mòżno winstalowac wëmôgónegò paczétu. Proszã zgłoszëc to jakno "
"felã. "

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:860
msgid "Can't guess meta-package"
msgstr "Ni mòże òpisac meta-paczétu"

#: ../DistUpgrade/DistUpgradeCache.py:861
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"Systema nie zamëkô w se paczétów ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop abò edubuntu-desktop ë ni mòże wëkrëc ùżëwóny wersëji Ubuntu.\n"
" Proszã winstalowac jeden z tich paczétów brëkùjąc programë Synaptic abò apt-"
"get nigle póńdzesz dali."

#: ../DistUpgrade/DistUpgradeController.py:86
msgid "Reading cache"
msgstr "Czëtanié pòdrãcznegò bùfora"

#: ../DistUpgrade/DistUpgradeController.py:189
msgid "Unable to get exclusive lock"
msgstr "Ni mòże dobëc blokadë na wëłãcznotã"

#: ../DistUpgrade/DistUpgradeController.py:190
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Zwëczajno òznôczô to, że jinszô aplikacëjô do sprôwianiô paczétama (jakno "
"apt-get abò aptitude) je zrëszonô. Nót je wprzód zamknąc nã aplikacëjã."

#: ../DistUpgrade/DistUpgradeController.py:236
msgid "Upgrading over remote connection not supported"
msgstr "Aktualizacëjô przez daleczé sparłãcznie nie je wspierónô"

#: ../DistUpgrade/DistUpgradeController.py:237
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:251
msgid "Continue running under SSH?"
msgstr "Jic dali ze sparłãczeniã SSH?"

#: ../DistUpgrade/DistUpgradeController.py:252
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:267
msgid "Starting additional sshd"
msgstr "Zrëszanié dodôwnëch ùsłëżnotów ssh"

#: ../DistUpgrade/DistUpgradeController.py:268
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Dodôwny demon sshd bãdze zrëszony na pòrce '%s', abë zletczic dobëwanié "
"nazôd w przëtrôfkù problemów z aktualaną ùsłëżnotą ssh. W przëtrôfkù "
"niedarzënkù z aktualną sesëją ssh, wcyg mòże przëłączëc sã do dodôwny "
"sesëji.\n"

#: ../DistUpgrade/DistUpgradeController.py:339
#: ../DistUpgrade/DistUpgradeController.py:384
msgid "Can not upgrade"
msgstr "Nié mòże zaktualnic"

#: ../DistUpgrade/DistUpgradeController.py:340
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr ""
"Aktualizacëjô z wersëji \\\"%s\\\" do \\\"%s\\\" nie je wspierónô przez to "
"nôrzãdze."

#: ../DistUpgrade/DistUpgradeController.py:349
msgid "Sandbox setup failed"
msgstr "Nastôw tekstowégò tribù nie darzëł sã"

#: ../DistUpgrade/DistUpgradeController.py:350
msgid "It was not possible to create the sandbox environment."
msgstr "Ùsôdzanié tekstowégò òkrãżô nie bëło mòżlëwé."

#: ../DistUpgrade/DistUpgradeController.py:356
msgid "Sandbox mode"
msgstr "Tekstowi trib"

#: ../DistUpgrade/DistUpgradeController.py:357
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a systemdir from now until the next reboot are "
"permanent."
msgstr ""
"Aktualizacëjô robi w tekstowim tribie. Wszëtczé zmianë są zapisóné do \"%s\" "
"ë bãdą pòcësniãté pò zrëszeniô kòmpùtra znowa. \n"
"\n"
"Do nôslédnegò zrëszeniô kòmpùtra *wszëtczé* wprowôdzoné do systemòwich "
"katalogów zmianë bãdą pòcësniãté."

#: ../DistUpgrade/DistUpgradeController.py:385
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"Instalacëjô python je zepsëtô. Proszã naprawic dowiązanié do "
"\"/usr/bin/python\"."

#: ../DistUpgrade/DistUpgradeController.py:411
msgid "Package 'debsig-verify' is installed"
msgstr "Paczét \"debsig-verify\" je winstalowóny"

#: ../DistUpgrade/DistUpgradeController.py:412
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:422
msgid "Include latest updates from the Internet?"
msgstr "Dodac nônowszé zaktualnienia z internetu?"

#: ../DistUpgrade/DistUpgradeController.py:423
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:639
#, python-format
msgid "disabled on upgrade to %s"
msgstr "wëłączony przë aktualizacëji do %s"

#: ../DistUpgrade/DistUpgradeController.py:666
msgid "No valid mirror found"
msgstr "Pòprôwny szpéglowi serwer ni nalazłi"

#: ../DistUpgrade/DistUpgradeController.py:667
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:687
msgid "Generate default sources?"
msgstr "Wëgenerowac domëszlné zdroje?"

#: ../DistUpgrade/DistUpgradeController.py:688
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:723
msgid "Repository information invalid"
msgstr "Lëchô wëdowiédzô ò repòzëtorëjach"

#: ../DistUpgrade/DistUpgradeController.py:724
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:730
msgid "Third party sources disabled"
msgstr "Zdoje samòstójnëch dostôwców òstałë włączoné"

#: ../DistUpgrade/DistUpgradeController.py:731
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:771
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Paczét w niezgòdnym stónie"
msgstr[1] "Paczétë w niezgòdnym stónie"
msgstr[2] "Paczétë w niezgòdnym stónie"

#: ../DistUpgrade/DistUpgradeController.py:774
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"Paczét \"%s\" je w niezgòdnym stónie ë mùszi bëc winstalowóny znowa, ni mòże "
"równak nalezc niżódnegò archiwùm negò paczétu. Proszã winstalowac paczét "
"rãczno abò rëmnąc gò z systemë."
msgstr[1] ""
"Paczétë \"%s\"są w niezgòdnym stónie ë mùszą bëc winstalowóné znowa, ni mòże "
"równak nalezc niżódnegò archiwùm nych paczétów. Proszã winstalowac paczétë "
"rãczno abò rëmnąc je z systemë."
msgstr[2] ""
"Paczétë \"%s\"są w niezgòdnym stónie ë mùszą bëc winstalowóné znowa, ni mòże "
"równak nalezc niżódnegò archiwùm nych paczétów. Proszã winstalowac paczétë "
"rãczno abò rëmnąc je z systemë."

#: ../DistUpgrade/DistUpgradeController.py:822
msgid "Error during update"
msgstr "Fela òbczas aktualizacëji"

#: ../DistUpgrade/DistUpgradeController.py:823
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""

#. print "on_button_install_clicked"
#: ../DistUpgrade/DistUpgradeController.py:832
#: ../UpdateManager/UpdateManager.py:628
msgid "Not enough free disk space"
msgstr "Za mało placu na diskù"

#: ../DistUpgrade/DistUpgradeController.py:833
#, python-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of %s free space on disk "
"'%s'. Please free at least an additional %s of disk space on '%s'. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:861
#: ../DistUpgrade/DistUpgradeController.py:1577
msgid "Calculating the changes"
msgstr "Przerôbianié zmianów"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:893
msgid "Do you want to start the upgrade?"
msgstr "Chcesz zrëszëc aktualizacëjã?"

#: ../DistUpgrade/DistUpgradeController.py:959
msgid "Upgrade canceled"
msgstr "Aktualizacëjô òprzestónô"

#: ../DistUpgrade/DistUpgradeController.py:960
msgid ""
"The upgrade cancels now and the original system state is restored. You can "
"resume the upgrade at a later time."
msgstr ""
"Aktualizacëjô bãdze terô òprzestónô, a systema bãdze doprowôdzony do "
"òridżinalnegò stónu. Aktualizacëjã mòże znowic pòzdze."

#: ../DistUpgrade/DistUpgradeController.py:965
#: ../DistUpgrade/DistUpgradeController.py:1064
msgid "Could not download the upgrades"
msgstr "Nié mòże zladowac zaktualnieniów"

#: ../DistUpgrade/DistUpgradeController.py:966
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far are kept."
msgstr ""

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1016
#: ../DistUpgrade/DistUpgradeController.py:1052
#: ../DistUpgrade/DistUpgradeController.py:1157
msgid "Error during commit"
msgstr "Fela òbczas zacwierdzaniô"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1018
#: ../DistUpgrade/DistUpgradeController.py:1054
#: ../DistUpgrade/DistUpgradeController.py:1196
msgid "Restoring original system state"
msgstr "Doprowôdzanié nazôd òriginalnegò stónu systemë"

#: ../DistUpgrade/DistUpgradeController.py:1019
#: ../DistUpgrade/DistUpgradeController.py:1033
#: ../DistUpgrade/DistUpgradeController.py:1055
msgid "Could not install the upgrades"
msgstr "Instalacëjô aktualizacëji nie darzëła sã."

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1024
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1029
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"Proszã zgłoszëc nã felã paczétu \"update-manager\", w rapòrce proszã dodac "
"lopczi z /var/log/dist-upgrade/.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1065
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1145
msgid "Remove obsolete packages?"
msgstr "Rëmnąc stôre paczétë?"

#: ../DistUpgrade/DistUpgradeController.py:1146
#: ../DistUpgrade/DistUpgrade.ui.h:22
msgid "_Keep"
msgstr "Ù_trzëmôj"

#: ../DistUpgrade/DistUpgradeController.py:1146
msgid "_Remove"
msgstr "_Rëmôj"

#: ../DistUpgrade/DistUpgradeController.py:1158
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr "Pòkôza sã fela przë czëszczeniô. Wicy wëdowiédzë niżi. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1234
msgid "Required depends is not installed"
msgstr "Wëmôgónô zanóleżnota nie je winstalowónô."

#: ../DistUpgrade/DistUpgradeController.py:1235
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "Wëmôgónô zanóleżnota '%s' nie je winstalowónô "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1480
#: ../DistUpgrade/DistUpgradeController.py:1547
msgid "Checking package manager"
msgstr "Sprôwdzanié menadżera paczétów"

#: ../DistUpgrade/DistUpgradeController.py:1485
msgid "Preparing the upgrade failed"
msgstr "Przëszëkòwanié aktualizacëjów nie darzëło sã"

#: ../DistUpgrade/DistUpgradeController.py:1486
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bug report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1502
msgid "Getting upgrade prerequisites failed"
msgstr "Dobëcé elementów nótrnych do aktualizacëji nie darzëło sã"

#: ../DistUpgrade/DistUpgradeController.py:1503
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bug report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1533
msgid "Updating repository information"
msgstr "Aktualizacëjô wëdowiédzë ò respòzëtorëjach"

#: ../DistUpgrade/DistUpgradeController.py:1565
msgid "Invalid package information"
msgstr "Lëchô wëdowiédzô ò paczétach"

#: ../DistUpgrade/DistUpgradeController.py:1566
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1583
#: ../DistUpgrade/DistUpgradeController.py:1631
msgid "Fetching"
msgstr "Zladënk"

#: ../DistUpgrade/DistUpgradeController.py:1589
#: ../DistUpgrade/DistUpgradeController.py:1635
msgid "Upgrading"
msgstr "Zaktualnienié"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1594
#: ../DistUpgrade/DistUpgradeController.py:1637
#: ../DistUpgrade/DistUpgradeController.py:1644
#: ../DistUpgrade/DistUpgradeController.py:1655
msgid "Upgrade complete"
msgstr "Zaktualnienié zakùńczoné"

#: ../DistUpgrade/DistUpgradeController.py:1595
#: ../DistUpgrade/DistUpgradeController.py:1638
#: ../DistUpgrade/DistUpgradeController.py:1645
msgid ""
"The upgrade is completed but there were errors during the upgrade process."
msgstr "Aktualizacëjô skùńczonô, dô równak fele w procese aktualizacëji."

#: ../DistUpgrade/DistUpgradeController.py:1602
msgid "Searching for obsolete software"
msgstr "Szëkba za stôrą softwôrą"

#: ../DistUpgrade/DistUpgradeController.py:1607
msgid "System upgrade is complete."
msgstr "Zaktualnienié systemë dzrzëło sã"

#: ../DistUpgrade/DistUpgradeController.py:1656
msgid "The partial upgrade was completed."
msgstr "Dzélowô aktualizacëjô skùńcoznô"

#: ../DistUpgrade/DistUpgradeQuirks.py:168
msgid "evms in use"
msgstr "EVMS w brëkùńkù"

#: ../DistUpgrade/DistUpgradeQuirks.py:169
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:434
#: ../DistUpgrade/DistUpgradeQuirks.py:462
#: ../DistUpgrade/DistUpgradeQuirks.py:489
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:438
#: ../DistUpgrade/DistUpgradeQuirks.py:466
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04 LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Kòmpùtr brëkùje czérownika graficzi NVIDIA \"nvidia\". Felënk wersëji "
"czérownika z chtërną wespółrobi twòjô hardwôra w Ubuntu 10.04 LTS.\n"
"\n"
"Jisc dali?"

#: ../DistUpgrade/DistUpgradeQuirks.py:493
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Kòmpùtr brëkùje czérownika graficzi AMD \"fglrx\". Felënk wersëji czérownika "
"z chtërną wespółrobi twòjô hardwôra w Ubuntu 10.04 LTS.\n"
"\n"
"Jisc dali?"

#: ../DistUpgrade/DistUpgradeQuirks.py:520
msgid "No ARMv6 CPU"
msgstr "Felënk procesora ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:521
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:541
msgid "No init available"
msgstr "Felënk przëstãpù do procesu init"

#: ../DistUpgrade/DistUpgradeQuirks.py:542
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:47
msgid "Sandbox upgrade using aufs"
msgstr "Testowô aktualizacëjô brëkùjąc aufs"

#: ../DistUpgrade/DistUpgradeMain.py:49
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr "Ùżëjë pòdóną stegnã do szëkbë za CD z paczétama aktualizacëji"

#: ../DistUpgrade/DistUpgradeMain.py:55
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Brëkùnk graficzny nôdkładczi. Terô przëstãpné: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:58
msgid "*DEPRECATED* this option will be ignore"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:61
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr "Ùżëjë blós dzélowi aktualizacëji (bez nadpisaniô source.list)"

#: ../DistUpgrade/DistUpgradeMain.py:63
msgid "Set datadir"
msgstr "Nastôwi stegnã do pòdôwków"

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:113
#: ../DistUpgrade/DistUpgradeViewKDE.py:190
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Proszã włożëc '%s' do nëkù '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:134
#: ../DistUpgrade/DistUpgradeViewKDE.py:204
msgid "Fetching is complete"
msgstr "Zladënk zakùńczony"

#: ../DistUpgrade/DistUpgradeViewGtk.py:145
#: ../DistUpgrade/DistUpgradeViewKDE.py:217
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Zladënk %li lopka z %li z chùtkòscą %sB/s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:148
#: ../DistUpgrade/DistUpgradeViewGtk.py:288
#: ../DistUpgrade/DistUpgradeViewKDE.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:358
#, python-format
msgid "About %s remaining"
msgstr "Òstało kòl %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:151
#: ../DistUpgrade/DistUpgradeViewKDE.py:220
#, python-format
msgid "Fetching file %li of %li"
msgstr "Zladënk lopka %li z %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:183
#: ../DistUpgrade/DistUpgradeViewKDE.py:254
msgid "Applying changes"
msgstr "Zacwierdzanié zmianów"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:208
#: ../DistUpgrade/DistUpgradeViewKDE.py:267
msgid "dependency problems - leaving unconfigured"
msgstr "problemë z zanôleżnotama - òstôwioné nieskònfigùrowóné"

#: ../DistUpgrade/DistUpgradeViewGtk.py:213
#: ../DistUpgrade/DistUpgradeViewKDE.py:269
#, python-format
msgid "Could not install '%s'"
msgstr "Nie bëło mòżno zainstalowac '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:214
#: ../DistUpgrade/DistUpgradeViewKDE.py:270
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:231
#: ../DistUpgrade/DistUpgradeViewKDE.py:291
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Zastãpic swój lopk kònfigùracëji\n"
"'%s'?"

#: ../DistUpgrade/DistUpgradeViewGtk.py:232
#: ../DistUpgrade/DistUpgradeViewKDE.py:292
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:246
#: ../DistUpgrade/DistUpgradeViewKDE.py:310
msgid "The 'diff' command was not found"
msgstr "Pòlét 'diff' nie òstôł nalazłi"

#: ../DistUpgrade/DistUpgradeViewGtk.py:454
#: ../DistUpgrade/DistUpgradeViewText.py:88
msgid "A fatal error occurred"
msgstr "Pòkôza sã kriticznô fela"

#: ../DistUpgrade/DistUpgradeViewGtk.py:455
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:472
msgid "Ctrl-c pressed"
msgstr "Wcësniãto Ctrl-C"

#: ../DistUpgrade/DistUpgradeViewGtk.py:473
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:621
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Abë nie ùtracëc pòdôwków proszã zamknąc wszëtczé òtemkłé aplikacëje ë "
"dokùmentë."

#: ../DistUpgrade/DistUpgradeViewGtk.py:635
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:636
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:637
#, python-format
msgid "Remove (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:638
#, python-format
msgid "No longer needed (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:639
#, python-format
msgid "Install (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:640
#, python-format
msgid "Upgrade (%s)"
msgstr ""

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:191
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Media Change"
msgstr "Zmiana media"

#: ../DistUpgrade/DistUpgradeViewKDE.py:322
msgid "Show Difference >>>"
msgstr "Wëskrzëni  nierównoscë >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:325
msgid "<<< Hide Difference"
msgstr "<<< Zatacë nierównoscë"

#: ../DistUpgrade/DistUpgradeViewKDE.py:539
msgid "Error"
msgstr "Fela"

#: ../DistUpgrade/DistUpgradeViewKDE.py:551
msgid "&Cancel"
msgstr "Ò&przestóń"

#: ../DistUpgrade/DistUpgradeViewKDE.py:553
#: ../DistUpgrade/DistUpgradeViewKDE.py:795
msgid "&Close"
msgstr "Z&amkni"

#: ../DistUpgrade/DistUpgradeViewKDE.py:599
msgid "Show Terminal >>>"
msgstr "Wëskrzëni terminal >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:602
msgid "<<< Hide Terminal"
msgstr "<<< Zatacë terminal"

#: ../DistUpgrade/DistUpgradeViewKDE.py:682
msgid "Information"
msgstr "Wëdowiédzô"

#: ../DistUpgrade/DistUpgradeViewKDE.py:733
#: ../DistUpgrade/DistUpgradeViewKDE.py:778
#: ../DistUpgrade/DistUpgradeViewKDE.py:781 ../DistUpgrade/DistUpgrade.ui.h:11
msgid "Details"
msgstr "Drobnotë"

#: ../DistUpgrade/DistUpgradeViewKDE.py:759
#, python-format
msgid "No longer supported %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:761
#, python-format
msgid "Remove %s"
msgstr "Rëmôj %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:763
#: ../DistUpgrade/DistUpgradeViewText.py:175
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "Rëmôj (bëło aùtomatno winstalowóné) %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:765
#, python-format
msgid "Install %s"
msgstr "Instalëjë %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:767
#, python-format
msgid "Upgrade %s"
msgstr "Aktualizëjë %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:791
#: ../DistUpgrade/DistUpgradeViewText.py:223
msgid "Restart required"
msgstr "Wëmôgóne je zrëszenié kòmpùtra znowa"

#: ../DistUpgrade/DistUpgradeViewKDE.py:791
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Zrëszë kòpmùtr znowa, żebë zakùńczëc aktualizacëjã</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:794 ../DistUpgrade/DistUpgrade.ui.h:25
#: ../data/glade/UpdateManager.ui.h:31
msgid "_Restart Now"
msgstr "_Zrëszë znowa"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:812
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"b><big>Òprzestac aktualizacëjã ?</big></b>\n"
"\n"
"Systema mòże stracëc sztabilnotã jeżlë òprzestóniesz aktualizacëjã. "
"Zamòdlëwô sã znowienié aktualizacëji."

#: ../DistUpgrade/DistUpgradeViewKDE.py:816
msgid "Cancel Upgrade?"
msgstr "Òprzestac zaktualnienié?"

#: ../DistUpgrade/DistUpgradeView.py:60
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li dzéń"
msgstr[1] "%li dni"
msgstr[2] "%li dniów"

#: ../DistUpgrade/DistUpgradeView.py:62
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li gòdzëna"
msgstr[1] "%li gòdzënë"
msgstr[2] "%li gòdzën"

#: ../DistUpgrade/DistUpgradeView.py:64
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li minuta"
msgstr[1] "%li minutë"
msgstr[2] "%li minutów"

#: ../DistUpgrade/DistUpgradeView.py:65
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li sekùnda"
msgstr[1] "%li sekòndë"
msgstr[2] "%li sekùndów"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:81
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:99
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:147
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"Zladënk dérëje kòl %s brëkùjąc sparłãczenia 1 Mbit DSL abò kòl %s brëkùjąc "
"mòdewòwégò sparłãczenia 56k."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:151
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "Zladënk mòże, w przëtrôfkù negò sparłãczenia, dérowac kòl %s . "

#: ../DistUpgrade/DistUpgradeView.py:253 ../DistUpgrade/DistUpgrade.ui.h:16
msgid "Preparing to upgrade"
msgstr "Przërechtowanié zaktualnienia"

#: ../DistUpgrade/DistUpgradeView.py:254
msgid "Getting new software channels"
msgstr "Zladënk nowich kanalów softwôrë"

#: ../DistUpgrade/DistUpgradeView.py:255 ../DistUpgrade/DistUpgrade.ui.h:14
msgid "Getting new packages"
msgstr "Zladënk nowich paczétów"

#: ../DistUpgrade/DistUpgradeView.py:256 ../DistUpgrade/DistUpgrade.ui.h:15
msgid "Installing the upgrades"
msgstr "Instalacëjô zaktualnieniô"

#: ../DistUpgrade/DistUpgradeView.py:257 ../DistUpgrade/DistUpgrade.ui.h:10
msgid "Cleaning up"
msgstr "Czëszczenié"

#: ../DistUpgrade/DistUpgradeView.py:341
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
msgstr[1] ""

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:350
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d paczét òstanié rëmniãty."
msgstr[1] "%d paczétë òstaną rëmniãte."
msgstr[2] "%d paczétów òstaną rëmniãtëch."

#: ../DistUpgrade/DistUpgradeView.py:355
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d nowi paczét òstanie winstalowóny."
msgstr[1] "%d nowé paczétë òstaną winstalowóné."
msgstr[2] "%d nowëch paczétów òstanie winstalowónëch."

#: ../DistUpgrade/DistUpgradeView.py:361
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d paczét òstanié zaktualiniony."
msgstr[1] "%d paczétë òstaną zaktualnione."
msgstr[2] "%d paczétów òstanie zaktualnionëch."

#: ../DistUpgrade/DistUpgradeView.py:366
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Mùszebny zladënk w grëpie %s. "

#: ../DistUpgrade/DistUpgradeView.py:370
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be cancelled."
msgstr ""
"Zladënk ë winstalowanié aktualizacëji mòże dérowac czile gòdzënów. Czéj "
"zladënk bãdze skùńczony, procesu nie bãdze szło ju òprzestac."

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:376 ../UpdateManager/UpdateManager.py:557
msgid "Your system is up-to-date"
msgstr "Twojô systema je fùl zaktualnionô"

#: ../DistUpgrade/DistUpgradeView.py:377
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"Felëjë przistãpnëch aktualizacëjów. Aktualizacëjô òstanié òprzestónô."

#: ../DistUpgrade/DistUpgradeView.py:390
msgid "Reboot required"
msgstr "Wëmôgóne je zrëszenié kòmpùtra znowa"

#: ../DistUpgrade/DistUpgradeView.py:391
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"Aktualizacëjô òsta zakùńczonô ë nót je zrëszëc kòmpùtr znowa. Zrobic to terô?"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid "Could not run the upgrade tool"
msgstr "Zrëszenié nôrzãdza aktualizacëji nie darzëło sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:205
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:205
msgid "Upgrade tool signature"
msgstr "Pòdpisënk nôrzãdza aktualizacëji"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:208
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:208
msgid "Upgrade tool"
msgstr "Nôrzãdze aktualizacëji"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:237
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:237
msgid "Failed to fetch"
msgstr "Zladënk nie darzëł sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:238
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""
"Zladënk aktualizacëji nie darzëł sã. Mòże to òznôczac problemë z sécą. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:242
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:242
msgid "Failed to extract"
msgstr "Rozpakòwëwanié nie darzëło sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:243
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Rozpakòwëwanié aktualizacëji nie darzëło sã. Mòże je to problem z sécą abò "
"serwerã. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:248
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:248
msgid "Verification failed"
msgstr "Werifikacëjô nie darzëła sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:249
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Werifikacëjô aktualizacëji nie darzëła sã. Mòże je to problem z sécą abò "
"serwerã. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:254
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:254
msgid "Authentication failed"
msgstr "Ùdowierzanié nie darzëło sã"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:255
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Ùdowierzanié aktualizacëji nie darzëło sã. Mòże je to problem z sécą abò "
"serwerã. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
#: ../DistUpgrade/DistUpgradeFetcherCore.py:275
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:269
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:275
msgid "Can not run the upgrade"
msgstr "Ni mòże nacząc aktualizacëji"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:270
msgid ""
"This usually is caused by a system were /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:276
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:276
#, python-format
msgid "The error message is '%s'."
msgstr "Zamkłosc wiadła felë: \\\"%s\\\""

#: ../DistUpgrade/DistUpgradeViewText.py:89
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:113
msgid "Aborting"
msgstr "Òprzestóń"

#: ../DistUpgrade/DistUpgradeViewText.py:118
msgid "Demoted:\n"
msgstr "Zdegradowóné:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:151
#: ../DistUpgrade/DistUpgradeViewText.py:189
#: ../DistUpgrade/DistUpgradeViewText.py:196
msgid "Continue [yN] "
msgstr "Biéj dali [jN] "

#: ../DistUpgrade/DistUpgradeViewText.py:151
#: ../DistUpgrade/DistUpgradeViewText.py:189
msgid "Details [d]"
msgstr "Detale [d]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:155
#: ../DistUpgrade/DistUpgradeViewText.py:199
msgid "y"
msgstr "j"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:158
#: ../DistUpgrade/DistUpgradeViewText.py:206
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:161
msgid "d"
msgstr "d"

#: ../DistUpgrade/DistUpgradeViewText.py:166
#, python-format
msgid "No longer supported: %s\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:171
#, python-format
msgid "Remove: %s\n"
msgstr "Rëmôj: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:181
#, python-format
msgid "Install: %s\n"
msgstr "Instalëjë %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:186
#, python-format
msgid "Upgrade: %s\n"
msgstr "Aktualizëjë %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:203
msgid "Continue [Yn] "
msgstr "Jisc dali [Jn] "

#: ../DistUpgrade/DistUpgradeViewText.py:224
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Abë skùńczëc aktualizacëjã je nót zrëszëc kòmpùtr znowa.\n"
"Pò wëbierkù \"J\" kòmpùtr bãdze zrëszony znowa."

#: ../DistUpgrade/DistUpgrade.ui.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.ui.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>Òprzestac aktualizacëjã?</big></b>\n"
"\n"
"Systema mòże stac sã nieprzëdatnô do brëkùnkù jeżlë òprzestóniesz "
"aktualizacëjã. Zamòdlëwô sã jisc dali z aktualizacëją."

#: ../DistUpgrade/DistUpgrade.ui.h:5
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>Dlô zakùńczeniô aktualizacëji zrëszë kòmpùtr znbowa</big></b>\n"
"\n"
"Proszã zapisaćc swòją robòtã, niglë póńdzesz dali"

#: ../DistUpgrade/DistUpgrade.ui.h:8
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Zacząc zaktualnienié?</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:9
msgid "<b><big>Upgrading Ubuntu to version 10.10</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:12
msgid "Difference between the files"
msgstr "Zjinaczi midze lopkama"

#: ../DistUpgrade/DistUpgrade.ui.h:13
msgid "Distribution Upgrade"
msgstr "Aktualizacëjô distribùcëji"

#: ../DistUpgrade/DistUpgrade.ui.h:17
msgid "Restarting the computer"
msgstr "Zrëszanié kòmpùtra znowa"

#: ../DistUpgrade/DistUpgrade.ui.h:18
msgid "Setting new software channels"
msgstr "Nastôwë nowich kanalów softwôrë"

#: ../DistUpgrade/DistUpgrade.ui.h:19
msgid "Terminal"
msgstr "Terminal"

#: ../DistUpgrade/DistUpgrade.ui.h:20
msgid "_Cancel Upgrade"
msgstr "Ò_przestóń zaktualnienié"

#: ../DistUpgrade/DistUpgrade.ui.h:21
msgid "_Continue"
msgstr "_Biéj dali"

#: ../DistUpgrade/DistUpgrade.ui.h:23
msgid "_Replace"
msgstr "_Zastãpi"

#: ../DistUpgrade/DistUpgrade.ui.h:24
msgid "_Report Bug"
msgstr "Zgłoszë _felã"

#: ../DistUpgrade/DistUpgrade.ui.h:26
msgid "_Resume Upgrade"
msgstr "_Znowi zaktualnienié"

#: ../DistUpgrade/DistUpgrade.ui.h:27
msgid "_Start Upgrade"
msgstr "_Startëjë zaktualnienié"

#: ../UpdateManager/backend/InstallBackendSynaptic.py:54
msgid "Please wait, this can take some time."
msgstr "Proszã żdac, to mòże kąsk dérowac."

#: ../UpdateManager/backend/InstallBackendSynaptic.py:56
msgid "Update is complete"
msgstr "Zaktualnienié zakùńczoné."

#: ../UpdateManager/DistUpgradeFetcher.py:85
#: ../UpdateManager/DistUpgradeFetcherKDE.py:103
msgid "Could not find the release notes"
msgstr "NIé mòże nalezc wëdowiédzë ò wëdôwkù"

#: ../UpdateManager/DistUpgradeFetcher.py:86
#: ../UpdateManager/DistUpgradeFetcherKDE.py:104
msgid "The server may be overloaded. "
msgstr "Serwera mòże bëc przeladowóny "

#: ../UpdateManager/DistUpgradeFetcher.py:96
#: ../UpdateManager/DistUpgradeFetcherKDE.py:108
msgid "Could not download the release notes"
msgstr "Zladënk wëdowiédzë ò wëdôwkò nie darzëł sã"

#: ../UpdateManager/DistUpgradeFetcher.py:97
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Please check your internet connection."
msgstr "Proszã sprôwdzëc sécowé nastôwë"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:62
#: ../UpdateManager/DistUpgradeFetcherKDE.py:85
msgid "Upgrade"
msgstr "Aktualizëjë"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:89
#: ../data/glade/UpdateManager.ui.h:13
#: ../data/glade/UpgradePromptDialog.ui.h:4
msgid "Release Notes"
msgstr "Wëdowiédzô ò wëdôwkù"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:128
#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
msgid "Downloading additional package files..."
msgstr "Zladënk dôdôwnych paczétów..."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Lopk %s z %s z chùtkòscą %sB/s"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
#, python-format
msgid "File %s of %s"
msgstr "Lopk %s z %s"

#: ../UpdateManager/ChangelogViewer.py:70
msgid "Open Link in Browser"
msgstr "Òtemkni lënk w przezérnikù"

#: ../UpdateManager/ChangelogViewer.py:72
msgid "Copy Link to Clipboard"
msgstr "Kòpérëjë lënk do tacnika"

#: ../UpdateManager/GtkProgress.py:161
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Ladowanié lopka %(current)li z %(total)li z chùtkòscą %(speed)s/s"

#: ../UpdateManager/GtkProgress.py:166
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Ladowanié lopka %(current)li z %(total)li"

#: ../UpdateManager/UpdateManager.py:326
#, python-format
msgid "Version %s: \n"
msgstr "Wersëjô %s: \n"

#: ../UpdateManager/UpdateManager.py:383
msgid "Downloading list of changes..."
msgstr "Zladënk lëstë zjinaków..."

#: ../UpdateManager/UpdateManager.py:423
msgid "_Uncheck All"
msgstr "_Òdznaczë wszëtczé"

#: ../UpdateManager/UpdateManager.py:429
msgid "_Check All"
msgstr "_Naznaczë wszëtczé"

#: ../UpdateManager/UpdateManager.py:476
#, python-format
msgid "%(count)s update has been selected."
msgid_plural "%(count)s updates have been selected."
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:480
#, python-format
msgid "%s will be downloaded."
msgstr ""

#: ../UpdateManager/UpdateManager.py:491
msgid "The update has already been downloaded, but not installed"
msgid_plural "The updates have already been downloaded, but not installed"
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:495
msgid "There are no updates to install"
msgstr ""

#. TRANSLATORS: this allows to switch the order of the count of
#. updates and the download size string (if needed)
#: ../UpdateManager/UpdateManager.py:500
#, python-format
msgid "%(count_str)s %(download_str)s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:507
msgid "Unknown download size."
msgstr ""

#: ../UpdateManager/UpdateManager.py:518
msgid ""
"It is unknown when the package information was updated last. Please try "
"clicking on the 'Check' button to update the information."
msgstr ""
"Je nót datuma slédny aktualizacëji wëdowiédzë ò paczétach.Proszã zaktualnic "
"wëdowiédzã klëkając na knąpã \"Sprôwdzë\"."

#: ../UpdateManager/UpdateManager.py:527
#, python-format
msgid "The package information was last updated %(days_ago)s day ago."
msgid_plural ""
"The package information was last updated %(days_ago)s days ago."
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:531
#, python-format
msgid "The package information was last updated %(hours_ago)s hour ago."
msgid_plural ""
"The package information was last updated %(hours_ago)s hours ago."
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:535
msgid "The package information was last updated less than one hour ago."
msgstr "Wëdowiédze ò paczétach zaktualnionô mni jakno %s gòdzënã nazôd."

#: ../UpdateManager/UpdateManager.py:555 ../data/glade/UpdateManager.ui.h:23
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""

#: ../UpdateManager/UpdateManager.py:575
msgid "Welcome to Ubuntu"
msgstr "Witómë w Ubuntu"

#: ../UpdateManager/UpdateManager.py:576
msgid ""
"These software updates have been issued since Ubuntu was released. If you "
"don't want to install them now, choose \"Update Manager\" from the "
"Administration Menu later."
msgstr ""

#: ../UpdateManager/UpdateManager.py:579
msgid "Software updates are available for this computer"
msgstr "Przëstãpné są zaktualnienia softwôrë"

#: ../UpdateManager/UpdateManager.py:580
msgid ""
"If you don't want to install them now, choose \"Update Manager\" from the "
"Administration menu later."
msgstr ""

#: ../UpdateManager/UpdateManager.py:629
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""

#: ../UpdateManager/UpdateManager.py:652
msgid ""
"The computer needs to restart to finish installing updates. Please save your "
"work before continuing."
msgstr ""
"Kòmpùtr mùszi bëc zrëszony znowa, abë skùńczëc instalacëjã aktualizacëji. "
"Proszã zapisac biéżną robòtã zaczëm póńdzesz dali."

#: ../UpdateManager/UpdateManager.py:704
#: ../UpdateManagerHildon/UpdateManagerHildon.py:114
msgid "Reading package information"
msgstr "Czëtanié wëdowiédzë ò paczétach"

#: ../UpdateManager/UpdateManager.py:719
msgid "Connecting..."
msgstr ""

#: ../UpdateManager/UpdateManager.py:729
msgid "You may not be able to check for updates or download new updates."
msgstr ""

#: ../UpdateManager/UpdateManager.py:846
msgid "Could not initialize the package information"
msgstr "Nié mòże zainicjowac wëdowiédzë ò paczétach"

#: ../UpdateManager/UpdateManager.py:847
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:871
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""

#: ../UpdateManager/UpdateManager.py:896
msgid " (New install)"
msgstr " (Nowô instalacëjô)"

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:903
#, python-format
msgid "(Size: %s)"
msgstr "(Miara: %s)"

#: ../UpdateManager/UpdateManager.py:905
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr "Z wersëji %(old_version)s do %(new_version)s"

#: ../UpdateManager/UpdateManager.py:909
#, python-format
msgid "Version %s"
msgstr "Wersëjô %s"

#: ../UpdateManager/UpdateManager.py:924
msgid "Your Ubuntu release is not supported anymore"
msgstr "Na wersëjô nie je ju wspierónô"

#: ../UpdateManager/UpdateManager.py:925
msgid ""
"You will not get any further security fixes or critical updates. Please "
"Upgrade to a later version of Ubuntu Linux."
msgstr ""
"Dôlszé pòprôwczi bezpiekù nie bãdą ju dôwóné. Proszã zaktualnic systemã do "
"nônowszi wersëji Ubuntu."

#: ../UpdateManager/UpdateManager.py:932
msgid "Upgrade information"
msgstr "Wëdowiedze ò aktualizacëji"

#: ../UpdateManager/UpdateManager.py:954 ../do-release-upgrade:84
msgid "Release upgrade not possible right now"
msgstr ""

#: ../UpdateManager/UpdateManager.py:955 ../do-release-upgrade:85
#, c-format, python-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""

#: ../UpdateManager/UpdateManager.py:957 ../check-new-release-gtk:85
msgid "Downloading the release upgrade tool"
msgstr "Zladënk nôrzãdza aktualizacëji wëdôwkù"

#: ../UpdateManager/UpdateManager.py:964
#, python-format
msgid "<b>New Ubuntu release '%s' is available</b>"
msgstr "<b>Przëstãpny je nowi wëdôwk Ubuntu: \"%s\"</b>"

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:1003
msgid "Software index is broken"
msgstr "Spisënk softwôrë mô felã"

#: ../UpdateManager/UpdateManager.py:1004
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""
"Instalacëjô ë rëmanié softwôrë nie je mòżlëwé. Proszã do tegò brëkòwac "
"menadżera paczétów  \"Synaptic\" abò wpisac w terminalu pòlét  \"sudo apt-"
"get install -f\" bë naprawic nen problem."

#: ../UpdateManagerHildon/UpdateManagerHildon.py:136
msgid "Downloading Package Information"
msgstr "Zladënk wëdowiédzë ò paczétach"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:137
msgid ""
"The repositories are being checked for new, removed, or updated software "
"packages"
msgstr "Sprôwdzanié nowich, rëmniãtich abò zaktualnionych paczétów softwôrë"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:145
msgid "Downloading Package Updates"
msgstr "Zladënk aktualizacëji paczétów"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:146
msgid ""
"The selected package updates are being downloaded and installed on the system"
msgstr "Wëbróné aktualizacëje paczétów są ladowóné ë instalowóné w systemie"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:152
msgid "run_synaptic called with unknown action"
msgstr "wëwòłóné run_synaptic z nieznónym dzejaniém"

#: ../UpdateManagerText/UpdateManagerText.py:26
msgid "Cancel"
msgstr "Òprzestóń"

#: ../UpdateManagerText/UpdateManagerText.py:27
msgid "Install"
msgstr "Instalëjë"

#: ../UpdateManagerText/UpdateManagerText.py:45
msgid "Building Updates List"
msgstr "Ùsôdzanié lëstë paczétów do zaktualnieniô"

#: ../UpdateManagerText/UpdateManagerText.py:48
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:117
msgid "Downloading changelog"
msgstr "Zladënk dniownika zjinaków"

#: ../UpdateManager/Core/MyCache.py:128
#, python-format
msgid "Other updates (%s)"
msgstr "Jinszé zaktualnienia (%s)"

#: ../UpdateManager/Core/MyCache.py:285
#, python-format
msgid ""
"Changes for the versions:\n"
"%s\n"
"%s\n"
"\n"
msgstr ""
"Zjinaczi w wersëjach:\n"
"%s\n"
"%s\n"
"\n"

#: ../UpdateManager/Core/MyCache.py:298
msgid "This change is not coming from a source that supports changelogs."
msgstr "Na zjinaka nie pòchôdô ze zdroju wspierającegò dniowniczi zjinaków."

#: ../UpdateManager/Core/MyCache.py:304 ../UpdateManager/Core/MyCache.py:324
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""
"Nie dało sã zladowac lëstë zmianów. \n"
"Proszã sprôwdzëc swòjé internetowé sparłãczenié."

#: ../UpdateManager/Core/MyCache.py:313
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"Dniownik zjinaków je nieprzëstãpny.\n"
"\n"
"Proszã brëkòwac http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"nigle zmianë bãdą ùprzëstãpnioné abò spróbòwac znowa."

#: ../UpdateManager/Core/MyCache.py:318
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"Lësta zmian nie je jesz przëstãpnô.\n"
"\n"
"Proszã brëkòwac http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"do czasu, jak zmianë bãdą ju przëstãpné, abò spróbòwac pòzdze."

#: ../UpdateManager/Core/UpdateList.py:52
msgid "Failed to detect distribution"
msgstr "Nie dało sã wëkrëc distribùcëji"

#: ../UpdateManager/Core/UpdateList.py:53
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr "Fela \\\"%s\\\" przë sprôwdzaniu brëkòwóny systemë."

#: ../UpdateManager/Core/UpdateList.py:64
msgid "Important security updates"
msgstr "Wôżné zaktualnienia bezpiekù"

#: ../UpdateManager/Core/UpdateList.py:65
msgid "Recommended updates"
msgstr "Zamòdlëwóné zaktualnienia"

#: ../UpdateManager/Core/UpdateList.py:66
msgid "Proposed updates"
msgstr "Bédowóné zaktualnienia"

#: ../UpdateManager/Core/UpdateList.py:67
msgid "Backports"
msgstr "Backpòrtë"

#: ../UpdateManager/Core/UpdateList.py:68
msgid "Distribution updates"
msgstr "Zaktualnienia distribùcëji"

#: ../UpdateManager/Core/UpdateList.py:73
msgid "Other updates"
msgstr "Jinszé zaktualnienia"

#: ../UpdateManager/Core/UpdateList.py:82
msgid "Previous selected"
msgstr "Rëchli wëbróné"

#: ../data/glade/UpdateManager.ui.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""
"<b><big>Nót je sprôwdzëc sómemù przëstãpnosc aktualizacëji</b></big>\n"
"\n"
"Aùtomatné aktualizacëje są wëłączoné. Mòże nastôwic no dzejanié w  "
"<i>Zdrojach softwôrë</i> w załóżce <i>Aktualizacëje</i>."

#: ../data/glade/UpdateManager.ui.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr "<big><b>Nie wszëtczé aktualizacëje mògą bëc winstalowóné</b></big>"

#: ../data/glade/UpdateManager.ui.h:5
msgid "<big><b>Running on battery</b></big>"
msgstr "<big><b>Robòta na baterëji</b></big>"

#: ../data/glade/UpdateManager.ui.h:6
msgid "<big><b>Starting Update Manager</b></big>"
msgstr "<big><b>Zrëszanié menadżera aktualizacëji</b></big>"

#: ../data/glade/UpdateManager.ui.h:7
msgid "Changes"
msgstr "Zjinaczi"

#: ../data/glade/UpdateManager.ui.h:8
msgid "Chec_k"
msgstr "Sp_rôwdzë"

#: ../data/glade/UpdateManager.ui.h:9
msgid "Co_ntinue"
msgstr "_Biéj dali"

#: ../data/glade/UpdateManager.ui.h:10
msgid "Description"
msgstr "Òpisënk"

#: ../data/glade/UpdateManager.ui.h:11
msgid "Description of update"
msgstr "Òpisënk zaktualnieniów"

#: ../data/glade/UpdateManager.ui.h:12
msgid ""
"It&#x2019;s safer to connect the computer to AC power before updating."
msgstr ""

#: ../data/glade/UpdateManager.ui.h:14
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:21
msgid "Settings..."
msgstr "Nastôwë..."

#: ../data/glade/UpdateManager.ui.h:22
#: ../data/glade/UpgradePromptDialog.ui.h:5
msgid "Show progress of individual files"
msgstr "Pòkrok zladënkù indiwidualnych lopków"

#: ../data/glade/UpdateManager.ui.h:24
msgid "Starting Update Manager"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:25
msgid "U_pgrade"
msgstr "_Aktualizëjë"

#: ../data/glade/UpdateManager.ui.h:26 ../data/update-manager.desktop.in.h:3
#: ../data/update-manager-hildon.desktop.in.h:3
msgid "Update Manager"
msgstr "Menedżera aktualizacëji"

#: ../data/glade/UpdateManager.ui.h:27
msgid "Your system is running on battery. Are you sure you want to continue?"
msgstr "Kòmpùtr robi z baterëji. Na gwës jisc dali?"

#: ../data/glade/UpdateManager.ui.h:28
msgid "_Hide this information in the future"
msgstr "_Zatacë tã wëdowiédzã w przińdnosce"

#: ../data/glade/UpdateManager.ui.h:29
msgid "_Install Updates"
msgstr "_Winstalëjë zaktualnienia"

#: ../data/glade/UpdateManager.ui.h:30
msgid "_Partial Upgrade"
msgstr "_Dzélowé zaktualnienié"

#: ../data/glade/UpdateManager.ui.h:32
msgid "_Upgrade"
msgstr "_Aktualizëjë"

#: ../data/glade/UpdateManager.ui.h:33
msgid "updates"
msgstr "zaktualnienia"

#: ../data/glade/UpgradePromptDialog.ui.h:1
msgid ""
"<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>Je przëstãpnô nowô wersëjô Ubuntu. Chcesz zaktualnic?</b>"

#: ../data/glade/UpgradePromptDialog.ui.h:2
msgid "Ask Me Later"
msgstr "Pëtôj mie pózdni"

#: ../data/glade/UpgradePromptDialog.ui.h:3
msgid "Don't Upgrade"
msgstr "Nie aktualizëjë"

#: ../data/glade/UpgradePromptDialog.ui.h:6
msgid "Yes, Upgrade Now"
msgstr "Jo, aktualizëjë terô"

#: ../data/glade/UpgradePromptDialog.ui.h:7
msgid ""
"You can upgrade at a later time by opening Update Manager and click on "
"\"Upgrade\"."
msgstr ""

#: ../data/glade/UpgradePromptDialog.ui.h:8
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "Môsz pòcësniãtą aktualizacëjã do nowi wersëji Ubuntu"

#: ../data/update-manager.desktop.in.h:1
#: ../data/update-manager-hildon.desktop.in.h:1
msgid "Show and install available updates"
msgstr "Wëskrzëni ë winstalëjë przëstãpné aktualizacëje"

#: ../data/update-manager.desktop.in.h:2
#: ../data/update-manager-hildon.desktop.in.h:2
msgid "Software Updates"
msgstr "Zaktualnienia softwôrë"

#: ../data/update-manager.schemas.in.h:1
msgid "*deprecated* Check for new distribution releases"
msgstr "*niezamòdlëwóné* Sprôwdzôj nowé wëdôwczi distribùcëji"

#: ../data/update-manager.schemas.in.h:2
msgid "Auto close the install window after successful install"
msgstr "Aùtomatné zamkniãcé òkna instalacëji pò ji ùdałim skùńczeniu."

#: ../data/update-manager.schemas.in.h:3
msgid "First run welcome message"
msgstr "Witającé wiadło przë pierszim zrëszeniu"

#: ../data/update-manager.schemas.in.h:4
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""
"Jeżlë aùtomatné sprôwdzanié przëstãpnotë je wëłączoné, nót je zladowac znowa "
"lëstã kanałów rãczno. Na òptacëjô zezwôlô na zatacenié przëbôczaniô ò tim."

#: ../data/update-manager.schemas.in.h:5
msgid "If this key is set a first run welcome message will be presented."
msgstr ""
"Jeżlë na òptacëjô  je nastôwionô, pierszé witającé wiadło bãdze wëskrzënioné."

#: ../data/update-manager.schemas.in.h:6
msgid ""
"If this key is set the install window will be automatically closed on "
"successful installation."
msgstr ""
"Jeżlë na òptacëjô  je nastôwionô, òkno instalacëji bãdze aùtomatno zamkniãté "
"pò ji ùdałim skùńczeniu."

#: ../data/update-manager.schemas.in.h:7
msgid ""
"If this key is set the main update list window will show version information "
"(from version to version)."
msgstr ""
"Jeżlë na òptacëjô  je nastôwionô, przédné òkno z lëstą zaktualnieniów bãdze "
"wëskrzëniac wëdowiédzã ò wersëjach (zdrojach ë docélowô)."

#: ../data/update-manager.schemas.in.h:8
msgid ""
"If this key is set, the main update list window will show the package "
"summary before the package name."
msgstr ""

#: ../data/update-manager.schemas.in.h:9
msgid "Remind to reload the channel list"
msgstr "Przebôczë ò zladënkù znowa lëstë kanałów"

#: ../data/update-manager.schemas.in.h:10
msgid "Show details of an update"
msgstr "Wëskrzëni detale aktualizacëjów"

#: ../data/update-manager.schemas.in.h:11
msgid "Show package summary before package name in update list"
msgstr ""

#: ../data/update-manager.schemas.in.h:12
msgid "Show version in update list"
msgstr "Wëskrzëni wersëje w lësce przëstãpnych aktualizacëjów"

#: ../data/update-manager.schemas.in.h:13
msgid "Stores the size of the update-manager dialog"
msgstr "Pamiãtô miarã òkna Menadżera aktualizacëji"

#: ../data/update-manager.schemas.in.h:14
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr ""
"Pamiãtô pòłóżenié rozwijónegò rumù zamëkającegò lëstã zjinaków ë òpisënk"

#: ../data/update-manager.schemas.in.h:15
msgid "The window size"
msgstr "Miara òkna"

#: ../data/update-manager.schemas.in.h:16
msgid ""
"This key is deprecated in favor of the file /etc/update-manager/release-"
"upgrades Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""

#: ../data/update-manager.schemas.in.h:17
msgid ""
"This will permanently hide the new release prompt from check-new-release-"
"gtk. Note that the small button in the main update-manager UI will still be "
"there."
msgstr ""

#: ../data/update-manager.schemas.in.h:18
msgid "make check-new-release-gtk ignore a given new release"
msgstr ""

#: ../update-manager:53 ../do-release-upgrade:33
msgid "Show version and exit"
msgstr "Wëskrzënianié wersëji ë wińdzënk"

#: ../update-manager:56
msgid "Directory that contains the data files"
msgstr "Katalog zamëkający lopczi pòdôwków"

#: ../update-manager:59
msgid "Check if a new Ubuntu release is available"
msgstr "Sprôwdzô, czë przëstãpny je nowi wëdôwk Ubuntu"

#: ../update-manager:62 ../do-release-upgrade:36 ../check-new-release-gtk:136
msgid "Check if upgrading to the latest devel release is possible"
msgstr "Sprôwdzë mòżnotã zaktualnieniô do nônowszi testowi wersëji"

#: ../update-manager:66
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""
"Aktualizacëjô z brëkùnkã nônowszi wersëji zamòdlëwóny przez aktualizownika "
"wëdôwków"

#: ../update-manager:73
msgid "Do not focus on map when starting"
msgstr "Nie kòncentrëje sã na karce przë zrëszaniu"

#: ../update-manager:76
msgid "Try to run a dist-upgrade"
msgstr "Spróbùjë zrëszëc zaktualnienié distribùcëji"

#: ../update-manager:80 ../do-release-upgrade:52
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "Testowô aktualizacëjô z nadkłôdką sandbox aufs"

#: ../update-manager:100
msgid "Running partial upgrade"
msgstr "Przerôbianié dzélowégò zaktualnienia"

#: ../do-release-upgrade:40 ../check-new-release-gtk:140
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Proszã spróbòwac zaktualnic do nônowszi wersëji brëkùjąc zaktualniający "
"programë z $distro-proposed"

#: ../do-release-upgrade:44
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Zrëszë w specjalnym tribie aktualizacëji.\n"
"Terô wspieróné są tribë \"desktop\" dlô kòmpùtrów ë \"server\" dlô "
"serwerowich systemów."

#: ../do-release-upgrade:50
msgid "Run the specified frontend"
msgstr "Zrëszë òpisóną nadkłôdkã"

#: ../do-release-upgrade:55
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""

#: ../do-release-upgrade:69
msgid "Checking for a new ubuntu release"
msgstr "Sprôwdzë przëstãpnosc nowegò wëdôwka Ubuntu"

#: ../do-release-upgrade:79
msgid "No new release found"
msgstr "Felënk nowegò wëdôwka"

#: ../do-release-upgrade:91
#, c-format
msgid "New release '%s' available."
msgstr "Nowi wëdôwk '%s' je przëstãpny"

#: ../do-release-upgrade:92
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "Zrëszë 'do-release-upgrade', abë zaktualnic."

#: ../check-new-release-gtk:65
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Przëstãpnô je aktualizacëjô do Ubuntu %(version)s"

#: ../check-new-release-gtk:101
#, c-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Pòcësniãto aktualizacëjã do Ubuntu %s"

#: ../Janitor/computerjanitor/exc.py:30
#, python-format
msgid "Unimplemented method: %s"
msgstr ""

#: ../Janitor/computerjanitor/file_cruft.py:46
msgid "A file on disk"
msgstr "Lopk na diskù"

#: ../Janitor/computerjanitor/package_cruft.py:45
msgid ".deb package"
msgstr "Paczét .deb"

#: ../Janitor/computerjanitor/missing_package_cruft.py:33
msgid "Install missing package."
msgstr "Instalacëjô felëjącegò paczétu."

#: ../Janitor/computerjanitor/missing_package_cruft.py:42
#, python-format
msgid "Package %s should be installed."
msgstr "Paczét %s mùszôłbë bëc winstalowóny."

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:36
#, python-format
msgid "%i obsolete entries in the status file"
msgstr "%i niepòtrzébnych wpisënków w lopkù stónu"

#: ../Janitor/plugins/dpkg_status_plugin.py:39
msgid "Obsolete entries in dpkg status"
msgstr "Niepòtrzébné wpisënczi stónu w dpkg"

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:42
msgid "Obsolete dpkg status entries"
msgstr "Niepòtrzébné wpisënczi stónu dpkg"

#: ../Janitor/plugins/kdelibs4to5_plugin.py:39
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""

#: ../Janitor/plugins/langpack_manual_plugin.py:34
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr "%s musi zostać oznaczony jako zainstalowany ręcznie."

#: ../Janitor/plugins/remove_lilo_plugin.py:28
msgid ""
"Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr ""

#~ msgid "Unknown download size"
#~ msgstr "Nieznónô miara lopków do zladënkù"

#, python-format
#~ msgid "<b>Downgrade %s</b>"
#~ msgstr "<b>Winstalëjë %s</b>"

#~ msgid "Support for some applications ended"
#~ msgstr "Wspiarce dlô niejednrch aplikacrjów skùńczëło sã"

#~ msgid ""
#~ "The upgrade is now aborted. Please check your Internet connection or "
#~ "installation media and try again. All files downloaded so far are kept."
#~ msgstr ""
#~ "Aktualizacëjô òprzestónô. Proszã òbôczëc stón internetowégò sparłãczenia abò "
#~ "instalacowégò medióm ë spróbòwac znowa. Wszëtczé do negò czasu zladowóné "
#~ "lopczi bãdą ùtrzëmóné."

#, python-format
#~ msgid "The package information was last updated %s day ago."
#~ msgid_plural "The package information was last updated %s days ago."
#~ msgstr[0] "Wëdowiédze ò paczétach zaktualnionô %s dzéń nazôd."
#~ msgstr[1] "Wëdowiédze ò paczétach zaktualnionô %s dni nazôd."
#~ msgstr[2] "Wëdowiédze ò paczétach zaktualnionô %s dniów nazôd."

#, python-format
#~ msgid "The package information was last updated %s hour ago."
#~ msgid_plural "The package information was last updated %s hours ago."
#~ msgstr[0] "Wëdowiédze ò paczétach zaktualnionô %s gòdzënã nazôd."
#~ msgstr[1] "Wëdowiédze ò paczétach zaktualnionô %s gòdzënë nazôd."
#~ msgstr[2] "Wëdowiédze ò paczétach zaktualnionô %s gòdzënów nazôd."

#~ msgid ""
#~ "The upgrade is now aborted. Please check your Internet connection or "
#~ "installation media and try again. "
#~ msgstr ""
#~ "Aktualizacëjô òprzestónô. Proszã sprôwdzëc stón internetowégò sparłãczenia "
#~ "abò instalacjowégò medium ë spróbòwac znowa. "
