# translation of update-manager to Spanish
# This file is distributed under the same license as the update-manager package.
#  Copyright (c) 2004 Canonical
#                2004 Michiel Sikkes
# Jorge Bernal <koke@amedias.org>, 2005.
# Jorge Bernal <koke@sindominio.net>, 2005.
#
msgid ""
msgstr ""
"Project-Id-Version: es\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2010-03-08 23:43+0000\n"
"PO-Revision-Date: 2010-03-09 05:48+0000\n"
"Last-Translator: Ricardo Pérez López <ricpelo@gmail.com>\n"
"Language-Team: Spanish <traductores@gnome.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2010-03-09 08:16+0000\n"
"X-Generator: Launchpad (build Unknown)\n"

#. TRANSLATORS: download size is 0
#: ../DistUpgrade/utils.py:305 ../UpdateManager/Core/utils.py:305
msgid "0 KB"
msgstr "0 KB"

#. TRANSLATORS: download size of very small updates
#: ../DistUpgrade/utils.py:308 ../UpdateManager/Core/utils.py:308
msgid "1 KB"
msgstr "1 KB"

#. TRANSLATORS: download size of small updates, e.g. "250 KB"
#: ../DistUpgrade/utils.py:311 ../UpdateManager/Core/utils.py:311
#, python-format
msgid "%.0f KB"
msgstr "%.0f KB"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:314 ../UpdateManager/Core/utils.py:314
#, python-format
msgid "%.1f MB"
msgstr "%.1f MB"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:208 ../DistUpgrade/distro.py:423
#, python-format
msgid "Server for %s"
msgstr "Servidor para %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:226 ../DistUpgrade/distro.py:232
#: ../DistUpgrade/distro.py:248
msgid "Main server"
msgstr "Servidor principal"

#: ../DistUpgrade/distro.py:252
msgid "Custom servers"
msgstr "Servidores personalizados"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:131
msgid "Could not calculate sources.list entry"
msgstr "No se puede calcular la entrada sources.list"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:234
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"Imposible localizar ningún paquete, quizás no es un disco de Ubuntu o no es "
"la arquitectura correcta."

#: ../DistUpgrade/DistUpgradeAptCdrom.py:277
msgid "Failed to add the CD"
msgstr "Error al añadir el CD"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:278
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"Ha habido un error al añadir el CD; se ha interrumpido la actualización. Por "
"favor, informe de esto como un fallo si este es un CD válido de Ubuntu.\n"
"\n"
"El mensaje de error fue:\n"
"«%s»"

#: ../DistUpgrade/DistUpgradeCache.py:130
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Eliminar paquete en mal estado"
msgstr[1] "Eliminar paquetes en mal estado"

#: ../DistUpgrade/DistUpgradeCache.py:133
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"El paquete «%s» está en un estado inconsistente y debe reinstalarse, pero no "
"se encuentra en ningún repositorio. ¿Desea desinstalar este paquete ahora "
"para continuar?"
msgstr[1] ""
"Los paquetes «%s» están en un estado inconsistente y deben reinstalarse, "
"pero no se encuentran en ningún repositorio. ¿Desea desinstalar estos "
"paquetes ahora para continuar?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:231
msgid "The server may be overloaded"
msgstr "El servidor puede estar sobrecargado"

#: ../DistUpgrade/DistUpgradeCache.py:341
msgid "Broken packages"
msgstr "Paquetes rotos"

#: ../DistUpgrade/DistUpgradeCache.py:342
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"Su sistema contiene paquetes rotos que no pueden ser arreglados con este "
"software. Por favor, arréglelos primero usando Synaptic o apt-get antes de "
"continuar."

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:618
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"Ha ocurrido un error irresoluble mientras se calculaba la actualización:\n"
"%s\n"
"\n"
" Esto puede deberse a:\n"
" * Que se está actualizando a una versión de Ubuntu aún no publicada\n"
" * Que se está usando la actual versión aún no publicada de Ubuntu\n"
" * Paquetes de software no oficiales, no suministrados por Ubuntu\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:628
msgid "This is most likely a transient problem, please try again later."
msgstr ""
"Probablemente sea un problema transitorio, inténtelo de nuevo más tarde."

#: ../DistUpgrade/DistUpgradeCache.py:631
msgid ""
"If none of this applies, then please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"Si no se corresponde con ninguno, informe de este fallo sobre el paquete "
"«update-manager» e incluya en el informe los archivos situados en "
"/var/log/dis-upgrade/."

#: ../DistUpgrade/DistUpgradeCache.py:637
#: ../UpdateManager/UpdateManager.py:765
msgid "Could not calculate the upgrade"
msgstr "No se ha podido calcular la actualización"

#: ../DistUpgrade/DistUpgradeCache.py:687
msgid "Error authenticating some packages"
msgstr "Error al autenticar algunos paquetes"

#: ../DistUpgrade/DistUpgradeCache.py:688
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"No ha sido posible autenticar algunos paquetes. Esto puede ser debido a un "
"problema transitorio en la red. Pruebe de nuevo más tarde. Vea abajo una "
"lista de los paquetes no autenticados."

#: ../DistUpgrade/DistUpgradeCache.py:708
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"El paquete «%s» está marcado para desinstalarse pero está en la lista negra "
"de desinstalación."

#: ../DistUpgrade/DistUpgradeCache.py:712
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "El paquete esencial «%s» ha sido marcado para su desinstalación."

#: ../DistUpgrade/DistUpgradeCache.py:721
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "Intentando instalar la versión prohibida «%s»"

#: ../DistUpgrade/DistUpgradeCache.py:821
#, python-format
msgid "Can not mark '%s' for upgrade"
msgstr "No se ha podido marcar «%s» para actualización"

#: ../DistUpgrade/DistUpgradeCache.py:835
#, python-format
msgid "Can't install '%s'"
msgstr "No se ha podido instalar «%s»"

#: ../DistUpgrade/DistUpgradeCache.py:836
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""
"No ha sido posible instalar un paquete requerido. Por favor, informe de esto "
"como un fallo. "

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:845
msgid "Can't guess meta-package"
msgstr "No se ha podido determinar el metapaquete"

#: ../DistUpgrade/DistUpgradeCache.py:846
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"Su sistema no contiene el paquete ubuntu-desktop,  kubuntu-desktop, xubuntu-"
"desktop o edubuntu-desktop, y no ha sido posible detectar qué versión de "
"Ubuntu está ejecutando.\n"
" Por favor, instale uno de los paquetes anteriores usando Synaptic o apt-get "
"antes de proceder."

#: ../DistUpgrade/DistUpgradeController.py:86
msgid "Reading cache"
msgstr "Leyendo caché"

#: ../DistUpgrade/DistUpgradeController.py:186
msgid "Unable to get exclusive lock"
msgstr "No se ha podido obtener un bloqueo exclusivo"

#: ../DistUpgrade/DistUpgradeController.py:187
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Esto normalmente significa que ya se está ejecutando otra aplicación de "
"gestión de paquetes (como apt-get o aptitude). Por favor, cierre esa "
"aplicación primero."

#: ../DistUpgrade/DistUpgradeController.py:233
msgid "Upgrading over remote connection not supported"
msgstr "Actualizando sobre conexión remota no soportada"

#: ../DistUpgrade/DistUpgradeController.py:234
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"Está ejecutando la actualización sobre una conexión ssh remota con una "
"interfaz de usuario que no lo permite. Intente actualizar en modo texto con "
"«do-release-upgrade».\n"
"\n"
"La actualización se detendrá ahora. Intente sin ssh."

#: ../DistUpgrade/DistUpgradeController.py:248
msgid "Continue running under SSH?"
msgstr "¿Continuar la ejecución bajo SSH?"

#: ../DistUpgrade/DistUpgradeController.py:249
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Esta sesión parece estar ejecutándose bajo ssh. No es recomendable hacer una "
"actualización sobre ssh actualmente, porque en caso de fallo es muy difícil "
"de recuperar.\n"
"\n"
"Si continua, se iniciará un demonio ssh adicional en el puerto «%s».\n"
"¿Desea continuar?"

#: ../DistUpgrade/DistUpgradeController.py:264
msgid "Starting additional sshd"
msgstr "Iniciando sshd adicional"

#: ../DistUpgrade/DistUpgradeController.py:265
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Para facilitar la recuperación en caso de fallo, se iniciará un sshd "
"adicional en el puerto «%s». Si algo va mal con el ssh en ejecución, aún "
"podrá conectarse al adicional.\n"

#: ../DistUpgrade/DistUpgradeController.py:336
#: ../DistUpgrade/DistUpgradeController.py:381
msgid "Can not upgrade"
msgstr "No se puede actualizar"

#: ../DistUpgrade/DistUpgradeController.py:337
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "Esta herramienta no soporta actualizaciones de «%s» a «%s»."

#: ../DistUpgrade/DistUpgradeController.py:346
msgid "Sandbox setup failed"
msgstr "Falló la configuración de la caja de arena"

#: ../DistUpgrade/DistUpgradeController.py:347
msgid "It was not possible to create the sandbox environment."
msgstr "No ha sido posible crear un entorno de caja de arena."

#: ../DistUpgrade/DistUpgradeController.py:353
msgid "Sandbox mode"
msgstr "Modo caja de arena"

#: ../DistUpgrade/DistUpgradeController.py:354
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a systemdir from now until the next reboot are "
"permanent."
msgstr ""
"Esta actualización está ejecutándose en un modo caja de arena (test). Todos "
"los cambios se escriben en «%s» y se perderán en el próximo reinicio.\n"
"\n"
"*No* se escribirán cambios permanentes a una carpeta de sistema desde ahora "
"hasta el próximo reinicio."

#: ../DistUpgrade/DistUpgradeController.py:382
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"Su instalación de python está dañada. Por favor, repare el enlace simbólico "
"«/usr/bin/python»."

#: ../DistUpgrade/DistUpgradeController.py:408
msgid "Package 'debsig-verify' is installed"
msgstr "El paquete «debsig-verify» esta instalado"

#: ../DistUpgrade/DistUpgradeController.py:409
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""
"La actualización no puede continuar con ese paquete instalado.\n"
"Desinstálelo con synaptic o «apt-get remove debsig-verify» primero y luego "
"intente actualizar nuevamente."

#: ../DistUpgrade/DistUpgradeController.py:419
msgid "Include latest updates from the Internet?"
msgstr "¿Incluir las últimas actualizaciones desde Internet?"

#: ../DistUpgrade/DistUpgradeController.py:420
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"El sistema de actualización a una nueva versión puede usar Internet para "
"descargar automáticamente las actualizaciones más recientes e instalarlas "
"durante el proceso. Si dispone de una conexión a la red, esto es muy "
"recomendable.\n"
"\n"
"La actualización llevará más tiempo, pero una vez terminada, el sistema "
"estará completamente actualizado. Puede elegir no hacerlo, pero deberá "
"instalar las nuevas actualizaciones inmediatamente después de pasar a la "
"nueva versión.\n"
"Si responde «no» ahora, la red no se usará para nada."

#: ../DistUpgrade/DistUpgradeController.py:644
#, python-format
msgid "disabled on upgrade to %s"
msgstr "(desactivado en la actualización a %s)"

#: ../DistUpgrade/DistUpgradeController.py:671
msgid "No valid mirror found"
msgstr "No se ha encontrado un servidor espejo válido"

#: ../DistUpgrade/DistUpgradeController.py:672
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"Mientras se exploraba la información de su repositorio, no se encontró "
"ninguna entrada para la réplica de la actualización. Esto puede ocurrir si "
"corre una réplica interna o si la información de la réplica es antigua.\n"
"\n"
"¿Desea reescribir su archivo «sources.list» de todos modos? Si elije «Sí» se "
"actualizará todas las entradas «%s» a «%s».\n"
"Si selecciona «No» la actualización se cancelará."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:692
msgid "Generate default sources?"
msgstr "¿Generar orígenes predeterminados?"

#: ../DistUpgrade/DistUpgradeController.py:693
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"Después de explorar su «sources.list» no se encontraron entradas válidas "
"para «%s».\n"
"\n"
"¿Se deben añadir entradas predeterminadas para «%s»? Si selecciona «No», la "
"actualización se cancelará."

#: ../DistUpgrade/DistUpgradeController.py:728
msgid "Repository information invalid"
msgstr "Información de repositorio no válida"

#: ../DistUpgrade/DistUpgradeController.py:729
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""
"La actualización de la información del repositorio generó un archivo "
"incorrecto. Por favor, informe de esto como un error."

#: ../DistUpgrade/DistUpgradeController.py:735
msgid "Third party sources disabled"
msgstr "Desactivados los orígenes de terceros"

#: ../DistUpgrade/DistUpgradeController.py:736
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"Se han desactivado algunas entradas de otros proveedores en su "
"«sources.list». Puede volver a activarlas tras la actualización con la "
"herramienta «Orígenes del software», o con su gestor de paquetes."

#: ../DistUpgrade/DistUpgradeController.py:776
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Paquete en un estado inconsistente"
msgstr[1] "Paquetes en un estado inconsistente"

#: ../DistUpgrade/DistUpgradeController.py:779
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"El paquete «%s» está en un estado inconsistente y debe reinstalarse, pero no "
"se encuentra en ningún repositorio. Por favor, reinstale el paquete "
"manualmente o desinstálelo del sistema."
msgstr[1] ""
"Los paquetes «%s» están en un estado inconsistente y deben reinstalarse, "
"pero no se encuentran en ningún repositorio. Por favor, reinstale los "
"paquetes manualmente o desinstálelos del sistema."

#: ../DistUpgrade/DistUpgradeController.py:827
msgid "Error during update"
msgstr "Error durante la actualización"

#: ../DistUpgrade/DistUpgradeController.py:828
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"Ocurrió un problema durante la actualización. Normalmente es debido a algún "
"tipo de problema en la red, por lo que le recomendamos que compruebe su "
"conexión de red y vuelva a intentarlo."

#. print "on_button_install_clicked"
#: ../DistUpgrade/DistUpgradeController.py:837
#: ../UpdateManager/UpdateManager.py:572
msgid "Not enough free disk space"
msgstr "No hay espacio suficiente en el disco"

#: ../DistUpgrade/DistUpgradeController.py:838
#, python-format
msgid ""
"The upgrade is now aborted. The upgrade needs a total of %s free space on "
"disk '%s'. Please free at least an additional %s of disk space on '%s'. "
"Empty your trash and remove temporary packages of former installations using "
"'sudo apt-get clean'."
msgstr ""
"Se ha cancelado la actualización. Ésta necesita un total de %s de espacio "
"libre en el disco «%s». Por favor, libere como mínimo %s de espacio de disco "
"en «%s». Vacíe su papelera y desinstale los paquetes temporales de "
"instalaciones anteriores mediante «sudo apt-get clean»."

#: ../DistUpgrade/DistUpgradeController.py:873
msgid ""
"Canonical Ltd. no longer provides support for the following software "
"packages. You can still get support from the community."
msgstr ""
"Canonical Ltd. ya no proporciona soporte para los siguientes paquetes. Puede "
"conseguir soporte de la comunidad."

#: ../DistUpgrade/DistUpgradeController.py:880
msgid ""
"Canonical Ltd. no longer provides support for the following software "
"packages. You can still get support from the community.\n"
"\n"
"These packages will be suggested for removal at the end of the upgrade "
"because you have not enabled the community maintained software channel "
"(universe)."
msgstr ""
"Canonical Ltd. ya no proporciona soporte para los siguientes paquetes de "
"software. Puede seguir recibiendo soporte por parte de la comunidad.\n"
"\n"
"Se le sugerirá que desinstale estos paquetes al final de la actualización, "
"ya que no tiene activado el canal de software mantenido por la comunidad "
"(universe)."

#: ../DistUpgrade/DistUpgradeController.py:888
msgid "Support for some applications ended"
msgstr "Algunas aplicaciones han dejado de tener soporte"

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:891
#: ../DistUpgrade/DistUpgradeController.py:1586
msgid "Calculating the changes"
msgstr "Calculando los cambios"

#. ask the user if he wants to do the changes
#: ../DistUpgrade/DistUpgradeController.py:906
msgid "Do you want to start the upgrade?"
msgstr "¿Desea comenzar la actualización?"

#: ../DistUpgrade/DistUpgradeController.py:971
msgid "Upgrade canceled"
msgstr "Actualización cancelada"

#: ../DistUpgrade/DistUpgradeController.py:972
msgid ""
"The upgrade cancels now and the original system state is restored. You can "
"resume the upgrade at a later time."
msgstr ""
"La actualización se cancela ahora y se restaura el estado original del "
"sistema. Puede reanudar la actualización más tarde."

#: ../DistUpgrade/DistUpgradeController.py:977
#: ../DistUpgrade/DistUpgradeController.py:1076
msgid "Could not download the upgrades"
msgstr "No se han podido descargar las actualizaciones"

#: ../DistUpgrade/DistUpgradeController.py:978
msgid ""
"The upgrade is now aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far are kept."
msgstr ""
"Se ha cancelado la actualización. Compruebe su conexión a Internet o el "
"soporte de la instalación y vuelva a intentarlo. Se conservarán todos los "
"archivos descargados hasta ahora."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1031
#: ../DistUpgrade/DistUpgradeController.py:1064
#: ../DistUpgrade/DistUpgradeController.py:1166
msgid "Error during commit"
msgstr "Error durante la confirmación"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1033
#: ../DistUpgrade/DistUpgradeController.py:1066
#: ../DistUpgrade/DistUpgradeController.py:1205
msgid "Restoring original system state"
msgstr "Restaurando el estado original del sistema"

#: ../DistUpgrade/DistUpgradeController.py:1034
#: ../DistUpgrade/DistUpgradeController.py:1048
#: ../DistUpgrade/DistUpgradeController.py:1067
msgid "Could not install the upgrades"
msgstr "No se han podido instalar las actualizaciones"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1039
msgid ""
"The upgrade is now aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"Se ha cancelado la actualización. Su sistema puede haber quedado en un "
"estado no utilizable. A continuación se iniciará una recuperación (dpkg --"
"configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1044
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"Por favor, informe de este fallo sobre el paquete «update-manager» e incluya "
"en el informe los archivos situados en /var/log/dist-upgrade/.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1077
msgid ""
"The upgrade is now aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"Se ha cancelado la actualización. Por favor, compruebe su conexión a "
"Internet o su soporte de instalación y vuelva a intentarlo. "

#: ../DistUpgrade/DistUpgradeController.py:1154
msgid "Remove obsolete packages?"
msgstr "¿Desinstalar los paquetes obsoletos?"

#: ../DistUpgrade/DistUpgradeController.py:1155
#: ../DistUpgrade/DistUpgrade.ui.h:22
msgid "_Keep"
msgstr "_Conservar"

#: ../DistUpgrade/DistUpgradeController.py:1155
msgid "_Remove"
msgstr "_Eliminar"

#: ../DistUpgrade/DistUpgradeController.py:1167
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""
"Ha ocurrido algún problema durante el limpiado. Por favor, lea el mensaje "
"siguiente para más información. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1243
msgid "Required depends is not installed"
msgstr "La dependencia requerida no está instalada"

#: ../DistUpgrade/DistUpgradeController.py:1244
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "La dependencia requerida «%s» no está instalada. "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1489
#: ../DistUpgrade/DistUpgradeController.py:1556
msgid "Checking package manager"
msgstr "Comprobando el gestor de paquetes"

#: ../DistUpgrade/DistUpgradeController.py:1494
msgid "Preparing the upgrade failed"
msgstr "Falló la preparación de la actualización"

#: ../DistUpgrade/DistUpgradeController.py:1495
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bug report."
msgstr ""
"Ha ocurrido un problema durante la preparación del sistema para la "
"actualización. Por favor, informe de este fallo sobre el paquete «update-"
"manager» e incluya en el informe los archivos situados en /var/log/dist-"
"upgrade/."

#: ../DistUpgrade/DistUpgradeController.py:1511
msgid "Getting upgrade prerequisites failed"
msgstr ""
"Ha fallado la obtención de los requisitos previos de la actualización"

#: ../DistUpgrade/DistUpgradeController.py:1512
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bug report."
msgstr ""
"El sistema no cumple con los requisitos necesarios para la actualización. Se "
"cancelará ésta y se procederá a restaurar el estado original del sistema.\n"
"\n"
"Por favor, informe de este fallo sobre el paquete «update-manager» e incluya "
"en el informe los archivos situados en /var/log/dist-upgrade/."

#: ../DistUpgrade/DistUpgradeController.py:1542
msgid "Updating repository information"
msgstr "Actualizando la información del repositorio"

#: ../DistUpgrade/DistUpgradeController.py:1574
msgid "Invalid package information"
msgstr "Información sobre los paquetes no válida"

#: ../DistUpgrade/DistUpgradeController.py:1575
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"Después de actualizar la información sobre los paquetes, ya no aparece el "
"paquete esencial «%s».\n"
"Esto indica un error serio; por favor, informe del fallo sobre el paquete "
"«update-manager» e incluya en el informe los archivos situados en "
"/var/log/dist-upgrade/."

#: ../DistUpgrade/DistUpgradeController.py:1592
#: ../DistUpgrade/DistUpgradeController.py:1640
msgid "Fetching"
msgstr "Descargando"

#: ../DistUpgrade/DistUpgradeController.py:1598
#: ../DistUpgrade/DistUpgradeController.py:1644
msgid "Upgrading"
msgstr "Actualizando"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1603
#: ../DistUpgrade/DistUpgradeController.py:1646
#: ../DistUpgrade/DistUpgradeController.py:1653
#: ../DistUpgrade/DistUpgradeController.py:1664
msgid "Upgrade complete"
msgstr "Actualización completada"

#: ../DistUpgrade/DistUpgradeController.py:1604
#: ../DistUpgrade/DistUpgradeController.py:1647
#: ../DistUpgrade/DistUpgradeController.py:1654
msgid ""
"The upgrade is completed but there were errors during the upgrade process."
msgstr ""
"La actualización se ha terminado pero ocurrieron errores en el proceso."

#: ../DistUpgrade/DistUpgradeController.py:1611
msgid "Searching for obsolete software"
msgstr "Buscando paquetes obsoletos"

#: ../DistUpgrade/DistUpgradeController.py:1616
msgid "System upgrade is complete."
msgstr "La actualización del sistema se ha completado."

#: ../DistUpgrade/DistUpgradeController.py:1665
msgid "The partial upgrade was completed."
msgstr "La actualización parcial se ha completado."

#: ../DistUpgrade/DistUpgradeQuirks.py:149
msgid "No ARMv6 CPU"
msgstr "No hay CPU ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:150
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"Su sistema usa una CPU ARM que es más antigua que la arquitectura ARMv6. "
"Todos los paquetes en karmic han sido construidos con optimizaciones que "
"requieren ARMv6 como arquitectura mínima. No es posible actualizar sus "
"sistema a la nueva versión de Ubuntu con este hardware."

#: ../DistUpgrade/DistUpgradeQuirks.py:164
msgid "No init available"
msgstr "El demonio init no está disponible"

#: ../DistUpgrade/DistUpgradeQuirks.py:165
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 9.10 cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"Parece que su sistema es un entorno virtualizado sin un demonio init (un "
"Linux-VServer, p.ej.). Ubuntu 9.10 no puede funcionar en este tipo de "
"entorno, por lo que primero se requiere una actualización de la "
"configuración de su máquina virtual.\n"
"\n"
"¿Está seguro de que desea continuar?"

#. TRANSLATORS: this string is not displayed in the 9.10 upgrade
#. (but it will be used for 8.04 -> 10.04 LTS upgrades)
#: ../DistUpgrade/DistUpgradeQuirks.py:186
#: ../DistUpgrade/DistUpgradeQuirks.py:271
#: ../DistUpgrade/DistUpgradeQuirks.py:298
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"La actualización puede reducir los efectos de escritorio, así como el "
"rendimiento de los juegos y otros programas que usen gráficos de forma "
"intensiva."

#: ../DistUpgrade/DistUpgradeQuirks.py:190
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Este quipo está usando el controlador gráfico  «fglrx» de AMD. No se "
"encuentra disponible en Ubuntu 10.04 una versión de este controlador que "
"funcione con su hardware.\n"
"\n"
"¿Desea continuar?"

#: ../DistUpgrade/DistUpgradeQuirks.py:275
#: ../DistUpgrade/DistUpgradeQuirks.py:302
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Este quipo está usando el controlador gráfico  «nvidia» de NVIDIA. No se "
"encuentra disponible en Ubuntu 10.04 una versión de este controlador que "
"funcione con su hardware.\n"
"\n"
"¿Desea continuar?"

#: ../DistUpgrade/DistUpgradeQuirks.py:472
msgid "evms in use"
msgstr "Se está usando «evms»"

#: ../DistUpgrade/DistUpgradeQuirks.py:473
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""
"Su sistema está usando el gestor de volúmenes «evms» en /proc/mounts. El "
"software «evms» ya no está soportado; por favor, desactívelo y vuelva a "
"ejecutar de nuevo la actualización."

#: ../DistUpgrade/DistUpgradeMain.py:43
msgid "Sandbox upgrade using aufs"
msgstr "Actualización de prueba usando aufs"

#: ../DistUpgrade/DistUpgradeMain.py:45
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr "Usar la ruta dada para buscar un CD-ROM con paquetes actualizables"

#: ../DistUpgrade/DistUpgradeMain.py:51
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Usar interfaz de usuario. Actualmente disponibles: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:54
msgid "*DEPRECATED* this option will be ignore"
msgstr "*OBSOLETA* esta opción será ignorada"

#: ../DistUpgrade/DistUpgradeMain.py:57
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""
"Realizar sólo una actualización parcial (no se reescribirá el «sources.list»)"

#: ../DistUpgrade/DistUpgradeMain.py:59
msgid "Set datadir"
msgstr "Establecer datadir"

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:109
#: ../DistUpgrade/DistUpgradeViewKDE.py:190
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Inserte «%s» en la unidad «%s»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:129
#: ../DistUpgrade/DistUpgradeViewKDE.py:204
msgid "Fetching is complete"
msgstr "La descarga se ha completado"

#: ../DistUpgrade/DistUpgradeViewGtk.py:141
#: ../DistUpgrade/DistUpgradeViewKDE.py:217
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Descargando archivo %li de %li a %sB/s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:142
#: ../DistUpgrade/DistUpgradeViewGtk.py:277
#: ../DistUpgrade/DistUpgradeViewKDE.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:358
#, python-format
msgid "About %s remaining"
msgstr "Faltan alrededor de %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:144
#: ../DistUpgrade/DistUpgradeViewKDE.py:220
#, python-format
msgid "Fetching file %li of %li"
msgstr "Descargando archivo %li de %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:176
#: ../DistUpgrade/DistUpgradeViewKDE.py:254
msgid "Applying changes"
msgstr "Aplicando los cambios"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:201
#: ../DistUpgrade/DistUpgradeViewKDE.py:267
msgid "dependency problems - leaving unconfigured"
msgstr "problemas de dependencias - se deja sin configurar"

#: ../DistUpgrade/DistUpgradeViewGtk.py:206
#: ../DistUpgrade/DistUpgradeViewKDE.py:269
#, python-format
msgid "Could not install '%s'"
msgstr "No se ha podido instalar «%s»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:207
#: ../DistUpgrade/DistUpgradeViewKDE.py:270
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"La actualización continuará, pero es posible que el paquete «%s» no se "
"encuentre en un estado funcional. Considere la posibilidad de enviar un "
"informe de error acerca de esto."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:223
#: ../DistUpgrade/DistUpgradeViewKDE.py:291
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"¿Desea sustituir el archivo de configuración modificado\n"
"«%s»?"

#: ../DistUpgrade/DistUpgradeViewGtk.py:224
#: ../DistUpgrade/DistUpgradeViewKDE.py:292
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"Perderá todos los cambios que haya realizado en este archivo de "
"configuración si decide sustituirlo por una nueva versión."

#: ../DistUpgrade/DistUpgradeViewGtk.py:237
#: ../DistUpgrade/DistUpgradeViewKDE.py:310
msgid "The 'diff' command was not found"
msgstr "No se ha encontrado la orden «diff»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:440
#: ../DistUpgrade/DistUpgradeViewText.py:88
msgid "A fatal error occurred"
msgstr "Ha ocurrido un error fatal"

#: ../DistUpgrade/DistUpgradeViewGtk.py:441
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade is now aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Por favor, informe de este fallo (si no lo ha hecho ya) e incluya en su "
"informe los archivos /var/log/dist-upgrade/main.log y /var/log/dist-"
"upgrade/apt.log. La actualización va a cancelarse ahora.\n"
"Su archivo sources.list original se guardó en "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewGtk.py:458
msgid "Ctrl-c pressed"
msgstr "Se ha pulsado Ctrl-C"

#: ../DistUpgrade/DistUpgradeViewGtk.py:459
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Esto cancelará la operación y puede dejar al sistema en un estado "
"defectuoso. ¿Seguro que desea hacer eso?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:604
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Para prevenir la pérdida de datos, cierre todas las aplicaciones y "
"documentos."

#: ../DistUpgrade/DistUpgradeViewGtk.py:618
#, python-format
msgid "<b>Downgrade %s</b>"
msgstr "<b>Desactualizar %s</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:620
#: ../DistUpgrade/DistUpgradeViewKDE.py:758
#, python-format
msgid "Remove %s"
msgstr "Eliminar %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:625
#: ../DistUpgrade/DistUpgradeViewKDE.py:760
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "Eliminar (fue autoinstalado) %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:628
#: ../DistUpgrade/DistUpgradeViewKDE.py:762
#, python-format
msgid "Install %s"
msgstr "Instalar %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:630
#: ../DistUpgrade/DistUpgradeViewKDE.py:764
#, python-format
msgid "Upgrade %s"
msgstr "Actualizar %s"

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:191
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Media Change"
msgstr "Cambio de soporte"

#: ../DistUpgrade/DistUpgradeViewKDE.py:322
msgid "Show Difference >>>"
msgstr "Mostrar diferencias >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:325
msgid "<<< Hide Difference"
msgstr "<<< Ocultar diferencias"

#: ../DistUpgrade/DistUpgradeViewKDE.py:539
msgid "Error"
msgstr "Error"

#: ../DistUpgrade/DistUpgradeViewKDE.py:551
msgid "&Cancel"
msgstr "&Cancelar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:553
#: ../DistUpgrade/DistUpgradeViewKDE.py:792
msgid "&Close"
msgstr "&Cerrar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:599
msgid "Show Terminal >>>"
msgstr "Mostrar terminal >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:602
msgid "<<< Hide Terminal"
msgstr "<<< Ocultar terminal"

#: ../DistUpgrade/DistUpgradeViewKDE.py:682
msgid "Information"
msgstr "Información"

#: ../DistUpgrade/DistUpgradeViewKDE.py:732
#: ../DistUpgrade/DistUpgradeViewKDE.py:775
#: ../DistUpgrade/DistUpgradeViewKDE.py:778 ../DistUpgrade/DistUpgrade.ui.h:11
msgid "Details"
msgstr "Detalles"

#: ../DistUpgrade/DistUpgradeViewKDE.py:788
#: ../DistUpgrade/DistUpgradeViewText.py:206
msgid "Restart required"
msgstr "Se requiere reiniciar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:788
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr ""
"<b><big>Reinicie el sistema para completar la actualización</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:791 ../DistUpgrade/DistUpgrade.ui.h:25
#: ../data/glade/UpdateManager.ui.h:31
msgid "_Restart Now"
msgstr "_Reiniciar ahora"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:803
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>¿Cancelar la actualización en curso?</big></b>\n"
"\n"
"El sistema podría quedar en un estado no utilizable si cancela la "
"actualización. Le recomendamos encarecidamente que continúe la actualización."

#: ../DistUpgrade/DistUpgradeViewKDE.py:807
msgid "Cancel Upgrade?"
msgstr "¿Cancelar la actualización?"

#: ../DistUpgrade/DistUpgradeView.py:60
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li día"
msgstr[1] "%li días"

#: ../DistUpgrade/DistUpgradeView.py:62
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li hora"
msgstr[1] "%li horas"

#: ../DistUpgrade/DistUpgradeView.py:64
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li minuto"
msgstr[1] "%li minutos"

#: ../DistUpgrade/DistUpgradeView.py:65
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li segundo"
msgstr[1] "%li segundos"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:78
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:93
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:128
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"Esta descarga tardará %s aproximadamente con una conexión DSL de 1Mbit y %s "
"aproximadamente con un módem de 56k."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:132
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "Esta descarga tardará aproximadamente %s con su conexión actual. "

#: ../DistUpgrade/DistUpgradeView.py:233 ../DistUpgrade/DistUpgrade.ui.h:16
msgid "Preparing to upgrade"
msgstr "Preparando la actualización"

#: ../DistUpgrade/DistUpgradeView.py:234
msgid "Getting new software channels"
msgstr "Obteniendo nuevos canales de software"

#: ../DistUpgrade/DistUpgradeView.py:235 ../DistUpgrade/DistUpgrade.ui.h:14
msgid "Getting new packages"
msgstr "Obteniendo paquetes nuevos"

#: ../DistUpgrade/DistUpgradeView.py:236 ../DistUpgrade/DistUpgrade.ui.h:15
msgid "Installing the upgrades"
msgstr "Instalando las actualizaciones"

#: ../DistUpgrade/DistUpgradeView.py:237 ../DistUpgrade/DistUpgrade.ui.h:10
msgid "Cleaning up"
msgstr "Limpiando"

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:321
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "Se va a desinstalar %d paquete."
msgstr[1] "Se van a desinstalar %d paquetes."

#: ../DistUpgrade/DistUpgradeView.py:326
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "Se va a instalar %d paquete nuevo."
msgstr[1] "Se van a instalar %d paquetes nuevos."

#: ../DistUpgrade/DistUpgradeView.py:332
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "Se va a actualizar %d paquete."
msgstr[1] "Se van a actualizar %d paquetes."

#: ../DistUpgrade/DistUpgradeView.py:337
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Debe descargar un total de %s. "

#: ../DistUpgrade/DistUpgradeView.py:341
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be cancelled."
msgstr ""
"Descargar e instalar la actualización puede llevar varias horas. Una vez "
"finalizada la descarga, el proceso no podrá cancelarse."

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:347 ../UpdateManager/UpdateManager.py:502
msgid "Your system is up-to-date"
msgstr "Su sistema está actualizado"

#: ../DistUpgrade/DistUpgradeView.py:348
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"No hay actualizaciones disponibles para su sistema. Se ha cancelado la "
"actualización."

#: ../DistUpgrade/DistUpgradeView.py:361
msgid "Reboot required"
msgstr "Se requiere reiniciar el equipo"

#: ../DistUpgrade/DistUpgradeView.py:362
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"La actualización ha finalizado y se requiere reiniciar el equipo. ¿Desea "
"hacerlo ahora?"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid "Could not run the upgrade tool"
msgstr "No se ha podido ejecutar la herramienta de actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""
"Lo más probable es que se trate de un fallo en la herramienta de "
"actualización. Por favor, informe de esto como un error."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:205
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:205
msgid "Upgrade tool signature"
msgstr "Firma de la herramienta de actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:208
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:208
msgid "Upgrade tool"
msgstr "Herramienta de actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:237
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:237
msgid "Failed to fetch"
msgstr "Error al descargar"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:238
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""
"Ha fallado la descarga de la actualización. Puede haber un problema con la "
"red. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:242
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:242
msgid "Failed to extract"
msgstr "Error al extraer"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:243
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Ha fallado la extracción de la actualización. Puede haber un problema con la "
"red o el servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:248
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:248
msgid "Verification failed"
msgstr "Falló la verificación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:249
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Ha fallado la verificación de la actualización. Puede haber un problema con "
"la red o con el servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:254
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:254
msgid "Authentication failed"
msgstr "Error de autenticación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:255
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Ha fallado la autenticación de la actualización. Es posible que exista un "
"problema con la red o el servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
#: ../DistUpgrade/DistUpgradeFetcherCore.py:275
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:269
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:275
msgid "Can not run the upgrade"
msgstr "No se ha podido ejecutar la actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:270
msgid ""
"This usually is caused by a system were /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"Esto normalmente lo provocan los sistemas cuyo /tmp se montan con la opción "
"noexec. Por favor, vuelva a montarlo sin el noexec y ejecute de nuevo la "
"actualización."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:276
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:276
#, python-format
msgid "The error message is '%s'."
msgstr "El mensaje de error es «%s»"

#: ../DistUpgrade/DistUpgradeViewText.py:89
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade is now aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Por favor, informe de este fallo e incluya en su informe los archivos "
"/var/log/dist-upgrade/main.log y /var/log/dist-upgrade/apt.log. La "
"actualización va a cancelarse ahora.\n"
"Su archivo sources.list original se guardó en "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewText.py:113
msgid "Aborting"
msgstr "Cancelando"

#: ../DistUpgrade/DistUpgradeViewText.py:118
msgid "Demoted:\n"
msgstr "Para quitar:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:150
#: ../DistUpgrade/DistUpgradeViewText.py:172
#: ../DistUpgrade/DistUpgradeViewText.py:179
msgid "Continue [yN] "
msgstr "Continuar [sN] "

#: ../DistUpgrade/DistUpgradeViewText.py:150
#: ../DistUpgrade/DistUpgradeViewText.py:172
msgid "Details [d]"
msgstr "Detalles [d]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:154
#: ../DistUpgrade/DistUpgradeViewText.py:182
msgid "y"
msgstr "s"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:157
#: ../DistUpgrade/DistUpgradeViewText.py:189
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:160
msgid "d"
msgstr "d"

#: ../DistUpgrade/DistUpgradeViewText.py:164
#, python-format
msgid "Remove: %s\n"
msgstr "Desinstalar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:167
#, python-format
msgid "Install: %s\n"
msgstr "Instalar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:170
#, python-format
msgid "Upgrade: %s\n"
msgstr "Actualizar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:186
msgid "Continue [Yn] "
msgstr "Continuar [Sn] "

#: ../DistUpgrade/DistUpgradeViewText.py:207
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Para finalizar la actualización se necesita reiniciar.\n"
"Si selecciona «s» el sistema reiniciará."

#: ../DistUpgrade/DistUpgrade.ui.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.ui.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>¿Cancelar la actualización en curso?</big></b>\n"
"\n"
"El sistema podría quedar en un estado no utilizable si cancela la "
"actualización. Le recomendamos encarecidamente que continúe la actualización."

#: ../DistUpgrade/DistUpgrade.ui.h:5
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>Reinicie el sistema para completar la actualización</big></b>\n"
"\n"
"Por favor guarde su trabajo antes de continuar."

#: ../DistUpgrade/DistUpgrade.ui.h:8
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>¿Comenzar la actualización?</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:9
msgid "<b><big>Upgrading Ubuntu to version 10.04 LTS</big></b>"
msgstr "<b><big>Actualice Ubuntu a la versión 10.04 LTS</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:12
msgid "Difference between the files"
msgstr "Diferencia entre los archivos"

#: ../DistUpgrade/DistUpgrade.ui.h:13
msgid "Distribution Upgrade"
msgstr "Actualización completa de la distribución"

#: ../DistUpgrade/DistUpgrade.ui.h:17
msgid "Restarting the computer"
msgstr "Reiniciando el equipo"

#: ../DistUpgrade/DistUpgrade.ui.h:18
msgid "Setting new software channels"
msgstr "Configurando nuevos canales de software"

#: ../DistUpgrade/DistUpgrade.ui.h:19
msgid "Terminal"
msgstr "Terminal"

#: ../DistUpgrade/DistUpgrade.ui.h:20
msgid "_Cancel Upgrade"
msgstr "_Cancelar la actualización"

#: ../DistUpgrade/DistUpgrade.ui.h:21
msgid "_Continue"
msgstr "_Continuar"

#: ../DistUpgrade/DistUpgrade.ui.h:23
msgid "_Replace"
msgstr "_Sustituir"

#: ../DistUpgrade/DistUpgrade.ui.h:24
msgid "_Report Bug"
msgstr "_Informar de un error"

#: ../DistUpgrade/DistUpgrade.ui.h:26
msgid "_Resume Upgrade"
msgstr "_Continuar la actualización"

#: ../DistUpgrade/DistUpgrade.ui.h:27
msgid "_Start Upgrade"
msgstr "_Iniciar la actualización"

#: ../UpdateManager/backend/InstallBackendSynaptic.py:42
msgid "Please wait, this can take some time."
msgstr "Por favor, espere; esto puede tardar un poco."

#: ../UpdateManager/backend/InstallBackendSynaptic.py:44
msgid "Update is complete"
msgstr "La actualización se ha completado"

#: ../UpdateManager/DistUpgradeFetcher.py:85
#: ../UpdateManager/DistUpgradeFetcherKDE.py:103
msgid "Could not find the release notes"
msgstr "No se han podido encontrar las notas de publicación"

#: ../UpdateManager/DistUpgradeFetcher.py:86
#: ../UpdateManager/DistUpgradeFetcherKDE.py:104
msgid "The server may be overloaded. "
msgstr "Puede que el servidor esté sobrecargado. "

#: ../UpdateManager/DistUpgradeFetcher.py:96
#: ../UpdateManager/DistUpgradeFetcherKDE.py:108
msgid "Could not download the release notes"
msgstr "No se han podido descargar las notas de publicación"

#: ../UpdateManager/DistUpgradeFetcher.py:97
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Please check your internet connection."
msgstr "Por favor, compruebe su conexión a Internet."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:62
#: ../UpdateManager/DistUpgradeFetcherKDE.py:85
msgid "Upgrade"
msgstr "Actualizar"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:89
#: ../data/glade/UpdateManager.ui.h:12
msgid "Release Notes"
msgstr "Notas de la versión"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:128
#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
msgid "Downloading additional package files..."
msgstr "Descargando archivos de paquetes adicionales..."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Archivo %s de %s a %sB/s"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
#, python-format
msgid "File %s of %s"
msgstr "Archivo %s de %s"

#: ../UpdateManager/ChangelogViewer.py:70
msgid "Open Link in Browser"
msgstr "Abrir vínculo en el navegador"

#: ../UpdateManager/ChangelogViewer.py:72
msgid "Copy Link to Clipboard"
msgstr "Copiar vínculo en el portapapeles"

#: ../UpdateManager/GtkProgress.py:115
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Descargando archivo %(current)li de %(total)li a %(speed)s/s"

#: ../UpdateManager/GtkProgress.py:120
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Descargando archivo %(current)li de %(total)li"

#: ../UpdateManager/UpdateManager.py:303
#, python-format
msgid "Version %s: \n"
msgstr "Versión %s: \n"

#: ../UpdateManager/UpdateManager.py:360
msgid "Downloading list of changes..."
msgstr "Descargando la lista de cambios..."

#: ../UpdateManager/UpdateManager.py:400
msgid "_Uncheck All"
msgstr "_Desmarcar todo"

#: ../UpdateManager/UpdateManager.py:406
msgid "_Check All"
msgstr "_Marcar todo"

#: ../UpdateManager/UpdateManager.py:450
#, python-format
msgid ""
"Download size: %s\n"
"%s selected."
msgstr ""
"Tamaño de descarga: %s\n"
"%s seleccionado."

#: ../UpdateManager/UpdateManager.py:455
msgid "Unknown download size"
msgstr "Tamaño de descarga desconocido"

#: ../UpdateManager/UpdateManager.py:463
msgid ""
"It is unknown when the package information was updated last. Please try "
"clicking on the 'Check' button to update the information."
msgstr ""
"Se desconoce cuándo se actualizó por última vez la información de los "
"paquetes. Pulse el botón «Comprobar» para actualizar la información."

#: ../UpdateManager/UpdateManager.py:472
#, python-format
msgid "The package information was last updated %s day ago."
msgid_plural "The package information was last updated %s days ago."
msgstr[0] ""
"La información de paquetes se actualizó por última vez hace %s día."
msgstr[1] ""
"La información de paquetes se actualizó por última vez hace %s días."

#: ../UpdateManager/UpdateManager.py:476
#, python-format
msgid "The package information was last updated %s hour ago."
msgid_plural "The package information was last updated %s hours ago."
msgstr[0] ""
"La información de paquetes se actualizó por última vez hace %s horas."
msgstr[1] ""
"La información de paquetes se actualizó por última vez hace %s horas."

#: ../UpdateManager/UpdateManager.py:480
msgid "The package information was last updated less than one hour ago."
msgstr ""
"La información sobre los paquetes se actualizó por última vez hace menos de "
"una hora."

#: ../UpdateManager/UpdateManager.py:500 ../data/glade/UpdateManager.ui.h:23
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""
"Las actualizaciones de software corrigen errores, eliminan fallos de "
"seguridad y proporcionan nuevas funcionalidades."

#: ../UpdateManager/UpdateManager.py:519
msgid "Welcome to Ubuntu"
msgstr "Bienvenido a Ubuntu"

#: ../UpdateManager/UpdateManager.py:520
msgid ""
"These software updates have been issued since Ubuntu was released. If you "
"don't want to install them now, choose \"Update Manager\" from the "
"Administration Menu later."
msgstr ""
"Estas actualizaciones de software son posteriores a la salida de Ubuntu. Si "
"no desea instalarlas ahora, hágalo luego usando el «Gestor de "
"actualizaciones» del menú Administración."

#: ../UpdateManager/UpdateManager.py:523
msgid "Software updates are available for this computer"
msgstr "Hay actualizaciones disponibles para este equipo"

#: ../UpdateManager/UpdateManager.py:524
msgid ""
"If you don't want to install them now, choose \"Update Manager\" from the "
"Administration menu later."
msgstr ""
"Si no desea instalarlas ahora, hágalo luego usando el «Gestor de "
"actualizaciones» del menú Administración."

#: ../UpdateManager/UpdateManager.py:573
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""
"La actualización necesita un total de %s de espacio libre en el disco «%s». "
"Libere al menos %s adicionales de espacio de disco en «%s». Vacíe su "
"papelera y elimine paquetes temporales de instalaciones anteriores usando "
"«sudo apt-get clean»."

#: ../UpdateManager/UpdateManager.py:630
#: ../UpdateManagerHildon/UpdateManagerHildon.py:114
msgid "Reading package information"
msgstr "Leyendo información de paquete"

#: ../UpdateManager/UpdateManager.py:743
msgid "Could not initialize the package information"
msgstr "No se ha podido inicializar la información de los paquetes"

#: ../UpdateManager/UpdateManager.py:744
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""
"Ha ocurrido un problema imposible de corregir cuando se inicializaba la "
"información de los paquetes.\n"
"\n"
"Por favor, informe de ésto como un fallo en el paquete «update-manager» e "
"incluya el siguiente mensaje de error:\n"

#: ../UpdateManager/UpdateManager.py:766
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""
"Ha ocurrido un problema imposible de corregir cuando se calculaba la "
"actualización.\n"
"\n"
"Por favor, informe de ésto como un fallo del paquete «update-manager» e "
"incluya el siguiente mensaje de error:"

#: ../UpdateManager/UpdateManager.py:789
msgid " (New install)"
msgstr " (Instalación nueva)"

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:793
#, python-format
msgid "(Size: %s)"
msgstr "(Tamaño: %s)"

#: ../UpdateManager/UpdateManager.py:795
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr "De la versión %(old_version)s a la %(new_version)s"

#: ../UpdateManager/UpdateManager.py:799
#, python-format
msgid "Version %s"
msgstr "Versión %s"

#: ../UpdateManager/UpdateManager.py:812
msgid "Your Ubuntu release is not supported anymore"
msgstr "Su versión actual de Ubuntu ya no está soportada"

#: ../UpdateManager/UpdateManager.py:813
msgid ""
"You will not get any further security fixes or critical updates. Please "
"Upgrade to a later version of Ubuntu Linux."
msgstr ""
"No obtendrá más correcciones de seguridad ni actualizaciones críticas. Por "
"favor, actualícese a una versión más reciente de Ubuntu Linux."

#: ../UpdateManager/UpdateManager.py:820
msgid "Upgrade information"
msgstr "Información de actualización"

#. print "on_button_dist_upgrade_clicked"
#: ../UpdateManager/UpdateManager.py:840
msgid "Downloading the release upgrade tool"
msgstr "Descargar la herramienta de actualización del lanzamiento"

#: ../UpdateManager/UpdateManager.py:847
#, python-format
msgid "<b>New Ubuntu release '%s' is available</b>"
msgstr "<b>Está disponible la nueva versión «%s» de Ubuntu</b>"

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:886
msgid "Software index is broken"
msgstr "El índice de software está dañado"

#: ../UpdateManager/UpdateManager.py:887
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""
"Es imposible instalar o desinstalar ningún programa. Utilice el gestor de "
"paquetes «Synaptic», o ejecute «sudo apt-get install -f» en una terminal, "
"para corregir este problema primero."

#: ../UpdateManagerHildon/UpdateManagerHildon.py:136
msgid "Downloading Package Information"
msgstr "Descargando información de paquetes"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:137
msgid ""
"The repositories are being checked for new, removed, or updated software "
"packages"
msgstr ""
"Se han comprobado los repositorios en busca de paquetes de software nuevos, "
"eliminados o actualizados"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:145
msgid "Downloading Package Updates"
msgstr "Descargando actualizaciones de paquetes"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:146
msgid ""
"The selected package updates are being downloaded and installed on the system"
msgstr ""
"Las actualizaciones de paquetes seleccionados se han descargado e instalado "
"en el sistema."

#: ../UpdateManagerHildon/UpdateManagerHildon.py:152
msgid "run_synaptic called with unknown action"
msgstr "run_synaptic llamado con una acción desconocida"

#: ../UpdateManagerText/UpdateManagerText.py:26
msgid "Cancel"
msgstr "Cancelar"

#: ../UpdateManagerText/UpdateManagerText.py:27
msgid "Install"
msgstr "Instalar"

#: ../UpdateManagerText/UpdateManagerText.py:45
msgid "Building Updates List"
msgstr "Construyendo la lista de actualizaciones"

#: ../UpdateManagerText/UpdateManagerText.py:48
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"\n"
"No se puede llevar a cabo una actualización normal, ejecute: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"Esto puede estar provocado por:\n"
" * Una actualización anterior incompleta\n"
" * Problemas con algún software instalado\n"
" * Paquetes no oficiales de software, no provistos por Ubuntu\n"
" * Cambios normales en una versión de prelanzamiento de Ubuntu"

#: ../UpdateManagerText/UpdateManagerText.py:117
msgid "Downloading changelog"
msgstr "Descargando el informe de cambios"

#: ../UpdateManager/Core/MyCache.py:124
#, python-format
msgid "Other updates (%s)"
msgstr "Otras actualizaciones (%s)"

#: ../UpdateManager/Core/MyCache.py:246
#, python-format
msgid ""
"Changes for the versions:\n"
"%s\n"
"%s\n"
"\n"
msgstr ""
"Cambios para las versiones:\n"
"%s\n"
"%s\n"
"\n"

#: ../UpdateManager/Core/MyCache.py:248
msgid "This change is not coming from a source that supports changelogs."
msgstr ""
"Este cambio no proviene de una fuente que admita registros de cambios."

#: ../UpdateManager/Core/MyCache.py:256
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"El registro de cambios no contiene ningún cambio relevante.\n"
"\n"
"Por favor, use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"hasta que los cambios estén disponibles, o pruebe de nuevo más tarde."

#: ../UpdateManager/Core/MyCache.py:261
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"La lista de cambios no está disponible todavía.\n"
"\n"
"Por favor, use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"hasta que los cambios estén disponibles, o inténtelo más tarde."

#: ../UpdateManager/Core/MyCache.py:267
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""
"Hubo un fallo al descargar la lista de cambios. \n"
"Compruebe su conexión a Internet."

#: ../UpdateManager/Core/UpdateList.py:50
msgid "Failed to detect distribution"
msgstr "Error al detectar la distribución"

#: ../UpdateManager/Core/UpdateList.py:51
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr ""
"Ha ocurrido un error «%s» mientras se comprobaba qué sistema está usando."

#: ../UpdateManager/Core/UpdateList.py:62
msgid "Important security updates"
msgstr "Actualizaciones importantes de seguridad"

#: ../UpdateManager/Core/UpdateList.py:63
msgid "Recommended updates"
msgstr "Actualizaciones recomendadas"

#: ../UpdateManager/Core/UpdateList.py:64
msgid "Proposed updates"
msgstr "Actualizaciones propuestas"

#: ../UpdateManager/Core/UpdateList.py:65
msgid "Backports"
msgstr "«Backports»"

#: ../UpdateManager/Core/UpdateList.py:66
msgid "Distribution updates"
msgstr "Actualizaciones de la distribución"

#: ../UpdateManager/Core/UpdateList.py:71
msgid "Other updates"
msgstr "Otras actualizaciones"

#: ../UpdateManager/Core/UpdateList.py:80
msgid "Previous selected"
msgstr "Selección anterior"

#: ../data/glade/UpdateManager.ui.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""
"<b><big>Debe comprobar las actualizaciones manualmente</big></b>\n"
"\n"
"Su sistema no comprueba automáticamente si existen actualizaciones. Puede "
"configurar este comportamiento en <i>Orígenes del software</i>, en la solapa "
"<i>Actualizaciones</i>."

#: ../data/glade/UpdateManager.ui.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr "<big><b>No se pueden instalar todas las actualizaciones</b></big>"

#: ../data/glade/UpdateManager.ui.h:5
msgid "<big><b>Running on battery</b></big>"
msgstr "<big><b>Alimentado por baterías</b></big>"

#: ../data/glade/UpdateManager.ui.h:6
msgid "<big><b>Starting Update Manager</b></big>"
msgstr "<big><b>Iniciando el gestor de actualizaciones</b></big>"

#: ../data/glade/UpdateManager.ui.h:7
msgid "Changes"
msgstr "Cambios"

#: ../data/glade/UpdateManager.ui.h:8
msgid "Chec_k"
msgstr "C_omprobar"

#: ../data/glade/UpdateManager.ui.h:9
msgid "Co_ntinue"
msgstr "Co_ntinuar"

#: ../data/glade/UpdateManager.ui.h:10
msgid "Description"
msgstr "Descripción"

#: ../data/glade/UpdateManager.ui.h:11
msgid "Description of update"
msgstr "Descripción de la actualización"

#: ../data/glade/UpdateManager.ui.h:13
msgid "Restart _Later"
msgstr "Reiniciar más _tarde"

#: ../data/glade/UpdateManager.ui.h:14
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"Ejecutar una actualización parcial, para instalar tantas actualizaciones "
"como sea posible. \n"
"\n"
"Esto puede ser debido a:\n"
" * Una actualización anterior que no se ha completado\n"
" * Problemas con algunos de los programas instalados\n"
" * Paquetes de software no oficiales ni distribuidos por Ubuntu\n"
" * Los cambios normales de una versión preliminar de Ubuntu"

#: ../data/glade/UpdateManager.ui.h:21
msgid "Settings..."
msgstr "Configuración..."

#: ../data/glade/UpdateManager.ui.h:22
msgid "Show progress of individual files"
msgstr "Mostrar el progreso de cada archivo individual"

#: ../data/glade/UpdateManager.ui.h:24
msgid ""
"The computer needs to restart to finish installing updates. Please save your "
"work before continuing."
msgstr ""
"El equipo necesita reiniciarse para finalizar la actualización. Guarde su "
"trabajo antes de continuar."

#: ../data/glade/UpdateManager.ui.h:25
msgid "U_pgrade"
msgstr "_Actualizar"

#: ../data/glade/UpdateManager.ui.h:26 ../data/update-manager.desktop.in.h:3
#: ../data/update-manager-hildon.desktop.in.h:3
msgid "Update Manager"
msgstr "Gestor de actualizaciones"

#: ../data/glade/UpdateManager.ui.h:27
msgid "Your system is running on battery. Are you sure you want to continue?"
msgstr ""
"Su sistema está alimentado por baterías. ¿Está seguro de que desea continuar?"

#: ../data/glade/UpdateManager.ui.h:28
msgid "_Hide this information in the future"
msgstr "_Ocultar esta información en el futuro"

#: ../data/glade/UpdateManager.ui.h:29
msgid "_Install Updates"
msgstr "_Instalar actualizaciones"

#: ../data/glade/UpdateManager.ui.h:30
msgid "_Partial Upgrade"
msgstr "_Actualización parcial"

#: ../data/glade/UpdateManager.ui.h:32
msgid "_Upgrade"
msgstr "_Actualizar"

#: ../data/glade/UpdateManager.ui.h:33
msgid "updates"
msgstr "actualizaciones"

#: ../data/update-manager.desktop.in.h:1
#: ../data/update-manager-hildon.desktop.in.h:1
msgid "Show and install available updates"
msgstr "Mostrar e instalar las actualizaciones disponibles"

#: ../data/update-manager.desktop.in.h:2
#: ../data/update-manager-hildon.desktop.in.h:2
msgid "Software Updates"
msgstr "Actualizaciones de software"

#: ../data/update-manager.schemas.in.h:1
msgid "*deprecated* Check for new distribution releases"
msgstr ""
"*obsoleto* Comprobar si existen nuevas publicaciones de la distribución"

#: ../data/update-manager.schemas.in.h:2
msgid "Auto close the install window after successful install"
msgstr ""
"Cerrar automáticamente la ventana de instalación tras una instalación "
"correcta"

#: ../data/update-manager.schemas.in.h:3
msgid "First run welcome message"
msgstr "Mensaje de bienvenida en la primera ejecución"

#: ../data/update-manager.schemas.in.h:4
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""
"Si desactiva la comprobación automática de actualizaciones, deberá recargar "
"la lista de canales manualmente. Esta opción le permite ocultar la "
"notificación que se muestra en este caso."

#: ../data/update-manager.schemas.in.h:5
msgid "If this key is set a first run welcome message will be presented."
msgstr ""
"Si se establece esta clave, se mostrará un mensaje de bienvenida la primera "
"vez que se ejecute."

#: ../data/update-manager.schemas.in.h:6
msgid ""
"If this key is set the install window will be automatically closed on "
"successful installation."
msgstr ""
"Si se establece esta clave, la ventana de instalación se cerrará "
"automáticamente tras una instalación correcta."

#: ../data/update-manager.schemas.in.h:7
msgid ""
"If this key is set the main update list window will show version information "
"(from version to version)."
msgstr ""
"Si se establece esta valor, la ventana principal que muestra la lista de "
"actualizaciones mostrará también la información de la versión (de «versión» "
"a «versión»)."

#: ../data/update-manager.schemas.in.h:8
msgid "Remind to reload the channel list"
msgstr "Recordar la recarga de la lista de canales"

#: ../data/update-manager.schemas.in.h:9
msgid "Show details of an update"
msgstr "Mostrar detalles de una actualización"

#: ../data/update-manager.schemas.in.h:10
msgid "Show version in update list"
msgstr "Mostrar la versión en la lista de actualizaciones"

#: ../data/update-manager.schemas.in.h:11
msgid "Stores the size of the update-manager dialog"
msgstr "Almacena el tamaño de la ventana del gestor de actualizaciones"

#: ../data/update-manager.schemas.in.h:12
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr ""
"Almacena el estado del expansor que contiene la lista de cambios y sus "
"descripciones"

#: ../data/update-manager.schemas.in.h:13
msgid "The window size"
msgstr "El tamaño de la ventana"

#: ../data/update-manager.schemas.in.h:14
msgid ""
"This key is deprecated in favor of the file /etc/update-manager/release-"
"upgrades Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""
"Esta clave está marcada como obsoleta en beneficio del archivo /etc/update-"
"manager/release-upgrades. Comprobar automáticamente si se encuentra "
"disponible una nueva versión de la distribución actual, y proponer su "
"actualización (si es posible)."

#: ../data/update-manager.schemas.in.h:15
msgid ""
"This will permanently hide the new release prompt from check-new-release-"
"gtk. Note that the small button in the main update-manager UI will still be "
"there."
msgstr ""

#: ../data/update-manager.schemas.in.h:16
msgid "make check-new-release-gtk ignore a given new release"
msgstr ""

#: ../update-manager:56 ../do-release-upgrade:33
msgid "Show version and exit"
msgstr "Mostrar la versión y salir"

#: ../update-manager:59
msgid "Directory that contains the data files"
msgstr "Directorio que contiene los archivos de datos"

#: ../update-manager:62
msgid "Check if a new Ubuntu release is available"
msgstr "Verificar si hay una nueva versión de Ubuntu disponible"

#: ../update-manager:65 ../do-release-upgrade:36 ../check-new-release:27
msgid "Check if upgrading to the latest devel release is possible"
msgstr "Comprobar si es posible actualizar a la última versión de desarrollo"

#: ../update-manager:69
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""
"Actualizar usando la versión más reciente propuesta por el actualizador"

#: ../update-manager:76
msgid "Do not focus on map when starting"
msgstr "No poner el foco sobre el mapa cuando se inicie"

#: ../update-manager:79
msgid "Try to run a dist-upgrade"
msgstr "Intente ejecutar dist-upgrade"

#: ../update-manager:83 ../do-release-upgrade:52
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "Comprobar la actualización en una capa aufs de caja de arena"

#: ../update-manager:103
msgid "Running partial upgrade"
msgstr "Ejecutando una actualización parcial"

#: ../do-release-upgrade:40 ../check-new-release:31
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Intente actualizar a la última versión usando el actualizador de $distro-"
"proposed"

#: ../do-release-upgrade:44
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Ejecutar en un modo especial de actualización.\n"
"Actualmente se soportan los modos «desktop» (para actualizaciones normales "
"de un sistema de escritorio) y «server» (para servidores)."

#: ../do-release-upgrade:50
msgid "Run the specified frontend"
msgstr "Ejecutar la interfaz especificada"

#: ../do-release-upgrade:55
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""

#: ../do-release-upgrade:69
msgid "Checking for a new ubuntu release"
msgstr "Comprobar si existe un nueva versión de Ubuntu"

#: ../do-release-upgrade:79
msgid "No new release found"
msgstr "No se ha encontrado ninguna edición nueva"

#: ../do-release-upgrade:85 ../check-new-release:56
#, c-format
msgid "New release '%s' available."
msgstr "Está disponible la nueva versión «%s»."

#: ../do-release-upgrade:86 ../check-new-release:57
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "Ejecute «do-release-upgrade» para actualizarse a ella."

#: ../check-new-release:35
#, c-format
msgid ""
"Do not output anything, just return %s if there is a new release and %s if "
"there is none."
msgstr ""
"No produce ninguna salida; tan sólo devuelve %s si hay una nueva versión y "
"%s si no hay ninguna."

#: ../Janitor/computerjanitor/exc.py:30
#, python-format
msgid "Unimplemented method: %s"
msgstr "Método no implementado: %s"

#: ../Janitor/computerjanitor/file_cruft.py:46
msgid "A file on disk"
msgstr "Un archivo en disco"

#: ../Janitor/computerjanitor/package_cruft.py:45
msgid ".deb package"
msgstr "Paquete .deb"

#: ../Janitor/computerjanitor/missing_package_cruft.py:33
msgid "Install missing package."
msgstr "Instalar paquete que falta."

#: ../Janitor/computerjanitor/missing_package_cruft.py:42
#, python-format
msgid "Package %s should be installed."
msgstr "Debe instalarse el paquete %s"

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:36
#, python-format
msgid "%i obsolete entries in the status file"
msgstr "%i entradas obsoletas en el archivo de estado"

#: ../Janitor/plugins/dpkg_status_plugin.py:39
msgid "Obsolete entries in dpkg status"
msgstr "Entradas obsoletas en estado de dpkg"

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:42
msgid "Obsolete dpkg status entries"
msgstr "Entradas de estado dpkg obsoletas"

#: ../Janitor/plugins/kdelibs4to5_plugin.py:39
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""
"Al actualizar. Sí  kdelibs4-dev esta instalado hay que instalar kdelibs5-"
"dev. Vea bugs.launchpad.net , bug #279621 para más detalles"

#: ../Janitor/plugins/langpack_manual_plugin.py:34
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr "Se debe marcar %s como instalado manualmente."

#: ../Janitor/plugins/remove_lilo_plugin.py:28
msgid ""
"Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr ""
"Se elimina LILO ya que GRUB también está instalado (Consulte el bug #314004 "
"para más información.)"

#, python-format
#~ msgid ""
#~ "This session appears to be running under ssh. It is not recommended to "
#~ "perform a upgrade over ssh currently because in case of failure it is harder "
#~ "to recover.\n"
#~ "\n"
#~ "If you continue, a additional ssh daemon will be started at port '%s'.\n"
#~ "Do you want to continue?"
#~ msgstr ""
#~ "Parece que esta sesión se está ejecutando bajo ssh. Actualmente, no se "
#~ "recomienda llevar a cabo una actualización sobre ssh, porque en caso de "
#~ "fallo sería más difícil de recuperar.\n"
#~ "\n"
#~ "Si continua, se iniciará un demonio ssh adicional en el puerto «%s».\n"
#~ "¿Desea continuar?"

#~ msgid ""
#~ "Canonical Ltd. no longer provides support for the following software "
#~ "packages. You can still get support from the community.\n"
#~ "\n"
#~ "If you have not enabled community maintained software (universe), these "
#~ "packages will be suggested for removal at the end of the upgrade."
#~ msgstr ""
#~ "Canonical Ltd. ya no soporta oficialmente los siguientes paquetes de "
#~ "software. Aunque puede obtener soporte de la comunidad.\n"
#~ "\n"
#~ "Si no tiene habilitado el software mantenido por la comunidad («universe»), "
#~ "se le sugerirá que desinstale estos paquetes al final del proceso de "
#~ "actualización."
