# translation of update-manager to Spanish
# This file is distributed under the same license as the update-manager package.
#  Copyright (c) 2004 Canonical
#                2004 Michiel Sikkes
# Jorge Bernal <koke@amedias.org>, 2005.
# Jorge Bernal <koke@sindominio.net>, 2005.
# Paco Molinero <paco@byasl.com>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version: es\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2013-05-22 21:30+0100\n"
"PO-Revision-Date: 2013-12-13 17:12+0000\n"
"Last-Translator: Paco Molinero <paco@byasl.com>\n"
"Language-Team: Spanish <traductores@gnome.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2014-04-23 06:53+0000\n"
"X-Generator: Launchpad (build 16985)\n"
"Language: es\n"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:211 ../DistUpgrade/distro.py:441
#, python-format
msgid "Server for %s"
msgstr "Servidor para %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:229 ../DistUpgrade/distro.py:235
#: ../DistUpgrade/distro.py:251
msgid "Main server"
msgstr "Servidor principal"

#: ../DistUpgrade/distro.py:255
msgid "Custom servers"
msgstr "Servidores personalizados"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:142
msgid "Could not calculate sources.list entry"
msgstr "No se puede calcular la entrada en sources.list"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:251
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"No se pudo localizar ningún paquete, quizá no es un disco de Ubuntu o no es "
"la arquitectura correcta."

#: ../DistUpgrade/DistUpgradeAptCdrom.py:294
msgid "Failed to add the CD"
msgstr "Error al añadir el CD"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:295
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"Ha habido un error al añadir el CD; se ha interrumpido la actualización. "
"Informe de esto como un fallo si este es un CD válido de Ubuntu.\n"
"\n"
"El mensaje de error fue:\n"
"«%s»"

#: ../DistUpgrade/DistUpgradeCache.py:152
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Desinstalar paquete en mal estado"
msgstr[1] "Desinstalar paquetes en mal estado"

#: ../DistUpgrade/DistUpgradeCache.py:155
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"El paquete «%s» está en un estado inconsistente y debe reinstalarse, pero no "
"se encuentra en ningún repositorio. ¿Quiere desinstalar este paquete ahora "
"para continuar?"
msgstr[1] ""
"Los paquetes «%s» están en un estado inconsistente y deben reinstalarse, "
"pero no se encuentran en ningún repositorio. ¿Quiere desinstalar estos "
"paquetes ahora para continuar?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:256
msgid "The server may be overloaded"
msgstr "El servidor puede estar sobrecargado"

#: ../DistUpgrade/DistUpgradeCache.py:369
msgid "Broken packages"
msgstr "Paquetes rotos"

#: ../DistUpgrade/DistUpgradeCache.py:370
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"Su sistema contiene paquetes rotos que no se pueden reparar con este "
"software. Repárelos primero mediante Synaptic o apt-get antes de continuar."

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:693
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"Ha ocurrido un error irresoluble mientras se calculaba la actualización:\n"
"%s\n"
"\n"
" Esto puede deberse a:\n"
" * Que se está actualizando a una versión de Ubuntu aún no publicada\n"
" * Que se está usando la actual versión aún no publicada de Ubuntu\n"
" * Paquetes de software no oficiales, no suministrados por Ubuntu\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:648
msgid "This is most likely a transient problem, please try again later."
msgstr ""
"Probablemente sea un problema transitorio, inténtelo de nuevo más tarde."

#: ../DistUpgrade/DistUpgradeCache.py:651
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""
"Si nada de esto aplica, informe de este error usando la orden «ubuntu-bug "
"ubuntu-release-upgrader-core» en una terminal."

#: ../DistUpgrade/DistUpgradeCache.py:656
msgid "Could not calculate the upgrade"
msgstr "No se ha podido calcular la actualización"

#: ../DistUpgrade/DistUpgradeCache.py:707
msgid "Error authenticating some packages"
msgstr "Error al autenticar algunos paquetes"

#: ../DistUpgrade/DistUpgradeCache.py:708
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"No ha sido posible autenticar algunos paquetes. Esto puede ser debido a un "
"problema transitorio en la red. Pruebe de nuevo más tarde. Vea abajo una "
"lista de los paquetes no autenticados."

#: ../DistUpgrade/DistUpgradeCache.py:728
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"El paquete «%s» está marcado para desinstalarse pero está en la lista negra "
"de desinstalación."

#: ../DistUpgrade/DistUpgradeCache.py:732
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "El paquete esencial «%s» ha sido marcado para su desinstalación."

#: ../DistUpgrade/DistUpgradeCache.py:741
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "Intentando instalar la versión prohibida «%s»"

#: ../DistUpgrade/DistUpgradeCache.py:859
#, python-format
msgid "Can't install '%s'"
msgstr "No se ha podido instalar «%s»"

#: ../DistUpgrade/DistUpgradeCache.py:860
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""
"Fue imposible instalar un paquete requerido. Informe de esto como un error "
"usando «ubuntu-bug ubuntu-release-upgrader-core» en una terminal."

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:871
msgid "Can't guess meta-package"
msgstr "No se ha podido determinar el metapaquete"

#: ../DistUpgrade/DistUpgradeCache.py:872
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"Su sistema no contiene el paquete ubuntu-desktop,  kubuntu-desktop, xubuntu-"
"desktop o edubuntu-desktop, y no ha sido posible detectar qué versión de "
"Ubuntu está ejecutando.\n"
" Instale uno de los paquetes anteriores usando Synaptic o apt-get antes de "
"proceder."

#: ../DistUpgrade/DistUpgradeController.py:126
msgid "Reading cache"
msgstr "Leyendo la caché"

#: ../DistUpgrade/DistUpgradeController.py:230
msgid "Unable to get exclusive lock"
msgstr "No se ha podido obtener un bloqueo exclusivo"

#: ../DistUpgrade/DistUpgradeController.py:231
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Esto normalmente significa que ya se está ejecutando otra aplicación de "
"gestión de paquetes (como apt-get o aptitude). Cierre esa aplicación primero."

#: ../DistUpgrade/DistUpgradeController.py:289
msgid "Upgrading over remote connection not supported"
msgstr "Actualizando sobre conexión remota no compatible"

#: ../DistUpgrade/DistUpgradeController.py:290
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"Está ejecutando la actualización sobre una conexión ssh remota con una "
"interfaz de usuario que no lo permite. Intente actualizar en modo texto con "
"«do-release-upgrade».\n"
"\n"
"La actualización se detendrá ahora. Pruebe sin ssh."

#: ../DistUpgrade/DistUpgradeController.py:304
msgid "Continue running under SSH?"
msgstr "¿Continuar la ejecución bajo SSH?"

#: ../DistUpgrade/DistUpgradeController.py:305
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Esta sesión parece estar ejecutándose bajo ssh. No es recomendable hacer una "
"actualización sobre ssh actualmente, porque en caso de fallo es muy difícil "
"recuperarla.\n"
"\n"
"Si continua, se iniciará un demonio ssh adicional en el puerto «%s».\n"
"¿Quiere continuar?"

#: ../DistUpgrade/DistUpgradeController.py:319
msgid "Starting additional sshd"
msgstr "Iniciando sshd adicional"

#: ../DistUpgrade/DistUpgradeController.py:320
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Para facilitar la recuperación en caso de fallo, se iniciará un sshd "
"adicional en el puerto «%s». Si algo va mal con el ssh en ejecución, aún "
"podrá conectarse al adicional.\n"

#: ../DistUpgrade/DistUpgradeController.py:328
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""
"Si ejecuta un cortafuegos, puede necesitar abrir este puerto temporalmente. "
"Como esto es potencialmente peligroso, no se hace automáticamente. Puede "
"abrir el puerto con:\n"
"«%s»"

#: ../DistUpgrade/DistUpgradeController.py:400
#: ../DistUpgrade/DistUpgradeController.py:445
msgid "Can not upgrade"
msgstr "No se puede actualizar"

#: ../DistUpgrade/DistUpgradeController.py:401
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "Esta herramienta no permite actualizaciones de «%s» a «%s»."

#: ../DistUpgrade/DistUpgradeController.py:410
msgid "Sandbox setup failed"
msgstr "Falló la configuración de prueba"

#: ../DistUpgrade/DistUpgradeController.py:411
msgid "It was not possible to create the sandbox environment."
msgstr "No ha sido posible crear un entorno de prueba."

#: ../DistUpgrade/DistUpgradeController.py:417
msgid "Sandbox mode"
msgstr "Modo de prueba"

#: ../DistUpgrade/DistUpgradeController.py:418
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a system directory from now until the next reboot "
"are permanent."
msgstr ""
"Esta actualización se esta realizando en el modo (prueba) «sandbox». Todos "
"los cambios se escriben en «%s» y se perderán en el siguiente arranque.\n"
"\n"
"*Ninguno* de los cambios escritos en el directorio de sistema desde ahora "
"hasta el siguiente arranque son permanentes."

#: ../DistUpgrade/DistUpgradeController.py:446
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"Su instalación de python está dañada. Repare el enlace simbólico "
"«/usr/bin/python»."

#: ../DistUpgrade/DistUpgradeController.py:472
msgid "Package 'debsig-verify' is installed"
msgstr "El paquete «debsig-verify» está instalado"

#: ../DistUpgrade/DistUpgradeController.py:473
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""
"La actualización no puede continuar con ese paquete instalado.\n"
"Desinstálelo con synaptic o «apt-get remove debsig-verify» primero y luego "
"intente actualizar nuevamente."

#: ../DistUpgrade/DistUpgradeController.py:485
#, python-format
msgid "Can not write to '%s'"
msgstr "No se puede escribir en «%s»"

#: ../DistUpgrade/DistUpgradeController.py:486
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""
"No es posible escribir el directorio de sistema «%s» en su sistema. La "
"actualización no puede continuar.\n"
"Asegúrese de que el directorio de sistema permite escribir."

#: ../DistUpgrade/DistUpgradeController.py:497
msgid "Include latest updates from the Internet?"
msgstr "¿Incluir las últimas actualizaciones desde Internet?"

#: ../DistUpgrade/DistUpgradeController.py:498
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"El sistema de actualización a una nueva versión puede usar Internet para "
"descargar automáticamente las actualizaciones más recientes e instalarlas "
"durante el proceso. Si dispone de una conexión a la red, esto es muy "
"recomendable.\n"
"\n"
"La actualización llevará más tiempo, pero una vez terminada, el sistema "
"estará completamente actualizado. Puede elegir no hacerlo, pero deberá "
"instalar las nuevas actualizaciones inmediatamente después de pasar a la "
"nueva versión.\n"
"Si responde «no» ahora, la red no se usará para nada."

#: ../DistUpgrade/DistUpgradeController.py:729
#, python-format
msgid "disabled on upgrade to %s"
msgstr "(desactivado al actualizar a %s)"

#: ../DistUpgrade/DistUpgradeController.py:762
msgid "No valid mirror found"
msgstr "No se ha encontrado un servidor espejo válido"

#: ../DistUpgrade/DistUpgradeController.py:753
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"Mientras se exploraba la información de su repositorio, no se encontró "
"ninguna entrada para la réplica de la actualización. Esto puede ocurrir si "
"corre una réplica interna o si la información de la réplica es antigua.\n"
"\n"
"¿Quiere reescribir su archivo «sources.list» de todos modos? Si elige «Sí» "
"se actualizarán todas las entradas «%s» a «%s».\n"
"Si selecciona «No» la actualización se cancelará."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:783
msgid "Generate default sources?"
msgstr "¿Generar orígenes predeterminados?"

#: ../DistUpgrade/DistUpgradeController.py:784
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"Después de explorar su «sources.list» no se encontraron entradas válidas "
"para «%s».\n"
"\n"
"¿Se deben añadir entradas predeterminadas para «%s»? Si selecciona «No», la "
"actualización se cancelará."

#: ../DistUpgrade/DistUpgradeController.py:819
msgid "Repository information invalid"
msgstr "Información de repositorio no válida"

#: ../DistUpgrade/DistUpgradeController.py:820
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr ""
"La actualización de la información del repositorio dio como resultado un "
"archivo no válido por lo que se está iniciando un proceso de notificación de "
"errores."

#: ../DistUpgrade/DistUpgradeController.py:827
msgid "Third party sources disabled"
msgstr "Desactivados los orígenes de terceros"

#: ../DistUpgrade/DistUpgradeController.py:828
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"Se han desactivado algunas entradas de otros proveedores en su "
"«sources.list». Puede volver a activarlas tras la actualización con la "
"herramienta «Orígenes del software», o con su gestor de paquetes."

#: ../DistUpgrade/DistUpgradeController.py:870
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Paquete en un estado inconsistente"
msgstr[1] "Paquetes en un estado inconsistente"

#: ../DistUpgrade/DistUpgradeController.py:873
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"El paquete «%s» está en un estado inconsistente y debe reinstalarse, pero no "
"se encuentra en ningún repositorio. Reinstale el paquete manualmente o "
"desinstálelo del sistema."
msgstr[1] ""
"Los paquetes «%s» están en un estado inconsistente y deben reinstalarse, "
"pero no se encuentran en ningún repositorio. Reinstale los paquetes "
"manualmente o desinstálelos del sistema."

#: ../DistUpgrade/DistUpgradeController.py:921
msgid "Error during update"
msgstr "Error durante la actualización"

#: ../DistUpgrade/DistUpgradeController.py:922
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"Ocurrió un problema durante la actualización. Normalmente es debido a algún "
"tipo de problema en la red, por lo que le recomendamos que compruebe su "
"conexión de red y vuelva a intentarlo."

#: ../DistUpgrade/DistUpgradeController.py:931
msgid "Not enough free disk space"
msgstr "No hay espacio suficiente en el disco"

#: ../DistUpgrade/DistUpgradeController.py:932
#, python-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of %s free space on disk "
"'%s'. Please free at least an additional %s of disk space on '%s'. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""
"La actualización se canceló. La actualización necesita un total de %s de "
"espacio libre en el disco «%s». Libere al menos %s de espacio en el disco "
"«%s». Pruebe vaciando su papelera y borrando paquetes temporales de antiguas "
"instalaciones usando la orden «sudo apt-get clean»."

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:961
#: ../DistUpgrade/DistUpgradeController.py:1743
msgid "Calculating the changes"
msgstr "Calculando los cambios"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:993
msgid "Do you want to start the upgrade?"
msgstr "¿Quiere comenzar la actualización?"

#: ../DistUpgrade/DistUpgradeController.py:1066
msgid "Upgrade canceled"
msgstr "Actualización cancelada"

#: ../DistUpgrade/DistUpgradeController.py:1067
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr ""
"La actualización se cancelará ahora y el sistema volverá a su estado "
"original. Puede reanudar la actualización posteriormente."

#: ../DistUpgrade/DistUpgradeController.py:1073
#: ../DistUpgrade/DistUpgradeController.py:1197
msgid "Could not download the upgrades"
msgstr "No se han podido descargar las actualizaciones"

#: ../DistUpgrade/DistUpgradeController.py:1074
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""
"La actualización se ha anulado. Compruebe su conexión a Internet o los "
"medios de instalación y vuelva a intentarlo. Todos los archivos descargados "
"hasta el momento se han mantenido."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1148
#: ../DistUpgrade/DistUpgradeController.py:1185
#: ../DistUpgrade/DistUpgradeController.py:1290
msgid "Error during commit"
msgstr "Error durante la confirmación"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1150
#: ../DistUpgrade/DistUpgradeController.py:1187
#: ../DistUpgrade/DistUpgradeController.py:1329
msgid "Restoring original system state"
msgstr "Restaurando el estado original del sistema"

#: ../DistUpgrade/DistUpgradeController.py:1151
#: ../DistUpgrade/DistUpgradeController.py:1166
#: ../DistUpgrade/DistUpgradeController.py:1188
msgid "Could not install the upgrades"
msgstr "No se han podido instalar las actualizaciones"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1156
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"La actualización se ha cancelado. Su sistema podría haber quedado en un "
"estado no utilizable. Ahora se llevará a cabo una recuperación (dpkg --"
"configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1161
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at "
"http://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+filebug "
"and attach the files in /var/log/dist-upgrade/ to the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"Informe de este error usando un navegador para ir a "
"http://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+filebug y "
"adjunte los archivos en /var/log/dist-upgrade/ al informe.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1198
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"La actualización se ha cancelado. Compruebe su conexión a Internet o el "
"soporte de instalación y vuelva a intentarlo. "

#: ../DistUpgrade/DistUpgradeController.py:1278
msgid "Remove obsolete packages?"
msgstr "¿Desinstalar los paquetes obsoletos?"

#: ../DistUpgrade/DistUpgradeController.py:1279
#: ../data/gtkbuilder/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "_Conservar"

#: ../DistUpgrade/DistUpgradeController.py:1279
msgid "_Remove"
msgstr "_Eliminar"

#: ../DistUpgrade/DistUpgradeController.py:1291
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""
"Ha ocurrido algún problema durante el limpiado. Lea el mensaje siguiente "
"para tener más información. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1367
msgid "Required depends is not installed"
msgstr "La dependencia requerida no está instalada"

#: ../DistUpgrade/DistUpgradeController.py:1368
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "La dependencia requerida «%s» no está instalada. "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1636
#: ../DistUpgrade/DistUpgradeController.py:1701
msgid "Checking package manager"
msgstr "Comprobando el gestor de paquetes"

#: ../DistUpgrade/DistUpgradeController.py:1641
msgid "Preparing the upgrade failed"
msgstr "Falló la preparación de la actualización"

#: ../DistUpgrade/DistUpgradeController.py:1642
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr ""
"Falló la preparación del sistema para actualizarse, de manera que se ha "
"iniciado el proceso de informe de errores."

#: ../DistUpgrade/DistUpgradeController.py:1656
msgid "Getting upgrade prerequisites failed"
msgstr ""
"Ha fallado la obtención de los requisitos previos de la actualización"

#: ../DistUpgrade/DistUpgradeController.py:1657
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""
"El sistema fue incapaz de obtener los requisitos previos para la "
"actualización. La actualización se interrumpirá ahora y se restaurará el "
"estado original del sistema.\n"
"\n"
"Adicionalmente, se está iniciando un proceso de notificación de errores."

#: ../DistUpgrade/DistUpgradeController.py:1685
msgid "Updating repository information"
msgstr "Actualizando la información del repositorio"

#: ../DistUpgrade/DistUpgradeController.py:1692
msgid "Failed to add the cdrom"
msgstr "Fallo al añadir el CDROM"

#: ../DistUpgrade/DistUpgradeController.py:1693
msgid "Sorry, adding the cdrom was not successful."
msgstr "Lo sentimos, no se pudo añadir el CDROM"

#: ../DistUpgrade/DistUpgradeController.py:1724
msgid "Invalid package information"
msgstr "Información sobre los paquetes no válida"

#: ../DistUpgrade/DistUpgradeController.py:1725
#, python-format
msgid ""
"After updating your package information, the essential package '%s' could "
"not be located. This may be because you have no official mirrors listed in "
"your software sources, or because of excessive load on the mirror you are "
"using. See /etc/apt/sources.list for the current list of configured software "
"sources.\n"
"In the case of an overloaded mirror, you may want to try the upgrade again "
"later."
msgstr ""
"Después de actualizar la información de paquete, el paquete esencial «%s» no "
"se puede localizar. Esto puede deberse a que no tiene las réplicas oficiales "
"listadas en sus de orígenes de software o por una carga excesiva en la "
"réplica que está usando. Vea /etc/apt/sources.list para conocer la "
"configuración de lista actual de orígenes de software.\n"
"En caso de tratarse de una sobrecarga de la réplica, debe esperar para "
"reintentar la actualización más tarde."

#: ../DistUpgrade/DistUpgradeController.py:1749
#: ../DistUpgrade/DistUpgradeController.py:1805
msgid "Fetching"
msgstr "Descargando"

#: ../DistUpgrade/DistUpgradeController.py:1755
#: ../DistUpgrade/DistUpgradeController.py:1809
msgid "Upgrading"
msgstr "Actualizando"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1760
#: ../DistUpgrade/DistUpgradeController.py:1811
#: ../DistUpgrade/DistUpgradeController.py:1818
#: ../DistUpgrade/DistUpgradeController.py:1829
msgid "Upgrade complete"
msgstr "Actualización completada"

#: ../DistUpgrade/DistUpgradeController.py:1761
#: ../DistUpgrade/DistUpgradeController.py:1812
#: ../DistUpgrade/DistUpgradeController.py:1819
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr "La actualización se completó pero hubo errores durante el proceso."

#: ../DistUpgrade/DistUpgradeController.py:1768
msgid "Searching for obsolete software"
msgstr "Buscando paquetes obsoletos"

#: ../DistUpgrade/DistUpgradeController.py:1781
msgid "System upgrade is complete."
msgstr "La actualización del sistema se ha completado."

#: ../DistUpgrade/DistUpgradeController.py:1830
msgid "The partial upgrade was completed."
msgstr "La actualización parcial se ha completado."

#: ../DistUpgrade/DistUpgradeFetcher.py:123
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:119
msgid "Could not find the release notes"
msgstr "No se han podido encontrar las notas de publicación"

#: ../DistUpgrade/DistUpgradeFetcher.py:124
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:120
msgid "The server may be overloaded. "
msgstr "Puede que el servidor esté sobrecargado. "

#: ../DistUpgrade/DistUpgradeFetcher.py:136
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:124
msgid "Could not download the release notes"
msgstr "No se han podido descargar las notas de publicación"

#: ../DistUpgrade/DistUpgradeFetcher.py:137
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:125
msgid "Please check your internet connection."
msgstr "Por favor, compruebe su conexión a Internet."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:75
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr "autenticar «%(file)s» contra «%(signature)s» "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#, python-format
msgid "extracting '%s'"
msgstr "extrayendo «%s»"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:157
#: ../DistUpgrade/DistUpgradeFetcherCore.py:158
msgid "Could not run the upgrade tool"
msgstr "No se ha podido ejecutar la herramienta de actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:159
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug ubuntu-release-upgrader-core'."
msgstr ""
"Lo más probable es que esto sea un error en la herramienta de actualización. "
"Informe de esto con la orden «ubuntu-bug ubuntu-release-upgrader-core»."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:236
msgid "Upgrade tool signature"
msgstr "Firma de la herramienta de actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
msgid "Upgrade tool"
msgstr "Herramienta de actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:277
msgid "Failed to fetch"
msgstr "Error al descargar"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:278
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""
"Ha fallado la descarga de la actualización. Puede haber un problema con la "
"red. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:282
msgid "Authentication failed"
msgstr "Error de autenticación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:283
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Ha fallado la autenticación de la actualización. Es posible que exista un "
"problema con la red o el servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:288
msgid "Failed to extract"
msgstr "Error al extraer"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:289
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Ha fallado la extracción de la actualización. Puede haber un problema con la "
"red o el servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:294
msgid "Verification failed"
msgstr "Falló la verificación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:295
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Ha fallado la verificación de la actualización. Puede haber un problema con "
"la red o con el servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:309
#: ../DistUpgrade/DistUpgradeFetcherCore.py:315
msgid "Can not run the upgrade"
msgstr "No se ha podido ejecutar la actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:310
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"Esto normalmente ocurre en un sistema donde /tmp se ha montado como no "
"ejecutable. Vuelva a montarlo sin «noexec» y ejecute de nuevo la "
"actualización."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:316
#, python-format
msgid "The error message is '%s'."
msgstr "El mensaje de error es «%s»"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:70
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:101
msgid "Upgrade"
msgstr "Actualizar"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:105
#: ../data/gtkbuilder/ReleaseNotes.ui.h:1
msgid "Release Notes"
msgstr "Notas de la versión"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:147
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:160
msgid "Downloading additional package files..."
msgstr "Descargando archivos de paquetes adicionales..."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:162
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Archivo %s de %s a %sB/s"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:166
#, python-format
msgid "File %s of %s"
msgstr "Archivo %s de %s"

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:173
#: ../DistUpgrade/DistUpgradeViewGtk.py:114
#: ../DistUpgrade/DistUpgradeViewGtk3.py:115
#: ../DistUpgrade/DistUpgradeViewKDE.py:196
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Inserte «%s» en la unidad «%s»"

#. change = QMessageBox.question(None, _("Media Change"), msg,
#. QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:176
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:177
#: ../DistUpgrade/DistUpgradeViewKDE.py:197
msgid "Media Change"
msgstr "Cambio de soporte"

#: ../DistUpgrade/DistUpgradeQuirks.py:208
msgid "evms in use"
msgstr "Se está usando «evms»"

#: ../DistUpgrade/DistUpgradeQuirks.py:209
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""
"Su sistema está usando el gestor de volúmenes «evms» en /proc/mounts. El "
"software «evms» ya no está soportado; por favor, desactívelo y vuelva a "
"ejecutar de nuevo la actualización."

#: ../DistUpgrade/DistUpgradeQuirks.py:511
msgid "Your graphics hardware may not be fully supported in Ubuntu 13.04."
msgstr ""
"Su hardware de gráficos podría no ser compatible completamente con Ubuntu "
"13.04."

#: ../DistUpgrade/DistUpgradeQuirks.py:248
msgid ""
"Running the 'unity' desktop environment is not fully supported by your "
"graphics hardware. You will maybe end up in a very slow environment after "
"the upgrade. Our advice is to keep the LTS version for now. For more "
"information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForUnity3D Do you still "
"want to continue with the upgrade?"
msgstr ""
"El entorno de escritorio en ejecución «Unity» no es totalmente compatible "
"con su hardware de gráficos. Tal vez terminé en un entorno muy lento después "
"de la actualización. Nuestro consejo es mantener la versión LTS, por ahora. "
"Para obtener más información, consulte "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForUnity3D ¿Aún desea "
"continuar con la actualización?"

#: ../DistUpgrade/DistUpgradeQuirks.py:272
msgid ""
"Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr ""
"Su hardware de gráficos no es plenamente compatible con Ubuntu 12.04 LTS."

#: ../DistUpgrade/DistUpgradeQuirks.py:274
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""
"La compatibilidad en Ubuntu 12.04 LTS para su hardware de gráficos Intel "
"está limitada y puede encontrar problemas tras la actualización. Para tener "
"más información vea "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx ¿Quiere continuar "
"con la actualización?"

#: ../DistUpgrade/DistUpgradeQuirks.py:294
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"La actualización puede reducir los efectos de escritorio, así como el "
"rendimiento de los juegos y otros programas que usen gráficos de forma "
"intensiva."

#: ../DistUpgrade/DistUpgradeQuirks.py:564
#: ../DistUpgrade/DistUpgradeQuirks.py:592
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04 LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Este equipo está usando el controlador gráfico  «nvidia» de NVIDIA. No se "
"encuentra disponible en Ubuntu 10.04 LTS una versión de este controlador que "
"funcione con su hardware.\n"
"\n"
"¿Quiere continuar?"

#: ../DistUpgrade/DistUpgradeQuirks.py:298
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Este equipo está usando el controlador gráfico  «fglrx» de AMD. No se "
"encuentra disponible en Ubuntu 10.04 LTS una versión de este controlador que "
"funcione con su hardware.\n"
"\n"
"¿Quiere continuar?"

#: ../DistUpgrade/DistUpgradeQuirks.py:333
msgid "No i686 CPU"
msgstr "Sin CPU i686"

#: ../DistUpgrade/DistUpgradeQuirks.py:334
msgid ""
"Your system uses an i586 CPU or a CPU that does not have the 'cmov' "
"extension. All packages were built with optimizations requiring i686 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"Su sistema usa una CPU i586 CPU o  una CPU que no tiene la extensión «cmov». "
"Todos los paquetes se han construido con optimizaciones que requieren i686 "
"como arquitectura mínima. No es posible actualizar su sistema a la nueva "
"versión de Ubuntu con este hardware."

#: ../DistUpgrade/DistUpgradeQuirks.py:370
msgid "No ARMv6 CPU"
msgstr "No hay CPU ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:371
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"Su sistema usa una CPU ARM que es más antigua que la arquitectura ARMv6. "
"Todos los paquetes en karmic han sido construidos con optimizaciones que "
"requieren ARMv6 como arquitectura mínima. No es posible actualizar sus "
"sistema a la nueva versión de Ubuntu con este hardware."

#: ../DistUpgrade/DistUpgradeQuirks.py:391
msgid "No init available"
msgstr "El demonio init no está disponible"

#: ../DistUpgrade/DistUpgradeQuirks.py:392
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"Parece que su sistema es un entorno virtualizado sin un demonio init (un "
"Linux-VServer, p.ej.). Ubuntu 10.04 LTS no puede funcionar en este tipo de "
"entorno, por lo que primero se requiere una actualización de la "
"configuración de su máquina virtual.\n"
"\n"
"¿Está seguro de que quiere continuar?"

#: ../DistUpgrade/DistUpgradeMain.py:64
msgid "Sandbox upgrade using aufs"
msgstr "Actualización de prueba usando aufs"

#: ../DistUpgrade/DistUpgradeMain.py:66
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr "Usar la ruta dada para buscar un CD-ROM con paquetes actualizables"

#: ../DistUpgrade/DistUpgradeMain.py:72
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Usar interfaz de usuario. Actualmente disponibles: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:75
msgid "*DEPRECATED* this option will be ignored"
msgstr "*OBSOLETO* esta opción se ignorará"

#: ../DistUpgrade/DistUpgradeMain.py:78
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""
"Realizar solo una actualización parcial (no se reescribirá el «sources.list»)"

#: ../DistUpgrade/DistUpgradeMain.py:81
msgid "Disable GNU screen support"
msgstr "Desactive el soporte de pantalla GNU"

#: ../DistUpgrade/DistUpgradeMain.py:83
msgid "Set datadir"
msgstr "Establecer datadir"

#: ../DistUpgrade/DistUpgradeViewGtk.py:135
#: ../DistUpgrade/DistUpgradeViewGtk3.py:136
#: ../DistUpgrade/DistUpgradeViewKDE.py:210
msgid "Fetching is complete"
msgstr "La descarga se ha completado"

#: ../DistUpgrade/DistUpgradeViewGtk.py:149
#: ../DistUpgrade/DistUpgradeViewGtk3.py:151
#: ../DistUpgrade/DistUpgradeViewKDE.py:226
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Descargando archivo %li de %li a %sB/s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:151
#: ../DistUpgrade/DistUpgradeViewGtk.py:298
#: ../DistUpgrade/DistUpgradeViewGtk3.py:153
#: ../DistUpgrade/DistUpgradeViewGtk3.py:310
#: ../DistUpgrade/DistUpgradeViewKDE.py:227
#: ../DistUpgrade/DistUpgradeViewKDE.py:375
#, python-format
msgid "About %s remaining"
msgstr "Faltan alrededor de %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:154
#: ../DistUpgrade/DistUpgradeViewGtk3.py:156
#: ../DistUpgrade/DistUpgradeViewKDE.py:229
#, python-format
msgid "Fetching file %li of %li"
msgstr "Descargando archivo %li de %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:185
#: ../DistUpgrade/DistUpgradeViewGtk3.py:187
#: ../DistUpgrade/DistUpgradeViewKDE.py:266
msgid "Applying changes"
msgstr "Aplicando los cambios"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:210
#: ../DistUpgrade/DistUpgradeViewGtk3.py:213
#: ../DistUpgrade/DistUpgradeViewKDE.py:279
msgid "dependency problems - leaving unconfigured"
msgstr "problemas de dependencias - se deja sin configurar"

#: ../DistUpgrade/DistUpgradeViewGtk.py:215
#: ../DistUpgrade/DistUpgradeViewGtk3.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:281
#, python-format
msgid "Could not install '%s'"
msgstr "No se ha podido instalar «%s»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:216
#: ../DistUpgrade/DistUpgradeViewGtk3.py:219
#: ../DistUpgrade/DistUpgradeViewKDE.py:282
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"La actualización continuará, pero es posible que el paquete «%s» no se "
"encuentre en un estado funcional. Considere la posibilidad de enviar un "
"informe de error acerca de esto."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:233
#: ../DistUpgrade/DistUpgradeViewGtk3.py:236
#: ../DistUpgrade/DistUpgradeViewKDE.py:303
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"¿Quiere sustituir el archivo de configuración modificado\n"
"«%s»?"

#: ../DistUpgrade/DistUpgradeViewGtk.py:234
#: ../DistUpgrade/DistUpgradeViewGtk3.py:237
#: ../DistUpgrade/DistUpgradeViewKDE.py:304
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"Perderá todos los cambios que haya realizado en este archivo de "
"configuración si decide sustituirlo por una nueva versión."

#: ../DistUpgrade/DistUpgradeViewGtk.py:253
#: ../DistUpgrade/DistUpgradeViewGtk3.py:257
#: ../DistUpgrade/DistUpgradeViewKDE.py:327
msgid "The 'diff' command was not found"
msgstr "No se ha encontrado la orden «diff»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:466
#: ../DistUpgrade/DistUpgradeViewGtk3.py:478
#: ../DistUpgrade/DistUpgradeViewText.py:100
msgid "A fatal error occurred"
msgstr "Ha ocurrido un error fatal"

#: ../DistUpgrade/DistUpgradeViewGtk.py:467
#: ../DistUpgrade/DistUpgradeViewGtk3.py:479
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Informe de este fallo (si todavía no lo ha hecho) e incluya los archivos "
"/var/log/dist-upgrade/main.log y /var/log/dist-upgrade/apt.log en el "
"informe. La actualización se ha cancelado.\n"
"Su archivo sources.list original se guardó en "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewGtk.py:484
#: ../DistUpgrade/DistUpgradeViewGtk3.py:496
msgid "Ctrl-c pressed"
msgstr "Se ha pulsado Ctrl-C"

#: ../DistUpgrade/DistUpgradeViewGtk.py:485
#: ../DistUpgrade/DistUpgradeViewGtk3.py:497
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Esto cancelará la operación y puede dejar al sistema en un estado "
"defectuoso. ¿Seguro que quiere hacer eso?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:633
#: ../DistUpgrade/DistUpgradeViewGtk3.py:630
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Para prevenir la pérdida de datos, cierre todas las aplicaciones y "
"documentos."

#: ../DistUpgrade/DistUpgradeViewGtk.py:647
#: ../DistUpgrade/DistUpgradeViewGtk3.py:644
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "Ya no está soportado por Canonical (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:648
#: ../DistUpgrade/DistUpgradeViewGtk3.py:645
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>Desactualizar (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:649
#: ../DistUpgrade/DistUpgradeViewGtk3.py:646
#, python-format
msgid "Remove (%s)"
msgstr "Eliminar (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:650
#: ../DistUpgrade/DistUpgradeViewGtk3.py:647
#, python-format
msgid "No longer needed (%s)"
msgstr "Ya no es necesario (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:651
#: ../DistUpgrade/DistUpgradeViewGtk3.py:648
#, python-format
msgid "Install (%s)"
msgstr "Instalar (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:652
#: ../DistUpgrade/DistUpgradeViewGtk3.py:649
#, python-format
msgid "Upgrade (%s)"
msgstr "Actualizar (%s)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:339
msgid "Show Difference >>>"
msgstr "Mostrar diferencias >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:342
msgid "<<< Hide Difference"
msgstr "<<< Ocultar diferencias"

#: ../DistUpgrade/DistUpgradeViewKDE.py:558
msgid "Error"
msgstr "Error"

#: ../DistUpgrade/DistUpgradeViewKDE.py:572
msgid "&Cancel"
msgstr "&Cancelar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:817
msgid "&Close"
msgstr "&Cerrar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:622
msgid "Show Terminal >>>"
msgstr "Mostrar terminal >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:625
msgid "<<< Hide Terminal"
msgstr "<<< Ocultar terminal"

#: ../DistUpgrade/DistUpgradeViewKDE.py:705
msgid "Information"
msgstr "Información"

#: ../DistUpgrade/DistUpgradeViewKDE.py:755
#: ../DistUpgrade/DistUpgradeViewKDE.py:800
#: ../DistUpgrade/DistUpgradeViewKDE.py:803
#: ../data/gtkbuilder/DistUpgrade.ui.h:7
msgid "Details"
msgstr "Detalles"

#: ../DistUpgrade/DistUpgradeViewKDE.py:781
#, python-format
msgid "No longer supported %s"
msgstr "Ya no está soportado %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:783
#, python-format
msgid "Remove %s"
msgstr "Eliminar %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:785
#: ../DistUpgrade/DistUpgradeViewText.py:194
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "Eliminar (fue autoinstalado) %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:787
#, python-format
msgid "Install %s"
msgstr "Instalar %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:789
#, python-format
msgid "Upgrade %s"
msgstr "Actualizar %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:813
#: ../DistUpgrade/DistUpgradeViewText.py:242
msgid "Restart required"
msgstr "Se requiere reiniciar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:813
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr ""
"<b><big>Reinicie el sistema para completar la actualización</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:816
#: ../data/gtkbuilder/DistUpgrade.ui.h:14
msgid "_Restart Now"
msgstr "_Reiniciar ahora"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:834
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>¿Cancelar la actualización en curso?</big></b>\n"
"\n"
"El sistema podría quedar en un estado no utilizable si cancela la "
"actualización. Le recomendamos encarecidamente que continúe la actualización."

#: ../DistUpgrade/DistUpgradeViewKDE.py:838
msgid "Cancel Upgrade?"
msgstr "¿Cancelar la actualización?"

#: ../DistUpgrade/DistUpgradeView.py:73
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li día"
msgstr[1] "%li días"

#: ../DistUpgrade/DistUpgradeView.py:75
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li hora"
msgstr[1] "%li horas"

#: ../DistUpgrade/DistUpgradeView.py:77
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li minuto"
msgstr[1] "%li minutos"

#: ../DistUpgrade/DistUpgradeView.py:78
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li segundo"
msgstr[1] "%li segundos"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:94
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:112
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:163
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"Esta descarga tardará %s aproximadamente con una conexión DSL de 1Mbit y %s "
"aproximadamente con un módem de 56k."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:167
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "Esta descarga tardará aproximadamente %s con su conexión actual. "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:271
#: ../data/gtkbuilder/DistUpgrade.ui.h:21
msgid "Preparing to upgrade"
msgstr "Preparando la actualización"

#: ../DistUpgrade/DistUpgradeView.py:272
msgid "Getting new software channels"
msgstr "Obteniendo nuevos canales de software"

#: ../DistUpgrade/DistUpgradeView.py:273
#: ../data/gtkbuilder/DistUpgrade.ui.h:23
msgid "Getting new packages"
msgstr "Obteniendo paquetes nuevos"

#: ../DistUpgrade/DistUpgradeView.py:274
#: ../data/gtkbuilder/DistUpgrade.ui.h:26
msgid "Installing the upgrades"
msgstr "Instalando las actualizaciones"

#: ../DistUpgrade/DistUpgradeView.py:275
#: ../data/gtkbuilder/DistUpgrade.ui.h:25
msgid "Cleaning up"
msgstr "Limpiando"

#: ../DistUpgrade/DistUpgradeView.py:360
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"%(amount)d paquete instalado ya no está soportado por Canonical. Puede "
"seguir obteniendo soporte de la comunidad."
msgstr[1] ""
"%(amount)d paquetes instalados ya no están soportados por Canonical. Puede "
"seguir obteniendo soporte de la comunidad."

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:369
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "Se va a desinstalar %d paquete."
msgstr[1] "Se van a desinstalar %d paquetes."

#: ../DistUpgrade/DistUpgradeView.py:374
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "Se va a instalar %d paquete nuevo."
msgstr[1] "Se van a instalar %d paquetes nuevos."

#: ../DistUpgrade/DistUpgradeView.py:380
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "Se va a actualizar %d paquete."
msgstr[1] "Se van a actualizar %d paquetes."

#: ../DistUpgrade/DistUpgradeView.py:388
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Debe descargar un total de %s. "

#: ../DistUpgrade/DistUpgradeView.py:393
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr ""
"Esta actualización puede tardar varias horas. Una vez finalice la descarga, "
"el proceso no se podrá cancelar."

#: ../DistUpgrade/DistUpgradeView.py:397
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr ""
"Recoger e instalar la actualización puede llevar varias horas. Una vez que "
"la descarga haya terminado, el proceso no se puede cancelar."

#: ../DistUpgrade/DistUpgradeView.py:402
msgid "Removing the packages can take several hours. "
msgstr "La desinstalación de los paquetes puede tardar varias horas. "

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:407
msgid "The software on this computer is up to date."
msgstr "El software de este equipo está actualizado."

#: ../DistUpgrade/DistUpgradeView.py:408
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"No hay actualizaciones disponibles para su sistema. Se ha cancelado la "
"actualización."

#: ../DistUpgrade/DistUpgradeView.py:421
msgid "Reboot required"
msgstr "Se requiere reiniciar el equipo"

#: ../DistUpgrade/DistUpgradeView.py:422
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"La actualización ha finalizado y se necesita reiniciar el equipo. ¿Quiere "
"hacerlo ahora?"

#: ../DistUpgrade/DistUpgradeViewText.py:101
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Informe de este fallo e incluya los archivos /var/log/dist-upgrade/main.log "
"y /var/log/dist-upgrade/apt.log en el informe. La actualización ha sido "
"cancelada.\n"
"Su archivo sources.list original se guardó en "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewText.py:125
msgid "Aborting"
msgstr "Cancelando"

#: ../DistUpgrade/DistUpgradeViewText.py:130
msgid "Demoted:\n"
msgstr "Para quitar:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:137
msgid "To continue please press [ENTER]"
msgstr "Para continuar, pulse Intro"

#: ../DistUpgrade/DistUpgradeViewText.py:169
#: ../DistUpgrade/DistUpgradeViewText.py:208
#: ../DistUpgrade/DistUpgradeViewText.py:215
msgid "Continue [yN] "
msgstr "Continuar [sN] "

#: ../DistUpgrade/DistUpgradeViewText.py:169
#: ../DistUpgrade/DistUpgradeViewText.py:208
msgid "Details [d]"
msgstr "Detalles [d]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:174
#: ../DistUpgrade/DistUpgradeViewText.py:218
msgid "y"
msgstr "s"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:177
#: ../DistUpgrade/DistUpgradeViewText.py:225
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:180
msgid "d"
msgstr "d"

#: ../DistUpgrade/DistUpgradeViewText.py:185
#, python-format
msgid "No longer supported: %s\n"
msgstr "Ya no está soportado: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:190
#, python-format
msgid "Remove: %s\n"
msgstr "Desinstalar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:200
#, python-format
msgid "Install: %s\n"
msgstr "Instalar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:205
#, python-format
msgid "Upgrade: %s\n"
msgstr "Actualizar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:222
msgid "Continue [Yn] "
msgstr "Continuar [Sn] "

#: ../DistUpgrade/DistUpgradeViewText.py:243
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Para finalizar la actualización se necesita reiniciar.\n"
"Si selecciona «s» el sistema reiniciará."

#: ../DistUpgrade/GtkProgress.py:73
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Descargando archivo %(current)li de %(total)li a %(speed)s/s"

#: ../DistUpgrade/GtkProgress.py:79
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Descargando archivo %(current)li de %(total)li"

#: ../data/gtkbuilder/AcquireProgress.ui.h:1
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
msgid "Show progress of individual files"
msgstr "Mostrar el progreso de cada archivo individual"

#: ../data/gtkbuilder/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "_Cancelar la actualización"

#: ../data/gtkbuilder/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "_Continuar la actualización"

#: ../data/gtkbuilder/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>¿Cancelar la actualización en curso?</big></b>\n"
"\n"
"El sistema podría quedar en un estado no utilizable si cancela la "
"actualización. Le recomendamos encarecidamente que continúe la actualización."

#: ../data/gtkbuilder/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "_Iniciar la actualización"

#: ../data/gtkbuilder/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "_Sustituir"

#: ../data/gtkbuilder/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "Diferencia entre los archivos"

#: ../data/gtkbuilder/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "_Informar de un error"

#: ../data/gtkbuilder/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "_Continuar"

#: ../data/gtkbuilder/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>¿Comenzar la actualización?</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>Reinicie el sistema para completar la actualización</big></b>\n"
"\n"
"Guarde su trabajo antes de continuar."

#: ../data/gtkbuilder/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "Actualización completa de la distribución"

#: ../data/gtkbuilder/DistUpgrade.ui.h:19
msgid "<b><big>Upgrading Ubuntu to version 13.04</big></b>"
msgstr "<b><big>Actualizando Ubuntu a la versión 13.04</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:20
msgid "    "
msgstr "    "

#: ../data/gtkbuilder/DistUpgrade.ui.h:22
msgid "Setting new software channels"
msgstr "Configurando nuevos canales de software"

#: ../data/gtkbuilder/DistUpgrade.ui.h:24
msgid "Restarting the computer"
msgstr "Reiniciando el equipo"

#: ../data/gtkbuilder/DistUpgrade.ui.h:27
msgid "Terminal"
msgstr "Terminal"

#: ../data/gtkbuilder/ReleaseNotes.ui.h:2
msgid "_Upgrade"
msgstr "_Actualizar"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid ""
"<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr ""
"<b>Está disponible una nueva versión de Ubuntu. ¿Le gustaría actualizar?</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Don't Upgrade"
msgstr "No actualizar"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Ask Me Later"
msgstr "Preguntar más tarde"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Yes, Upgrade Now"
msgstr "Sí, actualizar ahora"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "Ha decidido no actualizarse a la nueva versión de Ubuntu"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr ""
"Puede actualizar posteriormente yendo a la Actualización de software y "
"pulsando en «Actualizar»."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:1
msgid "Perform a release upgrade"
msgstr "Realizar una actualización de la versión"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:2
msgid "To upgrade Ubuntu, you need to authenticate."
msgstr "Para actualizar Ubuntu, necesita autenticarse."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:3
msgid "Perform a partial upgrade"
msgstr "Realizar una actualización parcial"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:4
msgid "To perform a partial upgrade, you need to authenticate."
msgstr "Para realizar una actualización parcial necesita autenticarse."

#: ../do-partial-upgrade:67 ../do-release-upgrade:69
msgid "Show version and exit"
msgstr "Mostrar la versión y salir"

#: ../do-partial-upgrade:70 ../do-release-upgrade:76
msgid "Directory that contains the data files"
msgstr "Directorio que contiene los archivos de datos"

#: ../do-partial-upgrade:73 ../do-release-upgrade:89
msgid "Run the specified frontend"
msgstr "Ejecutar la interfaz especificada"

#: ../do-partial-upgrade:90
msgid "Running partial upgrade"
msgstr "Ejecutando una actualización parcial"

#: ../do-release-upgrade:31
msgid "Downloading the release upgrade tool"
msgstr "Descargando la herramienta de actualización de la versión"

#: ../do-release-upgrade:72 ../check-new-release-gtk:177
msgid "Check if upgrading to the latest devel release is possible"
msgstr "Comprobar si es posible actualizar a la última versión de desarrollo"

#: ../do-release-upgrade:79 ../check-new-release-gtk:181
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Intente actualizar a la última versión usando el actualizador de $distro-"
"proposed"

#: ../do-release-upgrade:83
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Ejecutar en un modo especial de actualización.\n"
"Actualmente se permiten los modos «desktop» (para actualizaciones normales "
"de un sistema de escritorio) y «server» (para servidores)."

#: ../do-release-upgrade:91
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "Comprobar la actualización en una capa aufs de prueba"

#: ../do-release-upgrade:94
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"Comprueba únicamente si está disponible una nueva versión de la distribución "
"e informa del resultado mediante un código de salida"

#: ../do-release-upgrade:108
msgid "Checking for a new Ubuntu release"
msgstr "Comprobar si hay una nueva versión de Ubuntu"

#: ../do-release-upgrade:121
msgid "Your Ubuntu release is not supported anymore."
msgstr "Su versión de Ubuntu ya no tiene soporte."

#: ../do-release-upgrade:122
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""
"Para saber más sobre esta actualización, visite:\n"
"%(url)s\n"

#: ../do-release-upgrade:128
msgid "No new release found"
msgstr "No se ha encontrado ninguna edición nueva"

#: ../do-release-upgrade:133
msgid "Release upgrade not possible right now"
msgstr "En este momento no es posible la actualización de versión"

#: ../do-release-upgrade:134
#, c-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""
"La actualización de versión no se puede realizar en este momento, inténtelo "
"de nuevo después. El servidor informó: «%s»"

#: ../do-release-upgrade:140
#, c-format
msgid "New release '%s' available."
msgstr "Está disponible la nueva versión «%s»."

#: ../do-release-upgrade:141
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "Ejecute «do-release-upgrade» para actualizarse a ella."

#: ../check-new-release-gtk:113
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Está disponible la actualización a Ubuntu %(version)s"

#: ../check-new-release-gtk:144
#, c-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Ha decidido no actualizarse a Ubuntu %s"

#: ../check-new-release-gtk:186
msgid "Add debug output"
msgstr "Añadir resultado de la depuración"

#~ msgid "Authentication is required to perform a partial upgrade"
#~ msgstr "Para realizar una actualización parcial, necesita autenticarse"

#~ msgid "Authentication is required to perform a release upgrade"
#~ msgstr "Para actualizar la distribución, necesita autenticarse"
