# Icelandic translation for update-manager
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the update-manager package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2009-04-07 08:37+0000\n"
"PO-Revision-Date: 2009-04-02 21:47+0000\n"
"Last-Translator: Hlini Melsteð <Unknown>\n"
"Language-Team: Icelandic <is@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2009-04-08 12:12+0000\n"
"X-Generator: Launchpad (build Unknown)\n"

#. TRANSLATORS: download size is 0
#: ../DistUpgrade/utils.py:233 ../UpdateManager/Core/utils.py:233
msgid "0 KB"
msgstr "0 KB"

#. TRANSLATORS: download size of very small updates
#: ../DistUpgrade/utils.py:236 ../UpdateManager/Core/utils.py:236
msgid "1 KB"
msgstr "1 KB"

#. TRANSLATORS: download size of small updates, e.g. "250 KB"
#: ../DistUpgrade/utils.py:239 ../UpdateManager/Core/utils.py:239
#, python-format
msgid "%.0f KB"
msgstr "%.0f KB"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:242 ../UpdateManager/Core/utils.py:242
#, python-format
msgid "%.1f MB"
msgstr "%.1f MB"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:207 ../DistUpgrade/distro.py:422
#, python-format
msgid "Server for %s"
msgstr "Netþjónn fyrir %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:225 ../DistUpgrade/distro.py:231
#: ../DistUpgrade/distro.py:247
msgid "Main server"
msgstr "Aðalnetþjónn"

#: ../DistUpgrade/distro.py:251
msgid "Custom servers"
msgstr "Sérsniðnir netþjónar"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:131
msgid "Could not calculate sources.list entry"
msgstr "Gat ekki reiknað sources.list færslur"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:234
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""

#: ../DistUpgrade/DistUpgradeAptCdrom.py:277
msgid "Failed to add the CD"
msgstr "Ekki tókst að bæta við geisladisknum"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:278
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"Það kom babb í bátinn þegar geisladisknum var bætt við, hætt verður við "
"uppfærsluna. Tilkynntu þetta sem hugbúnaðarvillu ef þetta er gildur Ubuntu "
"geisladiskur.\n"
"\n"
"Villuskilaboðin voru:\n"
"‚%s‘"

#: ../DistUpgrade/DistUpgradeCache.py:130
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Fjarlægja pakkann sem er í lélegu ásigkomulagi"
msgstr[1] "Fjarlægja þá pakka sem eru í lélegu ásigkomulagi"

#: ../DistUpgrade/DistUpgradeCache.py:133
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"Pakkinn ‚%s‘ er í lélegu ásigkomulagi og mikilvægt er að hann sé settur upp "
"aftur, en því miður fannst hann ekki í neinu gangasafni. Viltu eyða pakkanum "
"og halda áfram?"
msgstr[1] ""
"Pakkarnir ‚%s‘ eru í lélegu ásigkomulagi og mikilvægt er að þeir séu settir "
"upp aftur, en því miður fundust þeir ekki í neinu gangasafni. Viltu eyða "
"pökkunum og halda áfram?"

#: ../DistUpgrade/DistUpgradeCache.py:330
msgid "Broken packages"
msgstr "Bilaðir pakkar"

#: ../DistUpgrade/DistUpgradeCache.py:331
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"Kerfið þitt inniheldur bilaða pakka sem ekki var hægt að laga með þessum "
"hugbúnaði. Lagaðu það með synaptic eða apt-get áður en lengra er haldið."

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:564
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"Óleysanleg villa er að koma upp við  uppfærslu þegar hún er reiknuð:\n"
"%s\n"
"\n"
" Orsakavaldir get verið eftirfarandi:\n"
" * Uppfæring í prufu útgáfu Ubuntu\n"
" * Við notkun á prufu útgáfu Ubuntu\n"
" * Óformlegir hugbúnaðarpakkar sem ekki er á vegum Ubuntu\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:574
msgid "This is most likely a transient problem, please try again later."
msgstr "Þetta er væntanlega tímabundið vandamál. Reynið aftur síðar."

#: ../DistUpgrade/DistUpgradeCache.py:577
msgid ""
"If none of this applies, then please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"Ef ekkert á þessu á við, þá vinsamlegast tilkynnið þessa villu gagnvart "
"'update-manager' pakkanum og látið fylgja afrit af /var/log/dist-upgrade/ í "
"villutilkynningunni."

#: ../DistUpgrade/DistUpgradeCache.py:583
#: ../UpdateManager/UpdateManager.py:727
msgid "Could not calculate the upgrade"
msgstr "Gat ekki reiknað uppfærsluna"

#: ../DistUpgrade/DistUpgradeCache.py:633
msgid "Error authenticating some packages"
msgstr "Villa við sannvottun einhverra pakka"

#: ../DistUpgrade/DistUpgradeCache.py:634
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"Ekki tókst að sannvotta einhverja pakka. Þetta gæti verið skammvinnt "
"netvandamál. Þú gætir reynt aftur síðar. Sjá hér fyrir neðan fyrir lista "
"yfir pakka sem tókst að sannvotta."

#: ../DistUpgrade/DistUpgradeCache.py:654
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"Þessi pakki '%s' er merktur til fjarlægingar en hann er á "
"fjarlægingarbannlista."

#: ../DistUpgrade/DistUpgradeCache.py:658
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "Þessi ómissandi pakki '%s' er merktur til fjarlægingar."

#: ../DistUpgrade/DistUpgradeCache.py:745
#, python-format
msgid "Can not mark '%s' for upgrade"
msgstr "Get ekki merkt '%s' til uppfærslu"

#: ../DistUpgrade/DistUpgradeCache.py:759
#, python-format
msgid "Can't install '%s'"
msgstr "Get ekki sett upp '%s'"

#: ../DistUpgrade/DistUpgradeCache.py:760
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""
"Ekki tókst að setja upp þann pakka sem var beðið um. Tilkynntu þetta sem "
"hugbúnaðarvillu. "

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:768
msgid "Can't guess meta-package"
msgstr "Get ekki giskað á lýsi-pakka"

#: ../DistUpgrade/DistUpgradeCache.py:769
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"Kerfið þitt inniheldur hvorki pakkann ubuntu-desktop, kubuntu-desktop, "
"xubuntu-desktop né edubuntu-desktop- og ekki tókst að bera kennsl á hvaða "
"tegund af Ubuntu þú ert að nota.\n"
" Vinsamlegast settu upp einn af áðurnefndum pökkum með því að nota Synaptic "
"pakkastjórann eða með því að nota apt-get áður en þú heldur áfram."

#: ../DistUpgrade/DistUpgradeController.py:85
msgid "Reading cache"
msgstr "Les skyndiminni"

#: ../DistUpgrade/DistUpgradeController.py:178
msgid "Unable to get exclusive lock"
msgstr "Fékk ekki útilokunarlæsingu"

#: ../DistUpgrade/DistUpgradeController.py:179
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Þetta þýðir yfirleitt að annað pakkastjórnunarforrit (til dæmis apt-get eða "
"aptitude) sé í gangi. Lokaðu því forriti fyrst."

#: ../DistUpgrade/DistUpgradeController.py:232
msgid "Upgrading over remote connection not supported"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:233
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. The upgrade will abort now. Please try without "
"ssh."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:244
msgid "Continue running under SSH?"
msgstr "Viltu halda áfram að keyra undir SSH?"

#: ../DistUpgrade/DistUpgradeController.py:245
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, a additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Þessi seta virðist keyra í gegnum ssh. Við mælum ekki með að uppfæra í "
"gegnum ssh sem stendur þar sem erfitt getur verið að halda áfram ef eitthvað "
"fer úrskeiðis.\n"
"\n"
"Ef þú heldur samt áfram verður nýr ssh þjónn stofnaður á gátt '%s'.\n"
"Viltu halda áfram?"

#: ../DistUpgrade/DistUpgradeController.py:260
msgid "Starting additional sshd"
msgstr "Keyri annað sshd"

#: ../DistUpgrade/DistUpgradeController.py:261
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Til að auðvelda endurréttingu þá mun auka sshd keyra í tenginum ‚%s‘. Ef "
"eitthvað fer úrskeyðis við að keyra ssh þá er hægt að tengjast við hitt.\n"

#: ../DistUpgrade/DistUpgradeController.py:331
#: ../DistUpgrade/DistUpgradeController.py:376
msgid "Can not upgrade"
msgstr "Get ekki uppfært"

#: ../DistUpgrade/DistUpgradeController.py:332
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "Þetta tól ræður ekki við uppfærslu frá ‚%s‘ til ‚%s'."

#: ../DistUpgrade/DistUpgradeController.py:341
msgid "Sandbox setup failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:342
msgid "It was not possible to create the sandbox environment."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:348
msgid "Sandbox mode"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:349
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a systemdir from now until the next reboot are "
"permanent."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:377
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"Uppsetning þín á python er skemmd. Vinsamlegast lagaðu ‚/usr/bin/python‘ "
"vísunina."

#: ../DistUpgrade/DistUpgradeController.py:403
msgid "Package 'debsig-verify' is installed"
msgstr "Pakkinn 'debsig-verify' uppsettur"

#: ../DistUpgrade/DistUpgradeController.py:404
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""
"Uppfærslan getur ekki haldið áfram þar sem þessi pakki er uppsettur.\n"
"Vinsamlegast fjarlægðu hann með synaptic pakkastjóranum eða með því að nota "
"‚apt-get remove debsig-verify‘ fyrst og keyra svo uppfærsluna aftur."

#: ../DistUpgrade/DistUpgradeController.py:414
msgid "Include latest updates from the Internet?"
msgstr "Viltu hafa með nýjustu uppfærslurnar af internetinu?"

#: ../DistUpgrade/DistUpgradeController.py:415
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"Uppfærslukerfið getur notað netið til að sækja nýjustu uppfærslurnar "
"sjálfkrafa og að setja þær upp á meðan á uppfærslunni stendur. Ef þú hefur "
"nettengingu þá er þetta ráðlagt.\n"
"\n"
"Uppfærslan mun taka lengur, en þegar hún er loks tilbúin mun kerfið vera af "
"nýjustu gerð. Þú getur valið um að gera þetta ekki en þú ættir að uppnýja "
"kerfið eftir að þú hefur uppfært það.\n"
"Ef þú segir ‚nei‘ hér þá mun netið ekki vera notað."

#: ../DistUpgrade/DistUpgradeController.py:626
#, python-format
msgid "disabled on upgrade to %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:652
msgid "No valid mirror found"
msgstr "Enginn gildur spegill fannst"

#: ../DistUpgrade/DistUpgradeController.py:653
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found.This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'no' the update will cancel."
msgstr ""
"Á meðan farið var yfir gagnasafnið fannst ekki spegill fyrir upplýsingarnar. "
"Þetta getur gerst ef þú notast við innri spegil, eða ef upplýsingarnar sem "
"spegillinn geymir eru gamaldags.\n"
"\n"
"Viltu samt skrifa skránna ‚sources.list‘ upp á nýtt? Ef þú velur ‚Í lagi‘ þá "
"mun það uppfæra allt ‚%s‘ yfir í ‚%s‘.\n"
"Ef þú velur ‚nei‘ þá mun vera hætt við uppfærsluna."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:673
msgid "Generate default sources?"
msgstr "Búa til sjálfgefin frumgögn?"

#: ../DistUpgrade/DistUpgradeController.py:674
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the update "
"will cancel."
msgstr ""
"Eftir að hafa lesið ‚sources.list‘ fannst ekkert um ‚%s‘.\n"
"\n"
"Viltu bæta við einhverju um ‚%s‘? Ef þú velur ‚Nei‘ mun uppfærslan hætta."

#: ../DistUpgrade/DistUpgradeController.py:709
msgid "Repository information invalid"
msgstr "Ógildar útibúaupplýsingar"

#: ../DistUpgrade/DistUpgradeController.py:710
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""
"Villa kom upp við að uppfæra upplýsingar um gagnahirslu. Taktu þér tíma við "
"að tilkynna þetta."

#: ../DistUpgrade/DistUpgradeController.py:716
msgid "Third party sources disabled"
msgstr "Frumgögn frá þriðja aðila voru afvirkjuð."

#: ../DistUpgrade/DistUpgradeController.py:717
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:758
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Pakki í óvissu ástandi"
msgstr[1] "Pakkar í óvissu ástandi"

#: ../DistUpgrade/DistUpgradeController.py:761
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeController.py:809
msgid "Error during update"
msgstr "Villa við uppfærslu"

#: ../DistUpgrade/DistUpgradeController.py:810
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""

#. print "on_button_install_clicked"
#: ../DistUpgrade/DistUpgradeController.py:819
#: ../UpdateManager/UpdateManager.py:563
msgid "Not enough free disk space"
msgstr "Ekki nægilegt diskapláss laust"

#: ../DistUpgrade/DistUpgradeController.py:820
#, python-format
msgid ""
"The upgrade is now aborted. The upgrade needs a total of %s free space on "
"disk '%s'. Please free at least an additional %s of disk space on '%s'. "
"Empty your trash and remove temporary packages of former installations using "
"'sudo apt-get clean'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:860
msgid "Support for some applications ended"
msgstr "Sum forrit eru ekki lengur studd"

#: ../DistUpgrade/DistUpgradeController.py:861
msgid ""
"Canonical Ltd. no longer provides support for the following software "
"packages. You can still get support from the community.\n"
"\n"
"If you have not enabled community maintained software (universe), these "
"packages will be suggested for removal at the end of the upgrade."
msgstr ""
"Canonical Ltd. styður ekki lengur eftirfarandi forrit. Þessu er þó ennþá "
"viðhaldið af samfélaginu.\n"
"\n"
"Ef þú hefur ekki leyft hugbúnað sem viðhaldið er af samfélaginu, þá verður "
"boðist til að eyða þessum pökkum eftir uppfærsluna."

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:870
#: ../DistUpgrade/DistUpgradeController.py:1529
msgid "Calculating the changes"
msgstr "Reikna út breytingar"

#. ask the user if he wants to do the changes
#: ../DistUpgrade/DistUpgradeController.py:885
msgid "Do you want to start the upgrade?"
msgstr "Langar þig að hefja uppfærsluna?"

#: ../DistUpgrade/DistUpgradeController.py:937
#: ../DistUpgrade/DistUpgradeController.py:1016
msgid "Could not download the upgrades"
msgstr "Gat ekki halað niður uppfærslunum"

#: ../DistUpgrade/DistUpgradeController.py:938
msgid ""
"The upgrade is now aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far are kept."
msgstr ""

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:984
#: ../DistUpgrade/DistUpgradeController.py:1107
msgid "Error during commit"
msgstr "Villa við staðfestingu"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:986
#: ../DistUpgrade/DistUpgradeController.py:1146
msgid "Restoring original system state"
msgstr "Endurstilli stýrikerfi í upprunalegt form"

#: ../DistUpgrade/DistUpgradeController.py:987
#: ../DistUpgrade/DistUpgradeController.py:1000
msgid "Could not install the upgrades"
msgstr "Gat ekki sett upp uppfærslurnar"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:991
msgid ""
"The upgrade is now aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:996
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bug report.\n"
"%s"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1017
msgid ""
"The upgrade is now aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1095
msgid "Remove obsolete packages?"
msgstr "Fjarlægja úrelta pakka?"

#: ../DistUpgrade/DistUpgradeController.py:1096
#: ../DistUpgrade/DistUpgrade.glade.h:20
msgid "_Keep"
msgstr "_Halda"

#: ../DistUpgrade/DistUpgradeController.py:1096
msgid "_Remove"
msgstr "_Fjarlægja"

#: ../DistUpgrade/DistUpgradeController.py:1108
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1184
msgid "Required depends is not installed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1185
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr ""

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1439
#: ../DistUpgrade/DistUpgradeController.py:1506
msgid "Checking package manager"
msgstr "Athuga pakkastjóra"

#: ../DistUpgrade/DistUpgradeController.py:1444
msgid "Preparing the upgrade failed"
msgstr "Undirbúningur fyrir uppfærslu mistókst"

#: ../DistUpgrade/DistUpgradeController.py:1445
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bug report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1461
msgid "Getting upgrade prerequisites failed"
msgstr "Ekki tókst að útvega forsendu uppfærslna"

#: ../DistUpgrade/DistUpgradeController.py:1462
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bug report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1492
msgid "Updating repository information"
msgstr "Uppfæri útibúa upplýsingar"

#: ../DistUpgrade/DistUpgradeController.py:1517
msgid "Invalid package information"
msgstr "Ógildar pakkaupplýsingar"

#: ../DistUpgrade/DistUpgradeController.py:1518
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1535
#: ../DistUpgrade/DistUpgradeController.py:1583
msgid "Fetching"
msgstr "Sæki"

#: ../DistUpgrade/DistUpgradeController.py:1542
#: ../DistUpgrade/DistUpgradeController.py:1587
msgid "Upgrading"
msgstr "Uppfæri"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1547
#: ../DistUpgrade/DistUpgradeController.py:1589
#: ../DistUpgrade/DistUpgradeController.py:1596
#: ../DistUpgrade/DistUpgradeController.py:1601
msgid "Upgrade complete"
msgstr "Uppfærslu lokið"

#: ../DistUpgrade/DistUpgradeController.py:1548
#: ../DistUpgrade/DistUpgradeController.py:1590
#: ../DistUpgrade/DistUpgradeController.py:1597
msgid ""
"The upgrade is completed but there were errors during the upgrade process."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1555
msgid "Searching for obsolete software"
msgstr "Leita að úreltum hugbúnaði"

#: ../DistUpgrade/DistUpgradeController.py:1560
msgid "System upgrade is complete."
msgstr "Uppfærslu á stýrikerfi lokið"

#: ../DistUpgrade/DistUpgradeController.py:1602
msgid "The partial upgrade was completed."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:166
#: ../DistUpgrade/DistUpgradeQuirks.py:235
#: ../DistUpgrade/DistUpgradeQuirks.py:260
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:170
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 9.04.\n"
"\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:239
#: ../DistUpgrade/DistUpgradeQuirks.py:264
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 8.10.\n"
"\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:434
msgid "evms in use"
msgstr "evms í notkun"

#: ../DistUpgrade/DistUpgradeQuirks.py:435
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:38
msgid "Sandbox upgrade using aufs"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:40
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:46
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:49
msgid "*DEPRECATED* this option will be ignore"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:52
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:54
msgid "Set datadir"
msgstr ""

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:108
#: ../DistUpgrade/DistUpgradeViewKDE.py:190
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Settu ‚%s‘ í drif ‚%s‘"

#: ../DistUpgrade/DistUpgradeViewGtk.py:127
#: ../DistUpgrade/DistUpgradeViewKDE.py:203
msgid "Fetching is complete"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:139
#: ../DistUpgrade/DistUpgradeViewKDE.py:216
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:140
#: ../DistUpgrade/DistUpgradeViewGtk.py:275
#: ../DistUpgrade/DistUpgradeViewKDE.py:217
#: ../DistUpgrade/DistUpgradeViewKDE.py:357
#, python-format
msgid "About %s remaining"
msgstr "Um það bil %s eftir"

#: ../DistUpgrade/DistUpgradeViewGtk.py:142
#: ../DistUpgrade/DistUpgradeViewKDE.py:219
#, python-format
msgid "Fetching file %li of %li"
msgstr "Sæki skrá %li af %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:174
#: ../DistUpgrade/DistUpgradeViewKDE.py:253
msgid "Applying changes"
msgstr "Sett inn breytingar"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:199
#: ../DistUpgrade/DistUpgradeViewKDE.py:266
msgid "dependency problems - leaving unconfigured"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:204
#: ../DistUpgrade/DistUpgradeViewKDE.py:268
#, python-format
msgid "Could not install '%s'"
msgstr "Gat ekki sett upp '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:205
#: ../DistUpgrade/DistUpgradeViewKDE.py:269
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may be in a not working "
"state. Please consider submitting a bug report about it."
msgstr ""

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:221
#: ../DistUpgrade/DistUpgradeViewKDE.py:290
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:222
#: ../DistUpgrade/DistUpgradeViewKDE.py:291
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"Þú munt tapa öllum breytingum sem þú hefur gert við þessa samskipunarskrá ef "
"þú ákveður að skipta henni út með nýrri útgáfu."

#: ../DistUpgrade/DistUpgradeViewGtk.py:235
#: ../DistUpgrade/DistUpgradeViewKDE.py:309
msgid "The 'diff' command was not found"
msgstr "'diff' skipunin fannst ekki"

#: ../DistUpgrade/DistUpgradeViewGtk.py:417
#: ../DistUpgrade/DistUpgradeViewText.py:107
msgid "A fatal error occurred"
msgstr "Það kom upp grafalvarleg villa"

#: ../DistUpgrade/DistUpgradeViewGtk.py:418
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade is now aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:433
msgid "Ctrl-c pressed"
msgstr "Ýtt á ctrl-c"

#: ../DistUpgrade/DistUpgradeViewGtk.py:434
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Þetta mun stöðva aðgerðina og skilja kerfið eftir bilað. Ertu viss um að þú "
"viljir halda áfram?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:570
msgid "To prevent data loss close all open applications and documents."
msgstr "Til að fyrirbyggja tap á gögnum skaltu loka öllum forritum og skrám"

#: ../DistUpgrade/DistUpgradeViewGtk.py:584
#, python-format
msgid "<b>Downgrade %s</b>"
msgstr "<b>Lækka %s</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:586
#: ../DistUpgrade/DistUpgradeViewKDE.py:750
#, python-format
msgid "Remove %s"
msgstr "Fjarlægja %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:591
#: ../DistUpgrade/DistUpgradeViewKDE.py:752
#, python-format
msgid "Install %s"
msgstr "Uppsetning á %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:593
#: ../DistUpgrade/DistUpgradeViewKDE.py:754
#, python-format
msgid "Upgrade %s"
msgstr "Uppfæri %s"

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:191
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Media Change"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:321
msgid "Show Difference >>>"
msgstr "Sýna mismun >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:324
msgid "<<< Hide Difference"
msgstr "<<< Fela mismun"

#: ../DistUpgrade/DistUpgradeViewKDE.py:531
msgid "Error"
msgstr "Villa"

#: ../DistUpgrade/DistUpgradeViewKDE.py:543
msgid "&Cancel"
msgstr "&Hætta við"

#: ../DistUpgrade/DistUpgradeViewKDE.py:545
#: ../DistUpgrade/DistUpgradeViewKDE.py:782
msgid "&Close"
msgstr "&Loka"

#: ../DistUpgrade/DistUpgradeViewKDE.py:591
msgid "Show Terminal >>>"
msgstr "Sýna Útstöð >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:594
msgid "<<< Hide Terminal"
msgstr "<<< Fela Útstöð"

#: ../DistUpgrade/DistUpgradeViewKDE.py:674
msgid "Information"
msgstr "Upplýsingar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:724
#: ../DistUpgrade/DistUpgradeViewKDE.py:765
#: ../DistUpgrade/DistUpgradeViewKDE.py:768
#: ../DistUpgrade/DistUpgrade.glade.h:9
msgid "Details"
msgstr "Nánar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:778
#: ../DistUpgrade/DistUpgradeViewText.py:225
msgid "Restart required"
msgstr "Þú þarft að endurræsa tölvuna"

#: ../DistUpgrade/DistUpgradeViewKDE.py:778
#: ../DistUpgrade/DistUpgrade.glade.h:5
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Endurræsa kerfið til að ljúka uppfærslunni</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:781
#: ../DistUpgrade/DistUpgrade.glade.h:23
msgid "_Restart Now"
msgstr "_Endurræsa núna"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:793
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:797
msgid "Cancel Upgrade?"
msgstr "Hætta við uppfærslu?"

#: ../DistUpgrade/DistUpgradeView.py:59
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li dagur"
msgstr[1] "%li dagar"

#: ../DistUpgrade/DistUpgradeView.py:61
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li klukkutími"
msgstr[1] "%li klukkutímar"

#: ../DistUpgrade/DistUpgradeView.py:63
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li mínúta"
msgstr[1] "%li mínútur"

#: ../DistUpgrade/DistUpgradeView.py:64
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li sekúnda"
msgstr[1] "%li sekúndur"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:77
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:92
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:113
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:117
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "Þetta niðurhal mun taka um %s með þinni tengingu. "

#: ../DistUpgrade/DistUpgradeView.py:207 ../DistUpgrade/DistUpgrade.glade.h:14
msgid "Preparing to upgrade"
msgstr "Undirbý að uppfæra"

#: ../DistUpgrade/DistUpgradeView.py:208
msgid "Getting new software channels"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:209 ../DistUpgrade/DistUpgrade.glade.h:12
msgid "Getting new packages"
msgstr "Sæki nýja pakka"

#: ../DistUpgrade/DistUpgradeView.py:210 ../DistUpgrade/DistUpgrade.glade.h:13
msgid "Installing the upgrades"
msgstr "Set upp uppfærslurnar"

#: ../DistUpgrade/DistUpgradeView.py:211 ../DistUpgrade/DistUpgrade.glade.h:8
msgid "Cleaning up"
msgstr "Hreinsa til"

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:284
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d pakki mun vera fjarlægður."
msgstr[1] "%d pakkar munu vera fjarlægðir."

#: ../DistUpgrade/DistUpgradeView.py:289
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d nýr pakki mun vera uppsettur."
msgstr[1] "%d nýir pakkar munu vera uppsettir."

#: ../DistUpgrade/DistUpgradeView.py:295
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d pakki mun vera uppfærður."
msgstr[1] "%d pakkar munu vera uppfærðir."

#: ../DistUpgrade/DistUpgradeView.py:300
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Þú þarft að niðurhala samtals %s. "

#: ../DistUpgrade/DistUpgradeView.py:304
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be cancelled."
msgstr ""
"Það að sækja uppfærsluna gæti tekið nokkra tíma. Ekki er hægt að hætta við "
"þegar niðurhalinu er lokið."

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:310 ../UpdateManager/UpdateManager.py:456
msgid "Your system is up-to-date"
msgstr "Kerfið þitt er af nýjustu gerð"

#: ../DistUpgrade/DistUpgradeView.py:311
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"Það eru engar uppfærslur fáanlega fyrir kerfið þitt. Uppfærslu verður nú hætt"

#: ../DistUpgrade/DistUpgradeView.py:324
msgid "Reboot required"
msgstr "Endurræsing nauðsynleg"

#: ../DistUpgrade/DistUpgradeView.py:325
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"Uppfærslu er lokið og endurræsing er nauðsynleg. Vilt þú gera svo nú?"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:134
#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:134
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
msgid "Could not run the upgrade tool"
msgstr "Gat ekki keyrt uppfærslu tólið"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""
"Það er sennilega villa í uppfærslutólinu. Vinamelgast tilkynntu það sem "
"villu."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:204
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:204
msgid "Upgrade tool signature"
msgstr "Auðkenni uppfærslutóls"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:207
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:207
msgid "Upgrade tool"
msgstr "Uppfærslutól"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:237
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:237
msgid "Failed to fetch"
msgstr "Mistókst að sækja"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:238
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""
"Það mistókst að sækja uppfærsluna. Það gæti verið vandamál með netið. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:242
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:242
msgid "Failed to extract"
msgstr "Mistókst að draga upplýsingar út"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:243
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Það mistókst að draga upplýsingar um uppfærlsuna út.  Það gæti verið "
"vandamál með netið eða með þjóninn. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:248
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:248
msgid "Verfication failed"
msgstr "Sannprófun mistókst"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:249
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Sannprófun á uppfærslunni mistókst. Það gæti verið vandamál með netið eða "
"með þjóninn. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:254
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:254
msgid "Authentication failed"
msgstr "Staðfesting aðkenna mistókst"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:255
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Það mistókst að staðfesta auðkenni uppfærslunar. Það gæti verið vandamál með "
"netið eða með þjóninn. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:263
#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:263
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:269
msgid "Can not run the upgrade"
msgstr "Get ekki keyrt uppfærsluna"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:264
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:264
msgid ""
"This usually is caused by a system were /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:270
#, python-format
msgid "The error message is '%s'."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:108
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade is now aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:132
msgid "Aborting"
msgstr "Hætti við..."

#: ../DistUpgrade/DistUpgradeViewText.py:137
msgid "Demoted:\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:169
#: ../DistUpgrade/DistUpgradeViewText.py:191
#: ../DistUpgrade/DistUpgradeViewText.py:198
msgid "Continue [yN] "
msgstr "Halda áfram [yN] "

#: ../DistUpgrade/DistUpgradeViewText.py:169
#: ../DistUpgrade/DistUpgradeViewText.py:191
msgid "Details [d]"
msgstr "Upplýsingar [u]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:173
#: ../DistUpgrade/DistUpgradeViewText.py:201
msgid "y"
msgstr "j"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:176
#: ../DistUpgrade/DistUpgradeViewText.py:208
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:179
msgid "d"
msgstr "u"

#: ../DistUpgrade/DistUpgradeViewText.py:183
#, python-format
msgid "Remove: %s\n"
msgstr "Fjarlægja: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:186
#, python-format
msgid "Install: %s\n"
msgstr "Setja upp: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:189
#, python-format
msgid "Upgrade: %s\n"
msgstr "Uppfæra: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:205
msgid "Continue [Yn] "
msgstr "Halda áfram [Yn] "

#: ../DistUpgrade/DistUpgradeViewText.py:226
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Þú þarft að endurræsa tölvuna til að ljúka uppfærslunni.\n"
"Ef þú velur ‚y‘ mun hún endurræsa sig."

#: ../DistUpgrade/DistUpgrade.glade.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.glade.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>Hætta við uppfærslu sem er þegar hafin?</big></b>\n"
"\n"
"Kerfið gæti orðið ónothæft ef þú hættir við uppfærlsuna. Það er sterklega "
"mælt með að þú haldir áfram með uppfærsluna."

#: ../DistUpgrade/DistUpgrade.glade.h:6
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Byrja á uppfærslunni?</big></b>"

#: ../DistUpgrade/DistUpgrade.glade.h:7
msgid "<b><big>Upgrading Ubuntu to version 9.04</big></b>"
msgstr "<b><big>Uppfæri upp í Ubuntu 9.04</big></b>"

#: ../DistUpgrade/DistUpgrade.glade.h:10
msgid "Difference between the files"
msgstr "Munur milli skránna"

#: ../DistUpgrade/DistUpgrade.glade.h:11
msgid "Distribution Upgrade"
msgstr "Uppfæra kerfið"

#: ../DistUpgrade/DistUpgrade.glade.h:15
msgid "Restarting the computer"
msgstr "Endurræsi tölvuna"

#: ../DistUpgrade/DistUpgrade.glade.h:16
msgid "Setting new software channels"
msgstr "Ákveð nýjar hugbúnaðarrásir"

#: ../DistUpgrade/DistUpgrade.glade.h:17
msgid "Terminal"
msgstr "Útstöð"

#: ../DistUpgrade/DistUpgrade.glade.h:18
msgid "_Cancel Upgrade"
msgstr "_Hætta við"

#: ../DistUpgrade/DistUpgrade.glade.h:19
msgid "_Continue"
msgstr "_Halda áfram"

#: ../DistUpgrade/DistUpgrade.glade.h:21
msgid "_Replace"
msgstr "_Skipta út"

#: ../DistUpgrade/DistUpgrade.glade.h:22
msgid "_Report Bug"
msgstr "_Tilkynna Villu"

#: ../DistUpgrade/DistUpgrade.glade.h:24
msgid "_Resume Upgrade"
msgstr "Hefja _aftur uppfærslu"

#: ../DistUpgrade/DistUpgrade.glade.h:25
msgid "_Start Upgrade"
msgstr "_Byrja að uppfæra"

#: ../UpdateManager/DistUpgradeFetcher.py:85
#: ../UpdateManager/DistUpgradeFetcherKDE.py:103
msgid "Could not find the release notes"
msgstr "Fann ekki upplýsingar um útgáfu"

#: ../UpdateManager/DistUpgradeFetcher.py:86
#: ../UpdateManager/DistUpgradeFetcherKDE.py:104
msgid "The server may be overloaded. "
msgstr "Þjóninn gæti verið með yfirálag "

#: ../UpdateManager/DistUpgradeFetcher.py:96
#: ../UpdateManager/DistUpgradeFetcherKDE.py:108
msgid "Could not download the release notes"
msgstr "Gat ekki halað niður upplýsingum um útgáfu"

#: ../UpdateManager/DistUpgradeFetcher.py:97
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Please check your internet connection."
msgstr "Athugaðu með nettenginguna þína"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:62
#: ../UpdateManager/DistUpgradeFetcherKDE.py:85
msgid "Upgrade"
msgstr "Uppfæra"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:89
#: ../data/glade/UpdateManager.glade.h:11
msgid "Release Notes"
msgstr "Útgáfu upplýsingar"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:128
#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
msgid "Downloading additional package files..."
msgstr "Hleð niður aukapökkum..."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Skrá %s af %s á %sB/sek"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
#, python-format
msgid "File %s of %s"
msgstr "Skrá %s af %s"

#: ../UpdateManager/ChangelogViewer.py:70
msgid "Open Link in Browser"
msgstr ""

#: ../UpdateManager/ChangelogViewer.py:72
msgid "Copy Link to Clipboard"
msgstr ""

#: ../UpdateManager/GtkProgress.py:111
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Hleð niður skrá %(current)li af %(total)li með %(speed)s/s"

#: ../UpdateManager/GtkProgress.py:116
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Hleð niður skrá %(current)li af %(total)li"

#: ../UpdateManager/UpdateManager.py:274
#, python-format
msgid "Version %s: \n"
msgstr "Útgáfa %s: \n"

#: ../UpdateManager/UpdateManager.py:335
msgid "Downloading list of changes..."
msgstr "Sækja lista yfir breytingar..."

#: ../UpdateManager/UpdateManager.py:367
msgid "_Uncheck All"
msgstr "_Afvelja allt"

#: ../UpdateManager/UpdateManager.py:373
msgid "_Check All"
msgstr "_Velja allt"

#. TRANSLATORS: b stands for Bytes
#: ../UpdateManager/UpdateManager.py:417 ../UpdateManager/UpdateManager.py:477
#, python-format
msgid "Download size: %s"
msgstr "Stærð niðurhals: %s"

#: ../UpdateManager/UpdateManager.py:421
msgid "Unknown download size"
msgstr "Óþekkt stærð niðurhals"

#: ../UpdateManager/UpdateManager.py:429
msgid ""
"It is unknown when the package information was updated last. Please try "
"clicking on the 'Check' button to update the information."
msgstr ""

#: ../UpdateManager/UpdateManager.py:438
#, python-format
msgid "The package information was last updated %s day ago."
msgid_plural "The package information was last updated %s days ago."
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:442
#, python-format
msgid "The package information was last updated %s hour ago."
msgid_plural "The package information was last updated %s hours ago."
msgstr[0] "Upplýsingar um þennan pakka voru uppfærðar fyrir %s tíma."
msgstr[1] "Upplýsingar um þennan pakka voru uppfærðar fyrir %s tímum."

#: ../UpdateManager/UpdateManager.py:446
msgid "The package information was last updated less than one hour ago."
msgstr ""
"Pakkaupplýsingarnar voru seinast uppfærðar fyrir minna en klst síðan."

#: ../UpdateManager/UpdateManager.py:454
#: ../data/glade/UpdateManager.glade.h:21
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""
"Hugbúnaðauppfærslur leiðrétta villur, lagfæra öryggisveilur og innleiða nýja "
"möguleika."

#: ../UpdateManager/UpdateManager.py:471
msgid "Welcome to Ubuntu"
msgstr "Velkomin til Ubuntu"

#: ../UpdateManager/UpdateManager.py:472
msgid ""
"These software updates have been issued since Ubuntu was released. If you "
"don't want to install them now, choose \"Update Manager\" from the "
"Administration Menu later."
msgstr ""
"Þessar uppfærslur voru gefnar út eftir að Ubuntu var gefið út. Ef þú vilt "
"ekki setja þær upp núna getur þú farið í ‚Uppfærslustjórann‘ í "
"aðalvalmyndinni (undir ‚Stjórnun‘) síðar."

#: ../UpdateManager/UpdateManager.py:475
msgid "Software updates are available for this computer"
msgstr "Hugbúnaðaruppfærslur eru tiltækar fyrir þessa tölvu"

#: ../UpdateManager/UpdateManager.py:476
msgid ""
"If you don't want to install them now, choose \"Update Manager\" from the "
"Administration menu later."
msgstr ""
"Þú getur farið í „Uppfærslustjórann“ í stjórnunarvalmyndinni seinna ef þú "
"vilt ekki setja þær upp núna."

#: ../UpdateManager/UpdateManager.py:515
msgid "Please wait, this can take some time."
msgstr "Hinkraðu augnablik, þetta gæti tekið drjúga stund."

#: ../UpdateManager/UpdateManager.py:517
msgid "Update is complete"
msgstr "Uppfærslu er lokið"

#: ../UpdateManager/UpdateManager.py:564
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""
"Uppfærslan krefst %s af plássa á diskinum ‚%s‘. Reyndu að rýma til alla "
"vegana %s af plássi á ‚%s‘. Prufaðu að tæma ruslið og að fjarlægja "
"bráðabirgðapakka sem gamlar uppsetningar skildu eftir sig með því að skrifa "
"‚sudo apt-get clean‘ í útstöðina."

#: ../UpdateManager/UpdateManager.py:603
#: ../UpdateManagerHildon/UpdateManagerHildon.py:114
msgid "Reading package information"
msgstr "Les pakkaupplýsingar"

#: ../UpdateManager/UpdateManager.py:705
msgid "Could not initialize the package information"
msgstr ""

#: ../UpdateManager/UpdateManager.py:706
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:728
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:753
#, python-format
msgid "(Size: %s)"
msgstr "(Stærð: %s)"

#: ../UpdateManager/UpdateManager.py:755
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr "Frá útgáfu %(old_version)s upp í %(new_version)s"

#: ../UpdateManager/UpdateManager.py:759
#, python-format
msgid "Version %s"
msgstr "Útgáfa %s"

#: ../UpdateManager/UpdateManager.py:772
msgid "Your distribution is not supported anymore"
msgstr "Dreifingin þin er ekki studd lengur"

#: ../UpdateManager/UpdateManager.py:773
msgid ""
"You will not get any further security fixes or critical updates. Upgrade to "
"a later version of Ubuntu Linux. See http://www.ubuntu.com for more "
"information on upgrading."
msgstr ""
"Þú færð ekki fleiri öryggislagfæringar eða mikilvægar dagréttingar. Þú ættir "
"að uppfæra í nýrri útgáfu af  Ubuntu Linux. Sjá http://www.ubuntu.com fyrir "
"nánari upplýsingar um uppfærslur."

#: ../UpdateManager/UpdateManager.py:805
#, python-format
msgid "<b>New distribution release '%s' is available</b>"
msgstr "<b>Ný útgáfa dreifngarinnar ,%s' er tiltæk</b>"

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:844
msgid "Software index is broken"
msgstr "Hugbúnaðarvísir er bilaður"

#: ../UpdateManager/UpdateManager.py:845
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""
"Það er ómögulegt að setja upp eða fjarlægja nokkurn hugbúnað. Vinsamlegast "
"notaðu pakkastjórann „Synaptic‟ eða keyrðu skipunina „sudo apt-get install -"
"f‟ í skjáhermi til að laga þetta vandamál fyrst."

#: ../UpdateManagerHildon/UpdateManagerHildon.py:136
msgid "Downloading Package Information"
msgstr "Hleð niður pakkaupplýsingum"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:137
msgid ""
"The repositories are being checked for new, removed, or updated software "
"packages"
msgstr ""

#: ../UpdateManagerHildon/UpdateManagerHildon.py:145
msgid "Downloading Package Updates"
msgstr "Sæki pakkaupplýsingar"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:146
msgid ""
"The selected package updates are being downloaded and installed on the system"
msgstr "Verið er að sækja og setja upp þær pakkaupplýsingar sem þú valdir"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:152
msgid "run_synaptic called with unknown action"
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:26
msgid "Cancel"
msgstr "Hætta við"

#: ../UpdateManagerText/UpdateManagerText.py:27
msgid "Install"
msgstr "Setja upp"

#: ../UpdateManagerText/UpdateManagerText.py:45
msgid "Building Updates List"
msgstr "Bý til lista yfir uppfærslur"

#: ../UpdateManagerText/UpdateManagerText.py:48
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" ◦ A previous upgrade which didn't complete\n"
" ◦ Problems with some of the installed software\n"
" ◦ Unofficial software packages not provided by Ubuntu\n"
" ◦ Normal changes of a pre-release version of Ubuntu"
msgstr ""
"\n"
"Ekki var mögulegt að reikna venjulega uppfærslu, vinsamlegast keyrið: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"Örsakavaldur getur verið eftirfarandi:\n"
" ◦ Fyrri uppfærsla kláraði sig ekki sem skildi\n"
" ◦ Vandamál í einhverjum uppsettum hugbúnaði\n"
" ◦ Óformlegir hugbúnaðarpakkar sem ekki er á vegum Ubuntu\n"
" ◦ Venjubundnar breytingar á prufu útgáfu Ubuntu"

#: ../UpdateManagerText/UpdateManagerText.py:117
msgid "Downloading changelog"
msgstr "Sæki breytingarskrá"

#. FIXME: better string, but we are in string freeze
#: ../UpdateManager/Core/MyCache.py:221 ../UpdateManager/Core/UpdateList.py:47
msgid "Failed to detect distribution"
msgstr ""

#: ../UpdateManager/Core/MyCache.py:228
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:233
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:239
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:48
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr "Villan ‚%s‘ kom upp við að kanna hvaða kerfi þú notar."

#: ../UpdateManager/Core/UpdateList.py:59
msgid "Important security updates"
msgstr "Mikilvægar öryggisuppfærslur"

#: ../UpdateManager/Core/UpdateList.py:60
msgid "Recommended updates"
msgstr "Uppfærslur sem mælt er með"

#: ../UpdateManager/Core/UpdateList.py:61
msgid "Proposed updates"
msgstr "Uppástunga að uppfærslum"

#: ../UpdateManager/Core/UpdateList.py:62
msgid "Backports"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:63
msgid "Distribution updates"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:68
msgid "Other updates"
msgstr "Aðrar uppfærslur"

#: ../UpdateManager/Core/UpdateList.py:77
msgid "Previous selected"
msgstr "Áður valið"

#: ../data/glade/UpdateManager.glade.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""

#: ../data/glade/UpdateManager.glade.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr "<big><b>Ekki var hægt að setja upp allar uppfærslurnar</b></big>"

#: ../data/glade/UpdateManager.glade.h:5
msgid "<big><b>Starting Update Manager</b></big>"
msgstr "d"

#: ../data/glade/UpdateManager.glade.h:6
msgid "Changes"
msgstr "Breytingar"

#: ../data/glade/UpdateManager.glade.h:7
msgid "Chec_k"
msgstr "_Kanna"

#: ../data/glade/UpdateManager.glade.h:8
msgid "Check the software channels for new updates"
msgstr "Kanna hvort nýjar dagréttingar finnast hugbúnaðarrásum"

#: ../data/glade/UpdateManager.glade.h:9
msgid "Description"
msgstr "Lýsing"

#: ../data/glade/UpdateManager.glade.h:10
msgid "Description of update"
msgstr "Lýsing"

#: ../data/glade/UpdateManager.glade.h:12
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" ◦ A previous upgrade which didn't complete\n"
" ◦ Problems with some of the installed software\n"
" ◦ Unofficial software packages not provided by Ubuntu\n"
" ◦ Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:19
msgid "Settings…"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:20
msgid "Show progress of individual files"
msgstr "Sjá hvernig einstaka skrám gengur"

#: ../data/glade/UpdateManager.glade.h:22
msgid "U_pgrade"
msgstr "U_ppfæra"

#: ../data/glade/UpdateManager.glade.h:23
#: ../data/update-manager.desktop.in.h:3
#: ../data/update-manager-hildon.desktop.in.h:3
msgid "Update Manager"
msgstr "Uppfærslustjóri"

#: ../data/glade/UpdateManager.glade.h:24
msgid "Upgrade to the latest version of Ubuntu"
msgstr "Uppfæra í nýjustu útgáfu af Ubuntu"

#: ../data/glade/UpdateManager.glade.h:25
msgid "_Hide this information in the future"
msgstr "_Fela þessar upplýsingar í framtíðinni"

#: ../data/glade/UpdateManager.glade.h:26
msgid "_Install Updates"
msgstr "_Setja upp uppfærslur"

#: ../data/glade/UpdateManager.glade.h:27
msgid "_Partial Upgrade"
msgstr "_Hlutauppfærsla"

#: ../data/glade/UpdateManager.glade.h:28
msgid "_Upgrade"
msgstr "_Uppfæra"

#: ../data/glade/UpdateManager.glade.h:29
msgid "updates"
msgstr "uppfærslur"

#: ../data/update-manager.desktop.in.h:1
#: ../data/update-manager-hildon.desktop.in.h:1
msgid "Show and install available updates"
msgstr "Sýna og setja upp tiltækar dagréttingar"

#: ../data/update-manager.desktop.in.h:2
#: ../data/update-manager-hildon.desktop.in.h:2
msgid "Software Updates"
msgstr "Hugbúnaðaruppsetningar"

#: ../data/update-manager.schemas.in.h:1
msgid "*deprecated* Check for new distribution releases"
msgstr ""

#: ../data/update-manager.schemas.in.h:2
msgid "Auto close the install window after successful install"
msgstr ""

#: ../data/update-manager.schemas.in.h:3
msgid "First run welcome message"
msgstr ""

#: ../data/update-manager.schemas.in.h:4
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""

#: ../data/update-manager.schemas.in.h:5
msgid "If this key is set a first run welcome message will be presented."
msgstr ""

#: ../data/update-manager.schemas.in.h:6
msgid ""
"If this key is set the install window will be automatically closed on "
"successful installation."
msgstr ""

#: ../data/update-manager.schemas.in.h:7
msgid ""
"If this key is set the main update list window will show version information "
"(from version to version)."
msgstr ""

#: ../data/update-manager.schemas.in.h:8
msgid "Remind to reload the channel list"
msgstr "Minna á að endurhlaða rásalista"

#: ../data/update-manager.schemas.in.h:9
msgid "Show details of an update"
msgstr "Birta smáatriði uppfærslna"

#: ../data/update-manager.schemas.in.h:10
msgid "Show version in update list"
msgstr ""

#: ../data/update-manager.schemas.in.h:11
msgid "Stores the size of the update-manager dialog"
msgstr "Geymir stærð svarglugga dagréttingastjóra"

#: ../data/update-manager.schemas.in.h:12
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr ""

#: ../data/update-manager.schemas.in.h:13
msgid "The window size"
msgstr "Gluggastærð"

#: ../data/update-manager.schemas.in.h:14
msgid ""
"This key is deprecated in favor of the file /etc/update-manager/release-"
"upgrades Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""

#: ../update-manager:55
msgid "Show version and exit"
msgstr "Sýna útgáfu og hætta"

#: ../update-manager:58
msgid "Check if a new distribution release is available"
msgstr ""

#: ../update-manager:61 ../do-release-upgrade:23 ../check-new-release:24
msgid "Check if upgrading to the latest devel release is possible"
msgstr ""

#: ../update-manager:65
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""

#: ../update-manager:72
msgid "Do not focus on map when starting"
msgstr ""

#: ../update-manager:75
msgid "Try to run a dist-upgrade"
msgstr "Reyndu að keyra drefingaruppfærslu"

#: ../update-manager:79 ../do-release-upgrade:39
msgid "Test upgrade with a sandbox aufs overlay"
msgstr ""

#: ../update-manager:98
msgid "Running partial upgrade"
msgstr ""

#: ../do-release-upgrade:27 ../check-new-release:28
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""

#: ../do-release-upgrade:31
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""

#: ../do-release-upgrade:37
msgid "Run the specified frontend"
msgstr ""

#: ../do-release-upgrade:43
msgid "Checking for a new ubuntu release"
msgstr "Leita að nýrri Ubuntu útgáfu"

#: ../do-release-upgrade:50
msgid "No new release found"
msgstr "Ekki fundust nýjar útgáfur"

#: ../check-new-release:32
#, c-format
msgid ""
"Do not output anything, just return %s if there is a new release and %s if "
"there is none."
msgstr ""

#: ../check-new-release:46
#, c-format
msgid "New release '%s' available."
msgstr ""

#: ../check-new-release:47
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr ""

#: ../Janitor/computerjanitor/exc.py:30
#, python-format
msgid "Unimplemented method: %s"
msgstr "Aðferð sem er ekki notuð: %s"

#: ../Janitor/computerjanitor/file_cruft.py:46
msgid "A file on disk"
msgstr "Skrá á diski"

#: ../Janitor/computerjanitor/package_cruft.py:45
msgid ".deb package"
msgstr ".deb pakki"

#: ../Janitor/computerjanitor/missing_package_cruft.py:33
msgid "Install missing package."
msgstr ""

#: ../Janitor/computerjanitor/missing_package_cruft.py:42
#, python-format
msgid "Package %s should be installed."
msgstr ""

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:36
#, python-format
msgid "%i obsolete entries in the status file"
msgstr ""

#: ../Janitor/plugins/dpkg_status_plugin.py:39
msgid "Obsolete entries in dpkg status"
msgstr ""

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:42
msgid "Obsolete dpkg status entries"
msgstr ""

#: ../Janitor/plugins/kdelibs4to5_plugin.py:39
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug ##279621 for details."
msgstr ""

#: ../Janitor/plugins/langpack_manual_plugin.py:34
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr ""

#: ../Janitor/plugins/remove_lilo_plugin.py:28
msgid ""
"Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr ""

#~ msgid "The upgrade tool will guide you through the upgrade process."
#~ msgstr "Uppfærslutólið mun hjálpa þér í gegnum uppfærlsuferlið."

#~ msgid "Can't upgrade required meta-packages"
#~ msgstr "Get ekki uppfært nauðsynlega lýsi-pakka"

#~ msgid "A essential package would have to be removed"
#~ msgstr "Fjarlægja yrði nauðsynlegan pakka"

#~ msgid ""
#~ "The upgrade is completed but there were errors during the ugprade process."
#~ msgstr "Uppfærslu lokið, en það komu upp villur við uppfærsluna."

#, python-format
#~ msgid ""
#~ "This download will take about %s with a 1Mbit DSL connection and about %s "
#~ "with a 56k modem"
#~ msgstr ""
#~ "Þetta niðurhal mun taka um %s á 1Mbit DSL tenginu og um %s á innhringi "
#~ "tengingu"

#~ msgid "Downloading the upgrade tool"
#~ msgstr "Hala niður uppfærslutólinu"

#~ msgid "Fetching file %li of %li at %sb/s"
#~ msgstr "Sæki skrá %li af %li hjá %sb/s"

#~ msgid "%li days %li hours %li minutes"
#~ msgstr "%li dagar %li klukkustundir %li mínútur"

#~ msgid "_Check"
#~ msgstr "_Athuga"

#~ msgid "_Skip This Step"
#~ msgstr "_Sleppa þessu skrefi"
