# Icelandic translation for update-manager
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the update-manager package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2008-03-22 22:49+0100\n"
"PO-Revision-Date: 2007-06-13 21:04+0000\n"
"Last-Translator: Tómas Árnason <arnason@samlokan.sytes.net>\n"
"Language-Team: Icelandic <is@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2007-09-24 08:45+0000\n"
"X-Generator: Launchpad (build Unknown)\n"

#. TRANSLATORS: download size is 0
#: ../DistUpgrade/utils.py:83 ../UpdateManager/Common/utils.py:83
msgid "0 KB"
msgstr ""

#. TRANSLATORS: download size of very small updates
#: ../DistUpgrade/utils.py:86 ../UpdateManager/Common/utils.py:86
msgid "1 KB"
msgstr ""

#. TRANSLATORS: download size of small updates, e.g. "250 KB"
#: ../DistUpgrade/utils.py:89 ../UpdateManager/Common/utils.py:89
#, python-format
msgid "%.0f KB"
msgstr ""

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:92 ../UpdateManager/Common/utils.py:92
#, python-format
msgid "%.1f MB"
msgstr ""

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:194 ../DistUpgrade/distro.py:401
#, python-format
msgid "Server for %s"
msgstr ""

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:213 ../DistUpgrade/distro.py:218
#: ../DistUpgrade/distro.py:232
msgid "Main server"
msgstr ""

#: ../DistUpgrade/distro.py:235
msgid "Custom servers"
msgstr ""

#: ../DistUpgrade/dist-upgrade.py:15
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr ""

#: ../DistUpgrade/dist-upgrade.py:21
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""

#: ../DistUpgrade/dist-upgrade.py:24
msgid ""
"Use special upgrade mode. Available:\n"
"desktop, server"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:73
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeCache.py:76
#, python-format
msgid ""
"The package '%s' is in a inconsistent state and needs to be reinstalled, but "
"no archive can be found for it. Do you want to remove this package now to "
"continue?"
msgid_plural ""
"The packages '%s' is in a inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeCache.py:241
msgid "Broken packages"
msgstr "Villa í sóttu efni"

#: ../DistUpgrade/DistUpgradeCache.py:242
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:570
msgid "Can't upgrade required meta-packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:574
msgid "A essential package would have to be removed"
msgstr ""

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:581
msgid ""
"A unresolvable problem occurred while calculating the upgrade.\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:591
msgid "This is most likely a transient problem, please try again later."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:594
msgid ""
"If none of this applies, then please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the "
"bugreport."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:599
#: ../UpdateManager/UpdateManager.py:894
msgid "Could not calculate the upgrade"
msgstr ""

#. FIXME: maybe ask a question here? instead of failing?
#: ../DistUpgrade/DistUpgradeCache.py:641
msgid "Error authenticating some packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:642
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:745
#, python-format
msgid "Can't install '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:746
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:753
msgid "Can't guess meta-package"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:754
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:92
msgid "Failed to add the CD"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:93
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:125
msgid "Reading cache"
msgstr "Les flýtimynni"

#: ../DistUpgrade/DistUpgradeController.py:201
msgid "Unable to get exclusive lock"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:202
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:222
msgid "Continue running under SSH?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:223
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, a additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:238
msgid "Starting additional sshd"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:239
#, python-format
msgid ""
"To make recovery in case of failure easier a additional sshd will be started "
"on port '%s'. If anything goes wrong with the running ssh you can still "
"connect to the additional one.\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:303
#: ../DistUpgrade/DistUpgradeController.py:326
msgid "Can not upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:304
#, python-format
msgid "A upgrade from '%s' to '%s' is not supported with this tool."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:327
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:346
msgid "Include latest updates from the Internet?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:347
msgid ""
"The upgrade process can automatically download the latest updates and "
"install them during the upgrade.  The upgrade will take longer, but when it "
"is complete, your system will be fully up to date.  You can choose not to do "
"this, but you should install the latest updates soon after upgrading."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:487
msgid "No valid mirror found"
msgstr "Enginn netþjónn fannst"

#: ../DistUpgrade/DistUpgradeController.py:488
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found.This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'no' the update will cancel."
msgstr ""

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:508
msgid "Generate default sources?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:509
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No' the update will "
"cancel."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:543
msgid "Repository information invalid"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:544
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:550
msgid "Third party sources disabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:551
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:585
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeController.py:588
#, python-format
msgid ""
"The package '%s' is in a inconsistent state and needs to be reinstalled, but "
"no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' is in a inconsistent state and needs to be reinstalled, "
"but no archive can be found for it.Please reinstall the packages manually or "
"remove them from the system."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeController.py:632
msgid "Error during update"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:633
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:642
msgid "Not enough free disk space"
msgstr "Ekki nóg pláss á disk"

#: ../DistUpgrade/DistUpgradeController.py:643
#, python-format
msgid ""
"The upgrade aborts now. The upgrade needs a total of %s free space on disk '%"
"s'. Please free at least an additional %s of disk space on '%s'. Empty your "
"trash and remove temporary packages of former installations using 'sudo apt-"
"get clean'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:754
#, fuzzy
msgid "Support for some applications ended"
msgstr "Stuðningur fyrir sum forrit er farinn"

#: ../DistUpgrade/DistUpgradeController.py:755
msgid ""
"Canonical Ltd. no longer provides support for the following software "
"packages. You can still get support from the community.\n"
"\n"
"If you have not enabled community maintained software (universe), these "
"packages will be suggested for removal at the end of the upgrade."
msgstr ""

#. ask the user if he wants to do the changes
#: ../DistUpgrade/DistUpgradeController.py:778
msgid "Do you want to start the upgrade?"
msgstr "Viltu byrja uppfærslu?"

#: ../DistUpgrade/DistUpgradeController.py:842
#: ../DistUpgrade/DistUpgradeController.py:896
msgid "Could not download the upgrades"
msgstr "Gat ekki sótt uppfærslur"

#: ../DistUpgrade/DistUpgradeController.py:843
#: ../DistUpgrade/DistUpgradeController.py:897
msgid ""
"The upgrade aborts now. Please check your internet connection or "
"installation media and try again. "
msgstr ""

#. invoke the frontend now
#: ../DistUpgrade/DistUpgradeController.py:870
msgid ""
"The upgrade aborts now. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:875
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bugreport.\n"
"%s"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:879
msgid "Could not install the upgrades"
msgstr "Gat ekki sett upp uppfærslur"

#: ../DistUpgrade/DistUpgradeController.py:1002
msgid "Remove obsolete packages?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1003
#: ../DistUpgrade/DistUpgrade.glade.h:20
msgid "_Keep"
msgstr "_Geyma"

#: ../DistUpgrade/DistUpgradeController.py:1003
msgid "_Remove"
msgstr "_Fjarlægja"

#: ../DistUpgrade/DistUpgradeController.py:1014
msgid "Error during commit"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1015
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1139
msgid "Restoring original system state"
msgstr "Endurstilli stýrikerfi í upprunalegt form"

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1177
msgid "Required depends is not installed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1178
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr ""

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1400
#: ../DistUpgrade/DistUpgradeController.py:1462
msgid "Checking package manager"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1405
msgid "Preparing the upgrade failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1406
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bugreport."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1421
msgid "Getting upgrade prerequisites failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1422
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bugreport."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1448
msgid "Updating repository information"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1473
msgid "Invalid package information"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1474
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the "
"bugreport."
msgstr ""

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:1485
#, fuzzy
msgid "Calculating the changes"
msgstr "Sæki og set upp uppfærslur"

#: ../DistUpgrade/DistUpgradeController.py:1491 ../update-manager:96
msgid "Fetching"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1501 ../update-manager:100
msgid "Upgrading"
msgstr "Uppfæri"

#: ../DistUpgrade/DistUpgradeController.py:1508
msgid "Searching for obsolete software"
msgstr "Leita að úreltum hugbúnaði"

#: ../DistUpgrade/DistUpgradeController.py:1513
msgid "System upgrade is complete."
msgstr "Uppfærslu á stýrikerfi lokið"

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:108
#: ../DistUpgrade/DistUpgradeViewKDE.py:166
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:127
#: ../DistUpgrade/DistUpgradeViewKDE.py:179
msgid "Fetching is complete"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:139
#: ../DistUpgrade/DistUpgradeViewKDE.py:192
#, python-format
msgid "Fetching file %li of %li at %sb/s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:140
#: ../DistUpgrade/DistUpgradeViewGtk.py:271
#: ../DistUpgrade/DistUpgradeViewKDE.py:193
#: ../DistUpgrade/DistUpgradeViewKDE.py:326
#, python-format
msgid "About %s remaining"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:142
#: ../DistUpgrade/DistUpgradeViewKDE.py:195
#, python-format
msgid "Fetching file %li of %li"
msgstr ""

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:175
#: ../DistUpgrade/DistUpgradeViewKDE.py:230
msgid "Applying changes"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:200
#: ../DistUpgrade/DistUpgradeViewKDE.py:242
#, python-format
msgid "Could not install '%s'"
msgstr "Gat ekki sett upp '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:201
#: ../DistUpgrade/DistUpgradeViewKDE.py:243
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may be in a not working "
"state. Please consider submitting a bugreport about it."
msgstr ""

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:217
#: ../DistUpgrade/DistUpgradeViewKDE.py:261
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:262
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:231
#: ../DistUpgrade/DistUpgradeViewKDE.py:279
msgid "The 'diff' command was not found"
msgstr "'diff' skipunin fannst ekki"

#: ../DistUpgrade/DistUpgradeViewGtk.py:409
#: ../DistUpgrade/DistUpgradeViewText.py:98
msgid "A fatal error occured"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:410
msgid ""
"Please report this as a bug (if you haven't already) and include thefiles /"
"var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade aborts now.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:539
msgid "To prevent data loss close all open applications and documents."
msgstr "Til að fyrirbyggja tap á gögnum skaltu loka öllum forritum og skrám"

#: ../DistUpgrade/DistUpgradeViewGtk.py:553
#, python-format
msgid "<b>Downgrade %s</b>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:555
#: ../DistUpgrade/DistUpgradeViewKDE.py:652
#, python-format
msgid "Remove %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:560
#: ../DistUpgrade/DistUpgradeViewKDE.py:654
#, python-format
msgid "Install %s"
msgstr "Uppsetning á %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:562
#: ../DistUpgrade/DistUpgradeViewKDE.py:656
#, python-format
msgid "Upgrade %s"
msgstr "Uppfæri %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:167
msgid "Media Change"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:291
msgid "Show Difference >>>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:294
msgid "<<< Hide Difference"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:534
msgid "Show Terminal >>>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:537
msgid "<<< Hide Terminal"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:635
#: ../DistUpgrade/DistUpgradeViewKDE.py:665
#: ../DistUpgrade/DistUpgradeViewKDE.py:668
#: ../DistUpgrade/DistUpgrade.glade.h:9
msgid "Details"
msgstr "Nánar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:681
#: ../DistUpgrade/DistUpgrade.glade.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:685
msgid "Cancel Upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:34
#, python-format
msgid "%li days %li hours %li minutes"
msgstr "%li dagar %li klukkustundir %li mínútur"

#: ../DistUpgrade/DistUpgradeView.py:36
#, python-format
msgid "%li hours %li minutes"
msgstr "%li klukkustundir %li mínútur"

#: ../DistUpgrade/DistUpgradeView.py:38
#, python-format
msgid "%li minutes"
msgstr "%li mínútur"

#: ../DistUpgrade/DistUpgradeView.py:39
#, python-format
msgid "%li seconds"
msgstr "%li sekúndur"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:56
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem"
msgstr ""
"Þetta niðurhal mun taka um %s á 1Mbit DSL tenginu og um %s á innhringi "
"tengingu"

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:60
#, fuzzy, python-format
msgid "This download will take about %s with your connection. "
msgstr ""
"Þetta niðurhal mun taka um %s á 1Mbit DSL tenginu og um %s á innhringi "
"tengingu"

#: ../DistUpgrade/DistUpgradeView.py:111 ../DistUpgrade/DistUpgrade.glade.h:14
#, fuzzy
msgid "Preparing to upgrade"
msgstr "Undirbý uppfærslu"

#: ../DistUpgrade/DistUpgradeView.py:112
#, fuzzy
msgid "Getting new software channels"
msgstr "Stilli hugbúnaðarrásir"

#: ../DistUpgrade/DistUpgradeView.py:113 ../DistUpgrade/DistUpgrade.glade.h:12
#, fuzzy
msgid "Getting new packages"
msgstr "Villa í sóttu efni"

#: ../DistUpgrade/DistUpgradeView.py:114 ../DistUpgrade/DistUpgrade.glade.h:13
#, fuzzy
msgid "Installing the upgrades"
msgstr "Sæki og set upp uppfærslur"

#: ../DistUpgrade/DistUpgradeView.py:115 ../DistUpgrade/DistUpgrade.glade.h:8
msgid "Cleaning up"
msgstr "Hreinsa til"

#. FIXME: make those two seperate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:184
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:189
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:195
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:200
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:205
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be cancelled."
msgstr ""

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:211 ../UpdateManager/UpdateManager.py:691
msgid "Your system is up-to-date"
msgstr "Kerfið þitt er af nýjustu gerð"

#: ../DistUpgrade/DistUpgradeView.py:212
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"Það eru engar uppfærslur fáanlega fyrir kerfið þitt. Uppfærslu verður nú hætt"

#: ../DistUpgrade/DistUpgradeView.py:225
msgid "Reboot required"
msgstr "Endurræsing nauðsynleg"

#: ../DistUpgrade/DistUpgradeView.py:226
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr "Uppfærslu er lokið og endurræsing er nauðsynleg. Vilt þú gera svo nú?"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:143
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:143
msgid "Could not run the upgrade tool"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:144
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:144
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:170
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:170
msgid "Upgrade tool signature"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:173
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:173
msgid "Upgrade tool"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:198
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:198
msgid "Failed to fetch"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:199
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:199
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:203
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:203
msgid "Failed to extract"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:204
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:204
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:209
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:209
msgid "Verfication failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:210
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:210
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:215
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:215
msgid "Authentication failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:216
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:216
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:99
msgid ""
"Please report this as a bug and include the files /var/log/dist-upgrade/main."
"log and /var/log/dist-upgrade/apt.log in your report. The upgrade aborts "
"now.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:123
msgid "Aborting"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:128
#, fuzzy
msgid "Demoted:\n"
msgstr "_Fjarlægja"

#: ../DistUpgrade/DistUpgradeViewText.py:148
#: ../DistUpgrade/DistUpgradeViewText.py:172
#, fuzzy
msgid "Continue [yN] "
msgstr "_Halda áfram"

#: ../DistUpgrade/DistUpgradeViewText.py:148
#, fuzzy
msgid "Details [d]"
msgstr "Nánar"

#. TRANSLATORS: the "y" is "yes"
#: ../DistUpgrade/DistUpgradeViewText.py:152
#: ../DistUpgrade/DistUpgradeViewText.py:176
msgid "y"
msgstr ""

#. TRANSLATORS: the "n" is "no"
#: ../DistUpgrade/DistUpgradeViewText.py:155
msgid "n"
msgstr ""

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:158
msgid "d"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:161
#, fuzzy, python-format
msgid "Remove: %s\n"
msgstr "_Fjarlægja"

#: ../DistUpgrade/DistUpgradeViewText.py:163
#, fuzzy, python-format
msgid "Install: %s\n"
msgstr "Uppsetning á %s"

#: ../DistUpgrade/DistUpgradeViewText.py:165
#, fuzzy, python-format
msgid "Upgrade: %s\n"
msgstr "Uppfæri %s"

#: ../DistUpgrade/DistUpgradeViewText.py:181
#, fuzzy
msgid "Restart required"
msgstr "Endurræsing nauðsynleg"

#: ../DistUpgrade/DistUpgradeViewText.py:182
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:186
#, fuzzy
msgid "Restart the system now [yN] "
msgstr "Endurræsi kerfi"

#: ../DistUpgrade/DistUpgrade.glade.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.glade.h:5
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:6
msgid "<b><big>Start the upgrade?</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:7
msgid "<b><big>Upgrading Ubuntu to version 8.04</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:10
msgid "Difference between the files"
msgstr "Munur milli skráa"

#: ../DistUpgrade/DistUpgrade.glade.h:11
msgid "Distribution Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:15
#, fuzzy
msgid "Restarting the computer"
msgstr "Endurræsi kerfi"

#: ../DistUpgrade/DistUpgrade.glade.h:16
#, fuzzy
msgid "Setting new software channels"
msgstr "Stilli hugbúnaðarrásir"

#: ../DistUpgrade/DistUpgrade.glade.h:17
msgid "Terminal"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:18
msgid "_Cancel Upgrade"
msgstr "_hætta við"

#: ../DistUpgrade/DistUpgrade.glade.h:19
msgid "_Continue"
msgstr "_Halda áfram"

#: ../DistUpgrade/DistUpgrade.glade.h:21
msgid "_Replace"
msgstr "_Endurskrifa"

#: ../DistUpgrade/DistUpgrade.glade.h:22
msgid "_Report Bug"
msgstr "_Tilkynna Villu"

#: ../DistUpgrade/DistUpgrade.glade.h:23
msgid "_Restart Now"
msgstr "_Endurræsa núna"

#: ../DistUpgrade/DistUpgrade.glade.h:24
msgid "_Resume Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:25
msgid "_Start Upgrade"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:79
msgid "Could not find the release notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:80
msgid "The server may be overloaded. "
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:90
msgid "Could not download the release notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:91
msgid "Please check your internet connection."
msgstr ""

#: ../UpdateManager/GtkProgress.py:108
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr ""

#: ../UpdateManager/GtkProgress.py:113
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr ""

#: ../UpdateManager/UpdateManager.py:245
msgid "The list of changes is not available"
msgstr ""

#: ../UpdateManager/UpdateManager.py:251
msgid ""
"The list of changes is not available yet.\n"
"Please try again later."
msgstr ""

#: ../UpdateManager/UpdateManager.py:256
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""

#: ../UpdateManager/UpdateManager.py:283
msgid "Important security updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:284
msgid "Recommended updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:285
msgid "Proposed updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:286
msgid "Backports"
msgstr ""

#: ../UpdateManager/UpdateManager.py:287
msgid "Distribution updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:292
msgid "Other updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:518
#, python-format
msgid "Version %s: \n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:579
msgid "Downloading list of changes..."
msgstr ""

#: ../UpdateManager/UpdateManager.py:606
msgid "_Uncheck All"
msgstr ""

#: ../UpdateManager/UpdateManager.py:612
msgid "_Check All"
msgstr ""

#. TRANSLATORS: b stands for Bytes
#: ../UpdateManager/UpdateManager.py:656 ../UpdateManager/UpdateManager.py:708
#, python-format
msgid "Download size: %s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:660
msgid "Unknown download size"
msgstr ""

#: ../UpdateManager/UpdateManager.py:668
msgid ""
"It is unknown when the package information was updated last. Please try "
"clicking on the 'Check' button to update the information."
msgstr ""

#: ../UpdateManager/UpdateManager.py:677
#, python-format
msgid "The package information was last updated %s days ago."
msgstr ""

#: ../UpdateManager/UpdateManager.py:679
#, python-format
msgid "The package information was last updated %s hours ago."
msgstr ""

#: ../UpdateManager/UpdateManager.py:681
msgid "The package information was last updated less than one hour ago."
msgstr ""

#: ../UpdateManager/UpdateManager.py:689
#: ../data/glade/UpdateManager.glade.h:21
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""

#: ../UpdateManager/UpdateManager.py:704
#, fuzzy, python-format
msgid "You can install %s update."
msgid_plural "You can install %s updates."
msgstr[0] "Gat ekki sett upp uppfærslur"
msgstr[1] "Gat ekki sett upp uppfærslur"

#: ../UpdateManager/UpdateManager.py:745
msgid "Please wait, this can take some time."
msgstr ""

#: ../UpdateManager/UpdateManager.py:747
msgid "Update is complete"
msgstr ""

#: ../UpdateManager/UpdateManager.py:799
msgid "Reading package information"
msgstr ""

#: ../UpdateManager/UpdateManager.py:872
msgid "Could not initialize the package information"
msgstr ""

#: ../UpdateManager/UpdateManager.py:873
msgid ""
"A unresolvable problem occurred while initializing the package information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:895
msgid ""
"A unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:920
#, python-format
msgid "(Size: %s)"
msgstr ""

#: ../UpdateManager/UpdateManager.py:930
msgid "Your distribution is not supported anymore"
msgstr ""

#: ../UpdateManager/UpdateManager.py:931
msgid ""
"You will not get any further security fixes or critical updates. Upgrade to "
"a later version of Ubuntu Linux. See http://www.ubuntu.com for more "
"information on upgrading."
msgstr ""

#: ../UpdateManager/UpdateManager.py:946
msgid "Downloading the upgrade tool"
msgstr ""

#: ../UpdateManager/UpdateManager.py:948
msgid "The upgrade tool will guide you through the upgrade process."
msgstr ""

#: ../UpdateManager/UpdateManager.py:956
#, python-format
msgid "<b>New distribution release '%s' is available</b>"
msgstr ""

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:999
msgid "Software index is broken"
msgstr ""

#: ../UpdateManager/UpdateManager.py:1000
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""

#: ../data/glade/UpdateManager.glade.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""

#: ../data/glade/UpdateManager.glade.h:4
msgid "<big><b>Keep your system up-to-date</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:5
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:6
msgid "<big><b>Starting Update Manager</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:7
msgid "Changes"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:8
msgid "Chec_k"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:9
msgid "Check the software channels for new updates"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:10
msgid "Description"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:11
msgid "Description of update"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:12
msgid "Release Notes"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:13
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" ◦ A previous upgrade which didn't complete\n"
" ◦ Problems with some of the installed software\n"
" ◦ Unofficial software packages not provided by Ubuntu\n"
" ◦ Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:20
msgid "Show progress of individual files"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:22
msgid "U_pgrade"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:23
#: ../data/update-manager.desktop.in.h:3
msgid "Update Manager"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:24
msgid "Upgrade to the latest version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:25
msgid "_Check"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:26
msgid "_Hide this information in the future"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:27
msgid "_Install Updates"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:28
msgid "_Partial Upgrade"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:29
msgid "_Upgrade"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:30
msgid "updates"
msgstr ""

#: ../data/update-manager.desktop.in.h:1
msgid "Show and install available updates"
msgstr ""

#: ../data/update-manager.desktop.in.h:2
msgid "Software Updates"
msgstr ""

#: ../data/update-manager.schemas.in.h:1
msgid "*deprecated* Check for new distribution releases"
msgstr ""

#: ../data/update-manager.schemas.in.h:2
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""

#: ../data/update-manager.schemas.in.h:3
msgid "Remind to reload the channel list"
msgstr ""

#: ../data/update-manager.schemas.in.h:4
msgid "Show details of an update"
msgstr ""

#: ../data/update-manager.schemas.in.h:5
msgid "Stores the size of the update-manager dialog"
msgstr ""

#: ../data/update-manager.schemas.in.h:6
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr ""

#: ../data/update-manager.schemas.in.h:7
msgid "The window size"
msgstr ""

#: ../data/update-manager.schemas.in.h:8
msgid ""
"This key is deprecated in favor of the file /etc/update-manager/release-"
"upgrades Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""

#: ../update-manager:54
msgid "Show version and exit"
msgstr ""

#: ../update-manager:57
msgid "Check if a new distribution release is available"
msgstr ""

#: ../update-manager:60 ../do-release-upgrade:19
msgid "Check if upgrading to the latest devel release is possible"
msgstr ""

#: ../update-manager:64 ../update-manager:67
msgid "Try to run a dist-upgrade"
msgstr ""

#: ../update-manager:85
msgid "Running partial upgrade"
msgstr ""

#: ../update-manager:105
msgid "Upgrade complete"
msgstr ""

#: ../update-manager:106
msgid "The upgrade was completed."
msgstr ""

#: ../do-release-upgrade:23
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""

#: ../do-release-upgrade:27
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""

#: ../do-release-upgrade:33
msgid "Run the specified frontend"
msgstr ""

#: ../do-release-upgrade:37
msgid "Checking for a new ubuntu release"
msgstr ""

#: ../do-release-upgrade:44
msgid "No new release found"
msgstr ""

#~ msgid "_Skip This Step"
#~ msgstr "_Sleppa þessu skrefi"

#, fuzzy
#~ msgid "Fetching the upgrades"
#~ msgstr "Undirbý uppfærslu"
