# Quechua translation for update-manager
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the update-manager package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2007-08-20 10:52+0200\n"
"PO-Revision-Date: 2006-10-09 15:50+0000\n"
"Last-Translator: Rosetta Administrators <rosetta@launchpad.net>\n"
"Language-Team: Quechua <qu@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=((n % 10 == 1 && n % 100 != 11) ? 0 : 1);\n"
"X-Rosetta-Export-Date: 2007-04-13 08:49:06+0000\n"

#: ../DistUpgrade/DistUpgradeCache.py:112
msgid "Broken packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:113
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:340
msgid "Can't upgrade required meta-packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:345
msgid "A essential package would have to be removed"
msgstr ""

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:348
#: ../UpdateManager/UpdateManager.py:873
msgid "Could not calculate the upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:349
msgid ""
"A unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bugreport."
msgstr ""

#. FIXME: maybe ask a question here? instead of failing?
#: ../DistUpgrade/DistUpgradeCache.py:387
msgid "Error authenticating some packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:388
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:491
#, python-format
msgid "Can't install '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:492
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:499
msgid "Can't guess meta-package"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:500
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:91
msgid "Failed to add the CD"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:92
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:124
msgid "Reading cache"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:175
msgid "Unable to get exclusive lock"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:176
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:194
msgid "Continue running under SSH?"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:195
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, a additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:208
msgid "Starting additional sshd"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:209
#, python-format
msgid ""
"To make recovery in case of failure easier a additional sshd will be started "
"on port '%s'. If anything goes wrong with the running ssh you can still "
"connect to the additional one.\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:273
#: ../DistUpgrade/DistUpgradeControler.py:282
msgid "Can not upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:274
#, python-format
msgid "A upgrade from '%s' to '%s' is not supoprted with this tool."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:283
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:302
msgid "Include latest updates from the Internet?"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:303
msgid ""
"The upgrade process can automatically download the latest updates and "
"install them during the upgrade.  The upgrade will take longer, but when it "
"is complete, your system will be fully up to date.  You can choose not to do "
"this, but you should install the latest updates soon after upgrading."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:447
msgid "No valid mirror found"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:448
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found.This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'no' the update will cancel."
msgstr ""

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeControler.py:465
msgid "Generate default sources?"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:466
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No' the update will "
"cancel."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:500
msgid "Repository information invalid"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:501
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:507
msgid "Third party sources disabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:508
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:566
msgid "Error during update"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:567
msgid ""
"A problem occured during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:576
msgid "Not enough free disk space"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:577
#, python-format
msgid ""
"The upgrade aborts now. The upgrade needs a total of %s free space on disk %"
"s. Please free at least an additional %s of disk space on %s. Empty your "
"trash and remove temporary packages of former installations using 'sudo apt-"
"get clean'."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:687
msgid "Support for some applications ended"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:688
msgid ""
"Canonical Ltd. no longer provides support for the following software "
"packages. You can still get support from the community.\n"
"\n"
"If you have not enabled community maintained software (universe), these "
"packages will be suggested for removal at the end of the upgrade."
msgstr ""

#. ask the user if he wants to do the changes
#: ../DistUpgrade/DistUpgradeControler.py:711
msgid "Do you want to start the upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:768
#: ../DistUpgrade/DistUpgradeControler.py:818
msgid "Could not download the upgrades"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:769
#: ../DistUpgrade/DistUpgradeControler.py:819
msgid ""
"The upgrade aborts now. Please check your internet connection or "
"installation media and try again. "
msgstr ""

#. invoke the frontend now
#: ../DistUpgrade/DistUpgradeControler.py:794
msgid ""
"The upgrade aborts now. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:798
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bugreport.\n"
"%s"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:802
msgid "Could not install the upgrades"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:888
msgid "Remove obsolete packages?"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:889
msgid "_Skip This Step"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:889
msgid "_Remove"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:900
msgid "Error during commit"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:901
msgid ""
"A problem occured during the clean-up. Please see the below message for more "
"information. "
msgstr ""

#. generate a new cache
#: ../DistUpgrade/DistUpgradeControler.py:1018
msgid "Restoring original system state"
msgstr ""

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeControler.py:1056
msgid "Required depends is not installed"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1057
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr ""

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeControler.py:1158
#: ../DistUpgrade/DistUpgradeControler.py:1215
msgid "Checking package manager"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1163
msgid "Preparing the upgrade failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1164
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bugreport."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1179
msgid "Getting upgrade pre-requists failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1180
msgid ""
"The system was unable to get the pre-requists for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bugreport."
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1201
msgid "Updating repository information"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1226
msgid "Invalid package information"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1227
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the "
"bugreport."
msgstr ""

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeControler.py:1238
msgid "Asking for confirmation"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1244 ../update-manager:83
msgid "Fetching"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1254 ../update-manager:87
msgid "Upgrading"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1261
msgid "Searching for obsolete software"
msgstr ""

#: ../DistUpgrade/DistUpgradeControler.py:1266
msgid "System upgrade is complete."
msgstr ""

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:107
#: ../DistUpgrade/DistUpgradeViewKDE.py:113
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:126
#: ../DistUpgrade/DistUpgradeViewKDE.py:126
msgid "Fetching is complete"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:138
#: ../DistUpgrade/DistUpgradeViewKDE.py:139
#, python-format
msgid "Fetching file %li of %li at %sb/s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:139
#: ../DistUpgrade/DistUpgradeViewGtk.py:266
#: ../DistUpgrade/DistUpgradeViewKDE.py:140
#: ../DistUpgrade/DistUpgradeViewKDE.py:258
#, python-format
msgid "About %s remaining"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:141
#: ../DistUpgrade/DistUpgradeViewKDE.py:142
#, python-format
msgid "Fetching file %li of %li"
msgstr ""

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:174
#: ../DistUpgrade/DistUpgradeViewKDE.py:171
msgid "Applying changes"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:199
#: ../DistUpgrade/DistUpgradeViewKDE.py:182
#, python-format
msgid "Could not install '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:200
#: ../DistUpgrade/DistUpgradeViewKDE.py:183
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may be in a not working "
"state. Please consider submitting a bugreport about it."
msgstr ""

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:216
#: ../DistUpgrade/DistUpgradeViewKDE.py:201
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:217
#: ../DistUpgrade/DistUpgradeViewKDE.py:202
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:230
#: ../DistUpgrade/DistUpgradeViewKDE.py:215
msgid "The 'diff' command was not found"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:402
msgid "A fatal error occured"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:403
msgid ""
"Please report this as a bug (if you haven't already) and include thefiles /"
"var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade aborts now.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#. FIXME: make those two seperate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeViewGtk.py:537
#: ../DistUpgrade/DistUpgradeViewKDE.py:550
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:542
#: ../DistUpgrade/DistUpgradeViewKDE.py:555
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:548
#: ../DistUpgrade/DistUpgradeViewKDE.py:561
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:553
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:559
#: ../DistUpgrade/DistUpgradeViewKDE.py:581
#: ../DistUpgrade/DistUpgradeViewKDE.py:589
msgid ""
"Fetching and installing the upgrade can take several hours and cannot be "
"canceled at any time later."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:562
#: ../DistUpgrade/DistUpgradeViewKDE.py:584
#: ../DistUpgrade/DistUpgradeViewKDE.py:592
msgid "To prevent data loss close all open applications and documents."
msgstr ""

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeViewGtk.py:568
#: ../DistUpgrade/DistUpgradeViewKDE.py:598
#: ../UpdateManager/UpdateManager.py:658
msgid "Your system is up-to-date"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:569
#: ../DistUpgrade/DistUpgradeViewKDE.py:599
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:585
#, python-format
msgid "<b>Remove %s</b>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:587
#: ../DistUpgrade/DistUpgradeViewKDE.py:622
#, python-format
msgid "Install %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:589
#: ../DistUpgrade/DistUpgradeViewKDE.py:624
#, python-format
msgid "Upgrade %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:114
msgid "Media Change"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:447
msgid "Show Terminal >>>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:450
msgid "<<< Hide Terminal"
msgstr ""

#. string = _("<p>You have to download a total of %s. ")
#. msg += string % apt_pkg.SizeToStr(downloadSize)
#. msg += _("<p>You have to download a total of %s. ") %#: ../DistUpgrade/DistUpgradeViewKDE.py:567
#: ../DistUpgrade/DistUpgradeViewKDE.py:573
#, python-format
msgid "<p>You have to download a total of %s. "
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:620
#, python-format
msgid "Remove %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:640
#: ../DistUpgrade/DistUpgrade.glade.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:644
msgid "Cancel Upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:33
#, python-format
msgid "%li days %li hours %li minutes"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:35
#, python-format
msgid "%li hours %li minutes"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:37
#, python-format
msgid "%li minutes"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:38
#, python-format
msgid "%li seconds"
msgstr ""

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:44
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:150
msgid "Reboot required"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:151
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""

#: ../DistUpgrade/dist-upgrade.py:15
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr ""

#: ../DistUpgrade/dist-upgrade.py:21
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""

#: ../DistUpgrade/dist-upgrade.py:24
msgid ""
"Use special upgrade mode. Available:\n"
"desktop, server"
msgstr ""

#. testcode to see if the bullets look nice in the dialog
#. for i in range(4):
#. view.setStep(i+1)
#. app.openCache()
#: ../DistUpgrade/DistUpgrade.glade.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.glade.h:5
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:6
msgid "<b><big>Start the upgrade?</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:7
msgid "<b><big>Upgrading Ubuntu to version 7.10</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:8
msgid "Cleaning up"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:9
msgid "Details"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:10
msgid "Difference between the files"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:11
msgid "Distribution Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:12
msgid "Fetching the upgrades"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:13
msgid "Installing the upgrades"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:14
msgid "Modifying the software channels"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:15
msgid "Preparing the upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:16
msgid "Restarting the system"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:17
msgid "Terminal"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:18
msgid "_Cancel Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:19
msgid "_Continue"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:20
msgid "_Keep"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:21
msgid "_Replace"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:22
msgid "_Report Bug"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:23
msgid "_Restart Now"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:24
msgid "_Resume Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.glade.h:25
msgid "_Start Upgrade"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:90
msgid "Could not find the release notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:91
msgid "The server may be overloaded. "
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:101
msgid "Could not download the release notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:102
msgid "Please check your internet connection."
msgstr ""

#: ../UpdateManager/GtkProgress.py:108
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr ""

#: ../UpdateManager/GtkProgress.py:113
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr ""

#: ../UpdateManager/UpdateManager.py:235
msgid "The list of changes is not available"
msgstr ""

#: ../UpdateManager/UpdateManager.py:241
msgid ""
"The list of changes is not available yet.\n"
"Please try again later."
msgstr ""

#: ../UpdateManager/UpdateManager.py:246
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""

#: ../UpdateManager/UpdateManager.py:273
msgid "Important security updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:274
msgid "Recommended updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:275
msgid "Proposed updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:276
msgid "Backports"
msgstr ""

#: ../UpdateManager/UpdateManager.py:277
msgid "Distribution updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:282
msgid "Other updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:508
#, python-format
msgid "Version %s: \n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:569
msgid "Downloading list of changes..."
msgstr ""

#: ../UpdateManager/UpdateManager.py:596
msgid "_Uncheck All"
msgstr ""

#: ../UpdateManager/UpdateManager.py:602
msgid "_Check All"
msgstr ""

#. TRANSLATORS: b stands for Bytes
#: ../UpdateManager/UpdateManager.py:646 ../UpdateManager/UpdateManager.py:673
#, python-format
msgid "Download size: %s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:650
msgid "Unknown download size"
msgstr ""

#: ../UpdateManager/UpdateManager.py:669
#, python-format
msgid "You can install %s update"
msgid_plural "You can install %s updates"
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:702
msgid "Please wait, this can take some time."
msgstr ""

#: ../UpdateManager/UpdateManager.py:704
msgid "Update is complete"
msgstr ""

#: ../UpdateManager/UpdateManager.py:756
msgid "Checking for updates"
msgstr ""

#: ../UpdateManager/UpdateManager.py:851
msgid "Could not initialize the package information"
msgstr ""

#: ../UpdateManager/UpdateManager.py:852
msgid ""
"A unresolvable problem occurred while initializing the package information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:874
msgid ""
"A unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""

#: ../UpdateManager/UpdateManager.py:899
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:903
#, python-format
msgid "Version %s"
msgstr ""

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:905
#, python-format
msgid "(Size: %s)"
msgstr ""

#: ../UpdateManager/UpdateManager.py:916
msgid "Your distribution is not supported anymore"
msgstr ""

#: ../UpdateManager/UpdateManager.py:917
msgid ""
"You will not get any further security fixes or critical updates. Upgrade to "
"a later version of Ubuntu Linux. See http://www.ubuntu.com for more "
"information on upgrading."
msgstr ""

#: ../UpdateManager/UpdateManager.py:932
msgid "Downloading the upgrade tool"
msgstr ""

#: ../UpdateManager/UpdateManager.py:934
msgid "The upgrade tool will guide you through the upgrade process."
msgstr ""

#: ../UpdateManager/UpdateManager.py:942
#, python-format
msgid "<b>New distribution release '%s' is available</b>"
msgstr ""

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:981
msgid "Software index is broken"
msgstr ""

#: ../UpdateManager/UpdateManager.py:982
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:120
msgid "Could not run the upgrade tool"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:121
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:147
msgid "Upgrade tool signature"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:150
msgid "Upgrade tool"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:174
msgid "Failed to fetch"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:175
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:179
msgid "Failed to extract"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:180
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:185
msgid "Verfication failed"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:186
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:191
msgid "Authentication failed"
msgstr ""

#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:192
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""

#: ../data/glade/UpdateManager.glade.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Internet Updates</i> tab."
msgstr ""

#: ../data/glade/UpdateManager.glade.h:4
msgid "<big><b>Keep your system up-to-date</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:5
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:6
msgid "<big><b>Starting Update Manager</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:7
msgid "Changes"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:8
msgid "Chec_k"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:9
msgid "Check the software channels for new updates"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:10
msgid "Description"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:11
msgid "Description of update"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:12
msgid "Release Notes"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:13
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" ◦ A previous upgrade which didn't complete\n"
" ◦ Unofficial software packages not provided by Ubuntu\n"
" ◦ Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:19
msgid "Show progress of single files"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:20
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""

#: ../data/glade/UpdateManager.glade.h:21
msgid "U_pgrade"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:22
#: ../data/update-manager.desktop.in.h:3
msgid "Update Manager"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:23
msgid "Upgrade to the latest version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:24
msgid "_Check"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:25
msgid "_Hide this information in the future"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:26
msgid "_Install Updates"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:27
msgid "_Partial Upgrade"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:28
msgid "_Upgrade"
msgstr ""

#: ../data/glade/UpdateManager.glade.h:29
msgid "updates"
msgstr ""

#: ../data/update-manager.desktop.in.h:1
msgid "Show and install available updates"
msgstr ""

#: ../data/update-manager.desktop.in.h:2
msgid "System Update Tool"
msgstr ""

#: ../data/update-manager.schemas.in.h:1
msgid ""
"Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""

#: ../data/update-manager.schemas.in.h:2
msgid "Check for new distribution releases"
msgstr ""

#: ../data/update-manager.schemas.in.h:3
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""

#: ../data/update-manager.schemas.in.h:4
msgid "Remind to reload the channel list"
msgstr ""

#: ../data/update-manager.schemas.in.h:5
msgid "Show details of an update"
msgstr ""

#: ../data/update-manager.schemas.in.h:6
msgid "Stores the size of the update-manager dialog"
msgstr ""

#: ../data/update-manager.schemas.in.h:7
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr ""

#: ../data/update-manager.schemas.in.h:8
msgid "The window size"
msgstr ""

#: ../update-manager:51
msgid "Check if a new distribution release is available"
msgstr ""

#: ../update-manager:54 ../do-release-upgrade:19
msgid "Check if upgrading to the latest devel release is possible"
msgstr ""

#: ../update-manager:58 ../update-manager:61
msgid "Try to run a dist-upgrade"
msgstr ""

#: ../update-manager:74
msgid "Running partial upgrade"
msgstr ""

#: ../update-manager:92
msgid "Upgrade complete"
msgstr ""

#: ../update-manager:93
msgid "The upgrade was completed."
msgstr ""

#: ../do-release-upgrade:23
msgid "Run the specified frontend"
msgstr ""

#: ../do-release-upgrade:26
msgid "Run in a special upgrade mode"
msgstr ""

#: ../do-release-upgrade:30
msgid "Checking for a new ubuntu release"
msgstr ""

#: ../do-release-upgrade:36
msgid "No new release found"
msgstr ""
